export const AgricultureAndRuralDevelopment = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['AG.AGR.TRAC.NO'      , 'Agricultural machinery, tractors'                                                          , ['AgriRural']                               ], 
    ['AG.CON.FERT.PT.ZS'   , 'Fertilizer consumption (% of fertilizer production)'                                       , ['AgriRural']                               ], 
    ['AG.CON.FERT.ZS'      , 'Fertilizer consumption (kilograms per hectare of arable land)'                             , ['AgriRural']                               ], 
    ['AG.LND.AGRI.K2'      , 'Agricultural land (sq. km)'                                                                , ['AgriRural', 'Climate']                    ], 
    ['AG.LND.AGRI.ZS'      , 'Agricultural land (% of land area)'                                                        , ['AgriRural', 'Climate', 'Env']             ], 
    ['AG.LND.ARBL.HA'      , 'Arable land (hectares)'                                                                    , ['AgriRural']                               ], 
    ['AG.LND.ARBL.HA.PC'   , 'Arable land (hectares per person)'                                                         , ['AgriRural']                               ], 
    ['AG.LND.ARBL.ZS'      , 'Arable land (% of land area)'                                                              , ['AgriRural', 'Climate', 'Env']             ], 
    ['AG.LND.CREL.HA'      , 'Land under cereal production (hectares)'                                                   , ['AgriRural']                               ], 
    ['AG.LND.CROP.ZS'      , 'Permanent cropland (% of land area)'                                                       , ['AgriRural']                               ], 
    ['AG.LND.EL5M.RU.K2'   , 'Rural land area where elevation is below 5 meters (sq. km)'                                , ['AgriRural', 'Climate', 'Env']             ], 
    ['AG.LND.EL5M.RU.ZS'   , 'Rural land area where elevation is below 5 meters (% of total land area)'                  , ['AgriRural', 'Climate', 'Env']             ], 
    ['AG.LND.FRST.K2'      , 'Forest area (sq. km)'                                                                      , ['AgriRural', 'Climate', 'Env']             ], 
    ['AG.LND.FRST.ZS'      , 'Forest area (% of land area)'                                                              , ['AgriRural', 'Climate', 'Env']             ], 
    ['AG.LND.IRIG.AG.ZS'   , 'Agricultural irrigated land (% of total agricultural land)'                                , ['AgriRural', 'Climate']                    ], 
    ['AG.LND.PRCP.MM'      , 'Average precipitation in depth (mm per year)'                                              , ['AgriRural', 'Climate', 'Env']             ], 
    ['AG.LND.TOTL.K2'      , 'Land area (sq. km)'                                                                        , ['AgriRural', 'Env']                        ], 
    ['AG.LND.TOTL.RU.K2'   , 'Rural land area (sq. km)'                                                                  , ['AgriRural', 'Env']                        ], 
    ['AG.LND.TRAC.ZS'      , 'Agricultural machinery, tractors per 100 sq. km of arable land'                            , ['AgriRural']                               ], 
    ['AG.PRD.CREL.MT'      , 'Cereal production (metric tons)'                                                           , ['AgriRural']                               ], 
    ['AG.PRD.CROP.XD'      , 'Crop production index (2014-2016 = 100)'                                                   , ['AgriRural']                               ], 
    ['AG.PRD.FOOD.XD'      , 'Food production index (2014-2016 = 100)'                                                   , ['AgriRural']                               ], 
    ['AG.PRD.LVSK.XD'      , 'Livestock production index (2014-2016 = 100)'                                              , ['AgriRural']                               ], 
    ['AG.SRF.TOTL.K2'      , 'Surface area (sq. km)'                                                                     , ['AgriRural', 'Env']                        ], 
    ['AG.YLD.CREL.KG'      , 'Cereal yield (kg per hectare)'                                                             , ['AgriRural', 'Climate']                    ], 
    ['EA.PRD.AGRI.KD'      , 'Agriculture value added per worker (constant 2010 US$)'                                    , ['AgriRural']                               ], 
    ['EG.ELC.ACCS.RU.ZS'   , 'Access to electricity, rural (% of rural population)'                                      , ['AgriRural', 'Energy']                     ], 
    ['EG.NSF.ACCS.RU.ZS'   , 'Access to non-solid fuel, rural (% of rural population)'                                   , ['AgriRural', 'Energy']                     ], 
    ['EN.AGR.EMPL'         , 'Economically active population in agriculture (number)'                                    , ['AgriRural']                               ], 
    ['EN.ATM.METH.AG.KT.CE', 'Agricultural methane emissions (thousand metric tons of CO2 equivalent)'                   , ['AgriRural', 'Env']                        ], 
    ['EN.ATM.METH.AG.ZS'   , 'Agricultural methane emissions (% of total)'                                               , ['AgriRural', 'Env']                        ], 
    ['EN.ATM.NOXE.AG.KT.CE', 'Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent)'             , ['AgriRural', 'Env']                        ], 
    ['EN.ATM.NOXE.AG.ZS'   , 'Agricultural nitrous oxide emissions (% of total)'                                         , ['AgriRural', 'Env']                        ], 
    ['EN.POP.EL5M.RU.ZS'   , 'Rural population living in areas where elevation is below 5 meters (% of total population)', ['AgriRural', 'Climate', 'Env']             ], 
    ['ER.H2O.FWAG.ZS'      , 'Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal)'             , ['AgriRural', 'Infras', 'Env']              ], 
    ['NV.AGR.TOTL.CD'      , 'Agriculture, forestry, and fishing, value added (current US$)'                             , ['AgriRural', 'Econ']                       ], 
    ['NV.AGR.TOTL.ZS'      , 'Agriculture, forestry, and fishing, value added (% of GDP)'                                , ['AgriRural', 'Econ', 'Climate']            ], 
    ['SH.H2O.SAFE.RU.ZS'   , 'Improved water source, rural (% of rural population with access)'                          , ['AgriRural', 'Climate', 'Infras', 'Health']], 
    ['SH.STA.ACSN.RU'      , 'Improved sanitation facilities, rural (% of rural population with access)'                 , ['AgriRural', 'Health']                     ], 
    ['SI.POV.RUGP'         , 'Rural poverty gap at national poverty lines (%)'                                           , ['AgriRural', 'Poverty']                    ], 
    ['SI.POV.RUHC'         , 'Rural poverty headcount ratio at national poverty lines (% of rural population)'           , ['AgriRural', 'Poverty']                    ], 
    ['SL.AGR.EMPL.FE.ZS'   , 'Employment in agriculture, female (% of female employment) (modeled ILO estimate)'         , ['AgriRural', 'Labor', 'Gender']            ], 
    ['SL.AGR.EMPL.MA.ZS'   , 'Employment in agriculture, male (% of male employment) (modeled ILO estimate)'             , ['AgriRural', 'Labor', 'Gender']            ], 
    ['SL.AGR.EMPL.ZS'      , 'Employment in agriculture (% of total employment) (modeled ILO estimate)'                  , ['AgriRural', 'Labor']                      ], 
    ['SP.RUR.TOTL'         , 'Rural population'                                                                          , ['AgriRural']                               ], 
    ['SP.RUR.TOTL.ZG'      , 'Rural population growth (annual %)'                                                        , ['AgriRural']                               ], 
    ['SP.RUR.TOTL.ZS'      , 'Rural population (% of total population)'                                                  , ['AgriRural']                               ], 
    ['TM.VAL.AGRI.ZS.UN'   , 'Agricultural raw materials imports (% of merchandise imports)'                             , ['AgriRural', 'Private', 'Trade']           ], 
    ['TX.VAL.AGRI.ZS.UN'   , 'Agricultural raw materials exports (% of merchandise exports)'                             , ['AgriRural', 'Private', 'Trade']           ], 
  ], 
}