export const AidEffectiveness = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['BX.GRT.EXTA.CD.WD', 'Grants, excluding technical cooperation (BoP, current US$)'                        , ['Econ', 'Debt', 'Aid']                      ], 
    ['BX.GRT.TECH.CD.WD', 'Technical cooperation grants (BoP, current US$)'                                   , ['Econ', 'Debt', 'Aid']                      ], 
    ['DC.DAC.AUSL.CD'   , 'Net bilateral aid flows from DAC donors, Australia (current US$)'                  , ['Aid']                                      ], 
    ['DC.DAC.AUTL.CD'   , 'Net bilateral aid flows from DAC donors, Austria (current US$)'                    , ['Aid']                                      ], 
    ['DC.DAC.BELL.CD'   , 'Net bilateral aid flows from DAC donors, Belgium (current US$)'                    , ['Aid']                                      ], 
    ['DC.DAC.CANL.CD'   , 'Net bilateral aid flows from DAC donors, Canada (current US$)'                     , ['Aid']                                      ], 
    ['DC.DAC.CECL.CD'   , 'Net bilateral aid flows from DAC donors, European Union institutions (current US$)', ['Aid']                                      ], 
    ['DC.DAC.CHEL.CD'   , 'Net bilateral aid flows from DAC donors, Switzerland (current US$)'                , ['Aid']                                      ], 
    ['DC.DAC.CZEL.CD'   , 'Net bilateral aid flows from DAC donors, Czech Republic (current US$)'             , ['Aid']                                      ], 
    ['DC.DAC.DEUL.CD'   , 'Net bilateral aid flows from DAC donors, Germany (current US$)'                    , ['Aid']                                      ], 
    ['DC.DAC.DNKL.CD'   , 'Net bilateral aid flows from DAC donors, Denmark (current US$)'                    , ['Aid']                                      ], 
    ['DC.DAC.ESPL.CD'   , 'Net bilateral aid flows from DAC donors, Spain (current US$)'                      , ['Aid']                                      ], 
    ['DC.DAC.FINL.CD'   , 'Net bilateral aid flows from DAC donors, Finland (current US$)'                    , ['Aid']                                      ], 
    ['DC.DAC.FRAL.CD'   , 'Net bilateral aid flows from DAC donors, France (current US$)'                     , ['Aid']                                      ], 
    ['DC.DAC.GBRL.CD'   , 'Net bilateral aid flows from DAC donors, United Kingdom (current US$)'             , ['Aid']                                      ], 
    ['DC.DAC.GRCL.CD'   , 'Net bilateral aid flows from DAC donors, Greece (current US$)'                     , ['Aid']                                      ], 
    ['DC.DAC.IRLL.CD'   , 'Net bilateral aid flows from DAC donors, Ireland (current US$)'                    , ['Aid']                                      ], 
    ['DC.DAC.ISLL.CD'   , 'Net bilateral aid flows from DAC donors, Iceland (current US$)'                    , ['Aid']                                      ], 
    ['DC.DAC.ITAL.CD'   , 'Net bilateral aid flows from DAC donors, Italy (current US$)'                      , ['Aid']                                      ], 
    ['DC.DAC.JPNL.CD'   , 'Net bilateral aid flows from DAC donors, Japan (current US$)'                      , ['Aid']                                      ], 
    ['DC.DAC.KORL.CD'   , 'Net bilateral aid flows from DAC donors, Korea, Rep. (current US$)'                , ['Aid']                                      ], 
    ['DC.DAC.LUXL.CD'   , 'Net bilateral aid flows from DAC donors, Luxembourg (current US$)'                 , ['Aid']                                      ], 
    ['DC.DAC.NLDL.CD'   , 'Net bilateral aid flows from DAC donors, Netherlands (current US$)'                , ['Aid']                                      ], 
    ['DC.DAC.NORL.CD'   , 'Net bilateral aid flows from DAC donors, Norway (current US$)'                     , ['Aid']                                      ], 
    ['DC.DAC.NZLL.CD'   , 'Net bilateral aid flows from DAC donors, New Zealand (current US$)'                , ['Aid']                                      ], 
    ['DC.DAC.POLL.CD'   , 'Net bilateral aid flows from DAC donors, Poland (current US$)'                     , ['Aid']                                      ], 
    ['DC.DAC.PRTL.CD'   , 'Net bilateral aid flows from DAC donors, Portugal (current US$)'                   , ['Aid']                                      ], 
    ['DC.DAC.SVKL.CD'   , 'Net bilateral aid flows from DAC donors, Slovak Republic (current US$)'            , ['Aid']                                      ], 
    ['DC.DAC.SVNL.CD'   , 'Net bilateral aid flows from DAC donors, Slovenia (current US$)'                   , ['Aid']                                      ], 
    ['DC.DAC.SWEL.CD'   , 'Net bilateral aid flows from DAC donors, Sweden (current US$)'                     , ['Aid']                                      ], 
    ['DC.DAC.TOTL.CD'   , 'Net bilateral aid flows from DAC donors, Total (current US$)'                      , ['Aid']                                      ], 
    ['DC.DAC.USAL.CD'   , 'Net bilateral aid flows from DAC donors, United States (current US$)'              , ['Aid']                                      ], 
    ['DT.DIS.IDAG.CD'   , 'IDA grants (current US$)'                                                          , ['Aid', 'Debt']                              ], 
    ['DT.DOD.MDRI.CD'   , 'Debt forgiveness grants (current US$)'                                             , ['Aid', 'Debt']                              ], 
    ['DT.NFL.FAOG.CD'   , 'Net official flows from UN agencies, FAO (current US$)'                            , ['Aid']                                      ], 
    ['DT.NFL.IAEA.CD'   , 'Net official flows from UN agencies, IAEA (current US$)'                           , ['Aid']                                      ], 
    ['DT.NFL.IFAD.CD'   , 'Net official flows from UN agencies, IFAD (current US$)'                           , ['Aid']                                      ], 
    ['DT.NFL.ILOG.CD'   , 'Net official flows from UN agencies, ILO (current US$)'                            , ['Aid']                                      ], 
    ['DT.NFL.UNAI.CD'   , 'Net official flows from UN agencies, UNAIDS (current US$)'                         , ['Aid']                                      ], 
    ['DT.NFL.UNCF.CD'   , 'Net official flows from UN agencies, UNICEF (current US$)'                         , ['Aid']                                      ], 
    ['DT.NFL.UNCR.CD'   , 'Net official flows from UN agencies, UNHCR (current US$)'                          , ['Aid']                                      ], 
    ['DT.NFL.UNDP.CD'   , 'Net official flows from UN agencies, UNDP (current US$)'                           , ['Aid']                                      ], 
    ['DT.NFL.UNEC.CD'   , 'Net official flows from UN agencies, UNECE (current US$)'                          , ['Aid']                                      ], 
    ['DT.NFL.UNFP.CD'   , 'Net official flows from UN agencies, UNFPA (current US$)'                          , ['Aid']                                      ], 
    ['DT.NFL.UNPB.CD'   , 'Net official flows from UN agencies, UNPBF (current US$)'                          , ['Aid']                                      ], 
    ['DT.NFL.UNRW.CD'   , 'Net official flows from UN agencies, UNRWA (current US$)'                          , ['Aid']                                      ], 
    ['DT.NFL.UNTA.CD'   , 'Net official flows from UN agencies, UNTA (current US$)'                           , ['Aid']                                      ], 
    ['DT.NFL.WFPG.CD'   , 'Net official flows from UN agencies, WFP (current US$)'                            , ['Aid']                                      ], 
    ['DT.NFL.WHOL.CD'   , 'Net official flows from UN agencies, WHO (current US$)'                            , ['Aid']                                      ], 
    ['DT.ODA.ALLD.CD'   , 'Net official development assistance and official aid received (current US$)'       , ['Aid']                                      ], 
    ['DT.ODA.ALLD.KD'   , 'Net official development assistance and official aid received (constant 2015 US$)' , ['Aid']                                      ], 
    ['DT.ODA.OATL.CD'   , 'Net official aid received (current US$)'                                           , ['Aid']                                      ], 
    ['DT.ODA.OATL.KD'   , 'Net official aid received (constant 2015 US$)'                                     , ['Aid']                                      ], 
    ['DT.ODA.ODAT.CD'   , 'Net official development assistance received (current US$)'                        , ['Aid', 'Econ', 'Debt']                      ], 
    ['DT.ODA.ODAT.GI.ZS', 'Net ODA received (% of gross capital formation)'                                   , ['Aid']                                      ], 
    ['DT.ODA.ODAT.GN.ZS', 'Net ODA received (% of GNI)'                                                       , ['Aid', 'Econ', 'Debt']                      ], 
    ['DT.ODA.ODAT.KD'   , 'Net official development assistance received (constant 2015 US$)'                  , ['Aid']                                      ], 
    ['DT.ODA.ODAT.MP.ZS', 'Net ODA received (% of imports of goods, services and primary income)'             , ['Aid']                                      ], 
    ['DT.ODA.ODAT.PC.ZS', 'Net ODA received per capita (current US$)'                                         , ['Aid', 'Econ', 'Debt']                      ], 
    ['DT.ODA.ODAT.XP.ZS', 'Net ODA received (% of central government expense)'                                , ['Aid']                                      ], 
    ['SE.ENR.PRSC.FM.ZS', 'School enrollment, primary and secondary (gross), gender parity index (GPI)'       , ['Aid', 'Climate', 'Edu', 'Gender', 'Social']], 
    ['SE.PRM.CMPT.ZS'   , 'Primary completion rate, total (% of relevant age group)'                          , ['Aid', 'Climate', 'Edu']                    ], 
    ['SH.DYN.AIDS.ZS'   , 'Prevalence of HIV, total (% of population ages 15-49)'                             , ['Health', 'Aid']                            ], 
    ['SH.DYN.MORT'      , 'Mortality rate, under-5 (per 1,000 live births)'                                   , ['Health', 'Aid', 'Climate']                 ], 
    ['SH.STA.ACSN'      , 'Improved sanitation facilities (% of population with access)'                      , ['Health', 'Aid', 'Climate']                 ], 
    ['SH.STA.ANVC.ZS'   , 'Pregnant women receiving prenatal care (%)'                                        , ['Health', 'Gender', 'Aid']                  ], 
    ['SH.STA.MMRT'      , 'Maternal mortality ratio (modeled estimate, per 100,000 live births)'              , ['Health', 'Gender', 'Aid']                  ], 
    ['SH.STA.STNT.ZS'   , 'Prevalence of stunting, height for age (% of children under 5)'                    , ['Health', 'Aid']                            ], 
    ['SH.TBS.INCD'      , 'Incidence of tuberculosis (per 100,000 people)'                                    , ['Health', 'Aid']                            ], 
    ['SI.DST.FRST.20'   , 'Income share held by lowest 20%'                                                   , ['Poverty', 'Aid']                           ], 
    ['SI.POV.DDAY'      , 'Poverty headcount ratio at $1.90 a day (2011 PPP) (% of population)'               , ['Poverty', 'Aid', 'Climate']                ], 
    ['SL.EMP.VULN.ZS'   , 'Vulnerable employment, total (% of total employment) (modeled ILO estimate)'       , ['Labor', 'Aid']                             ], 
    ['SM.POP.NETM'      , 'Net migration'                                                                     , ['Fin', 'Health', 'Aid']                     ], 
  ], 
}