export const ClimateChange = {
  head: ['id', 'name', 'topics'],
  rows: [
    ['AG.LND.AGRI.K2', 'Agricultural land (sq. km)', ['AgriRural', 'Climate']],
    ['AG.LND.AGRI.ZS', 'Agricultural land (% of land area)', ['AgriRural', 'Climate', 'Env']],
    ['AG.LND.ARBL.ZS', 'Arable land (% of land area)', ['AgriRural', 'Climate', 'Env']],
    ['AG.LND.EL5M.RU.K2', 'Rural land area where elevation is below 5 meters (sq. km)', ['AgriRural', 'Climate', 'Env']],
    ['AG.LND.EL5M.RU.ZS', 'Rural land area where elevation is below 5 meters (% of total land area)', ['AgriRural', 'Climate', 'Env']],
    ['AG.LND.EL5M.UR.K2', 'Urban land area where elevation is below 5 meters (sq. km)', ['Climate', 'Urban', 'Env']],
    ['AG.LND.EL5M.UR.ZS', 'Urban land area where elevation is below 5 meters (% of total land area)', ['Climate', 'Urban', 'Env']],
    ['AG.LND.EL5M.ZS', 'Land area where elevation is below 5 meters (% of total land area)', ['Climate', 'Env']],
    ['AG.LND.FRST.K2', 'Forest area (sq. km)', ['AgriRural', 'Climate', 'Env']],
    ['AG.LND.FRST.ZS', 'Forest area (% of land area)', ['AgriRural', 'Climate', 'Env']],
    ['AG.LND.IRIG.AG.ZS', 'Agricultural irrigated land (% of total agricultural land)', ['AgriRural', 'Climate']],
    ['AG.LND.PRCP.MM', 'Average precipitation in depth (mm per year)', ['AgriRural', 'Climate', 'Env']],
    ['AG.YLD.CREL.KG', 'Cereal yield (kg per hectare)', ['AgriRural', 'Climate']],
    ['BX.KLT.DINV.WD.GD.ZS', 'Foreign direct investment, net inflows (% of GDP)', ['Econ', 'Fin', 'Climate']],
    ['EG.ELC.ACCS.ZS', 'Access to electricity (% of population)', ['Energy', 'Climate', 'Env']],
    ['EG.ELC.COAL.ZS', 'Electricity production from coal sources (% of total)', ['Energy', 'Climate', 'Infras']],
    ['EG.ELC.HYRO.ZS', 'Electricity production from hydroelectric sources (% of total)', ['Energy', 'Climate', 'Infras']],
    ['EG.ELC.NGAS.ZS', 'Electricity production from natural gas sources (% of total)', ['Energy', 'Climate', 'Infras']],
    ['EG.ELC.NUCL.ZS', 'Electricity production from nuclear sources (% of total)', ['Energy', 'Climate', 'Infras']],
    ['EG.ELC.PETR.ZS', 'Electricity production from oil sources (% of total)', ['Energy', 'Climate', 'Infras']],
    ['EG.ELC.RNEW.ZS', 'Renewable electricity output (% of total electricity output)', ['Energy', 'Climate', 'Env']],
    ['EG.ELC.RNWX.KH', 'Electricity production from renewable sources, excluding hydroelectric (kWh)', ['Energy', 'Climate', 'Env']],
    ['EG.ELC.RNWX.ZS', 'Electricity production from renewable sources, excluding hydroelectric (% of total)', ['Energy', 'Climate', 'Env']],
    ['EG.FEC.RNEW.ZS', 'Renewable energy consumption (% of total final energy consumption)', ['Energy', 'Climate', 'Env']],
    ['EG.USE.COMM.GD.PP.KD', 'Energy use (kg of oil equivalent) per $1,000 GDP (constant 2017 PPP)', ['Energy', 'Climate']],
    ['EG.USE.ELEC.KH.PC', 'Electric power consumption (kWh per capita)', ['Energy', 'Climate', 'Infras']],
    ['EG.USE.PCAP.KG.OE', 'Energy use (kg of oil equivalent per capita)', ['Energy', 'Climate']],
    ['EN.ATM.CO2E.EG.ZS', 'CO2 intensity (kg per kg of oil equivalent energy use)', ['Climate', 'Env']],
    ['EN.ATM.CO2E.GF.KT', 'CO2 emissions from gaseous fuel consumption (kt) ', ['Climate', 'Env']],
    ['EN.ATM.CO2E.GF.ZS', 'CO2 emissions from gaseous fuel consumption (% of total) ', ['Energy', 'Climate', 'Env']],
    ['EN.ATM.CO2E.KD.GD', 'CO2 emissions (kg per 2010 US$ of GDP)', ['Climate', 'Env']],
    ['EN.ATM.CO2E.KT', 'CO2 emissions (kt)', ['Climate', 'Env']],
    ['EN.ATM.CO2E.LF.KT', 'CO2 emissions from liquid fuel consumption (kt) ', ['Energy', 'Climate', 'Env']],
    ['EN.ATM.CO2E.LF.ZS', 'CO2 emissions from liquid fuel consumption (% of total) ', ['Climate', 'Env']],
    ['EN.ATM.CO2E.PC', 'CO2 emissions (metric tons per capita)', ['Climate', 'Env']],
    ['EN.ATM.CO2E.PP.GD', 'CO2 emissions (kg per PPP $ of GDP)', ['Climate', 'Env']],
    ['EN.ATM.CO2E.PP.GD.KD', 'CO2 emissions (kg per 2017 PPP $ of GDP)', ['Climate', 'Env']],
    ['EN.ATM.CO2E.SF.KT', 'CO2 emissions from solid fuel consumption (kt) ', ['Climate', 'Env']],
    ['EN.ATM.CO2E.SF.ZS', 'CO2 emissions from solid fuel consumption (% of total)', ['Climate', 'Env']],
    ['EN.ATM.GHGO.KT.CE', 'Other greenhouse gas emissions, HFC, PFC and SF6 (thousand metric tons of CO2 equivalent)', ['Climate', 'Env']],
    ['EN.ATM.GHGO.ZG', 'Other greenhouse gas emissions (% change from 1990)', ['Climate', 'Env']],
    ['EN.ATM.GHGT.KT.CE', 'Total greenhouse gas emissions (kt of CO2 equivalent)', ['Climate', 'Env']],
    ['EN.ATM.GHGT.ZG', 'Total greenhouse gas emissions (% change from 1990)', ['Climate', 'Env']],
    ['EN.ATM.HFCG.KT.CE', 'HFC gas emissions (thousand metric tons of CO2 equivalent)', ['Climate', 'Env']],
    ['EN.ATM.METH.KT.CE', 'Methane emissions (kt of CO2 equivalent)', ['Climate', 'Env']],
    ['EN.ATM.METH.ZG', 'Methane emissions (% change from 1990)', ['Climate', 'Env']],
    ['EN.ATM.NOXE.KT.CE', 'Nitrous oxide emissions (thousand metric tons of CO2 equivalent)', ['Climate', 'Env']],
    ['EN.ATM.NOXE.ZG', 'Nitrous oxide emissions (% change from 1990)', ['Climate', 'Env']],
    ['EN.ATM.PFCG.KT.CE', 'PFC gas emissions (thousand metric tons of CO2 equivalent)', ['Climate', 'Env']],
    ['EN.ATM.SF6G.KT.CE', 'SF6 gas emissions (thousand metric tons of CO2 equivalent)', ['Climate', 'Env']],
    ['EN.CLC.DRSK.XQ', 'Disaster risk reduction progress score (1-5 scale; 5=best)', ['Climate', 'Env']],
    ['EN.CLC.GHGR.MT.CE', 'GHG net emissions/removals by LUCF (Mt of CO2 equivalent)', ['Climate', 'Env']],
    ['EN.CLC.MDAT.ZS', 'Droughts, floods, extreme temperatures (% of population, average 1990-2009)', ['Climate', 'Env']],
    ['EN.POP.EL5M.RU.ZS', 'Rural population living in areas where elevation is below 5 meters (% of total population)', ['AgriRural', 'Climate', 'Env']],
    ['EN.POP.EL5M.UR.ZS', 'Urban population living in areas where elevation is below 5 meters (% of total population)', ['Climate', 'Urban', 'Env']],
    ['EN.POP.EL5M.ZS', 'Population living in areas where elevation is below 5 meters (% of total population)', ['Climate', 'Env']],
    ['EN.URB.MCTY.TL.ZS', 'Population in urban agglomerations of more than 1 million (% of total population)', ['Climate', 'Urban']],
    ['ER.H2O.FWTL.K3', 'Annual freshwater withdrawals, total (billion cubic meters)', ['Climate', 'Infras', 'Env']],
    ['ER.H2O.FWTL.ZS', 'Annual freshwater withdrawals, total (% of internal resources)', ['Climate', 'Infras', 'Env']],
    ['ER.LND.PTLD.ZS', 'Terrestrial protected areas (% of total land area)', ['Climate', 'Env']],
    ['ER.MRN.PTMR.ZS', 'Marine protected areas (% of territorial waters)', ['Climate', 'Env']],
    ['ER.PTD.TOTL.ZS', 'Terrestrial and marine protected areas (% of total territorial area)', ['Climate', 'Env']],
    ['IC.BUS.EASE.XQ', 'Ease of doing business index (1=most business-friendly regulations)', ['Climate', 'Private']],
    ['IQ.CPA.PUBS.XQ', 'CPIA public sector management and institutions cluster average (1=low to 6=high)', ['Climate', 'Public']],
    ['IS.ROD.PAVE.ZS', 'Roads, paved (% of total roads)', ['Infras', 'Climate']],
    ['NV.AGR.TOTL.ZS', 'Agriculture, forestry, and fishing, value added (% of GDP)', ['AgriRural', 'Econ', 'Climate']],
    ['SE.ENR.PRSC.FM.ZS', 'School enrollment, primary and secondary (gross), gender parity index (GPI)', ['Aid', 'Climate', 'Edu', 'Gender', 'Social']],
    ['SE.PRM.CMPT.ZS', 'Primary completion rate, total (% of relevant age group)', ['Aid', 'Climate', 'Edu']],
    ['SH.DYN.MORT', 'Mortality rate, under-5 (per 1,000 live births)', ['Health', 'Aid', 'Climate']],
    ['SH.H2O.SAFE.RU.ZS', 'Improved water source, rural (% of rural population with access)', ['AgriRural', 'Climate', 'Infras', 'Health']],
    ['SH.H2O.SAFE.UR.ZS', 'Improved water source, urban (% of urban population with access)', ['Climate', 'Infras', 'Health', 'Urban']],
    ['SH.H2O.SAFE.ZS', 'Improved water source (% of population with access)', ['Climate', 'Infras', 'Health']],
    ['SH.MED.CMHW.P3', 'Community health workers (per 1,000 people)', ['Health', 'Climate']],
    ['SH.MLR.INCD', 'Notified cases of malaria (per 100,000 people)', ['Health', 'Climate']],
    ['SH.STA.ACSN', 'Improved sanitation facilities (% of population with access)', ['Health', 'Aid', 'Climate']],
    ['SH.STA.MALN.ZS', 'Prevalence of underweight, weight for age (% of children under 5)', ['Health', 'Climate']],
    ['SI.POV.DDAY', 'Poverty headcount ratio at $1.90 a day (2011 PPP) (% of population)', ['Poverty', 'Aid', 'Climate']],
    ['SP.POP.GROW', 'Population growth (annual %)', ['Climate', 'Health']],
    ['SP.POP.TOTL', 'Population, total', ['Climate', 'Health']],
    ['SP.URB.GROW', 'Urban population growth (annual %)', ['Climate', 'Urban']],
    ['SP.URB.TOTL', 'Urban population', ['Climate', 'Urban']],
    ['SP.URB.TOTL.IN.ZS', 'Urban population (% of total population)', ['Climate', 'Urban']],
  ],
}