export const EconomyAndGrowth = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['5.0.AMeanIncGr.All'       , 'Annualized Mean Income Growth (2004-2014)'                                                  , ['Econ']                        ], 
    ['5.0.AMeanIncGr.B40'       , 'Annualized Mean Income Growth Bottom 40 Percent (2004-2014)'                                , ['Econ']                        ], 
    ['5.1.AMeanIncGr.All'       , 'Annualized Mean Income Growth (2004-2009)'                                                  , ['Econ']                        ], 
    ['5.1.AMeanIncGr.B40'       , 'Annualized Mean Income Growth Bottom 40 Percent (2004-2009)'                                , ['Econ']                        ], 
    ['5.2.AMeanIncGr.All'       , 'Annualized Mean Income Growth (2009-2014)'                                                  , ['Econ']                        ], 
    ['5.2.AMeanIncGr.B40'       , 'Annualized Mean Income Growth Bottom 40 Percent (2009-2014)'                                , ['Econ']                        ], 
    ['6.0.Conspc'               , 'Consumption per capita (2011 $)'                                                            , ['Econ']                        ], 
    ['6.0.GDP_current'          , 'GDP (current $)'                                                                            , ['Econ']                        ], 
    ['6.0.GDP_growth'           , 'GDP growth (annual %)'                                                                      , ['Econ']                        ], 
    ['6.0.GDP_usd'              , 'GDP (constant 2005 $)'                                                                      , ['Econ']                        ], 
    ['6.0.GDPpc_constant'       , 'GDP per capita, PPP (constant 2011 international $) '                                       , ['Econ']                        ], 
    ['6.0.GNIpc'                , 'GNI per capita (2011 $)'                                                                    , ['Econ']                        ], 
    ['9.0.Labor.B40'            , 'Labor Force Participation Rate (%)-Bottom 40 Percent'                                       , ['Econ']                        ], 
    ['9.0.Labor.T60'            , 'Labor Force Participation Rate (%)-Top 60 Percent'                                          , ['Econ']                        ], 
    ['9.1.Labor.B40'            , 'Labor Force Participation Rate (%)-Bottom 40 Percent, Male'                                 , ['Econ']                        ], 
    ['9.1.Labor.T60'            , 'Labor Force Participation Rate (%)-Top 60 Percent, Male'                                    , ['Econ']                        ], 
    ['9.2.Labor.B40'            , 'Labor Force Participation Rate (%)-Bottom 40 Percent, Female'                               , ['Econ']                        ], 
    ['9.2.Labor.T60'            , 'Labor Force Participation Rate (%)-Top 60 Percent, Female'                                  , ['Econ']                        ], 
    ['BG.GSR.NFSV.GD.ZS'        , 'Trade in services (% of GDP)'                                                               , ['Econ', 'Private', 'Trade']    ], 
    ['BM.GSR.CMCP.ZS'           , 'Communications, computer, etc. (% of service imports, BoP)'                                 , ['Econ', 'Trade']               ], 
    ['BM.GSR.FCTY.CD'           , 'Primary income payments (BoP, current US$)'                                                 , ['Econ']                        ], 
    ['BM.GSR.GNFS.CD'           , 'Imports of goods and services (BoP, current US$)'                                           , ['Econ', 'Trade']               ], 
    ['BM.GSR.INSF.ZS'           , 'Insurance and financial services (% of service imports, BoP)'                               , ['Econ', 'Private', 'Trade']    ], 
    ['BM.GSR.MRCH.CD'           , 'Goods imports (BoP, current US$)'                                                           , ['Econ', 'Trade']               ], 
    ['BM.GSR.NFSV.CD'           , 'Service imports (BoP, current US$)'                                                         , ['Econ', 'Trade']               ], 
    ['BM.GSR.ROYL.CD'           , 'Charges for the use of intellectual property, payments (BoP, current US$)'                  , ['Econ', 'Stem']                ], 
    ['BM.GSR.TOTL.CD'           , 'Imports of goods, services and primary income (BoP, current US$)'                           , ['Econ', 'Debt', 'Trade']       ], 
    ['BM.GSR.TRAN.ZS'           , 'Transport services (% of service imports, BoP)'                                             , ['Econ', 'Trade']               ], 
    ['BM.GSR.TRVL.ZS'           , 'Travel services (% of service imports, BoP)'                                                , ['Econ', 'Trade']               ], 
    ['BM.KLT.DINV.CD.WD'        , 'Foreign direct investment, net outflows (BoP, current US$)'                                 , ['Econ', 'Fin']                 ], 
    ['BM.KLT.DINV.WD.GD.ZS'     , 'Foreign direct investment, net outflows (% of GDP)'                                         , ['Econ', 'Fin']                 ], 
    ['BM.TRF.PRVT.CD'           , 'Secondary income, other sectors, payments (BoP, current US$)'                               , ['Econ']                        ], 
    ['BM.TRF.PWKR.CD.DT'        , 'Personal remittances, paid (current US$)'                                                   , ['Econ', 'Fin']                 ], 
    ['BN.CAB.XOKA.CD'           , 'Current account balance (BoP, current US$)'                                                 , ['Econ', 'Debt']                ], 
    ['BN.CAB.XOKA.GD.ZS'        , 'Current account balance (% of GDP)'                                                         , ['Econ']                        ], 
    ['BN.FIN.TOTL.CD'           , 'Net financial account (BoP, current US$)'                                                   , ['Econ']                        ], 
    ['BN.GSR.FCTY.CD'           , 'Net primary income (BoP, current US$)'                                                      , ['Econ']                        ], 
    ['BN.GSR.GNFS.CD'           , 'Net trade in goods and services (BoP, current US$)'                                         , ['Econ', 'Trade']               ], 
    ['BN.GSR.MRCH.CD'           , 'Net trade in goods (BoP, current US$)'                                                      , ['Econ', 'Trade']               ], 
    ['BN.KAC.EOMS.CD'           , 'Net errors and omissions (BoP, current US$)'                                                , ['Econ']                        ], 
    ['BN.KLT.DINV.CD'           , 'Foreign direct investment, net (BoP, current US$)'                                          , ['Econ', 'Fin']                 ], 
    ['BN.KLT.PRVT.CD'           , 'Private capital flows, total (BoP, current US$)'                                            , ['Econ']                        ], 
    ['BN.KLT.PRVT.GD.ZS'        , 'Private capital flows, total (% of GDP)'                                                    , ['Econ']                        ], 
    ['BN.KLT.PTXL.CD'           , 'Portfolio Investment, net (BoP, current US$)'                                               , ['Econ', 'Fin']                 ], 
    ['BN.RES.INCL.CD'           , 'Reserves and related items (BoP, current US$)'                                              , ['Econ']                        ], 
    ['BN.TRF.CURR.CD'           , 'Net secondary income (BoP, current US$)'                                                    , ['Econ']                        ], 
    ['BN.TRF.KOGT.CD'           , 'Net capital account (BoP, current US$)'                                                     , ['Econ']                        ], 
    ['BX.GRT.EXTA.CD.WD'        , 'Grants, excluding technical cooperation (BoP, current US$)'                                 , ['Econ', 'Debt', 'Aid']         ], 
    ['BX.GRT.TECH.CD.WD'        , 'Technical cooperation grants (BoP, current US$)'                                            , ['Econ', 'Debt', 'Aid']         ], 
    ['BX.GSR.CCIS.CD'           , 'ICT service exports (BoP, current US$)'                                                     , ['Econ', 'Infras', 'Trade']     ], 
    ['BX.GSR.CCIS.ZS'           , 'ICT service exports (% of service exports, BoP)'                                            , ['Econ', 'Infras', 'Trade']     ], 
    ['BX.GSR.CMCP.ZS'           , 'Communications, computer, etc. (% of service exports, BoP)'                                 , ['Econ', 'Trade']               ], 
    ['BX.GSR.FCTY.CD'           , 'Primary income receipts (BoP, current US$)'                                                 , ['Econ']                        ], 
    ['BX.GSR.GNFS.CD'           , 'Exports of goods and services (BoP, current US$)'                                           , ['Econ', 'Trade']               ], 
    ['BX.GSR.INCL.CD'           , 'Exports of goods, services, income and workers\' remittances (BoP, current US$)'            , ['Econ']                        ], 
    ['BX.GSR.INSF.ZS'           , 'Insurance and financial services (% of service exports, BoP)'                               , ['Econ', 'Private', 'Trade']    ], 
    ['BX.GSR.MRCH.CD'           , 'Goods exports (BoP, current US$)'                                                           , ['Econ', 'Trade']               ], 
    ['BX.GSR.NFSV.CD'           , 'Service exports (BoP, current US$)'                                                         , ['Econ', 'Trade']               ], 
    ['BX.GSR.ROYL.CD'           , 'Charges for the use of intellectual property, receipts (BoP, current US$)'                  , ['Econ', 'Stem']                ], 
    ['BX.GSR.TOTL.CD'           , 'Exports of goods, services and primary income (BoP, current US$)'                           , ['Econ', 'Debt', 'Trade']       ], 
    ['BX.GSR.TRAN.ZS'           , 'Transport services (% of service exports, BoP)'                                             , ['Econ', 'Trade']               ], 
    ['BX.GSR.TRVL.ZS'           , 'Travel services (% of service exports, BoP)'                                                , ['Econ', 'Trade']               ], 
    ['BX.KLT.DINV.CD.WD'        , 'Foreign direct investment, net inflows (BoP, current US$)'                                  , ['Econ', 'Fin', 'Debt']         ], 
    ['BX.KLT.DINV.WD.GD.ZS'     , 'Foreign direct investment, net inflows (% of GDP)'                                          , ['Econ', 'Fin', 'Climate']      ], 
    ['BX.KLT.DREM.CD.DT'        , 'Primary income on FDI (current US$)'                                                        , ['Econ', 'Fin', 'Debt']         ], 
    ['BX.PEF.TOTL.CD.WD'        , 'Portfolio equity, net inflows (BoP, current US$)'                                           , ['Econ', 'Fin', 'Debt']         ], 
    ['BX.TRF.CURR.CD'           , 'Secondary income receipts (BoP, current US$)'                                               , ['Econ']                        ], 
    ['BX.TRF.PWKR.CD'           , 'Personal transfers, receipts (BoP, current US$)'                                            , ['Econ', 'Fin']                 ], 
    ['BX.TRF.PWKR.CD.DT'        , 'Personal remittances, received (current US$)'                                               , ['Econ', 'Fin', 'Debt']         ], 
    ['BX.TRF.PWKR.DT.GD.ZS'     , 'Personal remittances, received (% of GDP)'                                                  , ['Econ', 'Fin']                 ], 
    ['DT.DOD.DECT.CD'           , 'External debt stocks, total (DOD, current US$)'                                             , ['Econ', 'Debt']                ], 
    ['DT.DOD.DECT.EX.ZS'        , 'External debt stocks (% of exports of goods, services and primary income)'                  , ['Econ', 'Debt']                ], 
    ['DT.DOD.DECT.GN.ZS'        , 'External debt stocks (% of GNI)'                                                            , ['Econ', 'Debt']                ], 
    ['DT.DOD.DSTC.IR.ZS'        , 'Short-term debt (% of total reserves)'                                                      , ['Econ', 'Debt']                ], 
    ['DT.DOD.DSTC.XP.ZS'        , 'Short-term debt (% of exports of goods, services and primary income)'                       , ['Econ', 'Debt']                ], 
    ['DT.DOD.PVLX.CD'           , 'Present value of external debt (current US$)'                                               , ['Econ', 'Debt']                ], 
    ['DT.DOD.PVLX.EX.ZS'        , 'Present value of external debt (% of exports of goods, services and primary income)'        , ['Econ', 'Debt']                ], 
    ['DT.DOD.PVLX.GN.ZS'        , 'Present value of external debt (% of GNI)'                                                  , ['Econ', 'Debt']                ], 
    ['DT.INT.DECT.EX.ZS'        , 'Interest payments on external debt (% of exports of goods, services and primary income)'    , ['Econ', 'Debt']                ], 
    ['DT.INT.DECT.GN.ZS'        , 'Interest payments on external debt (% of GNI)'                                              , ['Econ', 'Debt']                ], 
    ['DT.ODA.DACD.HIV.CNTRL.CD' , 'ODA aid disbursements for STD control including HIV/AIDS, DAC donors (current US$)'         , ['Econ']                        ], 
    ['DT.ODA.DACD.HIV.MITI.CD'  , 'ODA aid disbursements for Social mitigation of HIV/AIDS, DAC donors (current US$)'          , ['Econ']                        ], 
    ['DT.ODA.DACD.MLR.CNTRL.CD' , 'ODA aid disbursements for Malaria control, DAC donors total (current US$)'                  , ['Econ']                        ], 
    ['DT.ODA.MULTI.HIV.CNTRL.CD', 'ODA aid disbursements for STD control including HIV/AIDS, Multilateral donors (current US$)', ['Econ']                        ], 
    ['DT.ODA.MULTI.HIV.MITI.CD' , 'ODA aid disbursements for Social mitigation of HIV/AIDS, Multilateral donors (current US$)' , ['Econ']                        ], 
    ['DT.ODA.MULTI.MLR.CNTRL.CD', 'ODA aid disbursements for Malaria control, multilateral donors total (current US$)'         , ['Econ']                        ], 
    ['DT.ODA.ODAT.CD'           , 'Net official development assistance received (current US$)'                                 , ['Aid', 'Econ', 'Debt']         ], 
    ['DT.ODA.ODAT.GN.ZS'        , 'Net ODA received (% of GNI)'                                                                , ['Aid', 'Econ', 'Debt']         ], 
    ['DT.ODA.ODAT.PC.ZS'        , 'Net ODA received per capita (current US$)'                                                  , ['Aid', 'Econ', 'Debt']         ], 
    ['DT.TDS.DECT.EX.ZS'        , 'Total debt service (% of exports of goods, services and primary income)'                    , ['Econ', 'Debt']                ], 
    ['DT.TDS.DECT.GN.ZS'        , 'Total debt service (% of GNI)'                                                              , ['Econ', 'Debt']                ], 
    ['FI.RES.TOTL.CD'           , 'Total reserves (includes gold, current US$)'                                                , ['Econ', 'Fin', 'Debt']         ], 
    ['FI.RES.XGLD.CD'           , 'Total reserves minus gold (current US$)'                                                    , ['Econ', 'Fin']                 ], 
    ['FP.CPI.TOTL.ZG'           , 'Inflation, consumer prices (annual %)'                                                      , ['Econ', 'Fin']                 ], 
    ['GC.DOD.TOTL.GD.ZS'        , 'Central government debt, total (% of GDP)'                                                  , ['Econ', 'Public']              ], 
    ['GC.REV.XGRT.GD.ZS'        , 'Revenue, excluding grants (% of GDP)'                                                       , ['Econ', 'Public']              ], 
    ['GC.XPN.TOTL.GD.ZS'        , 'Expense (% of GDP)'                                                                         , ['Econ', 'Public']              ], 
    ['NE.CON.GOVT.CD'           , 'General government final consumption expenditure (current US$)'                             , ['Econ']                        ], 
    ['NE.CON.GOVT.CN'           , 'General government final consumption expenditure (current LCU)'                             , ['Econ']                        ], 
    ['NE.CON.GOVT.KD'           , 'General government final consumption expenditure (constant 2010 US$)'                       , ['Econ']                        ], 
    ['NE.CON.GOVT.KD.ZG'        , 'General government final consumption expenditure (annual % growth)'                         , ['Econ']                        ], 
    ['NE.CON.GOVT.KN'           , 'General government final consumption expenditure (constant LCU)'                            , ['Econ']                        ], 
    ['NE.CON.GOVT.ZS'           , 'General government final consumption expenditure (% of GDP)'                                , ['Econ']                        ], 
    ['NE.CON.PETC.CD'           , 'Household final consumption expenditure, etc. (current US$)'                                , ['Econ']                        ], 
    ['NE.CON.PETC.CN'           , 'Household final consumption expenditure, etc. (current LCU)'                                , ['Econ']                        ], 
    ['NE.CON.PETC.KD'           , 'Household final consumption expenditure, etc. (constant 2010 US$)'                          , ['Econ']                        ], 
    ['NE.CON.PETC.KD.ZG'        , 'Household final consumption expenditure, etc. (annual % growth)'                            , ['Econ']                        ], 
    ['NE.CON.PETC.KN'           , 'Household final consumption expenditure, etc. (constant LCU)'                               , ['Econ']                        ], 
    ['NE.CON.PETC.ZS'           , 'Household final consumption expenditure, etc. (% of GDP)'                                   , ['Econ']                        ], 
    ['NE.CON.PRVT.CD'           , 'Households and NPISHs Final consumption expenditure (current US$)'                          , ['Econ']                        ], 
    ['NE.CON.PRVT.CN'           , 'Households and NPISHs Final consumption expenditure (current LCU)'                          , ['Econ']                        ], 
    ['NE.CON.PRVT.CN.AD'        , 'Households and NPISHs final consumption expenditure: linked series (current LCU)'           , ['Econ']                        ], 
    ['NE.CON.PRVT.KD'           , 'Households and NPISHs Final consumption expenditure (constant 2010 US$)'                    , ['Econ']                        ], 
    ['NE.CON.PRVT.KD.ZG'        , 'Households and NPISHs Final consumption expenditure (annual % growth)'                      , ['Econ']                        ], 
    ['NE.CON.PRVT.KN'           , 'Households and NPISHs Final consumption expenditure (constant LCU)'                         , ['Econ']                        ], 
    ['NE.CON.PRVT.PC.KD'        , 'Households and NPISHs Final consumption expenditure per capita (constant 2010 US$)'         , ['Econ']                        ], 
    ['NE.CON.PRVT.PC.KD.ZG'     , 'Households and NPISHs Final consumption expenditure per capita growth (annual %)'           , ['Econ']                        ], 
    ['NE.CON.PRVT.PP.CD'        , 'Households and NPISHs Final consumption expenditure, PPP (current international $)'         , ['Econ']                        ], 
    ['NE.CON.PRVT.PP.KD'        , 'Households and NPISHs Final consumption expenditure, PPP (constant 2017 international $)'   , ['Econ']                        ], 
    ['NE.CON.PRVT.ZS'           , 'Households and NPISHs final consumption expenditure (% of GDP)'                             , ['Econ']                        ], 
    ['NE.CON.TETC.CD'           , 'Final consumption expenditure, etc. (current US$)'                                          , ['Econ']                        ], 
    ['NE.CON.TETC.CN'           , 'Final consumption expenditure, etc. (current LCU)'                                          , ['Econ']                        ], 
    ['NE.CON.TETC.KD'           , 'Final consumption expenditure, etc. (constant 2010 US$)'                                    , ['Econ']                        ], 
    ['NE.CON.TETC.KD.ZG'        , 'Final consumption expenditure, etc. (annual % growth)'                                      , ['Econ']                        ], 
    ['NE.CON.TETC.KN'           , 'Final consumption expenditure, etc. (constant LCU)'                                         , ['Econ']                        ], 
    ['NE.CON.TETC.ZS'           , 'Final consumption expenditure, etc. (% of GDP)'                                             , ['Econ']                        ], 
    ['NE.CON.TOTL.CD'           , 'Final consumption expenditure (current US$)'                                                , ['Econ']                        ], 
    ['NE.CON.TOTL.CN'           , 'Final consumption expenditure (current LCU)'                                                , ['Econ']                        ], 
    ['NE.CON.TOTL.KD'           , 'Final consumption expenditure (constant 2010 US$)'                                          , ['Econ']                        ], 
    ['NE.CON.TOTL.KD.ZG'        , 'Final consumption expenditure (annual % growth)'                                            , ['Econ']                        ], 
    ['NE.CON.TOTL.KN'           , 'Final consumption expenditure (constant LCU)'                                               , ['Econ']                        ], 
    ['NE.CON.TOTL.ZS'           , 'Final consumption expenditure (% of GDP)'                                                   , ['Econ']                        ], 
    ['NE.DAB.DEFL.ZS'           , 'Gross national expenditure deflator (base year varies by country)'                          , ['Econ']                        ], 
    ['NE.DAB.TOTL.CD'           , 'Gross national expenditure (current US$)'                                                   , ['Econ']                        ], 
    ['NE.DAB.TOTL.CN'           , 'Gross national expenditure (current LCU)'                                                   , ['Econ']                        ], 
    ['NE.DAB.TOTL.KD'           , 'Gross national expenditure (constant 2010 US$)'                                             , ['Econ']                        ], 
    ['NE.DAB.TOTL.KN'           , 'Gross national expenditure (constant LCU)'                                                  , ['Econ']                        ], 
    ['NE.DAB.TOTL.ZS'           , 'Gross national expenditure (% of GDP)'                                                      , ['Econ']                        ], 
    ['NE.EXP.GNFS.CD'           , 'Exports of goods and services (current US$)'                                                , ['Econ', 'Trade']               ], 
    ['NE.EXP.GNFS.CN'           , 'Exports of goods and services (current LCU)'                                                , ['Econ']                        ], 
    ['NE.EXP.GNFS.KD'           , 'Exports of goods and services (constant 2010 US$)'                                          , ['Econ', 'Trade']               ], 
    ['NE.EXP.GNFS.KD.ZG'        , 'Exports of goods and services (annual % growth)'                                            , ['Econ', 'Trade']               ], 
    ['NE.EXP.GNFS.KN'           , 'Exports of goods and services (constant LCU)'                                               , ['Econ']                        ], 
    ['NE.EXP.GNFS.ZS'           , 'Exports of goods and services (% of GDP)'                                                   , ['Econ', 'Trade']               ], 
    ['NE.GDI.FPRV.CN'           , 'Gross fixed capital formation, private sector (current LCU)'                                , ['Econ']                        ], 
    ['NE.GDI.FPRV.ZS'           , 'Gross fixed capital formation, private sector (% of GDP)'                                   , ['Econ']                        ], 
    ['NE.GDI.FTOT.CD'           , 'Gross fixed capital formation (current US$)'                                                , ['Econ']                        ], 
    ['NE.GDI.FTOT.CN'           , 'Gross fixed capital formation (current LCU)'                                                , ['Econ']                        ], 
    ['NE.GDI.FTOT.KD'           , 'Gross fixed capital formation (constant 2010 US$)'                                          , ['Econ']                        ], 
    ['NE.GDI.FTOT.KD.ZG'        , 'Gross fixed capital formation (annual % growth)'                                            , ['Econ']                        ], 
    ['NE.GDI.FTOT.KN'           , 'Gross fixed capital formation (constant LCU)'                                               , ['Econ']                        ], 
    ['NE.GDI.FTOT.ZS'           , 'Gross fixed capital formation (% of GDP)'                                                   , ['Econ']                        ], 
    ['NE.GDI.STKB.CD'           , 'Changes in inventories (current US$)'                                                       , ['Econ']                        ], 
    ['NE.GDI.STKB.CN'           , 'Changes in inventories (current LCU)'                                                       , ['Econ']                        ], 
    ['NE.GDI.STKB.KN'           , 'Changes in inventories (constant LCU)'                                                      , ['Econ']                        ], 
    ['NE.GDI.TOTL.CD'           , 'Gross capital formation (current US$)'                                                      , ['Econ']                        ], 
    ['NE.GDI.TOTL.CN'           , 'Gross capital formation (current LCU)'                                                      , ['Econ']                        ], 
    ['NE.GDI.TOTL.KD'           , 'Gross capital formation (constant 2010 US$)'                                                , ['Econ']                        ], 
    ['NE.GDI.TOTL.KD.ZG'        , 'Gross capital formation (annual % growth)'                                                  , ['Econ']                        ], 
    ['NE.GDI.TOTL.KN'           , 'Gross capital formation (constant LCU)'                                                     , ['Econ']                        ], 
    ['NE.GDI.TOTL.ZS'           , 'Gross capital formation (% of GDP)'                                                         , ['Econ']                        ], 
    ['NE.IMP.GNFS.CD'           , 'Imports of goods and services (current US$)'                                                , ['Econ', 'Trade']               ], 
    ['NE.IMP.GNFS.CN'           , 'Imports of goods and services (current LCU)'                                                , ['Econ']                        ], 
    ['NE.IMP.GNFS.KD'           , 'Imports of goods and services (constant 2010 US$)'                                          , ['Econ', 'Trade']               ], 
    ['NE.IMP.GNFS.KD.ZG'        , 'Imports of goods and services (annual % growth)'                                            , ['Econ', 'Trade']               ], 
    ['NE.IMP.GNFS.KN'           , 'Imports of goods and services (constant LCU)'                                               , ['Econ']                        ], 
    ['NE.IMP.GNFS.ZS'           , 'Imports of goods and services (% of GDP)'                                                   , ['Econ', 'Trade']               ], 
    ['NE.RSB.GNFS.CD'           , 'External balance on goods and services (current US$)'                                       , ['Econ', 'Trade']               ], 
    ['NE.RSB.GNFS.CN'           , 'External balance on goods and services (current LCU)'                                       , ['Econ']                        ], 
    ['NE.RSB.GNFS.KN'           , 'External balance on goods and services (constant LCU)'                                      , ['Econ']                        ], 
    ['NE.RSB.GNFS.ZS'           , 'External balance on goods and services (% of GDP)'                                          , ['Econ', 'Trade']               ], 
    ['NE.TRD.GNFS.ZS'           , 'Trade (% of GDP)'                                                                           , ['Econ', 'Trade']               ], 
    ['NV.AGR.EMPL.KD'           , 'Agriculture, forestry, and fishing, value added per worker (constant 2010 US$)'             , ['Econ']                        ], 
    ['NV.AGR.TOTL.CD'           , 'Agriculture, forestry, and fishing, value added (current US$)'                              , ['AgriRural', 'Econ']           ], 
    ['NV.AGR.TOTL.CN'           , 'Agriculture, forestry, and fishing, value added (current LCU)'                              , ['Econ']                        ], 
    ['NV.AGR.TOTL.KD'           , 'Agriculture, forestry, and fishing, value added (constant 2010 US$)'                        , ['Econ']                        ], 
    ['NV.AGR.TOTL.KD.ZG'        , 'Agriculture, forestry, and fishing, value added (annual % growth)'                          , ['Econ']                        ], 
    ['NV.AGR.TOTL.KN'           , 'Agriculture, forestry, and fishing, value added (constant LCU)'                             , ['Econ']                        ], 
    ['NV.AGR.TOTL.ZS'           , 'Agriculture, forestry, and fishing, value added (% of GDP)'                                 , ['AgriRural', 'Econ', 'Climate']], 
    ['NV.FSM.TOTL.CN'           , 'Financial intermediary services indirectly Measured (FISIM) (current LCU)'                  , ['Econ']                        ], 
    ['NV.FSM.TOTL.KN'           , 'Financial intermediary services indirectly Measured (FISIM) (constant LCU)'                 , ['Econ']                        ], 
    ['NV.IND.EMPL.KD'           , 'Industry (including construction), value added per worker (constant 2010 US$)'              , ['Econ']                        ], 
    ['NV.IND.MANF.CD'           , 'Manufacturing, value added (current US$)'                                                   , ['Econ']                        ], 
    ['NV.IND.MANF.CN'           , 'Manufacturing, value added (current LCU)'                                                   , ['Econ']                        ], 
    ['NV.IND.MANF.KD'           , 'Manufacturing, value added (constant 2010 US$)'                                             , ['Econ']                        ], 
    ['NV.IND.MANF.KD.ZG'        , 'Manufacturing, value added (annual % growth)'                                               , ['Econ']                        ], 
    ['NV.IND.MANF.KN'           , 'Manufacturing, value added (constant LCU)'                                                  , ['Econ']                        ], 
    ['NV.IND.MANF.ZS'           , 'Manufacturing, value added (% of GDP)'                                                      , ['Econ']                        ], 
    ['NV.IND.TOTL.CD'           , 'Industry (including construction), value added (current US$)'                               , ['Econ']                        ], 
    ['NV.IND.TOTL.CN'           , 'Industry (including construction), value added (current LCU)'                               , ['Econ']                        ], 
    ['NV.IND.TOTL.KD'           , 'Industry (including construction), value added (constant 2010 US$)'                         , ['Econ']                        ], 
    ['NV.IND.TOTL.KD.ZG'        , 'Industry (including construction), value added (annual % growth)'                           , ['Econ']                        ], 
    ['NV.IND.TOTL.KN'           , 'Industry (including construction), value added (constant LCU)'                              , ['Econ']                        ], 
    ['NV.IND.TOTL.ZS'           , 'Industry (including construction), value added (% of GDP)'                                  , ['Econ']                        ], 
    ['NV.MNF.CHEM.ZS.UN'        , 'Chemicals (% of value added in manufacturing)'                                              , ['Econ']                        ], 
    ['NV.MNF.FBTO.ZS.UN'        , 'Food, beverages and tobacco (% of value added in manufacturing)'                            , ['Econ']                        ], 
    ['NV.MNF.MTRN.ZS.UN'        , 'Machinery and transport equipment (% of value added in manufacturing)'                      , ['Econ']                        ], 
    ['NV.MNF.OTHR.ZS.UN'        , 'Other manufacturing (% of value added in manufacturing)'                                    , ['Econ']                        ], 
    ['NV.MNF.TECH.ZS.UN'        , 'Medium and high-tech Industry (including construction) (% manufacturing value added)'       , ['Econ']                        ], 
    ['NV.MNF.TXTL.ZS.UN'        , 'Textiles and clothing (% of value added in manufacturing)'                                  , ['Econ']                        ], 
    ['NV.SRV.EMPL.KD'           , 'Services, value added per worker (constant 2010 US$)'                                       , ['Econ']                        ], 
    ['NV.SRV.TETC.CD'           , 'Services, etc., value added (current US$)'                                                  , ['Econ']                        ], 
    ['NV.SRV.TETC.CN'           , 'Services, etc., value added (current LCU)'                                                  , ['Econ']                        ], 
    ['NV.SRV.TETC.KD'           , 'Services, etc., value added (constant 2010 US$)'                                            , ['Econ']                        ], 
    ['NV.SRV.TETC.KD.ZG'        , 'Services, etc., value added (annual % growth)'                                              , ['Econ']                        ], 
    ['NV.SRV.TETC.KN'           , 'Services, etc., value added (constant LCU)'                                                 , ['Econ']                        ], 
    ['NV.SRV.TETC.ZS'           , 'Services, etc., value added (% of GDP)'                                                     , ['Econ']                        ], 
    ['NV.SRV.TOTL.CD'           , 'Services, value added (current US$)'                                                        , ['Econ']                        ], 
    ['NV.SRV.TOTL.CN'           , 'Services, value added (current LCU)'                                                        , ['Econ']                        ], 
    ['NV.SRV.TOTL.KD'           , 'Services, value added (constant 2010 US$)'                                                  , ['Econ']                        ], 
    ['NV.SRV.TOTL.KD.ZG'        , 'Services, value added (annual % growth)'                                                    , ['Econ']                        ], 
    ['NV.SRV.TOTL.KN'           , 'Services, value added (constant LCU)'                                                       , ['Econ']                        ], 
    ['NV.SRV.TOTL.ZS'           , 'Services, value added (% of GDP)'                                                           , ['Econ']                        ], 
    ['NY.ADJ.AEDU.CD'           , 'Adjusted savings: education expenditure (current US$)'                                      , ['Econ', 'Env']                 ], 
    ['NY.ADJ.AEDU.GN.ZS'        , 'Adjusted savings: education expenditure (% of GNI)'                                         , ['Econ', 'Env']                 ], 
    ['NY.ADJ.DCO2.CD'           , 'Adjusted savings: carbon dioxide damage (current US$)'                                      , ['Econ', 'Env']                 ], 
    ['NY.ADJ.DCO2.GN.ZS'        , 'Adjusted savings: carbon dioxide damage (% of GNI)'                                         , ['Econ', 'Env']                 ], 
    ['NY.ADJ.DFOR.CD'           , 'Adjusted savings: net forest depletion (current US$)'                                       , ['Econ', 'Env']                 ], 
    ['NY.ADJ.DFOR.GN.ZS'        , 'Adjusted savings: net forest depletion (% of GNI)'                                          , ['Econ', 'Env']                 ], 
    ['NY.ADJ.DKAP.CD'           , 'Adjusted savings: consumption of fixed capital (current US$)'                               , ['Econ', 'Env']                 ], 
    ['NY.ADJ.DKAP.GN.ZS'        , 'Adjusted savings: consumption of fixed capital (% of GNI)'                                  , ['Econ', 'Env']                 ], 
    ['NY.ADJ.DMIN.CD'           , 'Adjusted savings: mineral depletion (current US$)'                                          , ['Econ', 'Energy', 'Env']       ], 
    ['NY.ADJ.DMIN.GN.ZS'        , 'Adjusted savings: mineral depletion (% of GNI)'                                             , ['Econ', 'Energy', 'Env']       ], 
    ['NY.ADJ.DNGY.CD'           , 'Adjusted savings: energy depletion (current US$)'                                           , ['Econ', 'Energy', 'Env']       ], 
    ['NY.ADJ.DNGY.GN.ZS'        , 'Adjusted savings: energy depletion (% of GNI)'                                              , ['Econ', 'Energy', 'Env']       ], 
    ['NY.ADJ.DPEM.CD'           , 'Adjusted savings: particulate emission damage (current US$)'                                , ['Econ', 'Env']                 ], 
    ['NY.ADJ.DPEM.GN.ZS'        , 'Adjusted savings: particulate emission damage (% of GNI)'                                   , ['Econ', 'Env']                 ], 
    ['NY.ADJ.DRES.GN.ZS'        , 'Adjusted savings: natural resources depletion (% of GNI)'                                   , ['Econ', 'Energy']              ], 
    ['NY.ADJ.ICTR.GN.ZS'        , 'Adjusted savings: gross savings (% of GNI)'                                                 , ['Econ', 'Env']                 ], 
    ['NY.ADJ.NNAT.CD'           , 'Adjusted savings: net national savings (current US$)'                                       , ['Econ', 'Env']                 ], 
    ['NY.ADJ.NNAT.GN.ZS'        , 'Adjusted savings: net national savings (% of GNI)'                                          , ['Econ', 'Env']                 ], 
    ['NY.ADJ.NNTY.CD'           , 'Adjusted net national income (current US$)'                                                 , ['Econ']                        ], 
    ['NY.ADJ.NNTY.KD'           , 'Adjusted net national income (constant 2010 US$)'                                           , ['Econ']                        ], 
    ['NY.ADJ.NNTY.KD.ZG'        , 'Adjusted net national income (annual % growth)'                                             , ['Econ']                        ], 
    ['NY.ADJ.NNTY.PC.CD'        , 'Adjusted net national income per capita (current US$)'                                      , ['Econ']                        ], 
    ['NY.ADJ.NNTY.PC.KD'        , 'Adjusted net national income per capita (constant 2010 US$)'                                , ['Econ']                        ], 
    ['NY.ADJ.NNTY.PC.KD.ZG'     , 'Adjusted net national income per capita (annual % growth)'                                  , ['Econ']                        ], 
    ['NY.ADJ.SVNG.CD'           , 'Adjusted net savings, including particulate emission damage (current US$)'                  , ['Econ', 'Env']                 ], 
    ['NY.ADJ.SVNG.GN.ZS'        , 'Adjusted net savings, including particulate emission damage (% of GNI)'                     , ['Econ', 'Env']                 ], 
    ['NY.ADJ.SVNX.CD'           , 'Adjusted net savings, excluding particulate emission damage (current US$)'                  , ['Econ', 'Env']                 ], 
    ['NY.ADJ.SVNX.GN.ZS'        , 'Adjusted net savings, excluding particulate emission damage (% of GNI)'                     , ['Econ', 'Env']                 ], 
    ['NY.EXP.CAPM.KN'           , 'Exports as a capacity to import (constant LCU)'                                             , ['Econ', 'Trade']               ], 
    ['NY.GDP.DEFL.KD.ZG'        , 'Inflation, GDP deflator (annual %)'                                                         , ['Econ']                        ], 
    ['NY.GDP.DEFL.ZS'           , 'GDP deflator (base year varies by country)'                                                 , ['Econ']                        ], 
    ['NY.GDP.DISC.CN'           , 'Discrepancy in expenditure estimate of GDP (current LCU)'                                   , ['Econ']                        ], 
    ['NY.GDP.DISC.KN'           , 'Discrepancy in expenditure estimate of GDP (constant LCU)'                                  , ['Econ']                        ], 
    ['NY.GDP.FCST.CD'           , 'Gross value added at basic prices (GVA) (current US$)'                                      , ['Econ']                        ], 
    ['NY.GDP.FCST.CN'           , 'Gross value added at basic prices (GVA) (current LCU)'                                      , ['Econ']                        ], 
    ['NY.GDP.FCST.KD'           , 'Gross value added at basic prices (GVA) (constant 2010 US$)'                                , ['Econ']                        ], 
    ['NY.GDP.FCST.KN'           , 'Gross value added at basic prices (GVA) (constant LCU)'                                     , ['Econ']                        ], 
    ['NY.GDP.MKTP.CD'           , 'GDP (current US$)'                                                                          , ['Econ']                        ], 
    ['NY.GDP.MKTP.CN'           , 'GDP (current LCU)'                                                                          , ['Econ']                        ], 
    ['NY.GDP.MKTP.CN.AD'        , 'GDP: linked series (current LCU)'                                                           , ['Econ']                        ], 
    ['NY.GDP.MKTP.KD'           , 'GDP (constant 2010 US$)'                                                                    , ['Econ']                        ], 
    ['NY.GDP.MKTP.KD.ZG'        , 'GDP growth (annual %)'                                                                      , ['Econ']                        ], 
    ['NY.GDP.MKTP.KN'           , 'GDP (constant LCU)'                                                                         , ['Econ']                        ], 
    ['NY.GDP.MKTP.PP.CD'        , 'GDP, PPP (current international $)'                                                         , ['Econ']                        ], 
    ['NY.GDP.MKTP.PP.KD'        , 'GDP, PPP (constant 2017 international $)'                                                   , ['Econ']                        ], 
    ['NY.GDP.PCAP.CD'           , 'GDP per capita (current US$)'                                                               , ['Econ']                        ], 
    ['NY.GDP.PCAP.CN'           , 'GDP per capita (current LCU)'                                                               , ['Econ']                        ], 
    ['NY.GDP.PCAP.KD'           , 'GDP per capita (constant 2010 US$)'                                                         , ['Econ']                        ], 
    ['NY.GDP.PCAP.KD.ZG'        , 'GDP per capita growth (annual %)'                                                           , ['Econ']                        ], 
    ['NY.GDP.PCAP.KN'           , 'GDP per capita (constant LCU)'                                                              , ['Econ']                        ], 
    ['NY.GDP.PCAP.PP.CD'        , 'GDP per capita, PPP (current international $)'                                              , ['Econ']                        ], 
    ['NY.GDP.PCAP.PP.KD'        , 'GDP per capita, PPP (constant 2017 international $)'                                        , ['Econ']                        ], 
    ['NY.GDS.TOTL.CD'           , 'Gross domestic savings (current US$)'                                                       , ['Econ']                        ], 
    ['NY.GDS.TOTL.CN'           , 'Gross domestic savings (current LCU)'                                                       , ['Econ']                        ], 
    ['NY.GDS.TOTL.ZS'           , 'Gross domestic savings (% of GDP)'                                                          , ['Econ']                        ], 
    ['NY.GDY.TOTL.KN'           , 'Gross domestic income (constant LCU)'                                                       , ['Econ']                        ], 
    ['NY.GNP.ATLS.CD'           , 'GNI, Atlas method (current US$)'                                                            , ['Econ']                        ], 
    ['NY.GNP.MKTP.CD'           , 'GNI (current US$)'                                                                          , ['Econ', 'Debt']                ], 
    ['NY.GNP.MKTP.CN'           , 'GNI (current LCU)'                                                                          , ['Econ']                        ], 
    ['NY.GNP.MKTP.CN.AD'        , 'GNI: linked series (current LCU)'                                                           , ['Econ']                        ], 
    ['NY.GNP.MKTP.KD'           , 'GNI (constant 2010 US$)'                                                                    , ['Econ']                        ], 
    ['NY.GNP.MKTP.KD.ZG'        , 'GNI growth (annual %)'                                                                      , ['Econ']                        ], 
    ['NY.GNP.MKTP.KN'           , 'GNI (constant LCU)'                                                                         , ['Econ']                        ], 
    ['NY.GNP.MKTP.PP.CD'        , 'GNI, PPP (current international $)'                                                         , ['Econ']                        ], 
    ['NY.GNP.MKTP.PP.KD'        , 'GNI, PPP (constant 2017 international $)'                                                   , ['Econ']                        ], 
    ['NY.GNP.PCAP.CD'           , 'GNI per capita, Atlas method (current US$)'                                                 , ['Econ']                        ], 
    ['NY.GNP.PCAP.CN'           , 'GNI per capita (current LCU)'                                                               , ['Econ']                        ], 
    ['NY.GNP.PCAP.KD'           , 'GNI per capita (constant 2010 US$)'                                                         , ['Econ']                        ], 
    ['NY.GNP.PCAP.KD.ZG'        , 'GNI per capita growth (annual %)'                                                           , ['Econ']                        ], 
    ['NY.GNP.PCAP.KN'           , 'GNI per capita (constant LCU)'                                                              , ['Econ']                        ], 
    ['NY.GNP.PCAP.PP.CD'        , 'GNI per capita, PPP (current international $)'                                              , ['Econ']                        ], 
    ['NY.GNP.PCAP.PP.KD'        , 'GNI per capita, PPP (constant 2017 international $)'                                        , ['Econ']                        ], 
    ['NY.GNS.ICTR.CD'           , 'Gross savings (current US$)'                                                                , ['Econ']                        ], 
    ['NY.GNS.ICTR.CN'           , 'Gross savings (current LCU)'                                                                , ['Econ']                        ], 
    ['NY.GNS.ICTR.GN.ZS'        , 'Gross savings (% of GNI)'                                                                   , ['Econ']                        ], 
    ['NY.GNS.ICTR.ZS'           , 'Gross savings (% of GDP)'                                                                   , ['Econ']                        ], 
    ['NY.GNY.TOTL.KN'           , 'Gross national income (constant LCU)'                                                       , ['Econ']                        ], 
    ['NY.GSR.NFCY.CD'           , 'Net primary income (Net income from abroad) (current US$)'                                  , ['Econ']                        ], 
    ['NY.GSR.NFCY.CN'           , 'Net primary income (Net income from abroad) (current LCU)'                                  , ['Econ']                        ], 
    ['NY.GSR.NFCY.KN'           , 'Net primary income (Net income from abroad) (constant LCU)'                                 , ['Econ']                        ], 
    ['NY.TAX.NIND.CD'           , 'Taxes less subsidies on products (current US$)'                                             , ['Econ']                        ], 
    ['NY.TAX.NIND.CN'           , 'Taxes less subsidies on products (current LCU)'                                             , ['Econ']                        ], 
    ['NY.TAX.NIND.KN'           , 'Taxes less subsidies on products (constant LCU)'                                            , ['Econ']                        ], 
    ['NY.TRF.NCTR.CD'           , 'Net secondary income (Net current transfers from abroad) (current US$)'                     , ['Econ']                        ], 
    ['NY.TRF.NCTR.CN'           , 'Net secondary income (Net current transfers from abroad) (current LCU)'                     , ['Econ']                        ], 
    ['NY.TRF.NCTR.KN'           , 'Net secondary income (Net current transfers from abroad) (constant LCU)'                    , ['Econ']                        ], 
    ['NY.TTF.GNFS.KN'           , 'Terms of trade adjustment (constant LCU)'                                                   , ['Econ']                        ], 
    ['PA.NUS.ATLS'              , 'DEC alternative conversion factor (LCU per US$)'                                            , ['Econ', 'Fin']                 ], 
    ['PA.NUS.PPP'               , 'PPP conversion factor, GDP (LCU per international $)'                                       , ['Econ']                        ], 
    ['PA.NUS.PPP.05'            , '2005 PPP conversion factor, GDP (LCU per international $)'                                  , ['Econ']                        ], 
    ['PA.NUS.PPPC.RF'           , 'Price level ratio of PPP conversion factor (GDP) to market exchange rate'                   , ['Econ']                        ], 
    ['PA.NUS.PRVT.PP'           , 'PPP conversion factor, private consumption (LCU per international $)'                       , ['Econ']                        ], 
    ['PA.NUS.PRVT.PP.05'        , '2005 PPP conversion factor, private consumption (LCU per international $)'                  , ['Econ']                        ], 
  ], 
}