export const EnergyAndMining = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['EG.EGY.PRIM.PP.KD'   , 'Energy intensity level of primary energy (MJ/$2011 PPP GDP)'                        , ['Energy', 'Env']              ], 
    ['EG.ELC.ACCS.RU.ZS'   , 'Access to electricity, rural (% of rural population)'                               , ['AgriRural', 'Energy']        ], 
    ['EG.ELC.ACCS.UR.ZS'   , 'Access to electricity, urban (% of urban population)'                               , ['Energy', 'Urban']            ], 
    ['EG.ELC.ACCS.ZS'      , 'Access to electricity (% of population)'                                            , ['Energy', 'Climate', 'Env']   ], 
    ['EG.ELC.COAL.ZS'      , 'Electricity production from coal sources (% of total)'                              , ['Energy', 'Climate', 'Infras']], 
    ['EG.ELC.FOSL.ZS'      , 'Electricity production from oil, gas and coal sources (% of total)'                 , ['Energy', 'Env']              ], 
    ['EG.ELC.HYRO.ZS'      , 'Electricity production from hydroelectric sources (% of total)'                     , ['Energy', 'Climate', 'Infras']], 
    ['EG.ELC.LOSS.ZS'      , 'Electric power transmission and distribution losses (% of output)'                  , ['Energy', 'Infras']           ], 
    ['EG.ELC.NGAS.ZS'      , 'Electricity production from natural gas sources (% of total)'                       , ['Energy', 'Climate', 'Infras']], 
    ['EG.ELC.NUCL.ZS'      , 'Electricity production from nuclear sources (% of total)'                           , ['Energy', 'Climate', 'Infras']], 
    ['EG.ELC.PETR.ZS'      , 'Electricity production from oil sources (% of total)'                               , ['Energy', 'Climate', 'Infras']], 
    ['EG.ELC.RNEW.ZS'      , 'Renewable electricity output (% of total electricity output)'                       , ['Energy', 'Climate', 'Env']   ], 
    ['EG.ELC.RNWX.KH'      , 'Electricity production from renewable sources, excluding hydroelectric (kWh)'       , ['Energy', 'Climate', 'Env']   ], 
    ['EG.ELC.RNWX.ZS'      , 'Electricity production from renewable sources, excluding hydroelectric (% of total)', ['Energy', 'Climate', 'Env']   ], 
    ['EG.FEC.RNEW.ZS'      , 'Renewable energy consumption (% of total final energy consumption)'                 , ['Energy', 'Climate', 'Env']   ], 
    ['EG.GDP.PUSE.KO.PP'   , 'GDP per unit of energy use (PPP $ per kg of oil equivalent)'                        , ['Energy']                     ], 
    ['EG.GDP.PUSE.KO.PP.KD', 'GDP per unit of energy use (constant 2017 PPP $ per kg of oil equivalent)'          , ['Energy']                     ], 
    ['EG.IMP.CONS.ZS'      , 'Energy imports, net (% of energy use)'                                              , ['Energy', 'Trade']            ], 
    ['EG.NSF.ACCS.RU.ZS'   , 'Access to non-solid fuel, rural (% of rural population)'                            , ['AgriRural', 'Energy']        ], 
    ['EG.NSF.ACCS.UR.ZS'   , 'Access to non-solid fuel, urban (% of urban population)'                            , ['Energy', 'Urban']            ], 
    ['EG.NSF.ACCS.ZS'      , 'Access to non-solid fuel (% of population)'                                         , ['Energy', 'Env']              ], 
    ['EG.USE.COMM.CL.ZS'   , 'Alternative and nuclear energy (% of total energy use)'                             , ['Energy']                     ], 
    ['EG.USE.COMM.FO.ZS'   , 'Fossil fuel energy consumption (% of total)'                                        , ['Energy']                     ], 
    ['EG.USE.COMM.GD.PP.KD', 'Energy use (kg of oil equivalent) per $1,000 GDP (constant 2017 PPP)'               , ['Energy', 'Climate']          ], 
    ['EG.USE.CRNW.ZS'      , 'Combustible renewables and waste (% of total energy)'                               , ['Energy']                     ], 
    ['EG.USE.ELEC.KH.PC'   , 'Electric power consumption (kWh per capita)'                                        , ['Energy', 'Climate', 'Infras']], 
    ['EG.USE.PCAP.KG.OE'   , 'Energy use (kg of oil equivalent per capita)'                                       , ['Energy', 'Climate']          ], 
    ['EN.ATM.CO2E.GF.ZS'   , 'CO2 emissions from gaseous fuel consumption (% of total) '                          , ['Energy', 'Climate', 'Env']   ], 
    ['EN.ATM.CO2E.LF.KT'   , 'CO2 emissions from liquid fuel consumption (kt) '                                   , ['Energy', 'Climate', 'Env']   ], 
    ['EN.ATM.METH.EG.KT.CE', 'Methane emissions in energy sector (thousand metric tons of CO2 equivalent)'        , ['Energy', 'Env']              ], 
    ['EN.ATM.METH.EG.ZS'   , 'Energy related methane emissions (% of total)'                                      , ['Energy', 'Env']              ], 
    ['EN.ATM.NOXE.EG.KT.CE', 'Nitrous oxide emissions in energy sector (thousand metric tons of CO2 equivalent)'  , ['Energy', 'Env']              ], 
    ['EN.ATM.NOXE.EG.ZS'   , 'Nitrous oxide emissions in energy sector (% of total)'                              , ['Energy', 'Env']              ], 
    ['EP.PMP.DESL.CD'      , 'Pump price for diesel fuel (US$ per liter)'                                         , ['Energy', 'Urban']            ], 
    ['EP.PMP.SGAS.CD'      , 'Pump price for gasoline (US$ per liter)'                                            , ['Energy', 'Urban']            ], 
    ['IC.ELC.DURS'         , 'Time to obtain an electrical connection (days)'                                     , ['Energy', 'Private']          ], 
    ['IC.ELC.TIME'         , 'Time required to get electricity (days)'                                            , ['Energy', 'Private']          ], 
    ['IC.FRM.BNKS.ZS'      , 'Firms using banks to finance investment (% of firms)'                               , ['Energy', 'Private']          ], 
    ['IC.FRM.OUTG.ZS'      , 'Value lost due to electrical outages (% of sales for affected firms)'               , ['Energy', 'Private']          ], 
    ['IE.PPI.ENGY.CD'      , 'Investment in energy with private participation (current US$)'                      , ['Energy', 'Infras', 'Private']], 
    ['NY.ADJ.DMIN.CD'      , 'Adjusted savings: mineral depletion (current US$)'                                  , ['Econ', 'Energy', 'Env']      ], 
    ['NY.ADJ.DMIN.GN.ZS'   , 'Adjusted savings: mineral depletion (% of GNI)'                                     , ['Econ', 'Energy', 'Env']      ], 
    ['NY.ADJ.DNGY.CD'      , 'Adjusted savings: energy depletion (current US$)'                                   , ['Econ', 'Energy', 'Env']      ], 
    ['NY.ADJ.DNGY.GN.ZS'   , 'Adjusted savings: energy depletion (% of GNI)'                                      , ['Econ', 'Energy', 'Env']      ], 
    ['NY.ADJ.DRES.GN.ZS'   , 'Adjusted savings: natural resources depletion (% of GNI)'                           , ['Econ', 'Energy']             ], 
    ['NY.GDP.MINR.RT.ZS'   , 'Mineral rents (% of GDP)'                                                           , ['Energy', 'Env']              ], 
    ['NY.GDP.NGAS.RT.ZS'   , 'Natural gas rents (% of GDP)'                                                       , ['Energy', 'Env']              ], 
    ['NY.GDP.PETR.RT.ZS'   , 'Oil rents (% of GDP)'                                                               , ['Energy', 'Env']              ], 
    ['NY.GDP.TOTL.RT.ZS'   , 'Total natural resources rents (% of GDP)'                                           , ['Energy', 'Env']              ], 
    ['TM.VAL.FUEL.ZS.UN'   , 'Fuel imports (% of merchandise imports)'                                            , ['Energy', 'Private', 'Trade'] ], 
    ['TM.VAL.MMTL.ZS.UN'   , 'Ores and metals imports (% of merchandise imports)'                                 , ['Energy', 'Private', 'Trade'] ], 
    ['TX.VAL.FUEL.ZS.UN'   , 'Fuel exports (% of merchandise exports)'                                            , ['Energy', 'Private', 'Trade'] ], 
    ['TX.VAL.MMTL.ZS.UN'   , 'Ores and metals exports (% of merchandise exports)'                                 , ['Energy', 'Private', 'Trade'] ], 
  ], 
}