export const Environment = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['AG.LND.AGRI.ZS'      , 'Agricultural land (% of land area)'                                                                                               , ['AgriRural', 'Climate', 'Env']], 
    ['AG.LND.ARBL.ZS'      , 'Arable land (% of land area)'                                                                                                     , ['AgriRural', 'Climate', 'Env']], 
    ['AG.LND.EL5M.RU.K2'   , 'Rural land area where elevation is below 5 meters (sq. km)'                                                                       , ['AgriRural', 'Climate', 'Env']], 
    ['AG.LND.EL5M.RU.ZS'   , 'Rural land area where elevation is below 5 meters (% of total land area)'                                                         , ['AgriRural', 'Climate', 'Env']], 
    ['AG.LND.EL5M.UR.K2'   , 'Urban land area where elevation is below 5 meters (sq. km)'                                                                       , ['Climate', 'Urban', 'Env']    ], 
    ['AG.LND.EL5M.UR.ZS'   , 'Urban land area where elevation is below 5 meters (% of total land area)'                                                         , ['Climate', 'Urban', 'Env']    ], 
    ['AG.LND.EL5M.ZS'      , 'Land area where elevation is below 5 meters (% of total land area)'                                                               , ['Climate', 'Env']             ], 
    ['AG.LND.FRST.K2'      , 'Forest area (sq. km)'                                                                                                             , ['AgriRural', 'Climate', 'Env']], 
    ['AG.LND.FRST.ZS'      , 'Forest area (% of land area)'                                                                                                     , ['AgriRural', 'Climate', 'Env']], 
    ['AG.LND.PRCP.MM'      , 'Average precipitation in depth (mm per year)'                                                                                     , ['AgriRural', 'Climate', 'Env']], 
    ['AG.LND.TOTL.K2'      , 'Land area (sq. km)'                                                                                                               , ['AgriRural', 'Env']           ], 
    ['AG.LND.TOTL.RU.K2'   , 'Rural land area (sq. km)'                                                                                                         , ['AgriRural', 'Env']           ], 
    ['AG.LND.TOTL.UR.K2'   , 'Urban land area (sq. km)'                                                                                                         , ['Urban', 'Env']               ], 
    ['AG.SRF.TOTL.K2'      , 'Surface area (sq. km)'                                                                                                            , ['AgriRural', 'Env']           ], 
    ['EE.BOD.TOTL.KG'      , 'Organic water pollutant (BOD) emissions (kg per day)'                                                                             , ['Env']                        ], 
    ['EG.CFT.ACCS.ZS'      , 'Access to clean fuels and technologies for cooking (% of population)'                                                             , ['Env']                        ], 
    ['EG.EGY.PRIM.PP.KD'   , 'Energy intensity level of primary energy (MJ/$2011 PPP GDP)'                                                                      , ['Energy', 'Env']              ], 
    ['EG.ELC.ACCS.ZS'      , 'Access to electricity (% of population)'                                                                                          , ['Energy', 'Climate', 'Env']   ], 
    ['EG.ELC.FOSL.ZS'      , 'Electricity production from oil, gas and coal sources (% of total)'                                                               , ['Energy', 'Env']              ], 
    ['EG.ELC.RNEW.ZS'      , 'Renewable electricity output (% of total electricity output)'                                                                     , ['Energy', 'Climate', 'Env']   ], 
    ['EG.ELC.RNWX.KH'      , 'Electricity production from renewable sources, excluding hydroelectric (kWh)'                                                     , ['Energy', 'Climate', 'Env']   ], 
    ['EG.ELC.RNWX.ZS'      , 'Electricity production from renewable sources, excluding hydroelectric (% of total)'                                              , ['Energy', 'Climate', 'Env']   ], 
    ['EG.FEC.RNEW.ZS'      , 'Renewable energy consumption (% of total final energy consumption)'                                                               , ['Energy', 'Climate', 'Env']   ], 
    ['EG.NSF.ACCS.ZS'      , 'Access to non-solid fuel (% of population)'                                                                                       , ['Energy', 'Env']              ], 
    ['EN.ATM.CO2E.EG.ZS'   , 'CO2 intensity (kg per kg of oil equivalent energy use)'                                                                           , ['Climate', 'Env']             ], 
    ['EN.ATM.CO2E.GF.KT'   , 'CO2 emissions from gaseous fuel consumption (kt) '                                                                                , ['Climate', 'Env']             ], 
    ['EN.ATM.CO2E.GF.ZS'   , 'CO2 emissions from gaseous fuel consumption (% of total) '                                                                        , ['Energy', 'Climate', 'Env']   ], 
    ['EN.ATM.CO2E.KD.GD'   , 'CO2 emissions (kg per 2010 US$ of GDP)'                                                                                           , ['Climate', 'Env']             ], 
    ['EN.ATM.CO2E.KT'      , 'CO2 emissions (kt)'                                                                                                               , ['Climate', 'Env']             ], 
    ['EN.ATM.CO2E.LF.KT'   , 'CO2 emissions from liquid fuel consumption (kt) '                                                                                 , ['Energy', 'Climate', 'Env']   ], 
    ['EN.ATM.CO2E.LF.ZS'   , 'CO2 emissions from liquid fuel consumption (% of total) '                                                                         , ['Climate', 'Env']             ], 
    ['EN.ATM.CO2E.PC'      , 'CO2 emissions (metric tons per capita)'                                                                                           , ['Climate', 'Env']             ], 
    ['EN.ATM.CO2E.PP.GD'   , 'CO2 emissions (kg per PPP $ of GDP)'                                                                                              , ['Climate', 'Env']             ], 
    ['EN.ATM.CO2E.PP.GD.KD', 'CO2 emissions (kg per 2017 PPP $ of GDP)'                                                                                         , ['Climate', 'Env']             ], 
    ['EN.ATM.CO2E.SF.KT'   , 'CO2 emissions from solid fuel consumption (kt) '                                                                                  , ['Climate', 'Env']             ], 
    ['EN.ATM.CO2E.SF.ZS'   , 'CO2 emissions from solid fuel consumption (% of total)'                                                                           , ['Climate', 'Env']             ], 
    ['EN.ATM.GHGO.KT.CE'   , 'Other greenhouse gas emissions, HFC, PFC and SF6 (thousand metric tons of CO2 equivalent)'                                        , ['Climate', 'Env']             ], 
    ['EN.ATM.GHGO.ZG'      , 'Other greenhouse gas emissions (% change from 1990)'                                                                              , ['Climate', 'Env']             ], 
    ['EN.ATM.GHGT.KT.CE'   , 'Total greenhouse gas emissions (kt of CO2 equivalent)'                                                                            , ['Climate', 'Env']             ], 
    ['EN.ATM.GHGT.ZG'      , 'Total greenhouse gas emissions (% change from 1990)'                                                                              , ['Climate', 'Env']             ], 
    ['EN.ATM.HFCG.KT.CE'   , 'HFC gas emissions (thousand metric tons of CO2 equivalent)'                                                                       , ['Climate', 'Env']             ], 
    ['EN.ATM.METH.AG.KT.CE', 'Agricultural methane emissions (thousand metric tons of CO2 equivalent)'                                                          , ['AgriRural', 'Env']           ], 
    ['EN.ATM.METH.AG.ZS'   , 'Agricultural methane emissions (% of total)'                                                                                      , ['AgriRural', 'Env']           ], 
    ['EN.ATM.METH.EG.KT.CE', 'Methane emissions in energy sector (thousand metric tons of CO2 equivalent)'                                                      , ['Energy', 'Env']              ], 
    ['EN.ATM.METH.EG.ZS'   , 'Energy related methane emissions (% of total)'                                                                                    , ['Energy', 'Env']              ], 
    ['EN.ATM.METH.IN.ZS'   , 'Energy related methane emissions (% of total)'                                                                                    , ['Env']                        ], 
    ['EN.ATM.METH.KT.CE'   , 'Methane emissions (kt of CO2 equivalent)'                                                                                         , ['Climate', 'Env']             ], 
    ['EN.ATM.METH.ZG'      , 'Methane emissions (% change from 1990)'                                                                                           , ['Climate', 'Env']             ], 
    ['EN.ATM.NOXE.AG.KT.CE', 'Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent)'                                                    , ['AgriRural', 'Env']           ], 
    ['EN.ATM.NOXE.AG.ZS'   , 'Agricultural nitrous oxide emissions (% of total)'                                                                                , ['AgriRural', 'Env']           ], 
    ['EN.ATM.NOXE.EG.KT.CE', 'Nitrous oxide emissions in energy sector (thousand metric tons of CO2 equivalent)'                                                , ['Energy', 'Env']              ], 
    ['EN.ATM.NOXE.EG.ZS'   , 'Nitrous oxide emissions in energy sector (% of total)'                                                                            , ['Energy', 'Env']              ], 
    ['EN.ATM.NOXE.IN.ZS'   , 'Nitrous oxide emissions in industrial and energy processes (% of total nitrous oxide emissions)'                                  , ['Env']                        ], 
    ['EN.ATM.NOXE.KT.CE'   , 'Nitrous oxide emissions (thousand metric tons of CO2 equivalent)'                                                                 , ['Climate', 'Env']             ], 
    ['EN.ATM.NOXE.ZG'      , 'Nitrous oxide emissions (% change from 1990)'                                                                                     , ['Climate', 'Env']             ], 
    ['EN.ATM.PFCG.KT.CE'   , 'PFC gas emissions (thousand metric tons of CO2 equivalent)'                                                                       , ['Climate', 'Env']             ], 
    ['EN.ATM.PM25.MC.M3'   , 'PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)'                                                           , ['Urban', 'Env']               ], 
    ['EN.ATM.PM25.MC.T1.ZS', 'PM2.5 pollution, population exposed to levels exceeding WHO Interim Target-1 value (% of total)'                                  , ['Env']                        ], 
    ['EN.ATM.PM25.MC.T2.ZS', 'PM2.5 pollution, population exposed to levels exceeding WHO Interim Target-2 value (% of total)'                                  , ['Env']                        ], 
    ['EN.ATM.PM25.MC.T3.ZS', 'PM2.5 pollution, population exposed to levels exceeding WHO Interim Target-3 value (% of total)'                                  , ['Env']                        ], 
    ['EN.ATM.PM25.MC.ZS'   , 'PM2.5 air pollution, population exposed to levels exceeding WHO guideline value (% of total)'                                     , ['Urban', 'Env']               ], 
    ['EN.ATM.SF6G.KT.CE'   , 'SF6 gas emissions (thousand metric tons of CO2 equivalent)'                                                                       , ['Climate', 'Env']             ], 
    ['EN.BIR.THRD.NO'      , 'Bird species, threatened'                                                                                                         , ['Env']                        ], 
    ['EN.CLC.DRSK.XQ'      , 'Disaster risk reduction progress score (1-5 scale; 5=best)'                                                                       , ['Climate', 'Env']             ], 
    ['EN.CLC.GHGR.MT.CE'   , 'GHG net emissions/removals by LUCF (Mt of CO2 equivalent)'                                                                        , ['Climate', 'Env']             ], 
    ['EN.CLC.MDAT.ZS'      , 'Droughts, floods, extreme temperatures (% of population, average 1990-2009)'                                                      , ['Climate', 'Env']             ], 
    ['EN.CO2.BLDG.ZS'      , 'CO2 emissions from residential buildings and commercial and public services (% of total fuel combustion)'                         , ['Env']                        ], 
    ['EN.CO2.ETOT.ZS'      , 'CO2 emissions from electricity and heat production, total (% of total fuel combustion)'                                           , ['Env']                        ], 
    ['EN.CO2.MANF.ZS'      , 'CO2 emissions from manufacturing industries and construction (% of total fuel combustion)'                                        , ['Env']                        ], 
    ['EN.CO2.OTHX.ZS'      , 'CO2 emissions from other sectors, excluding residential buildings and commercial and public services (% of total fuel combustion)', ['Env']                        ], 
    ['EN.CO2.TRAN.ZS'      , 'CO2 emissions from transport (% of total fuel combustion)'                                                                        , ['Env']                        ], 
    ['EN.FSH.THRD.NO'      , 'Fish species, threatened'                                                                                                         , ['Env']                        ], 
    ['EN.HPT.THRD.NO'      , 'Plant species (higher), threatened'                                                                                               , ['Env']                        ], 
    ['EN.MAM.THRD.NO'      , 'Mammal species, threatened'                                                                                                       , ['Env']                        ], 
    ['EN.POP.EL5M.RU.ZS'   , 'Rural population living in areas where elevation is below 5 meters (% of total population)'                                       , ['AgriRural', 'Climate', 'Env']], 
    ['EN.POP.EL5M.UR.ZS'   , 'Urban population living in areas where elevation is below 5 meters (% of total population)'                                       , ['Climate', 'Urban', 'Env']    ], 
    ['EN.POP.EL5M.ZS'      , 'Population living in areas where elevation is below 5 meters (% of total population)'                                             , ['Climate', 'Env']             ], 
    ['EN.POP.SLUM.UR.ZS'   , 'Population living in slums (% of urban population)'                                                                               , ['Poverty', 'Urban', 'Env']    ], 
    ['ER.FSH.AQUA.MT'      , 'Aquaculture production (metric tons)'                                                                                             , ['Env']                        ], 
    ['ER.FSH.CAPT.MT'      , 'Capture fisheries production (metric tons)'                                                                                       , ['Env']                        ], 
    ['ER.FSH.PROD.MT'      , 'Total fisheries production (metric tons)'                                                                                         , ['Env']                        ], 
    ['ER.GDP.FWTL.M3.KD'   , 'Water productivity, total (constant 2010 US$ GDP per cubic meter of total freshwater withdrawal)'                                 , ['Env']                        ], 
    ['ER.H2O.FWAG.ZS'      , 'Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal)'                                                    , ['AgriRural', 'Infras', 'Env'] ], 
    ['ER.H2O.FWDM.ZS'      , 'Annual freshwater withdrawals, domestic (% of total freshwater withdrawal)'                                                       , ['Infras', 'Env']              ], 
    ['ER.H2O.FWIN.ZS'      , 'Annual freshwater withdrawals, industry (% of total freshwater withdrawal)'                                                       , ['Infras', 'Env']              ], 
    ['ER.H2O.FWST.ZS'      , 'Level of water stress: freshwater withdrawal as a proportion of available freshwater resources'                                   , ['Env']                        ], 
    ['ER.H2O.FWTL.K3'      , 'Annual freshwater withdrawals, total (billion cubic meters)'                                                                      , ['Climate', 'Infras', 'Env']   ], 
    ['ER.H2O.FWTL.ZS'      , 'Annual freshwater withdrawals, total (% of internal resources)'                                                                   , ['Climate', 'Infras', 'Env']   ], 
    ['ER.H2O.INTR.K3'      , 'Renewable internal freshwater resources, total (billion cubic meters)'                                                            , ['Infras', 'Env']              ], 
    ['ER.H2O.INTR.PC'      , 'Renewable internal freshwater resources per capita (cubic meters)'                                                                , ['Infras', 'Env']              ], 
    ['ER.LND.PTLD.ZS'      , 'Terrestrial protected areas (% of total land area)'                                                                               , ['Climate', 'Env']             ], 
    ['ER.MRN.PTMR.ZS'      , 'Marine protected areas (% of territorial waters)'                                                                                 , ['Climate', 'Env']             ], 
    ['ER.PTD.TOTL.ZS'      , 'Terrestrial and marine protected areas (% of total territorial area)'                                                             , ['Climate', 'Env']             ], 
    ['NY.ADJ.AEDU.CD'      , 'Adjusted savings: education expenditure (current US$)'                                                                            , ['Econ', 'Env']                ], 
    ['NY.ADJ.AEDU.GN.ZS'   , 'Adjusted savings: education expenditure (% of GNI)'                                                                               , ['Econ', 'Env']                ], 
    ['NY.ADJ.DCO2.CD'      , 'Adjusted savings: carbon dioxide damage (current US$)'                                                                            , ['Econ', 'Env']                ], 
    ['NY.ADJ.DCO2.GN.ZS'   , 'Adjusted savings: carbon dioxide damage (% of GNI)'                                                                               , ['Econ', 'Env']                ], 
    ['NY.ADJ.DFOR.CD'      , 'Adjusted savings: net forest depletion (current US$)'                                                                             , ['Econ', 'Env']                ], 
    ['NY.ADJ.DFOR.GN.ZS'   , 'Adjusted savings: net forest depletion (% of GNI)'                                                                                , ['Econ', 'Env']                ], 
    ['NY.ADJ.DKAP.CD'      , 'Adjusted savings: consumption of fixed capital (current US$)'                                                                     , ['Econ', 'Env']                ], 
    ['NY.ADJ.DKAP.GN.ZS'   , 'Adjusted savings: consumption of fixed capital (% of GNI)'                                                                        , ['Econ', 'Env']                ], 
    ['NY.ADJ.DMIN.CD'      , 'Adjusted savings: mineral depletion (current US$)'                                                                                , ['Econ', 'Energy', 'Env']      ], 
    ['NY.ADJ.DMIN.GN.ZS'   , 'Adjusted savings: mineral depletion (% of GNI)'                                                                                   , ['Econ', 'Energy', 'Env']      ], 
    ['NY.ADJ.DNGY.CD'      , 'Adjusted savings: energy depletion (current US$)'                                                                                 , ['Econ', 'Energy', 'Env']      ], 
    ['NY.ADJ.DNGY.GN.ZS'   , 'Adjusted savings: energy depletion (% of GNI)'                                                                                    , ['Econ', 'Energy', 'Env']      ], 
    ['NY.ADJ.DPEM.CD'      , 'Adjusted savings: particulate emission damage (current US$)'                                                                      , ['Econ', 'Env']                ], 
    ['NY.ADJ.DPEM.GN.ZS'   , 'Adjusted savings: particulate emission damage (% of GNI)'                                                                         , ['Econ', 'Env']                ], 
    ['NY.ADJ.ICTR.GN.ZS'   , 'Adjusted savings: gross savings (% of GNI)'                                                                                       , ['Econ', 'Env']                ], 
    ['NY.ADJ.NNAT.CD'      , 'Adjusted savings: net national savings (current US$)'                                                                             , ['Econ', 'Env']                ], 
    ['NY.ADJ.NNAT.GN.ZS'   , 'Adjusted savings: net national savings (% of GNI)'                                                                                , ['Econ', 'Env']                ], 
    ['NY.ADJ.SVNG.CD'      , 'Adjusted net savings, including particulate emission damage (current US$)'                                                        , ['Econ', 'Env']                ], 
    ['NY.ADJ.SVNG.GN.ZS'   , 'Adjusted net savings, including particulate emission damage (% of GNI)'                                                           , ['Econ', 'Env']                ], 
    ['NY.ADJ.SVNX.CD'      , 'Adjusted net savings, excluding particulate emission damage (current US$)'                                                        , ['Econ', 'Env']                ], 
    ['NY.ADJ.SVNX.GN.ZS'   , 'Adjusted net savings, excluding particulate emission damage (% of GNI)'                                                           , ['Econ', 'Env']                ], 
    ['NY.GDP.COAL.RT.ZS'   , 'Coal rents (% of GDP)'                                                                                                            , ['Env']                        ], 
    ['NY.GDP.FRST.RT.ZS'   , 'Forest rents (% of GDP)'                                                                                                          , ['Env']                        ], 
    ['NY.GDP.MINR.RT.ZS'   , 'Mineral rents (% of GDP)'                                                                                                         , ['Energy', 'Env']              ], 
    ['NY.GDP.NGAS.RT.ZS'   , 'Natural gas rents (% of GDP)'                                                                                                     , ['Energy', 'Env']              ], 
    ['NY.GDP.PETR.RT.ZS'   , 'Oil rents (% of GDP)'                                                                                                             , ['Energy', 'Env']              ], 
    ['NY.GDP.TOTL.RT.ZS'   , 'Total natural resources rents (% of GDP)'                                                                                         , ['Energy', 'Env']              ], 
    ['SH.H2O.BASW.RU.ZS'   , 'People using at least basic drinking water services, rural (% of rural population)'                                               , ['Health', 'Env']              ], 
    ['SH.H2O.BASW.UR.ZS'   , 'People using at least basic drinking water services, urban (% of urban population)'                                               , ['Health', 'Env']              ], 
    ['SH.H2O.BASW.ZS'      , 'People using at least basic drinking water services (% of population)'                                                            , ['Health', 'Env']              ], 
    ['SH.H2O.SMDW.RU.ZS'   , 'People using safely managed drinking water services, rural (% of rural population)'                                               , ['Health', 'Env']              ], 
    ['SH.H2O.SMDW.UR.ZS'   , 'People using safely managed drinking water services, urban (% of urban population)'                                               , ['Health', 'Env']              ], 
    ['SH.H2O.SMDW.ZS'      , 'People using safely managed drinking water services (% of population)'                                                            , ['Health', 'Env']              ], 
    ['SH.STA.AIRP.P5'      , 'Mortality rate attributed to household and ambient air pollution, age-standardized (per 100,000 population)'                      , ['Health', 'Env']              ], 
    ['SH.STA.BASS.RU.ZS'   , 'People using at least basic sanitation services, rural (% of rural population)'                                                   , ['Health', 'Env']              ], 
    ['SH.STA.BASS.UR.ZS'   , 'People using at least basic sanitation services, urban (% of urban population)'                                                   , ['Health', 'Env']              ], 
    ['SH.STA.BASS.ZS'      , 'People using at least basic sanitation services (% of population)'                                                                , ['Health', 'Env']              ], 
    ['SH.STA.HYGN.RU.ZS'   , 'People with basic handwashing facilities including soap and water, rural (% of rural population)'                                 , ['Health', 'Env']              ], 
    ['SH.STA.HYGN.UR.ZS'   , 'People with basic handwashing facilities including soap and water, urban (% of urban population)'                                 , ['Health', 'Env']              ], 
    ['SH.STA.HYGN.ZS'      , 'People with basic handwashing facilities including soap and water (% of population)'                                              , ['Health', 'Env']              ], 
    ['SH.STA.ODFC.RU.ZS'   , 'People practicing open defecation, rural (% of rural population)'                                                                 , ['Health', 'Env']              ], 
    ['SH.STA.ODFC.UR.ZS'   , 'People practicing open defecation, urban (% of urban population)'                                                                 , ['Health', 'Env']              ], 
    ['SH.STA.ODFC.ZS'      , 'People practicing open defecation (% of population)'                                                                              , ['Health', 'Env']              ], 
    ['SH.STA.POIS.P5'      , 'Mortality rate attributed to unintentional poisoning (per 100,000 population)'                                                    , ['Health', 'Env']              ], 
    ['SH.STA.POIS.P5.FE'   , 'Mortality rate attributed to unintentional poisoning, female (per 100,000 female population)'                                     , ['Health', 'Env']              ], 
    ['SH.STA.POIS.P5.MA'   , 'Mortality rate attributed to unintentional poisoning, male (per 100,000 male population)'                                         , ['Health', 'Env']              ], 
    ['SH.STA.SMSS.RU.ZS'   , 'People using safely managed sanitation services, rural (% of rural population)'                                                   , ['Health', 'Env']              ], 
    ['SH.STA.SMSS.UR.ZS'   , 'People using safely managed sanitation services, urban (% of urban population)'                                                   , ['Health', 'Env']              ], 
    ['SH.STA.SMSS.ZS'      , 'People using safely managed sanitation services (% of population)'                                                                , ['Health', 'Env']              ], 
    ['SH.STA.WASH.P5'      , 'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene (per 100,000 population)'                        , ['Health', 'Env']              ], 
  ], 
}