export const Infrastructure = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['BX.GSR.CCIS.CD'   , 'ICT service exports (BoP, current US$)'                                                                                       , ['Econ', 'Infras', 'Trade']                 ], 
    ['BX.GSR.CCIS.ZS'   , 'ICT service exports (% of service exports, BoP)'                                                                              , ['Econ', 'Infras', 'Trade']                 ], 
    ['EG.ELC.COAL.ZS'   , 'Electricity production from coal sources (% of total)'                                                                        , ['Energy', 'Climate', 'Infras']             ], 
    ['EG.ELC.HYRO.ZS'   , 'Electricity production from hydroelectric sources (% of total)'                                                               , ['Energy', 'Climate', 'Infras']             ], 
    ['EG.ELC.LOSS.ZS'   , 'Electric power transmission and distribution losses (% of output)'                                                            , ['Energy', 'Infras']                        ], 
    ['EG.ELC.NGAS.ZS'   , 'Electricity production from natural gas sources (% of total)'                                                                 , ['Energy', 'Climate', 'Infras']             ], 
    ['EG.ELC.NUCL.ZS'   , 'Electricity production from nuclear sources (% of total)'                                                                     , ['Energy', 'Climate', 'Infras']             ], 
    ['EG.ELC.PETR.ZS'   , 'Electricity production from oil sources (% of total)'                                                                         , ['Energy', 'Climate', 'Infras']             ], 
    ['EG.USE.ELEC.KH.PC', 'Electric power consumption (kWh per capita)'                                                                                  , ['Energy', 'Climate', 'Infras']             ], 
    ['ER.H2O.FWAG.ZS'   , 'Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal)'                                                , ['AgriRural', 'Infras', 'Env']              ], 
    ['ER.H2O.FWDM.ZS'   , 'Annual freshwater withdrawals, domestic (% of total freshwater withdrawal)'                                                   , ['Infras', 'Env']                           ], 
    ['ER.H2O.FWIN.ZS'   , 'Annual freshwater withdrawals, industry (% of total freshwater withdrawal)'                                                   , ['Infras', 'Env']                           ], 
    ['ER.H2O.FWTL.K3'   , 'Annual freshwater withdrawals, total (billion cubic meters)'                                                                  , ['Climate', 'Infras', 'Env']                ], 
    ['ER.H2O.FWTL.ZS'   , 'Annual freshwater withdrawals, total (% of internal resources)'                                                               , ['Climate', 'Infras', 'Env']                ], 
    ['ER.H2O.INTR.K3'   , 'Renewable internal freshwater resources, total (billion cubic meters)'                                                        , ['Infras', 'Env']                           ], 
    ['ER.H2O.INTR.PC'   , 'Renewable internal freshwater resources per capita (cubic meters)'                                                            , ['Infras', 'Env']                           ], 
    ['IE.ICT.PCAP.CD'   , 'Information and communication technology expenditure per capita (current US$)'                                                , ['Infras']                                  ], 
    ['IE.ICT.TOTL.CD'   , 'Information and communication technology expenditure (current US$)'                                                           , ['Infras']                                  ], 
    ['IE.ICT.TOTL.GD.ZS', 'Information and communication technology expenditure (% of GDP)'                                                              , ['Infras']                                  ], 
    ['IE.PPI.ENGY.CD'   , 'Investment in energy with private participation (current US$)'                                                                , ['Energy', 'Infras', 'Private']             ], 
    ['IE.PPI.ICTI.CD'   , 'Investment in ICT with private participation (current US$)'                                                                   , ['Infras']                                  ], 
    ['IE.PPI.TELE.CD'   , 'Investment in telecoms with private participation (current US$)'                                                              , ['Infras', 'Private']                       ], 
    ['IE.PPI.TRAN.CD'   , 'Investment in transport with private participation (current US$)'                                                             , ['Infras', 'Private']                       ], 
    ['IE.PPI.WATR.CD'   , 'Investment in water and sanitation with private participation (current US$)'                                                  , ['Infras', 'Private']                       ], 
    ['IE.PPN.ENGY.CD'   , 'Public private partnerships investment in energy (current US$)'                                                               , ['Infras']                                  ], 
    ['IE.PPN.ICTI.CD'   , 'Public private partnerships investment in ICT (current US$)'                                                                  , ['Infras']                                  ], 
    ['IE.PPN.TELE.CD'   , 'Public private partnerships investment in telecom (current US$)'                                                              , ['Infras']                                  ], 
    ['IE.PPN.TRAN.CD'   , 'Public private partnerships investment in transport (current US$)'                                                            , ['Infras']                                  ], 
    ['IE.PPN.WATR.CD'   , 'Public private partnerships investment in water and sanitation (current US$)'                                                 , ['Infras']                                  ], 
    ['IP.IDS.NRCT'      , 'Industrial design applications, nonresident, by count'                                                                        , ['Infras']                                  ], 
    ['IP.IDS.RSCT'      , 'Industrial design applications, resident, by count'                                                                           , ['Infras']                                  ], 
    ['IP.TMK.NRCT'      , 'Trademark applications, nonresident, by count'                                                                                , ['Infras']                                  ], 
    ['IP.TMK.RSCT'      , 'Trademark applications, resident, by count'                                                                                   , ['Infras']                                  ], 
    ['IQ.WEF.PORT.XQ'   , 'Quality of port infrastructure, WEF (1=extremely underdeveloped to 7=well developed and efficient by international standards)', ['Infras']                                  ], 
    ['IS.AIR.DPRT'      , 'Air transport, registered carrier departures worldwide'                                                                       , ['Infras']                                  ], 
    ['IS.AIR.GOOD.MT.K1', 'Air transport, freight (million ton-km)'                                                                                      , ['Infras']                                  ], 
    ['IS.AIR.PSGR'      , 'Air transport, passengers carried'                                                                                            , ['Infras']                                  ], 
    ['IS.ROD.DNST.K2'   , 'Road density (km of road per 100 sq. km of land area)'                                                                        , ['Infras']                                  ], 
    ['IS.ROD.GOOD.MT.K6', 'Roads, goods transported (million ton-km)'                                                                                    , ['Infras']                                  ], 
    ['IS.ROD.PAVE.ZS'   , 'Roads, paved (% of total roads)'                                                                                              , ['Infras', 'Climate']                       ], 
    ['IS.ROD.PSGR.K6'   , 'Roads, passengers carried (million passenger-km)'                                                                             , ['Infras']                                  ], 
    ['IS.ROD.TOTL.KM'   , 'Roads, total network (km)'                                                                                                    , ['Infras']                                  ], 
    ['IS.RRS.GOOD.MT.K6', 'Railways, goods transported (million ton-km)'                                                                                 , ['Infras']                                  ], 
    ['IS.RRS.PASG.KM'   , 'Railways, passengers carried (million passenger-km)'                                                                          , ['Infras']                                  ], 
    ['IS.RRS.TOTL.KM'   , 'Rail lines (total route-km)'                                                                                                  , ['Infras']                                  ], 
    ['IS.SHP.GCNW.XQ'   , 'Liner shipping connectivity index (maximum value in 2004 = 100)'                                                              , ['Infras']                                  ], 
    ['IS.SHP.GOOD.TU'   , 'Container port traffic (TEU: 20 foot equivalent units)'                                                                       , ['Infras']                                  ], 
    ['IS.VEH.NVEH.P3'   , 'Motor vehicles (per 1,000 people)'                                                                                            , ['Infras', 'Urban']                         ], 
    ['IS.VEH.PCAR.P3'   , 'Passenger cars (per 1,000 people)'                                                                                            , ['Urban', 'Infras']                         ], 
    ['IS.VEH.ROAD.K1'   , 'Vehicles (per km of road)'                                                                                                    , ['Urban', 'Infras']                         ], 
    ['IT.CEL.SETS'      , 'Mobile cellular subscriptions'                                                                                                , ['Infras']                                  ], 
    ['IT.CEL.SETS.P2'   , 'Mobile cellular subscriptions (per 100 people)'                                                                               , ['Infras']                                  ], 
    ['IT.CMP.PCMP.P2'   , 'Personal computers (per 100 people)'                                                                                          , ['Infras']                                  ], 
    ['IT.MLT.MAIN'      , 'Fixed telephone subscriptions'                                                                                                , ['Infras']                                  ], 
    ['IT.MLT.MAIN.P2'   , 'Fixed telephone subscriptions (per 100 people)'                                                                               , ['Infras']                                  ], 
    ['IT.NET.BBND'      , 'Fixed broadband subscriptions'                                                                                                , ['Infras']                                  ], 
    ['IT.NET.BBND.P2'   , 'Fixed broadband subscriptions (per 100 people)'                                                                               , ['Infras']                                  ], 
    ['IT.NET.BNDW'      , 'International Internet bandwidth (Mbps)'                                                                                      , ['Infras']                                  ], 
    ['IT.NET.BNDW.PC'   , 'International Internet bandwidth (bits per person)'                                                                           , ['Infras']                                  ], 
    ['IT.NET.SECR'      , 'Secure Internet servers'                                                                                                      , ['Infras']                                  ], 
    ['IT.NET.SECR.P6'   , 'Secure Internet servers (per 1 million people)'                                                                               , ['Infras']                                  ], 
    ['IT.NET.USER.P2'   , 'Internet users (per 100 people)'                                                                                              , ['Infras']                                  ], 
    ['IT.NET.USER.ZS'   , 'Individuals using the Internet (% of population)'                                                                             , ['Infras']                                  ], 
    ['IT.PRT.NEWS.P3'   , 'Daily newspapers (per 1,000 people)'                                                                                          , ['Infras']                                  ], 
    ['IT.TEL.INVS.CN'   , 'Telecommunications investment (current LCU)'                                                                                  , ['Infras']                                  ], 
    ['IT.TEL.INVS.RV.ZS', 'Telecommunications investment (% of revenue)'                                                                                 , ['Infras']                                  ], 
    ['IT.TEL.REVN.CN'   , 'Telecommunications revenue (current LCU)'                                                                                     , ['Infras']                                  ], 
    ['IT.TEL.REVN.GD.ZS', 'Telecommunications revenue (% GDP)'                                                                                           , ['Infras']                                  ], 
    ['IT.TEL.TOTL'      , 'Mobile and fixed-line telephone subscribers'                                                                                  , ['Infras']                                  ], 
    ['IT.TEL.TOTL.P2'   , 'Fixed line and mobile cellular subscriptions (per 100 people)'                                                                , ['Infras']                                  ], 
    ['IT.TVS.HOUS.ZS'   , 'Households with television (%)'                                                                                               , ['Infras']                                  ], 
    ['SH.H2O.SAFE.RU.ZS', 'Improved water source, rural (% of rural population with access)'                                                             , ['AgriRural', 'Climate', 'Infras', 'Health']], 
    ['SH.H2O.SAFE.UR.ZS', 'Improved water source, urban (% of urban population with access)'                                                             , ['Climate', 'Infras', 'Health', 'Urban']    ], 
    ['SH.H2O.SAFE.ZS'   , 'Improved water source (% of population with access)'                                                                          , ['Climate', 'Infras', 'Health']             ], 
    ['TM.VAL.ICTG.ZS.UN', 'ICT goods imports (% total goods imports)'                                                                                    , ['Infras', 'Private', 'Trade']              ], 
    ['TX.VAL.ICTG.ZS.UN', 'ICT goods exports (% of total goods exports)'                                                                                 , ['Infras', 'Private', 'Trade']              ], 
  ], 
}