export const MilleniumDevelopmentGoals = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['DC.ODA.COMM.CD'   , 'Total bilateral ODA commitments (current US$)'                                                                              , ['2kGoals']], 
    ['DC.ODA.COMM.SA.CD', 'Total bilateral sector allocable ODA commitments (current US$)'                                                             , ['2kGoals']], 
    ['DC.ODA.SOCL.CD'   , 'Bilateral, sector-allocable ODA to basic social services (current US$)'                                                     , ['2kGoals']], 
    ['DC.ODA.SOCL.ZS'   , 'Bilateral, sector-allocable ODA to basic social services (% of bilateral ODA commitments)'                                  , ['2kGoals']], 
    ['DC.ODA.TLDC.CD'   , 'Net ODA provided, to the least developed countries (current US$)'                                                           , ['2kGoals']], 
    ['DC.ODA.TLDC.GN.ZS', 'Net ODA provided to the least developed countries (% of GNI)'                                                               , ['2kGoals']], 
    ['DC.ODA.TOTL.CD'   , 'Net ODA provided, total (current US$)'                                                                                      , ['2kGoals']], 
    ['DC.ODA.TOTL.GN.ZS', 'Net ODA provided, total (% of GNI)'                                                                                         , ['2kGoals']], 
    ['DC.ODA.TOTL.KD'   , 'Net ODA provided, total (constant 2015 US$)'                                                                                , ['2kGoals']], 
    ['DC.ODA.UNTD.CD'   , 'Bilateral ODA commitments that is untied (current US$)'                                                                     , ['2kGoals']], 
    ['DC.ODA.UNTD.ZS'   , 'Bilateral ODA commitments that is untied (% of bilateral ODA commitments)'                                                  , ['2kGoals']], 
    ['DT.HPC.COMR.PV'   , 'Debt relief committed under HIPC initiative, cumulative US$ in end-2012 NPV terms'                                          , ['2kGoals']], 
    ['DT.HPC.MDRI.PV'   , 'Debt relief delivered in full under MDRI initiative, cumulative US$ in end-2012 NPV terms'                                  , ['2kGoals']], 
    ['DT.HPC.STTS'      , 'Status under enhanced HIPC initiative'                                                                                      , ['2kGoals']], 
    ['DT.HPC.TOTL.PV'   , 'Debt relief committed under HIPC and MDRI initiatives, cumulative US$ in end-2012 NPV terms'                                , ['2kGoals']], 
    ['NY.AGR.SUBS.GD.ZS', 'Agricultural support estimate (% of GDP)'                                                                                   , ['2kGoals']], 
    ['SH.MLR.NETS.Q1.ZS', 'Malaria prevention, use of bed nets (% of under-5 children in the poorest quintile)'                                        , ['2kGoals']], 
    ['SH.MLR.NETS.Q5.ZS', 'Malaria prevention, use of bed nets (% of under-5 children in the richest quintile)'                                        , ['2kGoals']], 
    ['TM.MRC.NOTX.DV.ZS', 'Goods (excluding arms) admitted free of tariffs from developing countries (% total merchandise imports excluding arms)'     , ['2kGoals']], 
    ['TM.MRC.NOTX.LD.ZS', 'Goods (excluding arms) admitted free of tariffs from least developed countries (% total merchandise imports excluding arms)', ['2kGoals']], 
    ['TM.TAX.AGRI.CD.DV', 'Average tariffs imposed by developed countries on agricultural products from developing countries (%)'                      , ['2kGoals']], 
    ['TM.TAX.AGRI.CD.LD', 'Average tariffs imposed by developed countries on agricultural products from least developed countries (%)'                 , ['2kGoals']], 
    ['TM.TAX.CLTH.CD.DV', 'Average tariffs imposed by developed countries on clothing products from developing countries (%)'                          , ['2kGoals']], 
    ['TM.TAX.CLTH.CD.LD', 'Average tariffs imposed by developed countries on clothing products from least developed countries (%)'                     , ['2kGoals']], 
    ['TM.TAX.TXTL.CD.DV', 'Average tariffs imposed by developed countries on textile products from developing countries (%)'                           , ['2kGoals']], 
    ['TM.TAX.TXTL.CD.LD', 'Average tariffs imposed by developed countries on textile products from least developed countries (%)'                      , ['2kGoals']], 
  ], 
}