export const Poverty = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['1.0.HCount.1.90usd'   , 'Poverty Headcount ($1.90 a day)'                                                                                  , ['Poverty']                  ], 
    ['1.0.HCount.2.5usd'    , 'Poverty Headcount ($2.50 a day)'                                                                                  , ['Poverty']                  ], 
    ['1.0.HCount.Mid10to50' , 'Middle Class ($10-50 a day) Headcount'                                                                            , ['Poverty']                  ], 
    ['1.0.HCount.Ofcl'      , 'Official Moderate Poverty Rate-National'                                                                          , ['Poverty']                  ], 
    ['1.0.HCount.Poor4uds'  , 'Poverty Headcount ($4 a day)'                                                                                     , ['Poverty']                  ], 
    ['1.0.HCount.Vul4to10'  , 'Vulnerable ($4-10 a day) Headcount'                                                                               , ['Poverty']                  ], 
    ['1.0.PGap.1.90usd'     , 'Poverty Gap ($1.90 a day)'                                                                                        , ['Poverty']                  ], 
    ['1.0.PGap.2.5usd'      , 'Poverty Gap ($2.50 a day)'                                                                                        , ['Poverty']                  ], 
    ['1.0.PGap.Poor4uds'    , 'Poverty Gap ($4 a day)'                                                                                           , ['Poverty']                  ], 
    ['1.0.PSev.1.90usd'     , 'Poverty Severity ($1.90 a day)'                                                                                   , ['Poverty']                  ], 
    ['1.0.PSev.2.5usd'      , 'Poverty Severity ($2.50 a day)'                                                                                   , ['Poverty']                  ], 
    ['1.0.PSev.Poor4uds'    , 'Poverty Severity ($4 a day)'                                                                                      , ['Poverty']                  ], 
    ['1.1.HCount.1.90usd'   , 'Poverty Headcount ($1.90 a day)-Rural'                                                                            , ['Poverty']                  ], 
    ['1.1.HCount.2.5usd'    , 'Poverty Headcount ($2.50 a day)-Rural'                                                                            , ['Poverty']                  ], 
    ['1.1.HCount.Mid10to50' , 'Middle Class ($10-50 a day) Headcount-Rural'                                                                      , ['Poverty']                  ], 
    ['1.1.HCount.Ofcl'      , 'Official Moderate Poverty Rate- Rural'                                                                            , ['Poverty']                  ], 
    ['1.1.HCount.Poor4uds'  , 'Poverty Headcount ($4 a day)-Rural'                                                                               , ['Poverty']                  ], 
    ['1.1.HCount.Vul4to10'  , 'Vulnerable ($4-10 a day) Headcount-Rural'                                                                         , ['Poverty']                  ], 
    ['1.1.PGap.1.90usd'     , 'Poverty Gap ($1.90 a day)-Rural'                                                                                  , ['Poverty']                  ], 
    ['1.1.PGap.2.5usd'      , 'Poverty Gap ($2.50 a day)-Rural'                                                                                  , ['Poverty']                  ], 
    ['1.1.PGap.Poor4uds'    , 'Poverty Gap ($4 a day)-Rural'                                                                                     , ['Poverty']                  ], 
    ['1.1.PSev.1.90usd'     , 'Poverty Severity ($1.90 a day)-Rural'                                                                             , ['Poverty']                  ], 
    ['1.1.PSev.2.5usd'      , 'Poverty Severity ($2.50 a day)-Rural'                                                                             , ['Poverty']                  ], 
    ['1.1.PSev.Poor4uds'    , 'Poverty Severity ($4 a day)-Rural'                                                                                , ['Poverty']                  ], 
    ['1.2.HCount.1.90usd'   , 'Poverty Headcount ($1.90 a day)-Urban'                                                                            , ['Poverty']                  ], 
    ['1.2.HCount.2.5usd'    , 'Poverty Headcount ($2.50 a day)-Urban'                                                                            , ['Poverty']                  ], 
    ['1.2.HCount.Mid10to50' , 'Middle Class ($10-50 a day) Headcount-Urban'                                                                      , ['Poverty']                  ], 
    ['1.2.HCount.Ofcl'      , 'Official Moderate Poverty Rate-Urban'                                                                             , ['Poverty']                  ], 
    ['1.2.HCount.Poor4uds'  , 'Poverty Headcount ($4 a day)-Urban'                                                                               , ['Poverty']                  ], 
    ['1.2.HCount.Vul4to10'  , 'Vulnerable ($4-10 a day) Headcount-Urban'                                                                         , ['Poverty']                  ], 
    ['1.2.PGap.1.90usd'     , 'Poverty Gap ($1.90 a day)-Urban'                                                                                  , ['Poverty']                  ], 
    ['1.2.PGap.2.5usd'      , 'Poverty Gap ($2.50 a day)-Urban'                                                                                  , ['Poverty']                  ], 
    ['1.2.PGap.Poor4uds'    , 'Poverty Gap ($4 a day)-Urban'                                                                                     , ['Poverty']                  ], 
    ['1.2.PSev.1.90usd'     , 'Poverty Severity ($1.90 a day)-Urban'                                                                             , ['Poverty']                  ], 
    ['1.2.PSev.2.5usd'      , 'Poverty Severity ($2.50 a day)-Urban'                                                                             , ['Poverty']                  ], 
    ['1.2.PSev.Poor4uds'    , 'Poverty Severity ($4 a day)-Urban'                                                                                , ['Poverty']                  ], 
    ['2.0.cov.Cel'          , 'Coverage: Mobile Phone'                                                                                           , ['Poverty']                  ], 
    ['2.0.cov.Ele'          , 'Coverage: Electricity'                                                                                            , ['Poverty']                  ], 
    ['2.0.cov.Int'          , 'Coverage: Internet '                                                                                              , ['Poverty']                  ], 
    ['2.0.cov.Math.pl_2.all', 'Coverage: Mathematics Proficiency Level 2'                                                                        , ['Poverty']                  ], 
    ['2.0.cov.Math.pl_2.prv', 'Coverage: Mathematics Proficiency Level 2, Private schools'                                                       , ['Poverty']                  ], 
    ['2.0.cov.Math.pl_2.pub', 'Coverage: Mathematics Proficiency Level 2, Public schools'                                                        , ['Poverty']                  ], 
    ['2.0.cov.Math.pl_3.all', 'Coverage: Mathematics Proficiency Level 3'                                                                        , ['Poverty']                  ], 
    ['2.0.cov.Math.pl_3.prv', 'Coverage: Mathematics Proficiency Level 3, Private schools'                                                       , ['Poverty']                  ], 
    ['2.0.cov.Math.pl_3.pub', 'Coverage: Mathematics Proficiency Level 3, Public schools'                                                        , ['Poverty']                  ], 
    ['2.0.cov.Read.pl_2.all', 'Coverage: Reading Proficiency Level 2'                                                                            , ['Poverty']                  ], 
    ['2.0.cov.Read.pl_2.prv', 'Coverage: Reading Proficiency Level 2, Private schools'                                                           , ['Poverty']                  ], 
    ['2.0.cov.Read.pl_2.pub', 'Coverage: Reading Proficiency Level 2, Public schools'                                                            , ['Poverty']                  ], 
    ['2.0.cov.Read.pl_3.all', 'Coverage: Reading Proficiency Level 3'                                                                            , ['Poverty']                  ], 
    ['2.0.cov.Read.pl_3.prv', 'Coverage: Reading Proficiency Level 3, Private schools'                                                           , ['Poverty']                  ], 
    ['2.0.cov.Read.pl_3.pub', 'Coverage: Reading Proficiency Level 3, Public schools'                                                            , ['Poverty']                  ], 
    ['2.0.cov.San'          , 'Coverage: Sanitation'                                                                                             , ['Poverty']                  ], 
    ['2.0.cov.Sch'          , 'Coverage: School Enrollment'                                                                                      , ['Poverty']                  ], 
    ['2.0.cov.Scie.pl_2.all', 'Coverage: Science Proficiency Level 2'                                                                            , ['Poverty']                  ], 
    ['2.0.cov.Scie.pl_2.prv', 'Coverage: Science Proficiency Level 2, Private schools'                                                           , ['Poverty']                  ], 
    ['2.0.cov.Scie.pl_2.pub', 'Coverage: Science Proficiency Level 2, Public schools'                                                            , ['Poverty']                  ], 
    ['2.0.cov.Scie.pl_3.all', 'Coverage: Science Proficiency Level 3'                                                                            , ['Poverty']                  ], 
    ['2.0.cov.Scie.pl_3.prv', 'Coverage: Science Proficiency Level 3, Private schools'                                                           , ['Poverty']                  ], 
    ['2.0.cov.Scie.pl_3.pub', 'Coverage: Science Proficiency Level 3, Public schools'                                                            , ['Poverty']                  ], 
    ['2.0.cov.Wat'          , 'Coverage: Water'                                                                                                  , ['Poverty']                  ], 
    ['2.0.hoi.Cel'          , 'HOI: Mobile Phone'                                                                                                , ['Poverty']                  ], 
    ['2.0.hoi.Ele'          , 'HOI: Electricity'                                                                                                 , ['Poverty']                  ], 
    ['2.0.hoi.Int'          , 'HOI: Internet '                                                                                                   , ['Poverty']                  ], 
    ['2.0.hoi.Math.pl_2.all', 'HOI: Mathematics Proficiency Level 2'                                                                             , ['Poverty']                  ], 
    ['2.0.hoi.Math.pl_2.prv', 'HOI: Mathematics Proficiency Level 2, Private schools'                                                            , ['Poverty']                  ], 
    ['2.0.hoi.Math.pl_2.pub', 'HOI: Mathematics Proficiency Level 2, Public schools'                                                             , ['Poverty']                  ], 
    ['2.0.hoi.Math.pl_3.all', 'HOI: Mathematics Proficiency Level 3'                                                                             , ['Poverty']                  ], 
    ['2.0.hoi.Math.pl_3.prv', 'HOI: Mathematics Proficiency Level 3, Private schools'                                                            , ['Poverty']                  ], 
    ['2.0.hoi.Math.pl_3.pub', 'HOI: Mathematics Proficiency Level 3, Public schools'                                                             , ['Poverty']                  ], 
    ['2.0.hoi.Read.pl_2.all', 'HOI: Reading Proficiency Level 2'                                                                                 , ['Poverty']                  ], 
    ['2.0.hoi.Read.pl_2.prv', 'HOI: Reading Proficiency Level 2, Private schools'                                                                , ['Poverty']                  ], 
    ['2.0.hoi.Read.pl_2.pub', 'HOI: Reading Proficiency Level 2, Public schools'                                                                 , ['Poverty']                  ], 
    ['2.0.hoi.Read.pl_3.all', 'HOI: Reading Proficiency Level 3'                                                                                 , ['Poverty']                  ], 
    ['2.0.hoi.Read.pl_3.prv', 'HOI: Reading Proficiency Level 3, Private schools'                                                                , ['Poverty']                  ], 
    ['2.0.hoi.Read.pl_3.pub', 'HOI: Reading Proficiency Level 3, Public schools'                                                                 , ['Poverty']                  ], 
    ['2.0.hoi.San'          , 'HOI: Sanitation'                                                                                                  , ['Poverty']                  ], 
    ['2.0.hoi.Sch'          , 'HOI: School Enrollment'                                                                                           , ['Poverty']                  ], 
    ['2.0.hoi.Scie.pl_2.all', 'HOI: Science Proficiency Level 2'                                                                                 , ['Poverty']                  ], 
    ['2.0.hoi.Scie.pl_2.prv', 'HOI: Science Proficiency Level 2, Private schools'                                                                , ['Poverty']                  ], 
    ['2.0.hoi.Scie.pl_2.pub', 'HOI: Science Proficiency Level 2, Public schools'                                                                 , ['Poverty']                  ], 
    ['2.0.hoi.Scie.pl_3.all', 'HOI: Science Proficiency Level 3'                                                                                 , ['Poverty']                  ], 
    ['2.0.hoi.Scie.pl_3.prv', 'HOI: Science Proficiency Level 3, Private schools'                                                                , ['Poverty']                  ], 
    ['2.0.hoi.Scie.pl_3.pub', 'HOI: Science Proficiency Level 3, Public schools'                                                                 , ['Poverty']                  ], 
    ['2.0.hoi.Wat'          , 'HOI: Water'                                                                                                       , ['Poverty']                  ], 
    ['3.0.Atkin.0.5'        , 'Atkinson, A(.5)'                                                                                                  , ['Poverty']                  ], 
    ['3.0.Atkin.1'          , 'Atkinson, A(1)'                                                                                                   , ['Poverty']                  ], 
    ['3.0.Atkin.2'          , 'Atkinson, A(2)'                                                                                                   , ['Poverty']                  ], 
    ['3.0.GenEnt-1'         , 'Generalized Entrophy, GE(-1)'                                                                                     , ['Poverty']                  ], 
    ['3.0.GenEnt2'          , 'Generalized Entrophy, GE(2)'                                                                                      , ['Poverty']                  ], 
    ['3.0.Gini'             , 'Gini Coefficient'                                                                                                 , ['Poverty']                  ], 
    ['3.0.Gini_nozero'      , 'Gini Coefficient (No Zero Income)'                                                                                , ['Poverty']                  ], 
    ['3.0.IncShr.q1'        , 'Income Share of First Quintile'                                                                                   , ['Poverty']                  ], 
    ['3.0.IncShr.q2'        , 'Income Share of Second Quintile'                                                                                  , ['Poverty']                  ], 
    ['3.0.IncShr.q3'        , 'Income Share of Third Quintile'                                                                                   , ['Poverty']                  ], 
    ['3.0.IncShr.q4'        , 'Income Share of Fourth Quintile'                                                                                  , ['Poverty']                  ], 
    ['3.0.IncShr.q5'        , 'Income Share of Fifth Quintile'                                                                                   , ['Poverty']                  ], 
    ['3.0.MLongDev0'        , 'Mean Log Deviation, GE(0)'                                                                                        , ['Poverty']                  ], 
    ['3.0.Rate75-25'        , 'Rate 75/25'                                                                                                       , ['Poverty']                  ], 
    ['3.0.Rate90-10'        , 'Rate 90/10'                                                                                                       , ['Poverty']                  ], 
    ['3.0.TheilInd1'        , 'Theil Index, GE(1)'                                                                                               , ['Poverty']                  ], 
    ['3.1.Gini'             , 'Gini, Rural'                                                                                                      , ['Poverty']                  ], 
    ['3.1.MLongDev0'        , 'Mean Log Deviation, GE(0), Rural'                                                                                 , ['Poverty']                  ], 
    ['3.1.TheilInd1'        , 'Theil Index, GE(1), Rural'                                                                                        , ['Poverty']                  ], 
    ['3.2.Gini'             , 'Gini, Urban'                                                                                                      , ['Poverty']                  ], 
    ['3.2.MLongDev0'        , 'Mean Log Deviation, GE(0),Urban'                                                                                  , ['Poverty']                  ], 
    ['3.2.TheilInd1'        , 'Theil Index, GE(1),Urban'                                                                                         , ['Poverty']                  ], 
    ['8.0.LIPI'             , 'Labor Income Poverty Index'                                                                                       , ['Poverty']                  ], 
    ['EN.POP.SLUM.UR.ZS'    , 'Population living in slums (% of urban population)'                                                               , ['Poverty', 'Urban', 'Env']  ], 
    ['SI.DST.02ND.20'       , 'Income share held by second 20%'                                                                                  , ['Poverty']                  ], 
    ['SI.DST.03RD.20'       , 'Income share held by third 20%'                                                                                   , ['Poverty']                  ], 
    ['SI.DST.04TH.20'       , 'Income share held by fourth 20%'                                                                                  , ['Poverty']                  ], 
    ['SI.DST.05TH.20'       , 'Income share held by highest 20%'                                                                                 , ['Poverty']                  ], 
    ['SI.DST.10TH.10'       , 'Income share held by highest 10%'                                                                                 , ['Poverty']                  ], 
    ['SI.DST.50MD'          , 'Proportion of people living below 50 percent of median income (%)'                                                , ['Poverty']                  ], 
    ['SI.DST.FRST.10'       , 'Income share held by lowest 10%'                                                                                  , ['Poverty']                  ], 
    ['SI.DST.FRST.20'       , 'Income share held by lowest 20%'                                                                                  , ['Poverty', 'Aid']           ], 
    ['SI.POV.2DAY'          , 'Poverty headcount ratio at $3.10 a day (2011 PPP) (% of population)'                                              , ['Poverty']                  ], 
    ['SI.POV.DDAY'          , 'Poverty headcount ratio at $1.90 a day (2011 PPP) (% of population)'                                              , ['Poverty', 'Aid', 'Climate']], 
    ['SI.POV.GAP2'          , 'Poverty gap at $3.10 a day (2011 PPP) (%)'                                                                        , ['Poverty']                  ], 
    ['SI.POV.GAPS'          , 'Poverty gap at $1.90 a day (2011 PPP) (%)'                                                                        , ['Poverty']                  ], 
    ['SI.POV.GINI'          , 'Gini index (World Bank estimate)'                                                                                 , ['Poverty']                  ], 
    ['SI.POV.LMIC'          , 'Poverty headcount ratio at $3.20 a day (2011 PPP) (% of population)'                                              , ['Poverty']                  ], 
    ['SI.POV.LMIC.GP'       , 'Poverty gap at $3.20 a day (2011 PPP) (%)'                                                                        , ['Poverty']                  ], 
    ['SI.POV.MDIM'          , 'Multidimensional poverty headcount ratio (% of total population)'                                                 , ['Poverty']                  ], 
    ['SI.POV.MDIM.17'       , 'Multidimensional poverty headcount ratio, children (% of population ages 0-17)'                                   , ['Poverty']                  ], 
    ['SI.POV.MDIM.17.XQ'    , 'Multidimensional poverty index, children (population ages 0-17) (scale 0-1)'                                      , ['Poverty']                  ], 
    ['SI.POV.MDIM.FE'       , 'Multidimensional poverty headcount ratio, female (% of female population)'                                        , ['Poverty']                  ], 
    ['SI.POV.MDIM.HH'       , 'Multidimensional poverty headcount ratio, household (% of total households)'                                      , ['Poverty']                  ], 
    ['SI.POV.MDIM.IT'       , 'Multidimensional poverty intensity (average share of deprivations experienced by the poor)'                       , ['Poverty']                  ], 
    ['SI.POV.MDIM.MA'       , 'Multidimensional poverty headcount ratio, male (% of male population)'                                            , ['Poverty']                  ], 
    ['SI.POV.MDIM.XQ'       , 'Multidimensional poverty index (scale 0-1)'                                                                       , ['Poverty']                  ], 
    ['SI.POV.NAGP'          , 'Poverty gap at national poverty lines (%)'                                                                        , ['Poverty']                  ], 
    ['SI.POV.NAHC'          , 'Poverty headcount ratio at national poverty lines (% of population)'                                              , ['Poverty']                  ], 
    ['SI.POV.RUGP'          , 'Rural poverty gap at national poverty lines (%)'                                                                  , ['AgriRural', 'Poverty']     ], 
    ['SI.POV.RUHC'          , 'Rural poverty headcount ratio at national poverty lines (% of rural population)'                                  , ['AgriRural', 'Poverty']     ], 
    ['SI.POV.UMIC'          , 'Poverty headcount ratio at $5.50 a day (2011 PPP) (% of population)'                                              , ['Poverty']                  ], 
    ['SI.POV.UMIC.GP'       , 'Poverty gap at $5.50 a day (2011 PPP) (%)'                                                                        , ['Poverty']                  ], 
    ['SI.POV.URGP'          , 'Urban poverty gap at national poverty lines (%)'                                                                  , ['Poverty', 'Urban']         ], 
    ['SI.POV.URHC'          , 'Urban poverty headcount ratio at national poverty lines (% of urban population)'                                  , ['Poverty', 'Urban']         ], 
    ['SI.SPR.PC40'          , 'Survey mean consumption or income per capita, bottom 40% of population (2011 PPP $ per day)'                      , ['Poverty']                  ], 
    ['SI.SPR.PC40.05'       , 'Survey mean consumption or income per capita, bottom 40% (2005 PPP $ per day)'                                    , ['Poverty']                  ], 
    ['SI.SPR.PC40.ZG'       , 'Annualized average growth rate in per capita real survey mean consumption or income, bottom 40% of population (%)', ['Poverty']                  ], 
    ['SI.SPR.PCAP'          , 'Survey mean consumption or income per capita, total population (2011 PPP $ per day)'                              , ['Poverty']                  ], 
    ['SI.SPR.PCAP.05'       , 'Survey mean consumption or income per capita, total population (2005 PPP $ per day)'                              , ['Poverty']                  ], 
    ['SI.SPR.PCAP.ZG'       , 'Annualized average growth rate in per capita real survey mean consumption or income, total population (%)'        , ['Poverty']                  ], 
  ], 
}