export const PublicSector = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['GB.TAX.CMAR.ZS'   , 'Highest marginal tax rate, corporate rate (%)'                                                         , ['Public']                    ], 
    ['GC.AST.TOTL.CN'   , 'Net acquisition of financial assets (current LCU)'                                                     , ['Public']                    ], 
    ['GC.AST.TOTL.GD.ZS', 'Net acquisition of financial assets (% of GDP)'                                                        , ['Public']                    ], 
    ['GC.DOD.TOTL.CN'   , 'Central government debt, total (current LCU)'                                                          , ['Public']                    ], 
    ['GC.DOD.TOTL.GD.ZS', 'Central government debt, total (% of GDP)'                                                             , ['Econ', 'Public']            ], 
    ['GC.LBL.TOTL.CN'   , 'Net incurrence of liabilities, total (current LCU)'                                                    , ['Public']                    ], 
    ['GC.LBL.TOTL.GD.ZS', 'Net incurrence of liabilities, total (% of GDP)'                                                       , ['Public']                    ], 
    ['GC.NFN.TOTL.CN'   , 'Net investment in nonfinancial assets (current LCU)'                                                   , ['Public']                    ], 
    ['GC.NFN.TOTL.GD.ZS', 'Net investment in nonfinancial assets (% of GDP)'                                                      , ['Public']                    ], 
    ['GC.NLD.TOTL.CN'   , 'Net lending (+) / net borrowing (-) (current LCU)'                                                     , ['Public']                    ], 
    ['GC.NLD.TOTL.GD.ZS', 'Net lending (+) / net borrowing (-) (% of GDP)'                                                        , ['Public']                    ], 
    ['GC.REV.GOTR.CN'   , 'Grants and other revenue (current LCU)'                                                                , ['Public']                    ], 
    ['GC.REV.GOTR.ZS'   , 'Grants and other revenue (% of revenue)'                                                               , ['Public']                    ], 
    ['GC.REV.SOCL.CN'   , 'Social contributions (current LCU)'                                                                    , ['Public']                    ], 
    ['GC.REV.SOCL.ZS'   , 'Social contributions (% of revenue)'                                                                   , ['Public']                    ], 
    ['GC.REV.XGRT.CN'   , 'Revenue, excluding grants (current LCU)'                                                               , ['Public']                    ], 
    ['GC.REV.XGRT.GD.ZS', 'Revenue, excluding grants (% of GDP)'                                                                  , ['Econ', 'Public']            ], 
    ['GC.TAX.EXPT.CN'   , 'Taxes on exports (current LCU)'                                                                        , ['Public']                    ], 
    ['GC.TAX.EXPT.ZS'   , 'Taxes on exports (% of tax revenue)'                                                                   , ['Public', 'Trade']           ], 
    ['GC.TAX.GSRV.CN'   , 'Taxes on goods and services (current LCU)'                                                             , ['Public']                    ], 
    ['GC.TAX.GSRV.RV.ZS', 'Taxes on goods and services (% of revenue)'                                                            , ['Public']                    ], 
    ['GC.TAX.GSRV.VA.ZS', 'Taxes on goods and services (% value added of industry and services)'                                  , ['Public']                    ], 
    ['GC.TAX.IMPT.CN'   , 'Customs and other import duties (current LCU)'                                                         , ['Public']                    ], 
    ['GC.TAX.IMPT.ZS'   , 'Customs and other import duties (% of tax revenue)'                                                    , ['Public', 'Trade']           ], 
    ['GC.TAX.INTT.CN'   , 'Taxes on international trade (current LCU)'                                                            , ['Public']                    ], 
    ['GC.TAX.INTT.RV.ZS', 'Taxes on international trade (% of revenue)'                                                           , ['Public']                    ], 
    ['GC.TAX.OTHR.CN'   , 'Other taxes (current LCU)'                                                                             , ['Public']                    ], 
    ['GC.TAX.OTHR.RV.ZS', 'Other taxes (% of revenue)'                                                                            , ['Public']                    ], 
    ['GC.TAX.TOTL.CN'   , 'Tax revenue (current LCU)'                                                                             , ['Public']                    ], 
    ['GC.TAX.TOTL.GD.ZS', 'Tax revenue (% of GDP)'                                                                                , ['Public']                    ], 
    ['GC.TAX.YPKG.CN'   , 'Taxes on income, profits and capital gains (current LCU)'                                              , ['Public']                    ], 
    ['GC.TAX.YPKG.RV.ZS', 'Taxes on income, profits and capital gains (% of revenue)'                                             , ['Public']                    ], 
    ['GC.TAX.YPKG.ZS'   , 'Taxes on income, profits and capital gains (% of total taxes)'                                         , ['Public']                    ], 
    ['GC.XPN.COMP.CN'   , 'Compensation of employees (current LCU)'                                                               , ['Public']                    ], 
    ['GC.XPN.COMP.ZS'   , 'Compensation of employees (% of expense)'                                                              , ['Public']                    ], 
    ['GC.XPN.GSRV.CN'   , 'Goods and services expense (current LCU)'                                                              , ['Public']                    ], 
    ['GC.XPN.GSRV.ZS'   , 'Goods and services expense (% of expense)'                                                             , ['Public']                    ], 
    ['GC.XPN.INTP.CN'   , 'Interest payments (current LCU)'                                                                       , ['Public']                    ], 
    ['GC.XPN.INTP.RV.ZS', 'Interest payments (% of revenue)'                                                                      , ['Public']                    ], 
    ['GC.XPN.INTP.ZS'   , 'Interest payments (% of expense)'                                                                      , ['Public']                    ], 
    ['GC.XPN.OTHR.CN'   , 'Other expense (current LCU)'                                                                           , ['Public']                    ], 
    ['GC.XPN.OTHR.ZS'   , 'Other expense (% of expense)'                                                                          , ['Public']                    ], 
    ['GC.XPN.TOTL.CN'   , 'Expense (current LCU)'                                                                                 , ['Public']                    ], 
    ['GC.XPN.TOTL.GD.ZS', 'Expense (% of GDP)'                                                                                    , ['Econ', 'Public']            ], 
    ['GC.XPN.TRFT.CN'   , 'Subsidies and other transfers (current LCU)'                                                           , ['Public']                    ], 
    ['GC.XPN.TRFT.ZS'   , 'Subsidies and other transfers (% of expense)'                                                          , ['Public']                    ], 
    ['GF.XPD.BUDG.ZS'   , 'Primary government expenditures as a proportion of original approved budget (%)'                       , ['Public']                    ], 
    ['HD.HCI.OVRL'      , 'Human Capital Index (HCI) (scale 0-1)'                                                                 , ['Public']                    ], 
    ['HD.HCI.OVRL.FE'   , 'Human Capital Index (HCI), Female (scale 0-1)'                                                         , ['Public']                    ], 
    ['HD.HCI.OVRL.LB'   , 'Human Capital Index (HCI), Lower Bound (scale 0-1)'                                                    , ['Public']                    ], 
    ['HD.HCI.OVRL.LB.FE', 'Human Capital Index (HCI), Female, Lower Bound (scale 0-1)'                                            , ['Public']                    ], 
    ['HD.HCI.OVRL.LB.MA', 'Human Capital Index (HCI), Male, Lower Bound (scale 0-1)'                                              , ['Public']                    ], 
    ['HD.HCI.OVRL.MA'   , 'Human Capital Index (HCI), Male (scale 0-1)'                                                           , ['Public']                    ], 
    ['HD.HCI.OVRL.UB'   , 'Human Capital Index (HCI), Upper Bound (scale 0-1)'                                                    , ['Public']                    ], 
    ['HD.HCI.OVRL.UB.FE', 'Human Capital Index (HCI), Female, Upper Bound (scale 0-1)'                                            , ['Public']                    ], 
    ['HD.HCI.OVRL.UB.MA', 'Human Capital Index (HCI), Male, Upper Bound (scale 0-1)'                                              , ['Public']                    ], 
    ['IC.CRD.PUBL.ZS'   , 'Public credit registry coverage (% of adults)'                                                         , ['Fin', 'Private', 'Public']  ], 
    ['IC.LGL.CRED.XQ'   , 'Strength of legal rights index (0=weak to 12=strong)'                                                  , ['Fin', 'Private', 'Public']  ], 
    ['IC.TAX.DURS'      , 'Time to prepare and pay taxes (hours)'                                                                 , ['Private', 'Public']         ], 
    ['IC.TAX.PAYM'      , 'Tax payments (number)'                                                                                 , ['Private', 'Public']         ], 
    ['IC.TAX.TOTL.CP.ZS', 'Total tax and contribution rate (% of profit)'                                                         , ['Private', 'Public']         ], 
    ['IQ.CPA.BREG.XQ'   , 'CPIA business regulatory environment rating (1=low to 6=high)'                                         , ['Public']                    ], 
    ['IQ.CPA.DEBT.XQ'   , 'CPIA debt policy rating (1=low to 6=high)'                                                             , ['Public']                    ], 
    ['IQ.CPA.ECON.XQ'   , 'CPIA economic management cluster average (1=low to 6=high)'                                            , ['Public']                    ], 
    ['IQ.CPA.ENVR.XQ'   , 'CPIA policy and institutions for environmental sustainability rating (1=low to 6=high)'                , ['Public']                    ], 
    ['IQ.CPA.FINQ.XQ'   , 'CPIA quality of budgetary and financial management rating (1=low to 6=high)'                           , ['Public']                    ], 
    ['IQ.CPA.FINS.XQ'   , 'CPIA financial sector rating (1=low to 6=high)'                                                        , ['Public']                    ], 
    ['IQ.CPA.FISP.XQ'   , 'CPIA fiscal policy rating (1=low to 6=high)'                                                           , ['Public']                    ], 
    ['IQ.CPA.GNDR.XQ'   , 'CPIA gender equality rating (1=low to 6=high)'                                                         , ['Public']                    ], 
    ['IQ.CPA.HRES.XQ'   , 'CPIA building human resources rating (1=low to 6=high)'                                                , ['Public']                    ], 
    ['IQ.CPA.IRAI.XQ'   , 'IDA resource allocation index (1=low to 6=high)'                                                       , ['Public']                    ], 
    ['IQ.CPA.MACR.XQ'   , 'CPIA macroeconomic management rating (1=low to 6=high)'                                                , ['Public']                    ], 
    ['IQ.CPA.PADM.XQ'   , 'CPIA quality of public administration rating (1=low to 6=high)'                                        , ['Public']                    ], 
    ['IQ.CPA.PRES.XQ'   , 'CPIA equity of public resource use rating (1=low to 6=high)'                                           , ['Public']                    ], 
    ['IQ.CPA.PROP.XQ'   , 'CPIA property rights and rule-based governance rating (1=low to 6=high)'                               , ['Public']                    ], 
    ['IQ.CPA.PROT.XQ'   , 'CPIA social protection rating (1=low to 6=high)'                                                       , ['Public']                    ], 
    ['IQ.CPA.PUBS.XQ'   , 'CPIA public sector management and institutions cluster average (1=low to 6=high)'                      , ['Climate', 'Public']         ], 
    ['IQ.CPA.REVN.XQ'   , 'CPIA efficiency of revenue mobilization rating (1=low to 6=high)'                                      , ['Public']                    ], 
    ['IQ.CPA.SOCI.XQ'   , 'CPIA policies for social inclusion/equity cluster average (1=low to 6=high)'                           , ['Public']                    ], 
    ['IQ.CPA.STRC.XQ'   , 'CPIA structural policies cluster average (1=low to 6=high)'                                            , ['Public']                    ], 
    ['IQ.CPA.TRAD.XQ'   , 'CPIA trade rating (1=low to 6=high)'                                                                   , ['Public']                    ], 
    ['IQ.CPA.TRAN.XQ'   , 'CPIA transparency, accountability, and corruption in the public sector rating (1=low to 6=high)'       , ['Public']                    ], 
    ['IQ.SCI.MTHD'      , 'Methodology assessment of statistical capacity (scale 0 - 100)'                                        , ['Public']                    ], 
    ['IQ.SCI.OVRL'      , 'Statistical Capacity score (Overall average)'                                                          , ['Public']                    ], 
    ['IQ.SCI.PRDC'      , 'Periodicity and timeliness assessment of statistical capacity (scale 0 - 100)'                         , ['Public']                    ], 
    ['IQ.SCI.SRCE'      , 'Source data assessment of statistical capacity (scale 0 - 100)'                                        , ['Public']                    ], 
    ['IQ.SPI.OVRL'      , 'Statistical performance indicators (SPI): Overall score (scale 0-100)'                                 , ['Public']                    ], 
    ['IQ.SPI.PIL1'      , 'Statistical performance indicators (SPI): Pillar 1 data use score (scale 0-100)'                       , ['Public']                    ], 
    ['IQ.SPI.PIL2'      , 'Statistical performance indicators (SPI): Pillar 2 data services score (scale 0-100)'                  , ['Public']                    ], 
    ['IQ.SPI.PIL3'      , 'Statistical performance indicators (SPI): Pillar 3 data products score  (scale 0-100)'                 , ['Public']                    ], 
    ['IQ.SPI.PIL4'      , 'Statistical performance indicators (SPI): Pillar 4 data sources score (scale 0-100)'                   , ['Public']                    ], 
    ['IQ.SPI.PIL5'      , 'Statistical performance indicators (SPI): Pillar 5 data infrastructure score (scale 0-100)'            , ['Public']                    ], 
    ['MS.MIL.MPRT.KD'   , 'Arms imports (SIPRI trend indicator values)'                                                           , ['Public', 'Trade']           ], 
    ['MS.MIL.TOTL.P1'   , 'Armed forces personnel, total'                                                                         , ['Public']                    ], 
    ['MS.MIL.TOTL.TF.ZS', 'Armed forces personnel (% of total labor force)'                                                       , ['Public']                    ], 
    ['MS.MIL.XPND.CD'   , 'Military expenditure (current USD)'                                                                    , ['Public']                    ], 
    ['MS.MIL.XPND.CN'   , 'Military expenditure (current LCU)'                                                                    , ['Public']                    ], 
    ['MS.MIL.XPND.GD.ZS', 'Military expenditure (% of GDP)'                                                                       , ['Public']                    ], 
    ['MS.MIL.XPND.ZS'   , 'Military expenditure (% of general government expenditure)'                                            , ['Public']                    ], 
    ['MS.MIL.XPRT.KD'   , 'Arms exports (SIPRI trend indicator values)'                                                           , ['Public', 'Trade']           ], 
    ['SG.GEN.PARL.ZS'   , 'Proportion of seats held by women in national parliaments (%)'                                         , ['Public', 'Gender', 'Social']], 
    ['SG.JOB.NOPN.EQ'   , 'Nonpregnant and nonnursing women can do the same jobs as men (1=yes; 0=no)'                            , ['Public', 'Gender']          ], 
    ['SG.LAW.CHMR'      , 'Law prohibits or invalidates child or early marriage (1=yes; 0=no)'                                    , ['Public', 'Gender']          ], 
    ['SG.LAW.EQRM.WK'   , 'Law mandates equal remuneration for females and males for work of equal value (1=yes; 0=no)'           , ['Public', 'Gender', 'Gender']], 
    ['SG.LAW.LEVE.PU'   , 'Law mandates paid or unpaid maternity leave (1=yes; 0=no)'                                             , ['Public', 'Gender']          ], 
    ['SG.LAW.NODC.HR'   , 'Law prohibits discrimination in employment based on gender (1=yes; 0=no)'                              , ['Public', 'Gender', 'Gender']], 
    ['SG.LEG.DVAW'      , 'There is legislation specifically addressing domestic violence (1=yes; 0=no)'                          , ['Public', 'Gender', 'Gender']], 
    ['SG.MMR.LEVE.EP'   , 'Mothers are guaranteed an equivalent position after maternity leave (1=yes; 0=no)'                     , ['Public', 'Gender']          ], 
    ['SG.NOD.CONS'      , 'Nondiscrimination clause mentions gender in the constitution (1=yes; 0=no)'                            , ['Public', 'Gender']          ], 
    ['VC.BTL.DETH'      , 'Battle-related deaths (number of people)'                                                              , ['Public']                    ], 
    ['VC.IDP.NWCV'      , 'Internally displaced persons, new displacement associated with conflict and violence (number of cases)', ['Public']                    ], 
    ['VC.IDP.NWDS'      , 'Internally displaced persons, new displacement associated with disasters (number of cases)'            , ['Public']                    ], 
    ['VC.IDP.TOCV'      , 'Internally displaced persons, total displaced by conflict and violence (number of people)'             , ['Public']                    ], 
    ['VC.IDP.TOTL.HE'   , 'Internally displaced persons (number, high estimate)'                                                  , ['Public']                    ], 
    ['VC.IDP.TOTL.LE'   , 'Internally displaced persons (number, low estimate)'                                                   , ['Public']                    ], 
    ['VC.IHR.PSRC.FE.P5', 'Intentional homicides, female (per 100,000 female)'                                                    , ['Public']                    ], 
    ['VC.IHR.PSRC.MA.P5', 'Intentional homicides, male (per 100,000 male)'                                                        , ['Public']                    ], 
    ['VC.IHR.PSRC.P5'   , 'Intentional homicides (per 100,000 people)'                                                            , ['Public']                    ], 
    ['VC.PKP.TOTL.UN'   , 'Presence of peace keepers (number of troops, police, and military observers in mandate)'               , ['Public']                    ], 
  ], 
}