export const SocialDevelopment = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['SE.ADT.1524.LT.FM.ZS'  , 'Literacy rate, youth (ages 15-24), gender parity index (GPI)'                                           , ['Edu', 'Gender', 'Social']                  ], 
    ['SE.ENR.PRIM.FM.ZS'     , 'School enrollment, primary (gross), gender parity index (GPI)'                                          , ['Edu', 'Gender', 'Social']                  ], 
    ['SE.ENR.PRSC.FM.ZS'     , 'School enrollment, primary and secondary (gross), gender parity index (GPI)'                            , ['Aid', 'Climate', 'Edu', 'Gender', 'Social']], 
    ['SE.ENR.SECO.FM.ZS'     , 'School enrollment, secondary (gross), gender parity index (GPI)'                                        , ['Edu', 'Gender', 'Social']                  ], 
    ['SE.ENR.TERT.FM.ZS'     , 'School enrollment, tertiary (gross), gender parity index (GPI)'                                         , ['Edu', 'Gender', 'Social']                  ], 
    ['SG.GEN.PARL.ZS'        , 'Proportion of seats held by women in national parliaments (%)'                                          , ['Public', 'Gender', 'Social']               ], 
    ['SH.HIV.1524.FE.ZS'     , 'Prevalence of HIV, female (% ages 15-24)'                                                               , ['Health', 'Gender', 'Social']               ], 
    ['SH.HIV.1524.MA.ZS'     , 'Prevalence of HIV, male (% ages 15-24)'                                                                 , ['Health', 'Gender', 'Social']               ], 
    ['SL.EMP.INSV.FE.ZS'     , 'Share of women in wage employment in the nonagricultural sector (% of total nonagricultural employment)', ['Labor', 'Gender', 'Social']                ], 
    ['SL.EMP.VULN.FE.ZS'     , 'Vulnerable employment, female (% of female employment) (modeled ILO estimate)'                          , ['Labor', 'Gender', 'Social']                ], 
    ['SL.EMP.VULN.MA.ZS'     , 'Vulnerable employment, male (% of male employment) (modeled ILO estimate)'                              , ['Labor', 'Gender', 'Social']                ], 
    ['SL.TLF.0714.FE.ZS'     , 'Children in employment, female (% of female children ages 7-14)'                                        , ['Labor', 'Gender', 'Social']                ], 
    ['SL.TLF.0714.MA.ZS'     , 'Children in employment, male (% of male children ages 7-14)'                                            , ['Labor', 'Gender', 'Social']                ], 
    ['SL.TLF.0714.SW.FE.ZS'  , 'Children in employment, study and work, female (% of female children in employment, ages 7-14)'         , ['Labor', 'Gender', 'Social']                ], 
    ['SL.TLF.0714.SW.MA.ZS'  , 'Children in employment, study and work, male (% of male children in employment, ages 7-14)'             , ['Labor', 'Gender', 'Social']                ], 
    ['SL.TLF.0714.SW.ZS'     , 'Children in employment, study and work (% of children in employment, ages 7-14)'                        , ['Labor', 'Social']                          ], 
    ['SL.TLF.0714.WK.FE.ZS'  , 'Children in employment, work only, female (% of female children in employment, ages 7-14)'              , ['Labor', 'Gender', 'Social']                ], 
    ['SL.TLF.0714.WK.MA.ZS'  , 'Children in employment, work only, male (% of male children in employment, ages 7-14)'                  , ['Labor', 'Gender', 'Social']                ], 
    ['SL.TLF.0714.WK.ZS'     , 'Children in employment, work only (% of children in employment, ages 7-14)'                             , ['Labor', 'Social']                          ], 
    ['SL.TLF.0714.ZS'        , 'Children in employment, total (% of children ages 7-14)'                                                , ['Labor', 'Social']                          ], 
    ['SL.TLF.ACTI.1524.FE.ZS', 'Labor force participation rate for ages 15-24, female (%) (modeled ILO estimate)'                       , ['Labor', 'Social']                          ], 
    ['SL.TLF.ACTI.1524.MA.ZS', 'Labor force participation rate for ages 15-24, male (%) (modeled ILO estimate)'                         , ['Labor', 'Social']                          ], 
    ['SL.TLF.ACTI.1524.ZS'   , 'Labor force participation rate for ages 15-24, total (%) (modeled ILO estimate)'                        , ['Labor', 'Social']                          ], 
    ['SL.TLF.ACTI.FE.ZS'     , 'Labor force participation rate, female (% of female population ages 15-64) (modeled ILO estimate)'      , ['Labor', 'Social']                          ], 
    ['SL.TLF.ACTI.MA.ZS'     , 'Labor force participation rate, male (% of male population ages 15-64) (modeled ILO estimate)'          , ['Labor', 'Social']                          ], 
    ['SL.TLF.ACTI.ZS'        , 'Labor force participation rate, total (% of total population ages 15-64) (modeled ILO estimate)'        , ['Labor', 'Social']                          ], 
    ['SL.TLF.CACT.FE.ZS'     , 'Labor force participation rate, female (% of female population ages 15+) (modeled ILO estimate)'        , ['Labor', 'Gender', 'Social']                ], 
    ['SL.TLF.CACT.MA.ZS'     , 'Labor force participation rate, male (% of male population ages 15+) (modeled ILO estimate)'            , ['Labor', 'Gender', 'Social']                ], 
    ['SL.UEM.TOTL.FE.ZS'     , 'Unemployment, female (% of female labor force) (modeled ILO estimate)'                                  , ['Edu', 'Labor', 'Gender', 'Social']         ], 
    ['SL.UEM.TOTL.MA.ZS'     , 'Unemployment, male (% of male labor force) (modeled ILO estimate)'                                      , ['Edu', 'Labor', 'Gender', 'Social']         ], 
    ['SM.POP.REFG'           , 'Refugee population by country or territory of asylum'                                                   , ['Health', 'Social']                         ], 
    ['SM.POP.REFG.OR'        , 'Refugee population by country or territory of origin'                                                   , ['Health', 'Social']                         ], 
    ['SP.ADO.TFRT'           , 'Adolescent fertility rate (births per 1,000 women ages 15-19)'                                          , ['Health', 'Gender', 'Social']               ], 
    ['SP.DYN.LE00.FE.IN'     , 'Life expectancy at birth, female (years)'                                                               , ['Health', 'Gender', 'Social']               ], 
    ['SP.DYN.LE00.MA.IN'     , 'Life expectancy at birth, male (years)'                                                                 , ['Health', 'Gender', 'Social']               ], 
  ], 
}