export const Trade = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['BG.GSR.NFSV.GD.ZS'   , 'Trade in services (% of GDP)'                                                                                                   , ['Econ', 'Private', 'Trade']     ], 
    ['BM.GSR.CMCP.ZS'      , 'Communications, computer, etc. (% of service imports, BoP)'                                                                     , ['Econ', 'Trade']                ], 
    ['BM.GSR.GNFS.CD'      , 'Imports of goods and services (BoP, current US$)'                                                                               , ['Econ', 'Trade']                ], 
    ['BM.GSR.INSF.ZS'      , 'Insurance and financial services (% of service imports, BoP)'                                                                   , ['Econ', 'Private', 'Trade']     ], 
    ['BM.GSR.MRCH.CD'      , 'Goods imports (BoP, current US$)'                                                                                               , ['Econ', 'Trade']                ], 
    ['BM.GSR.NFSV.CD'      , 'Service imports (BoP, current US$)'                                                                                             , ['Econ', 'Trade']                ], 
    ['BM.GSR.TOTL.CD'      , 'Imports of goods, services and primary income (BoP, current US$)'                                                               , ['Econ', 'Debt', 'Trade']        ], 
    ['BM.GSR.TRAN.ZS'      , 'Transport services (% of service imports, BoP)'                                                                                 , ['Econ', 'Trade']                ], 
    ['BM.GSR.TRVL.ZS'      , 'Travel services (% of service imports, BoP)'                                                                                    , ['Econ', 'Trade']                ], 
    ['BN.GSR.GNFS.CD'      , 'Net trade in goods and services (BoP, current US$)'                                                                             , ['Econ', 'Trade']                ], 
    ['BN.GSR.MRCH.CD'      , 'Net trade in goods (BoP, current US$)'                                                                                          , ['Econ', 'Trade']                ], 
    ['BX.GSR.CCIS.CD'      , 'ICT service exports (BoP, current US$)'                                                                                         , ['Econ', 'Infras', 'Trade']      ], 
    ['BX.GSR.CCIS.ZS'      , 'ICT service exports (% of service exports, BoP)'                                                                                , ['Econ', 'Infras', 'Trade']      ], 
    ['BX.GSR.CMCP.ZS'      , 'Communications, computer, etc. (% of service exports, BoP)'                                                                     , ['Econ', 'Trade']                ], 
    ['BX.GSR.GNFS.CD'      , 'Exports of goods and services (BoP, current US$)'                                                                               , ['Econ', 'Trade']                ], 
    ['BX.GSR.INSF.ZS'      , 'Insurance and financial services (% of service exports, BoP)'                                                                   , ['Econ', 'Private', 'Trade']     ], 
    ['BX.GSR.MRCH.CD'      , 'Goods exports (BoP, current US$)'                                                                                               , ['Econ', 'Trade']                ], 
    ['BX.GSR.NFSV.CD'      , 'Service exports (BoP, current US$)'                                                                                             , ['Econ', 'Trade']                ], 
    ['BX.GSR.TOTL.CD'      , 'Exports of goods, services and primary income (BoP, current US$)'                                                               , ['Econ', 'Debt', 'Trade']        ], 
    ['BX.GSR.TRAN.ZS'      , 'Transport services (% of service exports, BoP)'                                                                                 , ['Econ', 'Trade']                ], 
    ['BX.GSR.TRVL.ZS'      , 'Travel services (% of service exports, BoP)'                                                                                    , ['Econ', 'Trade']                ], 
    ['EG.IMP.CONS.ZS'      , 'Energy imports, net (% of energy use)'                                                                                          , ['Energy', 'Trade']              ], 
    ['GC.TAX.EXPT.ZS'      , 'Taxes on exports (% of tax revenue)'                                                                                            , ['Public', 'Trade']              ], 
    ['GC.TAX.IMPT.ZS'      , 'Customs and other import duties (% of tax revenue)'                                                                             , ['Public', 'Trade']              ], 
    ['IC.CUS.DURS.EX'      , 'Average time to clear exports through customs (days)'                                                                           , ['Private', 'Trade']             ], 
    ['IC.EXP.COST.CD'      , 'Cost to export (US$ per container)'                                                                                             , ['Private', 'Trade']             ], 
    ['IC.EXP.CSBC.CD'      , 'Cost to export, border compliance (US$)'                                                                                        , ['Private', 'Trade']             ], 
    ['IC.EXP.CSDC.CD'      , 'Cost to export, documentary compliance (US$)'                                                                                   , ['Private', 'Trade']             ], 
    ['IC.EXP.DOCS'         , 'Documents to export (number)'                                                                                                   , ['Private', 'Trade']             ], 
    ['IC.EXP.DURS'         , 'Time to export (days)'                                                                                                          , ['Private', 'Trade']             ], 
    ['IC.EXP.TMBC'         , 'Time to export, border compliance (hours)'                                                                                      , ['Private', 'Trade']             ], 
    ['IC.EXP.TMDC'         , 'Time to export, documentary compliance (hours)'                                                                                 , ['Private', 'Trade']             ], 
    ['IC.IMP.COST.CD'      , 'Cost to import (US$ per container)'                                                                                             , ['Private', 'Trade']             ], 
    ['IC.IMP.CSBC.CD'      , 'Cost to import, border compliance (US$)'                                                                                        , ['Private', 'Trade']             ], 
    ['IC.IMP.CSDC.CD'      , 'Cost to import, documentary compliance (US$)'                                                                                   , ['Private', 'Trade']             ], 
    ['IC.IMP.DOCS'         , 'Documents to import (number)'                                                                                                   , ['Private', 'Trade']             ], 
    ['IC.IMP.DURS'         , 'Time to import (days)'                                                                                                          , ['Private', 'Trade']             ], 
    ['IC.IMP.TMBC'         , 'Time to import, border compliance (hours)'                                                                                      , ['Private', 'Trade']             ], 
    ['IC.IMP.TMDC'         , 'Time to import, documentary compliance (hours)'                                                                                 , ['Private', 'Trade']             ], 
    ['LP.EXP.DURS.MD'      , 'Lead time to export, median case (days)'                                                                                        , ['Trade', 'Private']             ], 
    ['LP.IMP.DURS.MD'      , 'Lead time to import, median case (days)'                                                                                        , ['Private', 'Trade']             ], 
    ['LP.LPI.CUST.XQ'      , 'Logistics performance index: Efficiency of customs clearance process (1=low to 5=high)'                                         , ['Private', 'Trade']             ], 
    ['LP.LPI.INFR.XQ'      , 'Logistics performance index: Quality of trade and transport-related infrastructure (1=low to 5=high)'                           , ['Private', 'Trade']             ], 
    ['LP.LPI.ITRN.XQ'      , 'Logistics performance index: Ease of arranging competitively priced shipments (1=low to 5=high)'                                , ['Private', 'Trade']             ], 
    ['LP.LPI.LOGS.XQ'      , 'Logistics performance index: Competence and quality of logistics services (1=low to 5=high)'                                    , ['Private', 'Trade']             ], 
    ['LP.LPI.OVRL.XQ'      , 'Logistics performance index: Overall (1=low to 5=high)'                                                                         , ['Private', 'Trade']             ], 
    ['LP.LPI.TIME.XQ'      , 'Logistics performance index: Frequency with which shipments reach consignee within scheduled or expected time (1=low to 5=high)', ['Private', 'Trade']             ], 
    ['LP.LPI.TRAC.XQ'      , 'Logistics performance index: Ability to track and trace consignments (1=low to 5=high)'                                         , ['Private', 'Trade']             ], 
    ['MS.MIL.MPRT.KD'      , 'Arms imports (SIPRI trend indicator values)'                                                                                    , ['Public', 'Trade']              ], 
    ['MS.MIL.XPRT.KD'      , 'Arms exports (SIPRI trend indicator values)'                                                                                    , ['Public', 'Trade']              ], 
    ['NE.EXP.GNFS.CD'      , 'Exports of goods and services (current US$)'                                                                                    , ['Econ', 'Trade']                ], 
    ['NE.EXP.GNFS.KD'      , 'Exports of goods and services (constant 2010 US$)'                                                                              , ['Econ', 'Trade']                ], 
    ['NE.EXP.GNFS.KD.ZG'   , 'Exports of goods and services (annual % growth)'                                                                                , ['Econ', 'Trade']                ], 
    ['NE.EXP.GNFS.ZS'      , 'Exports of goods and services (% of GDP)'                                                                                       , ['Econ', 'Trade']                ], 
    ['NE.IMP.GNFS.CD'      , 'Imports of goods and services (current US$)'                                                                                    , ['Econ', 'Trade']                ], 
    ['NE.IMP.GNFS.KD'      , 'Imports of goods and services (constant 2010 US$)'                                                                              , ['Econ', 'Trade']                ], 
    ['NE.IMP.GNFS.KD.ZG'   , 'Imports of goods and services (annual % growth)'                                                                                , ['Econ', 'Trade']                ], 
    ['NE.IMP.GNFS.ZS'      , 'Imports of goods and services (% of GDP)'                                                                                       , ['Econ', 'Trade']                ], 
    ['NE.RSB.GNFS.CD'      , 'External balance on goods and services (current US$)'                                                                           , ['Econ', 'Trade']                ], 
    ['NE.RSB.GNFS.ZS'      , 'External balance on goods and services (% of GDP)'                                                                              , ['Econ', 'Trade']                ], 
    ['NE.TRD.GNFS.ZS'      , 'Trade (% of GDP)'                                                                                                               , ['Econ', 'Trade']                ], 
    ['NY.EXP.CAPM.KN'      , 'Exports as a capacity to import (constant LCU)'                                                                                 , ['Econ', 'Trade']                ], 
    ['ST.INT.ARVL'         , 'International tourism, number of arrivals'                                                                                      , ['Private', 'Trade']             ], 
    ['ST.INT.DPRT'         , 'International tourism, number of departures'                                                                                    , ['Private', 'Trade']             ], 
    ['ST.INT.RCPT.CD'      , 'International tourism, receipts (current US$)'                                                                                  , ['Private', 'Trade']             ], 
    ['ST.INT.RCPT.XP.ZS'   , 'International tourism, receipts (% of total exports)'                                                                           , ['Private', 'Trade']             ], 
    ['ST.INT.TRNR.CD'      , 'International tourism, receipts for passenger transport items (current US$)'                                                    , ['Private', 'Trade']             ], 
    ['ST.INT.TRNX.CD'      , 'International tourism, expenditures for passenger transport items (current US$)'                                                , ['Private', 'Trade']             ], 
    ['ST.INT.TVLR.CD'      , 'International tourism, receipts for travel items (current US$)'                                                                 , ['Private', 'Trade']             ], 
    ['ST.INT.TVLX.CD'      , 'International tourism, expenditures for travel items (current US$)'                                                             , ['Private', 'Trade']             ], 
    ['ST.INT.XPND.CD'      , 'International tourism, expenditures (current US$)'                                                                              , ['Private', 'Trade']             ], 
    ['ST.INT.XPND.MP.ZS'   , 'International tourism, expenditures (% of total imports)'                                                                       , ['Private', 'Trade']             ], 
    ['TG.VAL.TOTL.GD.ZS'   , 'Merchandise trade (% of GDP)'                                                                                                   , ['Private', 'Trade']             ], 
    ['TM.QTY.MRCH.XD.WD'   , 'Import volume index (2000 = 100)'                                                                                               , ['Private', 'Trade']             ], 
    ['TM.TAX.MANF.BC.ZS'   , 'Binding coverage, manufactured products (%)'                                                                                    , ['Private', 'Trade']             ], 
    ['TM.TAX.MANF.BR.ZS'   , 'Bound rate, simple mean, manufactured products (%)'                                                                             , ['Private', 'Trade']             ], 
    ['TM.TAX.MANF.IP.ZS'   , 'Share of tariff lines with international peaks, manufactured products (%)'                                                      , ['Private', 'Trade']             ], 
    ['TM.TAX.MANF.SM.AR.ZS', 'Tariff rate, applied, simple mean, manufactured products (%)'                                                                   , ['Private', 'Trade']             ], 
    ['TM.TAX.MANF.SM.FN.ZS', 'Tariff rate, most favored nation, simple mean, manufactured products (%)'                                                       , ['Private', 'Trade']             ], 
    ['TM.TAX.MANF.SR.ZS'   , 'Share of tariff lines with specific rates, manufactured products (%)'                                                           , ['Private', 'Trade']             ], 
    ['TM.TAX.MANF.WM.AR.ZS', 'Tariff rate, applied, weighted mean, manufactured products (%)'                                                                 , ['Private', 'Trade']             ], 
    ['TM.TAX.MANF.WM.FN.ZS', 'Tariff rate, most favored nation, weighted mean, manufactured products (%)'                                                     , ['Private', 'Trade']             ], 
    ['TM.TAX.MRCH.BC.ZS'   , 'Binding coverage, all products (%)'                                                                                             , ['Private', 'Trade']             ], 
    ['TM.TAX.MRCH.BR.ZS'   , 'Bound rate, simple mean, all products (%)'                                                                                      , ['Private', 'Trade']             ], 
    ['TM.TAX.MRCH.IP.ZS'   , 'Share of tariff lines with international peaks, all products (%)'                                                               , ['Private', 'Trade']             ], 
    ['TM.TAX.MRCH.SM.AR.ZS', 'Tariff rate, applied, simple mean, all products (%)'                                                                            , ['Private', 'Trade']             ], 
    ['TM.TAX.MRCH.SM.FN.ZS', 'Tariff rate, most favored nation, simple mean, all products (%)'                                                                , ['Private', 'Trade']             ], 
    ['TM.TAX.MRCH.SR.ZS'   , 'Share of tariff lines with specific rates, all products (%)'                                                                    , ['Private', 'Trade']             ], 
    ['TM.TAX.MRCH.WM.AR.ZS', 'Tariff rate, applied, weighted mean, all products (%)'                                                                          , ['Private', 'Trade']             ], 
    ['TM.TAX.MRCH.WM.FN.ZS', 'Tariff rate, most favored nation, weighted mean, all products (%)'                                                              , ['Private', 'Trade']             ], 
    ['TM.TAX.TCOM.BC.ZS'   , 'Binding coverage, primary products (%)'                                                                                         , ['Private', 'Trade']             ], 
    ['TM.TAX.TCOM.BR.ZS'   , 'Bound rate, simple mean, primary products (%)'                                                                                  , ['Private', 'Trade']             ], 
    ['TM.TAX.TCOM.IP.ZS'   , 'Share of tariff lines with international peaks, primary products (%)'                                                           , ['Private', 'Trade']             ], 
    ['TM.TAX.TCOM.SM.AR.ZS', 'Tariff rate, applied, simple mean, primary products (%)'                                                                        , ['Private', 'Trade']             ], 
    ['TM.TAX.TCOM.SM.FN.ZS', 'Tariff rate, most favored nation, simple mean, primary products (%)'                                                            , ['Private', 'Trade']             ], 
    ['TM.TAX.TCOM.SR.ZS'   , 'Share of tariff lines with specific rates, primary products (%)'                                                                , ['Private', 'Trade']             ], 
    ['TM.TAX.TCOM.WM.AR.ZS', 'Tariff rate, applied, weighted mean, primary products (%)'                                                                      , ['Private', 'Trade']             ], 
    ['TM.TAX.TCOM.WM.FN.ZS', 'Tariff rate, most favored nation, weighted mean, primary products (%)'                                                          , ['Private', 'Trade']             ], 
    ['TM.VAL.AGRI.ZS.UN'   , 'Agricultural raw materials imports (% of merchandise imports)'                                                                  , ['AgriRural', 'Private', 'Trade']], 
    ['TM.VAL.FOOD.ZS.UN'   , 'Food imports (% of merchandise imports)'                                                                                        , ['Private', 'Trade']             ], 
    ['TM.VAL.FUEL.ZS.UN'   , 'Fuel imports (% of merchandise imports)'                                                                                        , ['Energy', 'Private', 'Trade']   ], 
    ['TM.VAL.ICTG.ZS.UN'   , 'ICT goods imports (% total goods imports)'                                                                                      , ['Infras', 'Private', 'Trade']   ], 
    ['TM.VAL.INSF.ZS.WT'   , 'Insurance and financial services (% of commercial service imports)'                                                             , ['Private', 'Trade']             ], 
    ['TM.VAL.MANF.ZS.UN'   , 'Manufactures imports (% of merchandise imports)'                                                                                , ['Private', 'Trade']             ], 
    ['TM.VAL.MMTL.ZS.UN'   , 'Ores and metals imports (% of merchandise imports)'                                                                             , ['Energy', 'Private', 'Trade']   ], 
    ['TM.VAL.MRCH.AL.ZS'   , 'Merchandise imports from economies in the Arab World (% of total merchandise imports)'                                          , ['Private', 'Trade']             ], 
    ['TM.VAL.MRCH.CD.WT'   , 'Merchandise imports (current US$)'                                                                                              , ['Private', 'Trade']             ], 
    ['TM.VAL.MRCH.HI.ZS'   , 'Merchandise imports from high-income economies (% of total merchandise imports)'                                                , ['Private', 'Trade']             ], 
    ['TM.VAL.MRCH.OR.ZS'   , 'Merchandise imports from low- and middle-income economies outside region (% of total merchandise imports)'                      , ['Private', 'Trade']             ], 
    ['TM.VAL.MRCH.R1.ZS'   , 'Merchandise imports from low- and middle-income economies in East Asia & Pacific (% of total merchandise imports)'              , ['Private', 'Trade']             ], 
    ['TM.VAL.MRCH.R2.ZS'   , 'Merchandise imports from low- and middle-income economies in Europe & Central Asia (% of total merchandise imports)'            , ['Private', 'Trade']             ], 
    ['TM.VAL.MRCH.R3.ZS'   , 'Merchandise imports from low- and middle-income economies in Latin America & the Caribbean (% of total merchandise imports)'    , ['Private', 'Trade']             ], 
    ['TM.VAL.MRCH.R4.ZS'   , 'Merchandise imports from low- and middle-income economies in Middle East & North Africa (% of total merchandise imports)'       , ['Private', 'Trade']             ], 
    ['TM.VAL.MRCH.R5.ZS'   , 'Merchandise imports from low- and middle-income economies in South Asia (% of total merchandise imports)'                       , ['Private', 'Trade']             ], 
    ['TM.VAL.MRCH.R6.ZS'   , 'Merchandise imports from low- and middle-income economies in Sub-Saharan Africa (% of total merchandise imports)'               , ['Private', 'Trade']             ], 
    ['TM.VAL.MRCH.RS.ZS'   , 'Merchandise imports by the reporting economy, residual (% of total merchandise imports)'                                        , ['Private', 'Trade']             ], 
    ['TM.VAL.MRCH.WL.CD'   , 'Merchandise imports by the reporting economy (current US$)'                                                                     , ['Private', 'Trade']             ], 
    ['TM.VAL.MRCH.WR.ZS'   , 'Merchandise imports from low- and middle-income economies within region (% of total merchandise imports)'                       , ['Private', 'Trade']             ], 
    ['TM.VAL.MRCH.XD.WD'   , 'Import value index (2000 = 100)'                                                                                                , ['Private', 'Trade']             ], 
    ['TM.VAL.OTHR.ZS.WT'   , 'Computer, communications and other services (% of commercial service imports)'                                                  , ['Private', 'Trade']             ], 
    ['TM.VAL.SERV.CD.WT'   , 'Commercial service imports (current US$)'                                                                                       , ['Private', 'Trade']             ], 
    ['TM.VAL.TRAN.ZS.WT'   , 'Transport services (% of commercial service imports)'                                                                           , ['Private', 'Trade']             ], 
    ['TM.VAL.TRVL.ZS.WT'   , 'Travel services (% of commercial service imports)'                                                                              , ['Private', 'Trade']             ], 
    ['TT.PRI.MRCH.XD.WD'   , 'Net barter terms of trade index (2000 = 100)'                                                                                   , ['Private', 'Trade']             ], 
    ['TX.QTY.MRCH.XD.WD'   , 'Export volume index (2000 = 100)'                                                                                               , ['Private', 'Trade']             ], 
    ['TX.VAL.AGRI.ZS.UN'   , 'Agricultural raw materials exports (% of merchandise exports)'                                                                  , ['AgriRural', 'Private', 'Trade']], 
    ['TX.VAL.FOOD.ZS.UN'   , 'Food exports (% of merchandise exports)'                                                                                        , ['Private', 'Trade']             ], 
    ['TX.VAL.FUEL.ZS.UN'   , 'Fuel exports (% of merchandise exports)'                                                                                        , ['Energy', 'Private', 'Trade']   ], 
    ['TX.VAL.ICTG.ZS.UN'   , 'ICT goods exports (% of total goods exports)'                                                                                   , ['Infras', 'Private', 'Trade']   ], 
    ['TX.VAL.INSF.ZS.WT'   , 'Insurance and financial services (% of commercial service exports)'                                                             , ['Private', 'Trade']             ], 
    ['TX.VAL.MANF.ZS.UN'   , 'Manufactures exports (% of merchandise exports)'                                                                                , ['Private', 'Trade']             ], 
    ['TX.VAL.MMTL.ZS.UN'   , 'Ores and metals exports (% of merchandise exports)'                                                                             , ['Energy', 'Private', 'Trade']   ], 
    ['TX.VAL.MRCH.AL.ZS'   , 'Merchandise exports to economies in the Arab World (% of total merchandise exports)'                                            , ['Private', 'Trade']             ], 
    ['TX.VAL.MRCH.CD.WT'   , 'Merchandise exports (current US$)'                                                                                              , ['Private', 'Trade']             ], 
    ['TX.VAL.MRCH.HI.ZS'   , 'Merchandise exports to high-income economies (% of total merchandise exports)'                                                  , ['Private', 'Trade']             ], 
    ['TX.VAL.MRCH.OR.ZS'   , 'Merchandise exports to low- and middle-income economies outside region (% of total merchandise exports)'                        , ['Private', 'Trade']             ], 
    ['TX.VAL.MRCH.R1.ZS'   , 'Merchandise exports to low- and middle-income economies in East Asia & Pacific (% of total merchandise exports)'                , ['Private', 'Trade']             ], 
    ['TX.VAL.MRCH.R2.ZS'   , 'Merchandise exports to low- and middle-income economies in Europe & Central Asia (% of total merchandise exports)'              , ['Private', 'Trade']             ], 
    ['TX.VAL.MRCH.R3.ZS'   , 'Merchandise exports to low- and middle-income economies in Latin America & the Caribbean (% of total merchandise exports)'      , ['Private', 'Trade']             ], 
    ['TX.VAL.MRCH.R4.ZS'   , 'Merchandise exports to low- and middle-income economies in Middle East & North Africa (% of total merchandise exports)'         , ['Private', 'Trade']             ], 
    ['TX.VAL.MRCH.R5.ZS'   , 'Merchandise exports to low- and middle-income economies in South Asia (% of total merchandise exports)'                         , ['Private', 'Trade']             ], 
    ['TX.VAL.MRCH.R6.ZS'   , 'Merchandise exports to low- and middle-income economies in Sub-Saharan Africa (% of total merchandise exports)'                 , ['Private', 'Trade']             ], 
    ['TX.VAL.MRCH.RS.ZS'   , 'Merchandise exports by the reporting economy, residual (% of total merchandise exports)'                                        , ['Private', 'Trade']             ], 
    ['TX.VAL.MRCH.WL.CD'   , 'Merchandise exports by the reporting economy (current US$)'                                                                     , ['Private', 'Trade']             ], 
    ['TX.VAL.MRCH.WR.ZS'   , 'Merchandise exports to low- and middle-income economies within region (% of total merchandise exports)'                         , ['Private', 'Trade']             ], 
    ['TX.VAL.MRCH.XD.WD'   , 'Export value index (2000 = 100)'                                                                                                , ['Private', 'Trade']             ], 
    ['TX.VAL.OTHR.ZS.WT'   , 'Computer, communications and other services (% of commercial service exports)'                                                  , ['Private', 'Trade']             ], 
    ['TX.VAL.SERV.CD.WT'   , 'Commercial service exports (current US$)'                                                                                       , ['Private', 'Trade']             ], 
    ['TX.VAL.TECH.CD'      , 'High-technology exports (current US$)'                                                                                          , ['Private', 'Stem', 'Trade']     ], 
    ['TX.VAL.TECH.MF.ZS'   , 'High-technology exports (% of manufactured exports)'                                                                            , ['Private', 'Stem', 'Trade']     ], 
    ['TX.VAL.TRAN.ZS.WT'   , 'Transport services (% of commercial service exports)'                                                                           , ['Private', 'Trade']             ], 
    ['TX.VAL.TRVL.ZS.WT'   , 'Travel services (% of commercial service exports)'                                                                              , ['Private', 'Trade']             ], 
  ], 
}