export const UrbanDevelopment = {
  head: ['id', 'name', 'topics'],
  rows: [
    ['AG.LND.EL5M.UR.K2', 'Urban land area where elevation is below 5 meters (sq. km)', ['Climate', 'Urban', 'Env']],
    ['AG.LND.EL5M.UR.ZS', 'Urban land area where elevation is below 5 meters (% of total land area)', ['Climate', 'Urban', 'Env']],
    ['AG.LND.TOTL.UR.K2', 'Urban land area (sq. km)', ['Urban', 'Env']],
    ['EG.ELC.ACCS.UR.ZS', 'Access to electricity, urban (% of urban population)', ['Energy', 'Urban']],
    ['EG.NSF.ACCS.UR.ZS', 'Access to non-solid fuel, urban (% of urban population)', ['Energy', 'Urban']],
    ['EN.ATM.PM25.MC.M3', 'PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)', ['Urban', 'Env']],
    ['EN.ATM.PM25.MC.ZS', 'PM2.5 air pollution, population exposed to levels exceeding WHO guideline value (% of total)', ['Urban', 'Env']],
    ['EN.POP.DNST', 'Population density (people per sq. km of land area)', ['Urban']],
    ['EN.POP.EL5M.UR.ZS', 'Urban population living in areas where elevation is below 5 meters (% of total population)', ['Climate', 'Urban', 'Env']],
    ['EN.POP.SLUM.UR.ZS', 'Population living in slums (% of urban population)', ['Poverty', 'Urban', 'Env']],
    ['EN.URB.LCTY', 'Population in largest city', ['Urban']],
    ['EN.URB.LCTY.UR.ZS', 'Population in the largest city (% of urban population)', ['Urban']],
    ['EN.URB.MCTY', 'Population in urban agglomerations of more than 1 million', ['Urban']],
    ['EN.URB.MCTY.TL.ZS', 'Population in urban agglomerations of more than 1 million (% of total population)', ['Climate', 'Urban']],
    ['EP.PMP.DESL.CD', 'Pump price for diesel fuel (US$ per liter)', ['Energy', 'Urban']],
    ['EP.PMP.SGAS.CD', 'Pump price for gasoline (US$ per liter)', ['Energy', 'Urban']],
    ['IS.VEH.NVEH.P3', 'Motor vehicles (per 1,000 people)', ['Infras', 'Urban']],
    ['IS.VEH.PCAR.P3', 'Passenger cars (per 1,000 people)', ['Urban', 'Infras']],
    ['IS.VEH.ROAD.K1', 'Vehicles (per km of road)', ['Urban', 'Infras']],
    ['SH.H2O.SAFE.UR.ZS', 'Improved water source, urban (% of urban population with access)', ['Climate', 'Infras', 'Health', 'Urban']],
    ['SH.STA.ACSN.UR', 'Improved sanitation facilities, urban (% of urban population with access)', ['Health', 'Urban']],
    ['SH.STA.TRAF.P5', 'Mortality caused by road traffic injury (per 100,000 people)', ['Health', 'Urban']],
    ['SI.POV.URGP', 'Urban poverty gap at national poverty lines (%)', ['Poverty', 'Urban']],
    ['SI.POV.URHC', 'Urban poverty headcount ratio at national poverty lines (% of urban population)', ['Poverty', 'Urban']],
    ['SP.URB.GROW', 'Urban population growth (annual %)', ['Climate', 'Urban']],
    ['SP.URB.TOTL', 'Urban population', ['Climate', 'Urban']],
    ['SP.URB.TOTL.IN.ZS', 'Urban population (% of total population)', ['Climate', 'Urban']],
  ],
}