export const CountryPartnershipStrategyForIndiaFy201317 = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['IN.AGR.GR.IRRIG.AREA'                 , 'Gross Irrigated Area under all crops (\'000 hectares)'                    , null], 
    ['IN.AGR.YLD.ALL'                       , 'Yield - All Foodgrains (Kgs/Hectare)'                                     , null], 
    ['IN.AGR.YLD.RICE'                      , 'Yield - Rice (Kgs/Hectare)'                                               , null], 
    ['IN.AGR.YLD.SUGRCANE'                  , 'Yield - Sugarcane (Kgs/Hectare)'                                          , null], 
    ['IN.EC.GSDP.PERCAP.NOM.INR'            , 'Nominal GSDP Per Capita (INR)'                                            , null], 
    ['IN.EC.GSDP.PERCAP.NOM.USD'            , 'Nominal GSDP Per Capita (USD)'                                            , null], 
    ['IN.EC.GSDP.PERCAP.REAL.INR'           , 'Real GSDP Per Capita (INR)'                                               , null], 
    ['IN.EC.GSDP.PERCAP.REAL.INR.GRWTHRAT'  , 'Real GSDP Per Capita (INR) Growth Rate'                                   , null], 
    ['IN.EC.GSDP.PERCAP.REAL.USD'           , 'Real GSDP Per Capita (USD)'                                               , null], 
    ['IN.EC.GSDP.PERCAP.REAL.USD.GRWTHRAT'  , 'Real GSDP Per Capita (USD) Growth Rate'                                   , null], 
    ['IN.EC.POP.GRWTHRAT'                   , 'Decadal Growth of Population (%)'                                         , null], 
    ['IN.EC.POP.GRWTHRAT.RURL'              , 'Decadal Growth of Population, Rural (%)'                                  , null], 
    ['IN.EC.POP.GRWTHRAT.URBN'              , 'Decadal Growth of Population, Urban (%)'                                  , null], 
    ['IN.EC.POP.RURL'                       , 'Population, Rural (Thousands)'                                            , null], 
    ['IN.EC.POP.RURL.PCT'                   , 'Population, Rural (%)'                                                    , null], 
    ['IN.EC.POP.TOTL'                       , 'Population (Thousands)'                                                   , null], 
    ['IN.EC.POP.URBN.PCT'                   , 'Population, Urban (%)'                                                    , null], 
    ['IN.EDU.ENROL.GEN'                     , 'Enrolment by Caste-General (%)'                                           , null], 
    ['IN.EDU.ENROL.MSLM'                    , 'Enrolment by Caste-Muslim (%)'                                            , null], 
    ['IN.EDU.ENROL.OBC'                     , 'Enrolment by Caste-OBC (%)'                                               , null], 
    ['IN.EDU.ENROL.SC'                      , 'Enrolment by Caste-SC (%)'                                                , null], 
    ['IN.EDU.ENROL.ST'                      , 'Enrolment by Caste-ST (%)'                                                , null], 
    ['IN.EDU.GR.ENRL.RATIO'                 , 'Gross Enrolment Ratio (%)'                                                , null], 
    ['IN.EDU.NET.ENRL.RATIO'                , 'Net Enrolment Ratio (%)'                                                  , null], 
    ['IN.EDU.PUPIL.TCHR'                    , 'Pupil-Teacher Ratio'                                                      , null], 
    ['IN.EDU.TCHR.NUM'                      , 'Teachers (Number)'                                                        , null], 
    ['IN.EDU.TCHRTRNG.NUM'                  , 'Teacher Education Institutes (DIETs, CTEs, IASEs)'                        , null], 
    ['IN.ENRGY.ELEC.CAP'                    , 'Total- Installed Capacity (MW)'                                           , null], 
    ['IN.ENRGY.ELEC.GEN'                    , 'Total-Electricity Generated Gross (GWh)'                                  , null], 
    ['IN.ENRGY.ELEC.PERCAP.CONSMPN'         , 'Utilities/Non Utilities Per Capita Consumption (KWh)'                     , null], 
    ['IN.ENRGY.ELEC.PERCAP.CONSMPN.NONUTLTS', 'Non Utilities Per Capita Consumption (KWh)'                               , null], 
    ['IN.ENRGY.ELEC.PERCAP.CONSMPN.TOTL'    , 'Total (Utilities & Non-Utilities) Per Capita Consumption (KWh)'           , null], 
    ['IN.ENRGY.GRID.RENEW.CAP'              , 'Grid interactive renewable power installed capacity (MW)'                 , null], 
    ['IN.ENRGY.TOWNS.ELECTRFIED.NUM'        , 'Number of Towns Electrified (Per 2001 Census)'                            , null], 
    ['IN.ENRGY.TOWNS.ELECTRFIED.PERCENT'    , 'Number of Towns Electrified (Percentage)'                                 , null], 
    ['IN.ENRGY.TOWNS.TOTL'                  , 'Number of Towns Total (Per 2001 Census)'                                  , null], 
    ['IN.ENRGY.VILLAG.ELECTRFIED'           , 'Number of Villages Electrified'                                           , null], 
    ['IN.ENRGY.VILLAG.ELECTRFIED.PERCENT'   , 'Number of Villages Electrified (Percentage)'                              , null], 
    ['IN.ENRGY.VILLAG.TOTL'                 , 'Number of Villages Total (Per 2001 Census)'                               , null], 
    ['IN.ENV.CO2.CONC'                      , 'CO2 Emission (in thousand metric tons of Carbon)'                         , null], 
    ['IN.ENV.CO2.PERCAP.CONC'               , 'Per Capita Emission ( metric tons of Carbon)'                             , null], 
    ['IN.ENV.COASTALZONE.AGRILAND.AREA'     , 'Agricultural land (SQ KMs)'                                               , null], 
    ['IN.ENV.COASTALZONE.AGRILAND.PCT'      , 'Ratio: Agricultural land to total coastal area of state (%)'              , null], 
    ['IN.ENV.COASTALZONE.BUILT.AREA'        , 'Built-up land (SQ KMs)'                                                   , null], 
    ['IN.ENV.COASTALZONE.BUILT.PCT'         , 'Ratio: Built-up land to total coastal area of state (%)'                  , null], 
    ['IN.ENV.COASTALZONE.FOREST.AREA'       , 'Forest (Non- tidal)/ Plantation (SQ KMs)'                                 , null], 
    ['IN.ENV.COASTALZONE.FOREST.PCT'        , 'Ratio: Forest (Non- tidal)/ Plantation to total coastal area of state (%)', null], 
    ['IN.ENV.COASTALZONE.OTHFEATURES.AREA'  , 'Other features (SQ KMs)'                                                  , null], 
    ['IN.ENV.COASTALZONE.OTHFEATURES.PCT'   , 'Ratio: Other features to total coastal area of state (%)'                 , null], 
    ['IN.ENV.COASTALZONE.SHORELAND.AREA'    , 'Shore land (SQ KMs)'                                                      , null], 
    ['IN.ENV.COASTALZONE.SHORELAND.PCT'     , 'Ratio: Shore land to total coastal area of state (%)'                     , null], 
    ['IN.ENV.COASTALZONE.WASTELAND.AREA'    , 'Barren wasteland (SQ KMs)'                                                , null], 
    ['IN.ENV.COASTALZONE.WASTELAND.PCT'     , 'Ratio: Barren/ wasteland to total coastal area of state (%)'              , null], 
    ['IN.ENV.COASTALZONE.WATERBODIES.AREA'  , 'Water bodies (SQ KMs)'                                                    , null], 
    ['IN.ENV.COASTALZONE.WATERBODIES.PCT'   , 'Ratio: Water bodies to total coastal area of state (%)'                   , null], 
    ['IN.ENV.COASTALZONE.WETLAND.AREA'      , 'Wetlands (SQ KMs)'                                                        , null], 
    ['IN.ENV.COASTALZONE.WETLAND.PCT'       , 'Ratio: Wetland to total coastal area of state (%)'                        , null], 
    ['IN.ENV.CROPINTENSIT.PCT'              , 'Cropping Intensity (%)'                                                   , null], 
    ['IN.ENV.FOREST.AREA'                   , 'Forest Cover  (\'000 hectares)'                                           , null], 
    ['IN.ENV.FOREST.PCT'                    , 'Forest Cover (Percent of Geographical Area)'                              , null], 
    ['IN.ENV.GEO.AREA'                      , 'Geographical Area (\'000 hectares)'                                       , null], 
    ['IN.ENV.GROSS.IRRIG.AREA'              , 'Gross Irrigated Area (\'000 hectares)'                                    , null], 
    ['IN.ENV.IRRIGTOCROPPED.PCT'            , 'Ratio: Gross Irrigated to Total Cropped Area (%)'                         , null], 
    ['IN.ENV.NET.IRRIG.AREA'                , 'Net Irrigated Area (\'000 hectares)'                                      , null], 
    ['IN.ENV.NO2.CONC'                      , 'AIr Quality: Nitrogen Oxide (Micrograms/Cubic Meter)'                     , null], 
    ['IN.ENV.NOCULTIVATION.AREA'            , 'Area not available for cultivation (\'000 hectares)'                      , null], 
    ['IN.ENV.OTHR.UNCULTIVABL.AREA'         , 'Other uncultivated (excl. fallow land) (\'000 hectares)'                  , null], 
    ['IN.ENV.PM.CONC'                       , 'AIr Quality: Particulate Matter (Micrograms/Cubic Meter)'                 , null], 
    ['IN.ENV.SO2.CONC'                      , 'AIr Quality: Sulfur Dioxide (Micrograms/Cubic Meter)'                     , null], 
    ['IN.FIN.COMMBANK.NUM'                  , 'Commercial Bank Offices (Total)'                                          , null], 
    ['IN.FIN.FININCL.INDX'                  , 'Financial Inclusion Index (CRISIL Method)'                                , null], 
    ['IN.FIN.HH.BNKG.SRVC.RURL'             , 'Total number of households availing banking services - Rural'             , null], 
    ['IN.FIN.HH.BNKG.SRVC.TOTL'             , 'Total number of households availing banking services'                     , null], 
    ['IN.FIN.HH.BNKG.SRVC.URBN'             , 'Total number of households availing banking services - Urban'             , null], 
    ['IN.FIN.HH.RURL'                       , 'Total number of households -Rural'                                        , null], 
    ['IN.FIN.HH.TOTL'                       , 'Total number of households'                                               , null], 
    ['IN.FIN.HH.URBN'                       , 'Total number of households - Urban'                                       , null], 
    ['IN.FIN.POP.PERBANK'                   , 'Average Population Per Bank Office (In Thousands)'                        , null], 
    ['IN.HLTH.AUXNURSE.NUM'                 , 'Auxiliary nursing midwives'                                               , null], 
    ['IN.HLTH.CHC.NUM'                      , 'Number of Community Health Centers (CHCs)'                                , null], 
    ['IN.HLTH.DISTHOSPTL.NUM'               , 'Number of District Hospitals'                                             , null], 
    ['IN.HLTH.DOCS.PER100K'                 , 'Number of Government Allopathic Doctors Per 100,000 Population'           , null], 
    ['IN.HLTH.GOVHOSPTL.BEDS.NUM'           , 'Government Hospitals Number of beds'                                      , null], 
    ['IN.HLTH.GOVHOSPTL.BEDS.PER100K'       , 'Government Hospitals Number of beds Per 100,000 Population'               , null], 
    ['IN.HLTH.GOVHOSPTL.NUM'                , 'Government Hospitals (Number)'                                            , null], 
    ['IN.HLTH.GOVHOSPTL.PER100K'            , 'Government Hospitals (Number) Per 100,000 Population'                     , null], 
    ['IN.HLTH.HIVDEATH.EST'                 , 'HIV/AIDS Related Death Estimates'                                         , null], 
    ['IN.HLTH.HIVINFECTION.EST'             , 'HIV Infection Estimates'                                                  , null], 
    ['IN.HLTH.HLTHSTAFF.NUM'                , 'Health visitors & Health supervisors'                                     , null], 
    ['IN.HLTH.MALARIA.CASES'                , 'Malaria - Cases'                                                          , null], 
    ['IN.HLTH.MALARIA.DEATH'                , 'Malaria - Deaths'                                                         , null], 
    ['IN.HLTH.SUBCTR.NUM'                   , 'Number of Sub-Centers (SCs)'                                              , null], 
    ['IN.IS.RRS.ELEC.KM'                    , 'Electrified Route Kilometres'                                             , null], 
    ['IN.IS.RRS.FRGT.LEAD'                  , 'Freight Traffic (revenue earning) - Lead (Average no. of KMs per tonne)'  , null], 
    ['IN.IS.RRS.FRGT.RATE'                  , 'Average Freight Rate per Tonne-KM (in Paise, for all commodities)'        , null], 
    ['IN.IS.RRS.FRGT.RVENU.NET.TON.KM'      , 'Freight Traffic (revenue earning) -Net Tonne Kilometers (millions)'       , null], 
    ['IN.IS.RRS.FRGT.SPEED'                 , 'Speed of Freight Trains (KMs/hour)'                                       , null], 
    ['IN.IS.RRS.FRGT.TONS.ORIG'             , 'Freight Traffic - Tonnes originating (Millions)'                          , null], 
    ['IN.IS.RRS.LOCO.NO'                    , 'Locomotives - Number in service'                                          , null], 
    ['IN.IS.RRS.LOCO.TRACT.KG3'             , 'Locomotives -Total tractive effort (\'000  Kgs)'                          , null], 
    ['IN.IS.RRS.PASG.KM.NONSUB'             , 'Passenger-Kilometers Traffic (Non-Suburban), in millions'                 , null], 
    ['IN.IS.RRS.PASG.KM.SUB'                , 'Passenger-Kilometers Traffic (Suburban), in millions'                     , null], 
    ['IN.IS.RRS.PASG.KM.TOTL'               , 'Total Passenger-Kilometers Traffic, in millions'                          , null], 
    ['IN.IS.RRS.RUN.KM'                     , 'Running Track Kilometres'                                                 , null], 
    ['IN.IS.RRS.TOTL.KM'                    , 'Total Route Kilometers'                                                   , null], 
    ['IN.IS.RRS.TRKDENSITY.NTKM'            , 'Net tonnes Kms. per Route Km. per Annum (\' 000s)'                        , null], 
    ['IN.IS.RRS.TRKDENSITY.TRAIN'           , 'Train Kms. per Running Track Km. per Day'                                 , null], 
    ['IN.IS.RRS.WAGN.LEAD'                  , 'Wagon Usage: Avergae Wagon Lead during run (in Tonnes)'                   , null], 
    ['IN.IS.RRS.WAGN.NTKM.PER.WAGNDAY'      , 'Wagon Usage: Net Tonne-KMs/Weagon Day'                                    , null], 
    ['IN.IS.RRS.WAGN.USAGE'                 , 'Wagon Usage (KMs/Wagon Day)'                                              , null], 
    ['IN.IS.RRS.WAGON.NO'                   , 'Number of wagons in service (All Gauges)'                                 , null], 
    ['IN.IS.RRSTRKDENSITY.PASG'             , 'Passenger Kms. per Route Km. per Annum 000s'                              , null], 
    ['IN.LABR.LABR.MYS'                     , 'Labor Force ages 15+ Rural & Urban: Mean Years of Schooling'              , null], 
    ['IN.LABR.LFPR.TOTL'                    , 'LFPR per 1000 for ages 15+ Rural & Urban: Level All Levels'               , null], 
    ['IN.LABR.LFPR.TOTL.DIPL'               , 'LFPR per 1000 for ages 15+ Rural & Urban: Level Diploma/Cert'             , null], 
    ['IN.LABR.LFPR.TOTL.HSCNDRY'            , 'LFPR per 1000 for ages 15+ Rural & Urban: Level Hr. Secondary'            , null], 
    ['IN.LABR.LFPR.TOTL.MIDDL'              , 'LFPR per 1000 for ages 15+ Rural & Urban: Level Middle'                   , null], 
    ['IN.LABR.LFPR.TOTL.NOTLITRT'           , 'LFPR per 1000 for ages 15+ Rural & Urban: Level Not Literate'             , null], 
    ['IN.LABR.LFPR.TOTL.PG'                 , 'LFPR per 1000 for ages 15+ Rural & Urban: Level Degree + Post Graduate'   , null], 
    ['IN.LABR.LFPR.TOTL.PRIMRY'             , 'LFPR per 1000 for ages 15+ Rural & Urban: Level Literacy upto Primary'    , null], 
    ['IN.LABR.LFPR.TOTL.SCNDRY'             , 'LFPR per 1000 for ages 15+ Rural & Urban: Level Secondary'                , null], 
    ['IN.POV.ASSETS.LANDMOBILE.PCT'         , 'Households with telephones (Landline & Mobile, %)'                        , null], 
    ['IN.POV.HCR.EST.RURL'                  , 'Poverty HCR Estimates (%) - Rural'                                        , null], 
    ['IN.POV.HCR.EST.TOTL'                  , 'Poverty HCR Estimates (%) - Total'                                        , null], 
    ['IN.POV.HCR.EST.URBN'                  , 'Poverty HCR Estimates (%) - Urban'                                        , null], 
    ['IN.POV.HH.ASSETS.COMP.INTERNET.PCT'   , 'Households having computer laptops (w/Internet, %)'                       , null], 
    ['IN.POV.HH.ASSETS.COMP.NOINTERNET.PCT' , 'Households having computer laptops (w/o Internet, %)'                     , null], 
    ['IN.POV.HH.ASSETS.COMPUTERS.PCT'       , 'Households having computer laptops (%)'                                   , null], 
    ['IN.POV.HH.ASSETS.LANDLINEPHONE.PCT'   , 'Households with telephones (Landline, %)'                                 , null], 
    ['IN.POV.HH.ASSETS.MOBILEPHONE.PCT'     , 'Households with telephones (Mobile, %)'                                   , null], 
    ['IN.POV.HH.ASSETS.NUM'                 , 'Households with assets (Number)'                                          , null], 
    ['IN.POV.HH.ASSETS.PHONE.PCT'           , 'Households with telephones (%)'                                           , null], 
    ['IN.POV.HH.DRKNGWATER'                 , 'Total households with drinking water facility'                            , null], 
    ['IN.POV.HH.DRKNGWATER.AWAY'            , 'Availability of drinking water from a source away'                        , null], 
    ['IN.POV.HH.DRKNGWATER.NEAR'            , 'Availability of drinking water source near the premises'                  , null], 
    ['IN.POV.HH.DRKNGWATER.WITHIN'          , 'Availability of drinking water source within the premises'                , null], 
    ['IN.POV.HH.DRNKNGWATER.RURL.PCT'       , 'Households Access to Safe Drinking Water - Rural (%)'                     , null], 
    ['IN.POV.HH.DRNKNGWATER.TOTL.PCT'       , 'Households Access to Safe Drinking Water - Total (%)'                     , null], 
    ['IN.POV.HH.DRNKNGWATER.URBN.PCT'       , 'Households Access to Safe Drinking Water - Urban (%)'                     , null], 
    ['IN.POV.HH.SLUMS.NUM'                  , 'Households in Slums (Number)'                                             , null], 
    ['IN.POV.HOUSNG.URBN.NUM'               , 'Urban housing - approved (number, cumulative total)'                      , null], 
    ['IN.POV.INF.MORTRATE'                  , 'Infant Mortality Rate (per 1,000)'                                        , null], 
    ['IN.POV.INF.MORTRATE.UNDR5'            , 'Under 5 Mortality Rate (Per 1,000)'                                       , null], 
    ['IN.POV.LIT.RAT.FEMALE'                , 'Literacy Rate Female (%)'                                                 , null], 
    ['IN.POV.LIT.RAT.MALE'                  , 'Literacy Rate Male (%)'                                                   , null], 
    ['IN.POV.LIT.RAT.RURL'                  , 'Literacy rate, Rural (%)'                                                 , null], 
    ['IN.POV.LIT.RAT.SLUMS.FEMALE.PCT'      , 'Literacy Rate in Slums-Female (%)'                                        , null], 
    ['IN.POV.LIT.RAT.SLUMS.MALE.PCT'        , 'Literacy Rate in Slums - Male (%)'                                        , null], 
    ['IN.POV.LIT.RAT.SLUMS.TOTL.PCT'        , 'Literacy Rate in Slums  - Total (%)'                                      , null], 
    ['IN.POV.LIT.RAT.TOTL'                  , 'Literacy Rate (%)'                                                        , null], 
    ['IN.POV.LIT.RAT.URBN'                  , 'Literacy rate, Urban (%)'                                                 , null], 
    ['IN.POV.LTRIN.POV.AWAY'                , 'Latrine not available within premises'                                    , null], 
    ['IN.POV.LTRIN.POV.WITHIN'              , 'Latrine facility available within premises'                               , null], 
    ['IN.POV.MIGRNTS.5TO9YEARS.NUM'         , 'Migrants, Total: 5 to 9 years  residence (Number)'                        , null], 
    ['IN.POV.MIGRNTS.FEMALE.1TO4YEARS.NUM'  , 'Migrants, Female 1 to 4 years  residence (Number)'                        , null], 
    ['IN.POV.MIGRNTS.FEMALE.5TO9YEARS.NUM'  , 'Migrants, Female: 5 to 9 years  residence (Number)'                       , null], 
    ['IN.POV.MIGRNTS.FEMALE.NUM'            , 'Migrants - Female (Number)'                                               , null], 
    ['IN.POV.MIGRNTS.FEMALE.UNDER1YEAR.NUM' , 'Migrants, Female: less than 1 Year  residence (Number)'                   , null], 
    ['IN.POV.MIGRNTS.MALE.1TO4YEARS.NUM'    , 'Migrants, Male: 1 to 4 years  residence (Number)'                         , null], 
    ['IN.POV.MIGRNTS.MALE.5TO9YEARS.NUM'    , 'Migrants, Male: 5 to 9 years  residence (Number)'                         , null], 
    ['IN.POV.MIGRNTS.MALE.NUM'              , 'Migrants - Male (Number)'                                                 , null], 
    ['IN.POV.MIGRNTS.MALE.UNDER1YEAR.NUM'   , 'Migrants, Male: less than 1 Year  residence (Number)'                     , null], 
    ['IN.POV.MIGRNTS.TOTL.1TO4YEARS.NUM'    , 'Migrants, Total: 1 to 4 years  residence (Number)'                        , null], 
    ['IN.POV.MIGRNTS.TOTL.NUM'              , 'Migrants, Total (Number)'                                                 , null], 
    ['IN.POV.MIGRNTS.TOTL.UNDER1YEAR.NUM'   , 'Migrants, Total: less than 1 Year  residence (Number)'                    , null], 
    ['IN.POV.SLUM.POP.FEMALE.NUM'           , 'Total Slum Population - Female (Number)'                                  , null], 
    ['IN.POV.SLUM.POP.MALE.NUM'             , 'Total Slum Population - Male (Number)'                                    , null], 
    ['IN.POV.SLUM.POP.TOTL.NUM'             , 'Total Slum Population (Number)'                                           , null], 
    ['IN.POV.WORKERS.SLUMS.FEMALE.NUM'      , 'Total Workers in Slums - Female (Number)'                                 , null], 
    ['IN.POV.WORKERS.SLUMS.MALE.NUM'        , 'Total Workers in Slums - Male (Number)'                                   , null], 
    ['IN.POV.WORKERS.SLUMS.TOTL.NUM'        , 'Total Workers in Slums (Number)'                                          , null], 
    ['IN.TRANSPORT.NATLHWY.BELOWSTD'        , 'National Highways (surfaced length) - Below standard single lane (KMs)'   , null], 
    ['IN.TRANSPORT.NATLHWY.DBLLANE'         , 'National Highways (surfaced length) - Standard double lane (KMs)'         , null], 
    ['IN.TRANSPORT.NATLHWY.MULTLANE'        , 'National Highways (surfaced length) - Standard multi lane (KMs)'          , null], 
    ['IN.TRANSPORT.NATLHWY.ONELANESTD'      , 'National Highways (surfaced length) - Standard single lane (KMs)'         , null], 
    ['IN.TRANSPORT.NATLHWY.TOTL'            , 'National Highways (surfaced length) - Total (KMs)'                        , null], 
    ['IN.TRANSPORT.RD.URBN'                 , 'Urban Roads (KMs)'                                                        , null], 
    ['IN.TRANSPORT.RD.URBN.BTCC.SURFACE'    , 'Urban Roads,  B.T/C.C surface (KMs)'                                      , null], 
    ['IN.TRANSPORT.RD.URBN.SURFACED'        , 'Urban Roads Surfaced (KMs)'                                               , null], 
    ['IN.TRANSPORT.RD.URBN.WBM.SURFACE'     , 'Urban Roads, W.B.M. surface (KMs)'                                        , null], 
    ['IN.TRANSPORT.RDCRASH.INJURD.NUM'      , 'Number of seriously injured in road traffic crashes'                      , null], 
    ['IN.TRANSPORT.RDCRASH.NUM'             , 'Number of road crashes'                                                   , null], 
    ['IN.TRANSPORT.RURLRD.DENSIT'           , 'Rural Road Density (KMs/1000 Population)'                                 , null], 
    ['IN.TRANSPORT.TRAFDEATH.NUM'           , 'Number of road traffic deaths'                                            , null], 
    ['IN.TRANSPORT.URBNRD.DENSIT'           , 'Urban Road Density (KMs Per 1000 Population)'                             , null], 
  ], 
}