export const CountryPolicyAndInstitutionalAssessment = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['IQ.CPA.BREG.XQ', 'CPIA business regulatory environment rating (1=low to 6=high)'                                  , ['Public']           ], 
    ['IQ.CPA.DEBT.XQ', 'CPIA debt policy rating (1=low to 6=high)'                                                      , ['Public']           ], 
    ['IQ.CPA.ECON.XQ', 'CPIA economic management cluster average (1=low to 6=high)'                                     , ['Public']           ], 
    ['IQ.CPA.ENVR.XQ', 'CPIA policy and institutions for environmental sustainability rating (1=low to 6=high)'         , ['Public']           ], 
    ['IQ.CPA.FINQ.XQ', 'CPIA quality of budgetary and financial management rating (1=low to 6=high)'                    , ['Public']           ], 
    ['IQ.CPA.FINS.XQ', 'CPIA financial sector rating (1=low to 6=high)'                                                 , ['Public']           ], 
    ['IQ.CPA.FISP.XQ', 'CPIA fiscal policy rating (1=low to 6=high)'                                                    , ['Public']           ], 
    ['IQ.CPA.GNDR.XQ', 'CPIA gender equality rating (1=low to 6=high)'                                                  , ['Public']           ], 
    ['IQ.CPA.HRES.XQ', 'CPIA building human resources rating (1=low to 6=high)'                                         , ['Public']           ], 
    ['IQ.CPA.IRAI.XQ', 'IDA resource allocation index (1=low to 6=high)'                                                , ['Public']           ], 
    ['IQ.CPA.MACR.XQ', 'CPIA macroeconomic management rating (1=low to 6=high)'                                         , ['Public']           ], 
    ['IQ.CPA.PADM.XQ', 'CPIA quality of public administration rating (1=low to 6=high)'                                 , ['Public']           ], 
    ['IQ.CPA.PRES.XQ', 'CPIA equity of public resource use rating (1=low to 6=high)'                                    , ['Public']           ], 
    ['IQ.CPA.PROP.XQ', 'CPIA property rights and rule-based governance rating (1=low to 6=high)'                        , ['Public']           ], 
    ['IQ.CPA.PROT.XQ', 'CPIA social protection rating (1=low to 6=high)'                                                , ['Public']           ], 
    ['IQ.CPA.PUBS.XQ', 'CPIA public sector management and institutions cluster average (1=low to 6=high)'               , ['Climate', 'Public']], 
    ['IQ.CPA.REVN.XQ', 'CPIA efficiency of revenue mobilization rating (1=low to 6=high)'                               , ['Public']           ], 
    ['IQ.CPA.SOCI.XQ', 'CPIA policies for social inclusion/equity cluster average (1=low to 6=high)'                    , ['Public']           ], 
    ['IQ.CPA.STRC.XQ', 'CPIA structural policies cluster average (1=low to 6=high)'                                     , ['Public']           ], 
    ['IQ.CPA.TRAD.XQ', 'CPIA trade rating (1=low to 6=high)'                                                            , ['Public']           ], 
    ['IQ.CPA.TRAN.XQ', 'CPIA transparency, accountability, and corruption in the public sector rating (1=low to 6=high)', ['Public']           ], 
  ], 
}