export const EnterpriseSurveys = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['IC.FRM.BRIB.GRAFT2'    , 'Bribery depth (% of public transactions where a gift or informal payment was requested)'             , null], 
    ['IC.FRM.BRIB.GRAFT3'    , 'Bribery incidence (percent of firms experiencing at least one bribe payment request)'                , null], 
    ['IC.FRM.CORR.CORR1'     , 'Percent of firms expected to give gifts in meetings with tax officials'                              , null], 
    ['IC.FRM.CORR.CORR10'    , 'Percent of firms expected to give gifts to get an operating license'                                 , null], 
    ['IC.FRM.CORR.CORR11'    , 'Percent of firms identifying corruption as a major constraint'                                       , null], 
    ['IC.FRM.CORR.CORR2'     , 'Percent of firms expected to give gifts to secure government contract'                               , null], 
    ['IC.FRM.CORR.CORR3'     , 'Value of gift expected to secure a government contract (% of contract value)'                        , null], 
    ['IC.FRM.CORR.CORR4'     , 'Percent of firms expected to give gifts to public officials "to get things done" '                   , null], 
    ['IC.FRM.CORR.CORR6'     , 'Percent of firms expected to give gifts to get an electrical connection'                             , null], 
    ['IC.FRM.CORR.CORR7'     , 'Percent of firms expected to give gifts to get a water connection'                                   , null], 
    ['IC.FRM.CORR.CORR8'     , 'Percent of firms expected to give gifts to get a construction permit'                                , null], 
    ['IC.FRM.CORR.CORR9'     , 'Percent of firms expected to give gifts to get an import license '                                   , null], 
    ['IC.FRM.CORR.CRIME9'    , 'Percent of firms identifying the courts system as a major constraint                         '       , null], 
    ['IC.FRM.CRM.CRIME1'     , 'Percent of firms paying for security'                                                                , null], 
    ['IC.FRM.CRM.CRIME10'    , 'Percent of firms experiencing losses due to theft and vandalism'                                     , null], 
    ['IC.FRM.CRM.CRIME2_C'   , 'If the establishment pays for security, average security costs (% of annual sales)'                  , null], 
    ['IC.FRM.CRM.CRIME3_C'   , 'If there were losses, average losses due to theft and vandalism (% of annual sales)'                 , null], 
    ['IC.FRM.CRM.CRIME5'     , 'Products shipped to supply domestic markets that were lost due to theft (% of product value)'        , null], 
    ['IC.FRM.CRM.CRIME8'     , 'Percent of firms identifying crime, theft and disorder as a major constraint              '          , null], 
    ['IC.FRM.EMP.GROW.PEFT2' , 'Annual employment growth (%)'                                                                        , null], 
    ['IC.FRM.FCHAR.CAR1'     , 'Age of the establishment (years)'                                                                    , null], 
    ['IC.FRM.FCHAR.CAR2'     , 'Proportion of private domestic ownership in a firm (%)'                                              , null], 
    ['IC.FRM.FCHAR.CAR7'     , 'Percent of firms with at least 10% of foreign ownership'                                             , null], 
    ['IC.FRM.FCHAR.CAR8'     , 'Percent of firms with at least 10% of government/state ownership'                                    , null], 
    ['IC.FRM.FCHAR.LFORM3'   , 'Percent of firms with legal status of Sole Proprietorship'                                           , null], 
    ['IC.FRM.FIAS.PEFT4'     , 'Percent of firms buying fixed assets'                                                                , null], 
    ['IC.FRM.FIN.FIN1'       , 'Proportion of investment financed internally (%)'                                                    , null], 
    ['IC.FRM.FIN.FIN10'      , 'Value of collateral needed for a loan (% of the loan amount)'                                        , null], 
    ['IC.FRM.FIN.FIN11'      , 'Proportion of loans requiring collateral (%)'                                                        , null], 
    ['IC.FRM.FIN.FIN12'      , 'Percent of firms using banks to finance investments'                                                 , null], 
    ['IC.FRM.FIN.FIN13'      , 'Percent of firms using banks to finance working capital'                                             , null], 
    ['IC.FRM.FIN.FIN14'      , 'Percent of firms with a bank loan/line of credit'                                                    , null], 
    ['IC.FRM.FIN.FIN15'      , 'Percent of firms with a checking or savings account'                                                 , null], 
    ['IC.FRM.FIN.FIN16'      , 'Percent of firms identifying access to finance as a major constraint'                                , null], 
    ['IC.FRM.FIN.FIN2'       , 'Proportion of investment financed by banks (%)'                                                      , null], 
    ['IC.FRM.FIN.FIN20'      , 'Percent of firms not needing a loan'                                                                 , null], 
    ['IC.FRM.FIN.FIN21'      , 'Percent of firms whose recent loan application was rejected'                                         , null], 
    ['IC.FRM.FIN.FIN22'      , 'Percent of firms using supplier/customer credit to finance working capital'                          , null], 
    ['IC.FRM.FIN.FIN7'       , 'Proportion of working capital financed by banks (%)'                                                 , null], 
    ['IC.FRM.GEN.GEND1'      , 'Percent of firms with female participation in ownership'                                             , null], 
    ['IC.FRM.GEN.GEND2'      , 'Proportion of permanent full-time workers that are female (%)'                                       , null], 
    ['IC.FRM.GEN.GEND3'      , 'Proportion of permanent full-time non-production workers that are female (%)'                        , null], 
    ['IC.FRM.GEN.GEND4'      , 'Percent of firms with a female top manager'                                                          , null], 
    ['IC.FRM.GEN.GEND5'      , 'Proportion of permanent full-time production workers that are female (%)'                            , null], 
    ['IC.FRM.GEN.GEND6'      , 'Percent of firms with majority female ownership'                                                     , null], 
    ['IC.FRM.INFOR.INFOR1'   , 'Percent of firms competing against unregistered or informal firms'                                   , null], 
    ['IC.FRM.INFOR.INFOR2'   , 'Percent of firms identifying practices of competitors in the informal sector as a major constraint  ', null], 
    ['IC.FRM.INFOR.INFOR4'   , 'Percent of firms formally registered when they started operations in the country'                    , null], 
    ['IC.FRM.INFOR.INFOR5'   , 'Number of years firm operated without formal registration'                                           , null], 
    ['IC.FRM.INFRA.IN1'      , 'Days to obtain an electrical connection (upon application)'                                          , null], 
    ['IC.FRM.INFRA.IN10_C'   , 'If a generator is used, average proportion of electricity from a generator (%)'                      , null], 
    ['IC.FRM.INFRA.IN11'     , 'Percent of firms identifying transportation as a major constraint'                                   , null], 
    ['IC.FRM.INFRA.IN12'     , 'Percent of firms identifying electricity as a major constraint'                                      , null], 
    ['IC.FRM.INFRA.IN14'     , 'Proportion of products lost to breakage or spoilage during shipping to domestic markets (%)'         , null], 
    ['IC.FRM.INFRA.IN16'     , 'Percent of firms experiencing electrical outages'                                                    , null], 
    ['IC.FRM.INFRA.IN17'     , 'Percent of firms experiencing water insufficiencies'                                                 , null], 
    ['IC.FRM.INFRA.IN2'      , 'Number of electrical outages in a typical month'                                                     , null], 
    ['IC.FRM.INFRA.IN3_C'    , 'If there were outages, average duration of a typical electrical outage (hours)'                      , null], 
    ['IC.FRM.INFRA.IN4_C'    , 'If there were outages, average losses due to electrical outages (% of annual sales)'                 , null], 
    ['IC.FRM.INFRA.IN6'      , 'Number of water insufficiencies in a typical month'                                                  , null], 
    ['IC.FRM.INFRA.IN9'      , 'Percent of firms owning or sharing a generator'                                                      , null], 
    ['IC.FRM.INNOV.T1'       , 'Percent of firms with an internationally-recognized quality certification'                           , null], 
    ['IC.FRM.INNOV.T10'      , 'Percent of firms that spend on R&D'                                                                  , null], 
    ['IC.FRM.INNOV.T2'       , 'Percent of firms with an annual financial statement reviewed by external auditors '                  , null], 
    ['IC.FRM.INNOV.T3'       , 'Capacity utilization (%)'                                                                            , null], 
    ['IC.FRM.INNOV.T4'       , 'Percent of firms using technology licensed from foreign companies'                                   , null], 
    ['IC.FRM.INNOV.T5'       , 'Percent of firms having their own Web site'                                                          , null], 
    ['IC.FRM.INNOV.T6'       , 'Percent of firms using e-mail to interact with clients/suppliers'                                    , null], 
    ['IC.FRM.INNOV.T7'       , 'Percent of firms that introduced a new product/service'                                              , null], 
    ['IC.FRM.INNOV.T8'       , 'Percent of firms whose new product/service is also new to the main market'                           , null], 
    ['IC.FRM.INNOV.T9'       , 'Percent of firms that introduced a process innovation'                                               , null], 
    ['IC.FRM.OBS.OBST1'      , 'Percent of firms choosing access to finance as their biggest obstacle'                               , null], 
    ['IC.FRM.OBS.OBST10'     , 'Percent of firms choosing labor regulations as their biggest obstacle'                               , null], 
    ['IC.FRM.OBS.OBST11'     , 'Percent of firms choosing political instability as their biggest obstacle'                           , null], 
    ['IC.FRM.OBS.OBST12'     , 'Percent of firms choosing practices of the informal sector as their biggest obstacle'                , null], 
    ['IC.FRM.OBS.OBST13'     , 'Percent of firms choosing tax administration as their biggest obstacle'                              , null], 
    ['IC.FRM.OBS.OBST14'     , 'Percent of firms choosing tax rates as their biggest obstacle'                                       , null], 
    ['IC.FRM.OBS.OBST15'     , 'Percent of firms choosing transportation as their biggest obstacle'                                  , null], 
    ['IC.FRM.OBS.OBST2'      , 'Percent of firms choosing access to land as their biggest obstacle'                                  , null], 
    ['IC.FRM.OBS.OBST3'      , 'Percent of firms choosing business licensing and permits as their biggest obstacle'                  , null], 
    ['IC.FRM.OBS.OBST4'      , 'Percent of firms choosing corruption as their biggest obstacle'                                      , null], 
    ['IC.FRM.OBS.OBST5'      , 'Percent of firms choosing courts as their biggest obstacle'                                          , null], 
    ['IC.FRM.OBS.OBST6'      , 'Percent of firms choosing crime, theft and disorder as their biggest obstacle'                       , null], 
    ['IC.FRM.OBS.OBST7'      , 'Percent of firms choosing customs and trade regulations as their biggest obstacle'                   , null], 
    ['IC.FRM.OBS.OBST8'      , 'Percent of firms choosing electricity as their biggest obstacle'                                     , null], 
    ['IC.FRM.OBS.OBST9'      , 'Percent of firms choosing inadequately educated workforce as their biggest obstacle'                 , null], 
    ['IC.FRM.PROD.GROW.PEFT3', 'Real annual labor productivity growth (%)'                                                           , null], 
    ['IC.FRM.REG.BUS1'       , 'Days to obtain an import license'                                                                    , null], 
    ['IC.FRM.REG.BUS2'       , 'Days to obtain an operating license'                                                                 , null], 
    ['IC.FRM.REG.BUS3'       , 'Days to obtain a construction-related permit'                                                        , null], 
    ['IC.FRM.REG.BUS5'       , 'Percent of firms identifying business licensing and permits as a major constraint'                   , null], 
    ['IC.FRM.REG.REG1'       , 'Senior management time spent dealing with the requirements of government regulation (%)'             , null], 
    ['IC.FRM.REG.REG2_C'     , 'If there were visits, average number of visits or required meetings with tax officials'              , null], 
    ['IC.FRM.REG.REG4'       , 'Percent of firms identifying tax rates as a major constraint'                                        , null], 
    ['IC.FRM.REG.REG5'       , 'Percent of firms identifying tax administration as a major constraint'                               , null], 
    ['IC.FRM.REG.REG6'       , 'Percent of firms visited or required to meet with tax officials'                                     , null], 
    ['IC.FRM.SLS.GROW.PEFT1' , 'Real annual sales growth (%)'                                                                        , null], 
    ['IC.FRM.TRD.TR1'        , 'Days to clear direct exports through customs'                                                        , null], 
    ['IC.FRM.TRD.TR11'       , 'Percent of firms using material inputs and/or supplies of foreign origin'                            , null], 
    ['IC.FRM.TRD.TR16'       , 'Percent of firms exporting directly (at least 10% of sales)'                                         , null], 
    ['IC.FRM.TRD.TR17'       , 'Percent of firms exporting directly or indirectly (at least 10% of sales)'                           , null], 
    ['IC.FRM.TRD.TR2'        , 'Days to clear imports from customs'                                                                  , null], 
    ['IC.FRM.TRD.TR5'        , 'Proportion of total sales that are exported directly (%)'                                            , null], 
    ['IC.FRM.TRD.TR8'        , 'Proportion of total inputs that are of foreign origin (%)'                                           , null], 
    ['IC.FRM.TRD.TR9'        , 'Percent of firms identifying customs and trade regulations as a major constraint'                    , null], 
    ['IC.FRM.WRKF.WK1'       , 'Percent of firms offering formal training'                                                           , null], 
    ['IC.FRM.WRKF.WK10'      , 'Percent of firms identifying an inadequately educated workforce as a major constraint'               , null], 
    ['IC.FRM.WRKF.WK14'      , 'Number of workers'                                                                                   , null], 
    ['IC.FRM.WRKF.WK15'      , 'Proportion of production workers (out of all permanent workers)'                                     , null], 
    ['IC.FRM.WRKF.WK17'      , 'Proportion of temporary workers (out of all workers)'                                                , null], 
    ['IC.FRM.WRKF.WK18'      , 'Proportion of permanent workers (out of all workers)'                                                , null], 
    ['IC.FRM.WRKF.WK19'      , 'Proportion of skilled workers (out of all production workers) (%)'                                   , null], 
    ['IC.FRM.WRKF.WK2'       , 'Proportion of workers offered formal training (%)'                                                   , null], 
    ['IC.FRM.WRKF.WK8'       , 'Years of the top manager\'s experience working in the firm\'s sector'                                , null], 
    ['IC.FRM.WRKF.WK9'       , 'Percent of firms identifying labor regulations as a major constraint'                                , null], 
  ], 
}