export const EnvironmentSocialAndGovernanceEsgData = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['AG.LND.AGRI.ZS'   , 'Agricultural land (% of land area)'                                                                       , ['AgriRural', 'Climate', 'Env']              ], 
    ['AG.LND.FRST.ZS'   , 'Forest area (% of land area)'                                                                             , ['AgriRural', 'Climate', 'Env']              ], 
    ['AG.PRD.FOOD.XD'   , 'Food production index (2014-2016 = 100)'                                                                  , ['AgriRural']                                ], 
    ['CC.EST'           , 'Control of Corruption: Estimate'                                                                          , null                                         ], 
    ['EG.CFT.ACCS.ZS'   , 'Access to clean fuels and technologies for cooking (% of population)'                                     , ['Env']                                      ], 
    ['EG.EGY.PRIM.PP.KD', 'Energy intensity level of primary energy (MJ/$2011 PPP GDP)'                                              , ['Energy', 'Env']                            ], 
    ['EG.ELC.ACCS.ZS'   , 'Access to electricity (% of population)'                                                                  , ['Energy', 'Climate', 'Env']                 ], 
    ['EG.ELC.COAL.ZS'   , 'Electricity production from coal sources (% of total)'                                                    , ['Energy', 'Climate', 'Infras']              ], 
    ['EG.ELC.RNEW.ZS'   , 'Renewable electricity output (% of total electricity output)'                                             , ['Energy', 'Climate', 'Env']                 ], 
    ['EG.FEC.RNEW.ZS'   , 'Renewable energy consumption (% of total final energy consumption)'                                       , ['Energy', 'Climate', 'Env']                 ], 
    ['EG.IMP.CONS.ZS'   , 'Energy imports, net (% of energy use)'                                                                    , ['Energy', 'Trade']                          ], 
    ['EG.USE.COMM.FO.ZS', 'Fossil fuel energy consumption (% of total)'                                                              , ['Energy']                                   ], 
    ['EG.USE.PCAP.KG.OE', 'Energy use (kg of oil equivalent per capita)'                                                             , ['Energy', 'Climate']                        ], 
    ['EN.ATM.CO2E.PC'   , 'CO2 emissions (metric tons per capita)'                                                                   , ['Climate', 'Env']                           ], 
    ['EN.ATM.METH.PC'   , 'Methane emissions (kt of CO2 equivalent per capita)'                                                      , null                                         ], 
    ['EN.ATM.NOXE.PC'   , 'Nitrous oxide emissions (metric tons of CO2 equivalent per capita)'                                       , null                                         ], 
    ['EN.ATM.PM25.MC.M3', 'PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)'                                   , ['Urban', 'Env']                             ], 
    ['EN.CLC.CDDY.XD'   , 'Cooling Degree Days (projected change in number of degree Celsius)'                                       , null                                         ], 
    ['EN.CLC.GHGR.MT.CE', 'GHG net emissions/removals by LUCF (Mt of CO2 equivalent)'                                                , ['Climate', 'Env']                           ], 
    ['EN.CLC.HEAT.XD'   , 'Heat Index 35 (projected change in days)'                                                                 , null                                         ], 
    ['EN.CLC.MDAT.ZS'   , 'Droughts, floods, extreme temperatures (% of population, average 1990-2009)'                              , ['Climate', 'Env']                           ], 
    ['EN.CLC.PRCP.XD'   , 'Maximum 5-day Rainfall, 25-year Return Level (projected change in mm)'                                    , null                                         ], 
    ['EN.CLC.SPEI.XD'   , 'Mean Drought Index (projected change, unitless)'                                                          , null                                         ], 
    ['EN.MAM.THRD.NO'   , 'Mammal species, threatened'                                                                               , ['Env']                                      ], 
    ['EN.POP.DNST'      , 'Population density (people per sq. km of land area)'                                                      , ['Urban']                                    ], 
    ['ER.H2O.FWTL.ZS'   , 'Annual freshwater withdrawals, total (% of internal resources)'                                           , ['Climate', 'Infras', 'Env']                 ], 
    ['ER.PTD.TOTL.ZS'   , 'Terrestrial and marine protected areas (% of total territorial area)'                                     , ['Climate', 'Env']                           ], 
    ['GB.XPD.RSDV.GD.ZS', 'Research and development expenditure (% of GDP)'                                                          , ['Stem']                                     ], 
    ['GE.EST'           , 'Government Effectiveness: Estimate'                                                                       , null                                         ], 
    ['IC.BUS.EASE.XQ'   , 'Ease of doing business index (1=most business-friendly regulations)'                                      , ['Climate', 'Private']                       ], 
    ['IC.LGL.CRED.XQ'   , 'Strength of legal rights index (0=weak to 12=strong)'                                                     , ['Fin', 'Private', 'Public']                 ], 
    ['IP.JRN.ARTC.SC'   , 'Scientific and technical journal articles'                                                                , ['Stem']                                     ], 
    ['IP.PAT.RESD'      , 'Patent applications, residents'                                                                           , ['Stem']                                     ], 
    ['IT.NET.USER.ZS'   , 'Individuals using the Internet (% of population)'                                                         , ['Infras']                                   ], 
    ['NV.AGR.TOTL.ZS'   , 'Agriculture, forestry, and fishing, value added (% of GDP)'                                               , ['AgriRural', 'Econ', 'Climate']             ], 
    ['NY.ADJ.DFOR.GN.ZS', 'Adjusted savings: net forest depletion (% of GNI)'                                                        , ['Econ', 'Env']                              ], 
    ['NY.ADJ.DRES.GN.ZS', 'Adjusted savings: natural resources depletion (% of GNI)'                                                 , ['Econ', 'Energy']                           ], 
    ['NY.GDP.MKTP.KD.ZG', 'GDP growth (annual %)'                                                                                    , ['Econ']                                     ], 
    ['PV.EST'           , 'Political Stability and Absence of Violence/Terrorism: Estimate'                                          , null                                         ], 
    ['RL.EST'           , 'Rule of Law: Estimate'                                                                                    , null                                         ], 
    ['RQ.EST'           , 'Regulatory Quality: Estimate'                                                                             , null                                         ], 
    ['SE.ADT.LITR.ZS'   , 'Literacy rate, adult total (% of people ages 15 and above)'                                               , ['Edu']                                      ], 
    ['SE.ENR.PRSC.FM.ZS', 'School enrollment, primary and secondary (gross), gender parity index (GPI)'                              , ['Aid', 'Climate', 'Edu', 'Gender', 'Social']], 
    ['SE.PRM.ENRR'      , 'School enrollment, primary (% gross)'                                                                     , ['Edu']                                      ], 
    ['SE.XPD.TOTL.GB.ZS', 'Government expenditure on education, total (% of government expenditure)'                                 , ['Edu']                                      ], 
    ['SG.GEN.PARL.ZS'   , 'Proportion of seats held by women in national parliaments (%)'                                            , ['Public', 'Gender', 'Social']               ], 
    ['SH.DTH.COMM.ZS'   , 'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)'    , ['Health']                                   ], 
    ['SH.DYN.MORT'      , 'Mortality rate, under-5 (per 1,000 live births)'                                                          , ['Health', 'Aid', 'Climate']                 ], 
    ['SH.H2O.SMDW.ZS'   , 'People using safely managed drinking water services (% of population)'                                    , ['Health', 'Env']                            ], 
    ['SH.MED.BEDS.ZS'   , 'Hospital beds (per 1,000 people)'                                                                         , ['Health']                                   ], 
    ['SH.STA.OWAD.ZS'   , 'Prevalence of overweight (% of adults)'                                                                   , null                                         ], 
    ['SH.STA.SMSS.ZS'   , 'People using safely managed sanitation services (% of population)'                                        , ['Health', 'Env']                            ], 
    ['SI.DST.FRST.20'   , 'Income share held by lowest 20%'                                                                          , ['Poverty', 'Aid']                           ], 
    ['SI.POV.GINI'      , 'Gini index (World Bank estimate)'                                                                         , ['Poverty']                                  ], 
    ['SI.POV.NAHC'      , 'Poverty headcount ratio at national poverty lines (% of population)'                                      , ['Poverty']                                  ], 
    ['SI.SPR.PCAP.ZG'   , 'Annualized average growth rate in per capita real survey mean consumption or income, total population (%)', ['Poverty']                                  ], 
    ['SL.TLF.0714.ZS'   , 'Children in employment, total (% of children ages 7-14)'                                                  , ['Labor', 'Social']                          ], 
    ['SL.TLF.ACTI.ZS'   , 'Labor force participation rate, total (% of total population ages 15-64) (modeled ILO estimate)'          , ['Labor', 'Social']                          ], 
    ['SL.TLF.CACT.FM.ZS', 'Ratio of female to male labor force participation rate (%) (modeled ILO estimate)'                        , ['Labor']                                    ], 
    ['SL.UEM.TOTL.ZS'   , 'Unemployment, total (% of total labor force) (modeled ILO estimate)'                                      , ['Edu', 'Labor']                             ], 
    ['SM.POP.NETM'      , 'Net migration'                                                                                            , ['Fin', 'Health', 'Aid']                     ], 
    ['SN.ITK.DEFC.ZS'   , 'Prevalence of undernourishment (% of population)'                                                         , ['Health']                                   ], 
    ['SP.DYN.LE00.IN'   , 'Life expectancy at birth, total (years)'                                                                  , ['Health']                                   ], 
    ['SP.DYN.TFRT.IN'   , 'Fertility rate, total (births per woman)'                                                                 , ['Health', 'Gender']                         ], 
    ['SP.POP.65UP.TO.ZS', 'Population ages 65 and above (% of total population)'                                                     , ['Health']                                   ], 
    ['SP.UWT.TFRT'      , 'Unmet need for contraception (% of married women ages 15-49)'                                             , ['Health']                                   ], 
    ['VA.EST'           , 'Voice and Accountability: Estimate'                                                                       , null                                         ], 
  ], 
}