export const ExporterDynamicsDatabaseIndicatorsAtCountryYearLevel = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['A1'    , '001.Number of Exporters'                                           , null], 
    ['A10i'  , '026.Export Value per Incumbent: Mean'                              , null], 
    ['A10ii' , '027.Export Value per Incumbent: Median'                            , null], 
    ['A10iii', '028.Export Value per Incumbent: StDev.'                            , null], 
    ['A10iv' , '029.Export Value per Incumbent: First Quartile'                    , null], 
    ['A10v'  , '030.Export Value per Incumbent: Third Quartile'                    , null], 
    ['A11i'  , '031.Growth of Incumbents: Mean'                                    , null], 
    ['A11ii' , '032.Growth of Incumbents: Median'                                  , null], 
    ['A11iii', '033.Growth of Incumbents: StDev.'                                  , null], 
    ['A11iv' , '034.Growth of Incumbents: First Quartile'                          , null], 
    ['A11v'  , '035.Growth of Incumbents: Third Quartile'                          , null], 
    ['A12i'  , '036.Growth of Surviving Entrants: Mean'                            , null], 
    ['A12ii' , '037.Growth of Surviving Entrants: Median'                          , null], 
    ['A12iii', '038.Growth of Surviving Entrants: StDev.'                          , null], 
    ['A12iv' , '039.Growth of Surviving Entrants: First Quartile'                  , null], 
    ['A12v'  , '040.Growth of Surviving Entrants: Third Quartile'                  , null], 
    ['A2'    , '002.Number of Entrants'                                            , null], 
    ['A3'    , '003.Number of Exiters'                                             , null], 
    ['A4'    , '004.Number of Surviving Entrants'                                  , null], 
    ['A5'    , '005.Number of Incumbents'                                          , null], 
    ['A6i'   , '006.Export Value per Exporter: Mean'                               , null], 
    ['A6ii'  , '007.Export Value per Exporter: Median'                             , null], 
    ['A6iii' , '008.Export Value per Exporter: StDev.'                             , null], 
    ['A6iv'  , '009.Export Value per Exporter: First Quartile'                     , null], 
    ['A6v'   , '010.Export Value per Exporter: Third Quartile'                     , null], 
    ['A7i'   , '011.Export Value per Entrant: Mean'                                , null], 
    ['A7ii'  , '012.Export Value per Entrant: Median'                              , null], 
    ['A7iii' , '013.Export Value per Entrant: StDev.'                              , null], 
    ['A7iv'  , '014.Export Value per Entrant: First Quartile'                      , null], 
    ['A7v'   , '015.Export Value per Entrant: Third Quartile'                      , null], 
    ['A8i'   , '016.Export Value per Exiter: Mean'                                 , null], 
    ['A8ii'  , '017.Export Value per Exiter: Median'                               , null], 
    ['A8iii' , '018.Export Value per Exiter: StDev.'                               , null], 
    ['A8iv'  , '019.Export Value per Exiter: First Quartile'                       , null], 
    ['A8v'   , '020.Export Value per Exiter: Third Quartile'                       , null], 
    ['A9i'   , '021.Export Value per Surviving Entrant: Mean'                      , null], 
    ['A9ii'  , '022.Export Value per Surviving Entrant: Median'                    , null], 
    ['A9iii' , '023.Export Value per Surviving Entrant: StDev.'                    , null], 
    ['A9iv'  , '024.Export Value per Surviving Entrant: First Quartile'            , null], 
    ['A9v'   , '025.Export Value per Surviving Entrant: Third Quartile'            , null], 
    ['B1'    , '041.Herfindahl-Hirschman Index'                                    , null], 
    ['B2i'   , '042.Share of top 1% Exporters in TEV (Total Export Value)'         , null], 
    ['B2ii'  , '043.Share of top 5% Exporters in TEV (Total Export Value)'         , null], 
    ['B2iii' , '044.Share of top 25% Exporters in TEV (Total Export Value)'        , null], 
    ['B3i'   , '045.Number of HS6 Products per Exporter: Mean'                     , null], 
    ['B3ii'  , '046.Number of HS6 Products per Exporter: Median'                   , null], 
    ['B3iii' , '047.Number of HS6 Products per Exporter: StDev.'                   , null], 
    ['B4i'   , '048.Number of Destinations per Exporter: Mean'                     , null], 
    ['B4ii'  , '049.Number of Destinations per Exporter: Median'                   , null], 
    ['B4iii' , '050.Number of Destinations per Exporter: StDev.'                   , null], 
    ['B5i'   , '051.Number of Exporters per HS6 Product: Mean'                     , null], 
    ['B5ii'  , '052.Number of Exporters per HS6 Product: Median'                   , null], 
    ['B5iii' , '053.Number of Exporters per HS6 Product: StDev.'                   , null], 
    ['B6i'   , '054.Number of Exporters per Destination: Mean'                     , null], 
    ['B6ii'  , '055.Number of Exporters per Destination: Median'                   , null], 
    ['B6iii' , '056.Number of Exporters per Destination: StDev.'                   , null], 
    ['C1'    , '057.Firm Entry Rate'                                               , null], 
    ['C2'    , '058.Firm Exit Rate'                                                , null], 
    ['C3'    , '059.Entrant 1st Year Survival Rate'                                , null], 
    ['C4'    , '060.Share of Entrants in TEV (Total Export Value)'                 , null], 
    ['C5'    , '061.Entrant 2nd Year Survival Rate'                                , null], 
    ['C6'    , '062.Entrant 3rd Year Survival Rate'                                , null], 
    ['D1i'   , '063.Product Entry Rate of Incumbents: Mean'                        , null], 
    ['D1ii'  , '064.Product Entry Rate of Incumbents: Median'                      , null], 
    ['D1iii' , '065.Product Entry Rate of Incumbents: StDev.'                      , null], 
    ['D2i'   , '066.Product Entry Rate of Surviving Entrants: Mean'                , null], 
    ['D2ii'  , '067.Product Entry Rate of Surviving Entrants: Median'              , null], 
    ['D2iii' , '068.Product Entry Rate of Surviving Entrants: StDev.'              , null], 
    ['D3i'   , '069.Share of New Products in TEV of Incumbents: Mean'              , null], 
    ['D3ii'  , '070.Share of New Products in TEV of Incumbents: Median'            , null], 
    ['D3iii' , '071.Share of New Products in TEV of Incumbents: StDev.'            , null], 
    ['D4i'   , '072.Share of New Products in TEV of Surviving Entrants: Mean'      , null], 
    ['D4ii'  , '073.Share of New Products in TEV of Surviving Entrants: Median'    , null], 
    ['D4iii' , '074.Share of New Products in TEV of Surviving Entrants: StDev.'    , null], 
    ['D5i'   , '075.Product Exit Rate of Incumbents: Mean'                         , null], 
    ['D5ii'  , '076.Product Exit Rate of Incumbents: Median'                       , null], 
    ['D5iii' , '077.Product Exit Rate of Incumbents: StDev.'                       , null], 
    ['D6i'   , '078.Product Survival Rate of 2-year Incumbents: Mean'              , null], 
    ['D6ii'  , '079.Product Survival Rate of 2-year Incumbents: Median'            , null], 
    ['D6iii' , '080.Product Survival Rate of 2-year Incumbents: StDev.'            , null], 
    ['E1i'   , '081.Destination Entry Rate of Incumbents: Mean'                    , null], 
    ['E1ii'  , '082.Destination Entry Rate of Incumbents: Median'                  , null], 
    ['E1iii' , '083.Destination Entry Rate of Incumbents: StDev.'                  , null], 
    ['E2i'   , '084.Destination Entry Rate of Surviving Entrants: Mean'            , null], 
    ['E2ii'  , '085.Destination Entry Rate of Surviving Entrants: Median'          , null], 
    ['E2iii' , '086.Destination Entry Rate of Surviving Entrants: StDev.'          , null], 
    ['E3i'   , '087.Share of New Destinations in TEV of Incumbents: Mean'          , null], 
    ['E3ii'  , '088.Share of New Destinations in TEV of Incumbents: Median'        , null], 
    ['E3iii' , '089.Share of New Destinations in TEV of Incumbents: StDev.'        , null], 
    ['E4i'   , '090.Share of New Destinations in TEV of Surviving Entrants: Mean'  , null], 
    ['E4ii'  , '091.Share of New Destinations in TEV of Surviving Entrants: Median', null], 
    ['E4iii' , '092.Share of New Destinations in TEV of Surviving Entrants: StDev.', null], 
    ['E5i'   , '093.Destination Exit Rate of Incumbents: Mean'                     , null], 
    ['E5ii'  , '094.Destination Exit Rate of Incumbents: Median'                   , null], 
    ['E5iii' , '095.Destination Exit Rate of Incumbents: StDev.'                   , null], 
    ['E6i'   , '096.Destination Survival Rate of 2-year Incumbents: Mean'          , null], 
    ['E6ii'  , '097.Destination Survival Rate of 2-year Incumbents: Median'        , null], 
    ['E6iii' , '098.Destination Survival Rate of 2-year Incumbents: StDev.'        , null], 
  ], 
}