export const G20FinancialInclusionIndicators = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['account_t_d'                  , 'Account (% age 15+)'                                                                                           , null], 
    ['account_t_d_1'                , 'Account, female (% age 15+)'                                                                                   , null], 
    ['account_t_d_2'                , 'Account, male (% age 15+)'                                                                                     , null], 
    ['account_t_d_3'                , 'Account, income, poorest 40% (% age 15+)'                                                                      , null], 
    ['account_t_d_4'                , 'Account, income, richest 60% (% age 15+)'                                                                      , null], 
    ['account_t_d_5'                , 'Account (% ages 15-34)'                                                                                        , null], 
    ['account_t_d_6'                , 'Account (% ages 35-59)'                                                                                        , null], 
    ['account_t_d_7'                , 'Account (% age 60+)'                                                                                           , null], 
    ['fin11q1'                      , 'SMEs with at least one female owner with a proportion of loans requiring collateral'                           , null], 
    ['fin11q2'                      , 'SMEs with a proportion of loans requiring collateral'                                                          , null], 
    ['fin14q1'                      , 'SMEs with at least one female owner with an outstanding loan or line of credit'                                , null], 
    ['fin14q2'                      , 'SMEs with an outstanding loan or line of credit'                                                               , null], 
    ['fin15q1'                      , 'SMEs with at least one female owner with an account at a formal financial institution'                         , null], 
    ['fin15q2'                      , 'SMEs with an account at a formal financial institution'                                                        , null], 
    ['fin16_t_a'                    , 'Saved for old age (% age 15+)'                                                                                 , null], 
    ['fin16_t_a_1'                  , 'Saved for old age, female (% age 15+)'                                                                         , null], 
    ['fin16_t_a_2'                  , 'Saved for old age, male (% age 15+)'                                                                           , null], 
    ['fin16_t_a_3'                  , 'Saved for old age, income, poorest 40% (% age 15+)'                                                            , null], 
    ['fin16_t_a_4'                  , 'Saved for old age, income, richest 60% (% age 15+)'                                                            , null], 
    ['fin16_t_a_5'                  , 'Saved for old age (% ages 15-34)'                                                                              , null], 
    ['fin16_t_a_6'                  , 'Saved for old age (% ages 35-59)'                                                                              , null], 
    ['fin16_t_a_7'                  , 'Saved for old age (% age 60+)'                                                                                 , null], 
    ['fin17a_t_a'                   , 'Saved at a financial institution (% age 15+)'                                                                  , null], 
    ['fin17a_t_a_1'                 , 'Saved at a financial institution, female  (% age 15+)'                                                         , null], 
    ['fin17a_t_a_2'                 , 'Saved at a financial institution, male (% age 15+)'                                                            , null], 
    ['fin17a_t_a_3'                 , 'Saved at a financial institution, income, poorest 40% (% age 15+)'                                             , null], 
    ['fin17a_t_a_4'                 , 'Saved at a financial institution, income, richest 60% (% age 15+)'                                             , null], 
    ['fin17a_t_a_5'                 , 'Saved at a financial institution (% ages 15-34)'                                                               , null], 
    ['fin17a_t_a_6'                 , 'Saved at a financial institution (% ages 35-59)'                                                               , null], 
    ['fin17a_t_a_7'                 , 'Saved at a financial institution (% age 60+)'                                                                  , null], 
    ['fin22a_t_d'                   , 'Borrowed from a financial institution or used a credit card (% age 15+)'                                       , null], 
    ['fin22a_t_d_1'                 , 'Borrowed from a financial institution or used a credit card, female (% age 15+)'                               , null], 
    ['fin22a_t_d_2'                 , 'Borrowed from a financial institution or used a credit card, male (% age 15+)'                                 , null], 
    ['fin22a_t_d_3'                 , 'Borrowed from a financial institution or used a credit card, income, poorest 40% (% age 15+)'                  , null], 
    ['fin22a_t_d_4'                 , 'Borrowed from a financial institution or used a credit card, income, richest 60% (% age 15+)'                  , null], 
    ['fin22a_t_d_5'                 , 'Borrowed from a financial institution or used a credit card (% ages 15-34)'                                    , null], 
    ['fin22a_t_d_6'                 , 'Borrowed from a financial institution or used a credit card (% ages 35-59)'                                    , null], 
    ['fin22a_t_d_7'                 , 'Borrowed from a financial institution or used a credit card (% age 60+)'                                       , null], 
    ['fin25a_t_a_s'                 , 'Main source of emergency funds: savings (% age 15+)'                                                           , null], 
    ['fin25a_t_a_s_1'               , 'Main source of emergency funds: savings, female  (% age 15+)'                                                  , null], 
    ['fin25a_t_a_s_2'               , 'Main source of emergency funds: savings, male (% age 15+)'                                                     , null], 
    ['fin25a_t_a_s_3'               , 'Main source of emergency funds: savings, income, poorest 40% (% age 15+)'                                      , null], 
    ['fin25a_t_a_s_4'               , 'Main source of emergency funds: savings, income, richest 60% (% age 15+)'                                      , null], 
    ['fin25a_t_a_s_5'               , 'Main source of emergency funds: savings, (% ages 15-34)'                                                       , null], 
    ['fin25a_t_a_s_6'               , 'Main source of emergency funds: savings (% ages 35-59)'                                                        , null], 
    ['fin25a_t_a_s_7'               , 'Main source of emergency funds: savings (% age 60+)'                                                           , null], 
    ['fin4_t_d'                     , 'Used a debit or credit card to make a purchase in the past year (% age 15+)'                                   , null], 
    ['fin48_a'                      , 'Has a national identity card (% age 15+)'                                                                      , null], 
    ['fin48_a_1'                    , 'Has a national identity card, female (% age 15+)'                                                              , null], 
    ['fin48_a_2'                    , 'Has a national identity card, male (% age 15+)'                                                                , null], 
    ['fin48_a_3'                    , 'Has a national identity card, income, poorest 40% (% age 15+)'                                                 , null], 
    ['fin48_a_4'                    , 'Has a national identity card, income, richest 60% (% age 15+)'                                                 , null], 
    ['fin48_a_5'                    , 'Has a national identity card (% ages 15-34)'                                                                   , null], 
    ['fin48_a_6'                    , 'Has a national identity card (% ages 35-59)'                                                                   , null], 
    ['fin48_a_7'                    , 'Has a national identity card (% age 60+)'                                                                      , null], 
    ['fin6_a'                       , 'Used a mobile phone or the internet to check account balance in the past year (% age 15+)'                     , null], 
    ['fin6_a_1'                     , 'Used a mobile phone or the internet to check account balance in the past year, female  (% age 15+)'            , null], 
    ['fin6_a_2'                     , 'Used a mobile phone or the internet to check account balance in the past year, male (% age 15+)"'              , null], 
    ['fin6_a_3'                     , 'Used a mobile phone or the internet to check account balance in the past year, income, poorest 40% (% age 15+)', null], 
    ['fin6_a_4'                     , 'Used a mobile phone or the internet to check account balance in the past year, income, richest 60% (% age 15+)', null], 
    ['fin6_a_5'                     , 'Used a mobile phone or the internet to check account balance in the past year (% ages 15-34)'                  , null], 
    ['fin6_a_6'                     , 'Used a mobile phone or the internet to check account balance in the past year (% ages 35-59)'                  , null], 
    ['fin6_a_7'                     , 'Used a mobile phone or the internet to check account balance in the past year (% age 60+)'                     , null], 
    ['g20_t'                        , 'Made or received digital payments in the past year (% age 15+)'                                                , null], 
    ['g20_t_1'                      , 'Made or received digital payments in the past year, female (% age 15+)'                                        , null], 
    ['g20_t_2'                      , 'Made or received digital payments in the past year, male (% age 15+)'                                          , null], 
    ['g20_t_3'                      , 'Made or received digital payments in the past year, income, poorest 40% (% age 15+)'                           , null], 
    ['g20_t_4'                      , 'Made or received digital payments in the past year, income, richest 60% (% age 15+)'                           , null], 
    ['g20_t_5'                      , 'Made or received digital payments in the past year (% ages 15-34)'                                             , null], 
    ['g20_t_6'                      , 'Made or received digital payments in the past year (% ages 35-59)'                                             , null], 
    ['g20_t_7'                      , 'Made or received digital payments in the past year (% age 60+)'                                                , null], 
    ['gf10_n'                       , 'Received wages or government transfers into an account (% age 15+)'                                            , null], 
    ['gf10_n_1'                     , 'Received wages or government transfers into an account, female (% age 15+)'                                    , null], 
    ['gf10_n_2'                     , 'Received wages or government transfers into an account, male (% age 15+)'                                      , null], 
    ['gf10_n_3'                     , 'Received wages or government transfers into an account, income, poorest 40% (% age 15+)'                       , null], 
    ['gf10_n_4'                     , 'Received wages or government transfers into an account, income, richest 60% (% age 15+)'                       , null], 
    ['gf10_n_5'                     , 'Received wages or government transfers into an account, (% ages 15-34)'                                        , null], 
    ['gf10_n_6'                     , 'Received wages or government transfers into an account (% ages 35-59)'                                         , null], 
    ['gf10_n_7'                     , 'Received wages or government transfers into an account (% age 60+)'                                            , null], 
    ['gf4_n'                        , 'Made payment using a mobile phone or the internet (% age 15+)'                                                 , null], 
    ['gf4_n_1'                      , 'Made payment using a mobile phone or the internet, female (% age 15+)'                                         , null], 
    ['gf4_n_2'                      , 'Made payment using a mobile phone or the internet, male (% age 15+)'                                           , null], 
    ['gf4_n_3'                      , 'Made payment using a mobile phone or the internet, income, poorest 40% (% age 15+)'                            , null], 
    ['gf4_n_4'                      , 'Made payment using a mobile phone or the internet, income, richest 60% (% age 15+)'                            , null], 
    ['gf4_n_5'                      , 'Made payment using a mobile phone or the internet (% ages 15-34)'                                              , null], 
    ['gf4_n_6'                      , 'Made payment using a mobile phone or the internet (% ages 35-59)'                                              , null], 
    ['gf4_n_7'                      , 'Made payment using a mobile phone or the internet (% age 60+)'                                                 , null], 
    ['gf7_n'                        , 'Active account (% age 15+)'                                                                                    , null], 
    ['gf7_n_1'                      , 'Active account, female (% age 15+)'                                                                            , null], 
    ['gf7_n_2'                      , 'Active account, male (% age 15+)'                                                                              , null], 
    ['gf7_n_3'                      , 'Active account, income, poorest 40% (% age 15+)'                                                               , null], 
    ['gf7_n_4'                      , 'Active account, income, richest 60% (% age 15+)'                                                               , null], 
    ['gf7_n_5'                      , 'Active account (% ages 15-34)'                                                                                 , null], 
    ['gf7_n_6'                      , 'Active account (% ages 35-59)'                                                                                 , null], 
    ['gf7_n_7'                      , 'Active account (% age 60+)'                                                                                    , null], 
    ['GPFI1_TOTL'                   , 'Financial knowledge score (0-3)'                                                                               , null], 
    ['GPFI2'                        , 'Disclosure index (0-5)'                                                                                        , null], 
    ['GPFI3'                        , 'Dispute resolution index (0-1)'                                                                                , null], 
    ['GPFI4'                        , 'Getting credit: Distance to frontier (0-100)'                                                                  , null], 
    ['GPSS'                         , 'Interoperability of ATM networks and interoperability of POS terminals (0-1)'                                  , null], 
    ['GPSS_1'                       , 'E-money accounts per 1,000 adults'                                                                             , null], 
    ['GPSS_2'                       , 'Retail cashless transactions per 1,000 adults'                                                                 , null], 
    ['GPSS_3'                       , 'Agents of payment service providers per 100,000 adults'                                                        , null], 
    ['GPSS_4'                       , 'POS terminals per 100,000 adults'                                                                              , null], 
    ['GPSS_5'                       , 'Debit cards per 1,000 adults'                                                                                  , null], 
    ['gwp1_n'                       , 'Access to a mobile phone (% age 15+)'                                                                          , null], 
    ['gwp1_n_1'                     , 'Access to a mobile phone, female (% age 15+)'                                                                  , null], 
    ['gwp1_n_2'                     , 'Access to a mobile phone, male (% age 15+)'                                                                    , null], 
    ['gwp1_n_3'                     , 'Access to a mobile phone, income, poorest 40% (% age 15+)'                                                     , null], 
    ['gwp1_n_4'                     , 'Access to a mobile phone, income, richest 60% (% age 15+)'                                                     , null], 
    ['gwp1_n_5'                     , 'Access to a mobile phone (% ages 15-34)'                                                                       , null], 
    ['gwp1_n_6'                     , 'Access to a mobile phone (% ages 35-59)'                                                                       , null], 
    ['gwp1_n_7'                     , 'Access to a mobile phone (% age 60+)'                                                                          , null], 
    ['gwp2_n'                       , 'Access to internet (% age 15+)'                                                                                , null], 
    ['gwp2_n_1'                     , 'Access to internet, female (% age 15+)'                                                                        , null], 
    ['gwp2_n_2'                     , 'Access to internet, male (% age 15+)'                                                                          , null], 
    ['gwp2_n_3'                     , 'Access to internet, income, poorest 40% (% age 15+)'                                                           , null], 
    ['gwp2_n_4'                     , 'Access to internet, income, richest 60% (% age 15+)'                                                           , null], 
    ['gwp2_n_5'                     , 'Access to internet (% ages 15-34)'                                                                             , null], 
    ['gwp2_n_6'                     , 'Access to internet (% ages 35-59)'                                                                             , null], 
    ['gwp2_n_7'                     , 'Access to internet (% age 60+)'                                                                                , null], 
    ['i_ATMs_pop'                   , 'ATMs per 100,000 adults'                                                                                       , null], 
    ['i_branches_A1_pop'            , 'Branches per 100,000 adults'                                                                                   , null], 
    ['i_deposit_acc_A1_pop'         , 'Deposit accounts per 1,000 adults'                                                                             , null], 
    ['i_deposit_acc_A1_sme_perNFC'  , 'SME deposit accounts (as a % of non-financial corporation borrowers)'                                          , null], 
    ['i_loan_acc_A1_sme_perNFC'     , 'SME loan accounts (as a % of non-financial corporation borrowers)'                                             , null], 
    ['i_mob_agent_pop_registered'   , 'Mobile agent outlets per 100,000 adults'                                                                       , null], 
    ['i_mob_transactions_number_pop', 'Mobile money transactions per 100,000 adults'                                                                  , null], 
    ['s_loans_A1'                   , 'Outstanding loans per 1,000 adults'                                                                            , null], 
    ['s_policyholders_B2_life'      , 'Insurance policy holders per 1,000 adults (life)'                                                              , null], 
    ['s_policyholders_B2_nonlife'   , 'Insurance policy holders per 1,000 adults (non-life)'                                                          , null], 
  ], 
}