export const GenderDisaggregatedLaborDatabaseGdld = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['gtap10VACapital', 'Value-added from Capital in GTAP10P3COD'                                                                  , null], 
    ['gtap10VALabor'  , 'Value-added from labor in GTAP10P3COD (in USD 2014 million)'                                              , null], 
    ['p_F_nsk'        , 'Share of female unskilled worker out of all workers in this sector, %'                                    , null], 
    ['p_F_skl'        , 'Share of female skilled worker out of all workers in this sector, %'                                      , null], 
    ['p_M_nsk'        , 'Share of male unskilled worker out of all workers in this sector, %'                                      , null], 
    ['p_M_skl'        , 'Share of male skilled worker out of all workers in this sector, %'                                        , null], 
    ['v_F_nsk'        , 'Labor volume for unskilled females, millions'                                                             , null], 
    ['v_F_skl'        , 'Labor volume for skilled females, millions'                                                               , null], 
    ['v_M_nsk'        , 'Labor volume for unskilled male, millions'                                                                , null], 
    ['v_M_skl'        , 'Labor volume for skilled males, millions'                                                                 , null], 
    ['w_F_nsk'        , 'Annual wage for unskilled female workers in US$'                                                          , null], 
    ['w_F_skl'        , 'Annual wage for skilled female workers  in US$'                                                           , null], 
    ['w_M_nsk'        , 'Annual wage for unskilled male workers  in US$'                                                           , null], 
    ['w_M_skl'        , 'Annual wage for skilled male workers  in US$'                                                             , null], 
    ['wpremia_F'      , 'Wage Premia for Females (the ratio of skilled female workers\' wage  to  unskilled female workers\' wage)', null], 
    ['wpremia_M'      , 'Wage Premia for Males  (the ratio of skilled male workers\' wage  to  unskilled male workers\' wage)'     , null], 
  ], 
}