export const GlobalFinancialInclusionAndConsumerProtectionSurveyInternal = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['FB.CAP.INST.ST.MS.WB', '661_Does government, industry, or NGOs participate in the multi-stakeholder structure to promote and coordinate financial education?_#VHQC_00'                                       , null], 
    ['FB.CAP.POLI.GL.WP'   , '670_Has the government issued written guidelines directed to all, some, or none of the providers of financial education on content and/or methodology?_#VHUA_00'                     , null], 
    ['FB.CAP.POLI.RE.WP'   , '673_Does the government explicitly require all, some, or none of the financial service providers to offer financial education?_#VHUB_00'                                             , null], 
    ['FB.CAP.POLI.RG.DC.WP', '665_Does the government regularly collect data from all, some, or none of the known providers of financial education on the reach of their programs?_#VHSA_00'                       , null], 
    ['FB.FCP.INST.ES.WH.EN', '314_When was the financial consumer protection (FCP) unit in this country established?_#VGUF_00'                                                                                     , null], 
    ['FB.FCP.INST.NS.HW.MY', '319_How many staff work in the financial consumer protection (FCP) unit in this country?_#VGUG_00'                                                                                   , null], 
    ['FB.FCP.INST.ST.RS.WT', '305_What type of institutional structure for financial consumer protection (FCP) regulation and supervision is implemented in this country?_#VGUC_00'                                , null], 
    ['FB.INC.EMNY.SP.IF.WH', '223_What fraction of customers\' e-money funds is required to be separated from e-money issuer\'s funds and kept at how many prudentially regulated financial institutions?_#VGLA_00', null], 
    ['FB.INC.INST.CB.AU.WR', '195_For commercial banks, is authorization of new or modified financial products explicitly required?_#VGJA_00'                                                                      , null], 
    ['FB.INC.INST.CB.LN.WL', '171_For commercial banks, is all, some, or no lending subject to interest rate caps or pricing limits?_#VGIA_00'                                                                     , null], 
    ['FB.INC.INST.FC.AU.WR', '203_For financial cooperatives, is authorization of new or modified financial products explicitly required?_#VGJA_02'                                                                , null], 
    ['FB.INC.INST.FC.LN.WL', '179_For financial cooperatives, is all, some, or no lending subject to interest rate caps or pricing limits?_#VGIA_02'                                                               , null], 
    ['FB.INC.INST.MC.AU.WR', '211_For microcredit institutions (MCIs), is authorization of new or modified financial products explicitly required?_#VGJA_04'                                                       , null], 
    ['FB.INC.INST.MC.LN.WL', '187_For microcredit institutions (MCIs), is all, some, or no lending subject to interest rate caps or pricing limits?_#VGIA_04'                                                      , null], 
    ['FB.INC.INST.NB.AU.WR', '215_For non-bank e-money issuers (NBEIs), is authorization of new or modified financial products explicitly required?_#VGJA_05'                                                      , null], 
    ['FB.INC.INST.OB.AU.WR', '199_For other banks, is authorization of new or modified financial products explicitly required?_#VGJA_01'                                                                           , null], 
    ['FB.INC.INST.OB.LN.WL', '175_For other banks, is all, some, or no lending subject to interest rate caps or pricing limits?_#VGIA_01'                                                                          , null], 
    ['FB.INC.INST.OD.AU.WR', '207_For other deposit taking institutions (ODTIs), is authorization of new or modified financial products explicitly required?_#VGJA_03'                                             , null], 
    ['FB.INC.INST.OD.LN.WL', '183_For other deposit taking institutions (ODTIs), is all, some, or no lending subject to interest rate caps or pricing limits?_#VGIA_03'                                            , null], 
  ], 
}