export const GlobalPublicProcurement = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['C0.01' , 'Region'                                                                                                , null], 
    ['C0.02' , 'Country ISO3'                                                                                          , null], 
    ['C0.5a' , 'Public comments'                                                                                       , null], 
    ['C0.6a' , 'Resource name'                                                                                         , null], 
    ['C0.6b' , 'Resource URL'                                                                                          , null], 
    ['C1.10' , 'Membership in international organizations'                                                             , null], 
    ['C1.11b', 'World Bank funding page'                                                                               , null], 
    ['C1.12' , 'Gross domestic product (in USD)'                                                                       , null], 
    ['C1.2'  , 'Population'                                                                                            , null], 
    ['C1.4'  , 'Base currency'                                                                                         , null], 
    ['C1.5'  , 'Conversion rate (from local currency to USD)'                                                          , null], 
    ['C1.6'  , 'Income level'                                                                                          , null], 
    ['C1.7'  , 'Gross national income (in USD)'                                                                        , null], 
    ['C1.8'  , 'Gross national income per capita'                                                                      , null], 
    ['C1.9'  , 'Percentage(%) of Gross Domestic Product as Public Procurement Expenditure'                             , null], 
    ['C2.1'  , 'Name of Public Procurement Agency (PPA)'                                                               , null], 
    ['C2.2'  , 'PPA website'                                                                                           , null], 
    ['C2.3'  , 'Is PPA a Central Purchasing Body?'                                                                     , null], 
    ['C2.4a' , 'Number of certified contracting officers (e.g. CIPS)'                                                  , null], 
    ['C2.4b' , 'Contracting officers certification program'                                                            , null], 
    ['C2.5a' , 'Name of Central Purchasing Body (CPB)'                                                                 , null], 
    ['C2.5b' , 'Sectors covered by the CPB'                                                                            , null], 
    ['C2.5c' , 'Name of relevant ministry'                                                                             , null], 
    ['C2.5d' , 'Region covered by the CPB'                                                                             , null], 
    ['C2.5e' , 'CPB website'                                                                                           , null], 
    ['C2.6'  , 'Public procurement law'                                                                                , null], 
    ['C2.7a' , 'Total Cost of Ownership (TCO) law clause'                                                              , null], 
    ['C2.7b' , 'Life Cycle Costing (LLC) law clause'                                                                   , null], 
    ['C2.7c' , 'Value for Money (VfM) law clause'                                                                      , null], 
    ['C2.7d' , 'Most Economically Advantageous Tender (MEAT) law clause'                                               , null], 
    ['C2.7e' , 'Sustainability law clause'                                                                             , null], 
    ['C2.7f' , 'Public Procurement Law requirement for awards to SMEs (Small and Medium-sized Enterprises) clause'     , null], 
    ['C2.7g' , 'Bid Securities and/or bid declaration clause'                                                          , null], 
    ['C2.7h' , 'Public bid openings clause'                                                                            , null], 
    ['C2.7i' , 'Domestic preference clause'                                                                            , null], 
    ['C2.7j' , 'Complaint resolution period clause'                                                                    , null], 
    ['C2.7ka', 'Standstill period for goods contracts regulation clause'                                               , null], 
    ['C2.7kb', 'Standstill period for works contracts regulation clause'                                               , null], 
    ['C2.7kc', 'Standstill period for services contacts regulation clause'                                             , null], 
    ['C2.7la', 'Bid validity period of goods awards regulation clause'                                                 , null], 
    ['C2.7lb', 'Bid validity period of works awards regulation clause'                                                 , null], 
    ['C2.7lc', 'Bid validity period of services awards regulation clause'                                              , null], 
    ['C2.7m' , 'Contract award disclosure threshold clause'                                                            , null], 
    ['C2.7n' , 'Tender threshold value'                                                                                , null], 
    ['C2.7oa', 'Number of days for advertisement of goods awards clause'                                               , null], 
    ['C2.7ob', 'Number of days for advertisement of works awards clause'                                               , null], 
    ['C2.7oc', 'Number of days for advertisement of services awards clause'                                            , null], 
    ['C2.7pa', 'Threshold value for direct contract awards of goods clause'                                            , null], 
    ['C2.7pb', 'Threshold value for direct contract awards of works clause'                                            , null], 
    ['C2.7pc', 'Threshold value for direct contract awards of services clause'                                         , null], 
    ['C3.1a' , 'eProcurement system name'                                                                              , null], 
    ['C3.1b' , 'eProcurement system website'                                                                           , null], 
    ['C3.1c' , 'eProcurement system launch date'                                                                       , null], 
    ['C3.1d' , 'eProcurement functionalities supported'                                                                , null], 
    ['C3.1e' , 'eSignature functionalities'                                                                            , null], 
    ['C3.1fa', 'eProcurement System used by the World Bank'                                                            , null], 
    ['C3.1fb', 'World Bank procurement method used for certification'                                                  , null], 
    ['C3.1g' , 'eProcurement system supported by the World Bank'                                                       , null], 
    ['C3.1h' , 'Supported language(s)'                                                                                 , null], 
    ['C3.1i' , 'Supported currencies'                                                                                  , null], 
    ['C3.1j' , 'Applicable charges'                                                                                    , null], 
    ['C3.1k' , 'eProcurement system custom vs Commercial Off the Shelf (COTS) vs. Open Source'                         , null], 
    ['C3.1l' , 'Business model for eProcurement'                                                                       , null], 
    ['C3.1m' , 'Website where eProcurement data are published as per Open Contracting Data Standard (OCDS) standard'   , null], 
    ['C3.2'  , 'Tender documents are downloadable'                                                                     , null], 
    ['C3.3'  , 'eProcurement assessments'                                                                              , null], 
    ['C3.4a' , 'Percentage of value spent through the use of eProcurement over total value spent'                      , null], 
    ['C3.4b' , 'Percentage of number of transactions through the use of eProcurement over total number of transactions', null], 
    ['C3.5'  , 'Number of professionals certified on eProcurement systems'                                             , null], 
    ['C3.6a' , 'Estimated annual savings value through the use of eProcurement (in USDs)'                              , null], 
    ['C3.6b' , 'Percentage of savings value through the use of eProcurement over total cost estimate'                  , null], 
    ['C3.6c' , 'Methodology used in order to calculate savings value through the use of eProcurement'                  , null], 
    ['C4.1'  , 'Common spend taxonomy used'                                                                            , null], 
    ['C4.10a', 'Average number of bidders per tender for goods contracts'                                              , null], 
    ['C4.10b', 'Average number of bidders per tender for works contracts'                                              , null], 
    ['C4.10c', 'Average number of bidders per tender for services contracts'                                           , null], 
    ['C4.11a', 'Number of accepted/justified complaints'                                                               , null], 
    ['C4.11b', 'Number of rejected/unjustified complaints'                                                             , null], 
    ['C4.11c', 'Number of complaints under investigation'                                                              , null], 
    ['C4.12' , 'Complaint resolution period (include average resolution time in days)'                                 , null], 
    ['C4.13' , 'Number of cancelled procurement procedures'                                                            , null], 
    ['C4.14' , 'Published public procurement annual reports'                                                           , null], 
    ['C4.15' , 'Procurement statistics'                                                                                , null], 
    ['C4.2a' , 'Number of annual tenders'                                                                              , null], 
    ['C4.2b' , 'Value of annual tenders (in USD)'                                                                      , null], 
    ['C4.3a' , 'Number of annual contracts'                                                                            , null], 
    ['C4.3b' , 'Value of annual contracts (in USD)'                                                                    , null], 
    ['C4.4a' , 'Number of contract awards of goods'                                                                    , null], 
    ['C4.4b' , 'Value of contracts awards of goods (in USD)'                                                           , null], 
    ['C4.4c' , 'Number of contract awards of works'                                                                    , null], 
    ['C4.4d' , 'Value of contracts awards of works (in USD)'                                                           , null], 
    ['C4.4e' , 'Number of contract awards of services'                                                                 , null], 
    ['C4.4f' , 'Value of contracts awards of services (in USD)'                                                        , null], 
    ['C4.5a' , 'Number of domestic contract awards'                                                                    , null], 
    ['C4.5b' , 'Value of domestic contract awards (in USD)'                                                            , null], 
    ['C4.5c' , 'Number of international contract awards'                                                               , null], 
    ['C4.5d' , 'Value of international contract awards (in USD)'                                                       , null], 
    ['C4.6a' , 'Number of open contract awards'                                                                        , null], 
    ['C4.6b' , 'Value of open contract awards (in USD)'                                                                , null], 
    ['C4.6c' , 'Number of direct contract awards'                                                                      , null], 
    ['C4.6d' , 'Value of direct contract awards (in USD)'                                                              , null], 
    ['C4.7a' , 'Number of awards to SMEs'                                                                              , null], 
    ['C4.7b' , 'Value of awards to SMEs (in USD)'                                                                      , null], 
    ['C4.8a' , 'Number of contract awards under framework agreements'                                                  , null], 
    ['C4.8b' , 'Value of contract awards under framework agreements (in USD)'                                          , null], 
    ['C4.9a' , 'Number of contract awards evaluated based on MEAT'                                                     , null], 
    ['C4.9b' , 'Value of contract awards evaluated based on MEAT (in USD)'                                             , null], 
    ['C4.9c' , 'Number of contract awards evaluated based on Lowest Price method'                                      , null], 
    ['C4.9d' , 'Value of contract awards evaluated based on Lowest Price method (in USD)'                              , null], 
    ['C5.1'  , 'Number of days from advertisement to contract award'                                                   , null], 
    ['C5.2'  , 'Average time for bid evaluation'                                                                       , null], 
  ], 
}