export const GlobalFinancialDevelopment = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['GFDD.AI.01'    , 'Bank accounts per 1,000 adults'                                                                               , ['Fin']              ], 
    ['GFDD.AI.02'    , 'Bank branches per 100,000 adults '                                                                            , ['Fin']              ], 
    ['GFDD.AI.03'    , 'Firms with a bank loan or line of credit (%)'                                                                 , ['Fin']              ], 
    ['GFDD.AI.04'    , 'Small firms with a bank loan or line of credit (%)'                                                           , ['Fin']              ], 
    ['GFDD.AI.05'    , 'Account at a formal financial institution (% age 15+)'                                                        , ['Fin']              ], 
    ['GFDD.AI.06'    , 'Saved at a financial institution in the past year (% age 15+)'                                                , ['Fin']              ], 
    ['GFDD.AI.07'    , 'Loan from a financial institution in the past year (% age 15+)'                                               , ['Fin']              ], 
    ['GFDD.AI.08'    , 'Account used for business purposes (% age 15+)'                                                               , ['Fin']              ], 
    ['GFDD.AI.09'    , 'Account used to receive government payments (% age 15+)'                                                      , ['Fin']              ], 
    ['GFDD.AI.10'    , 'Account used to receive remittances (% age 15+)'                                                              , ['Fin']              ], 
    ['GFDD.AI.11'    , 'Account used to receive wages (% age 15+)'                                                                    , ['Fin']              ], 
    ['GFDD.AI.12'    , 'Saved any money in the past year (% age 15+)'                                                                 , ['Fin']              ], 
    ['GFDD.AI.13'    , 'Saved using a savings club in the past year (% age 15+)'                                                      , ['Fin']              ], 
    ['GFDD.AI.14'    , 'Loan in the past year (% age 15+)'                                                                            , ['Fin']              ], 
    ['GFDD.AI.15'    , 'Loan from a private lender in the past year (% age 15+)'                                                      , ['Fin']              ], 
    ['GFDD.AI.16'    , 'Loan from an employer in the past year (% age 15+)'                                                           , ['Fin']              ], 
    ['GFDD.AI.17'    , 'Loan through store credit in the past year (% age 15+)'                                                       , ['Fin']              ], 
    ['GFDD.AI.18'    , 'Loan from family or friends in the past year (% age 15+)'                                                     , ['Fin']              ], 
    ['GFDD.AI.19'    , 'Checks used to make payments (% age 15+)'                                                                     , ['Fin']              ], 
    ['GFDD.AI.20'    , 'Credit card (% age 15+)'                                                                                      , ['Fin']              ], 
    ['GFDD.AI.21'    , 'Debit card (% age 15+)'                                                                                       , ['Fin']              ], 
    ['GFDD.AI.22'    , 'Electronic payments used to make payments (% age 15+)'                                                        , ['Fin']              ], 
    ['GFDD.AI.23'    , 'Mobile phone used to pay bills (% age 15+)'                                                                   , ['Fin']              ], 
    ['GFDD.AI.24'    , 'Mobile phone used to send money (% age 15+)'                                                                  , ['Fin']              ], 
    ['GFDD.AI.25'    , 'ATMs per 100,000 adults'                                                                                      , ['Fin']              ], 
    ['GFDD.AI.26'    , 'Depositing/withdrawing at least once in a typical month (% age 15+)'                                          , ['Fin']              ], 
    ['GFDD.AI.27'    , 'Firms with a checking or savings account (%)'                                                                 , ['Fin']              ], 
    ['GFDD.AI.28'    , 'Firms using banks to finance investments (%)'                                                                 , ['Fin']              ], 
    ['GFDD.AI.29'    , 'Firms using banks to finance working capital (%)'                                                             , ['Fin']              ], 
    ['GFDD.AI.30'    , 'Loans requiring collateral (%)'                                                                               , ['Fin']              ], 
    ['GFDD.AI.31'    , 'Value of collateral needed for a loan (% of the loan amount)'                                                 , ['Fin']              ], 
    ['GFDD.AI.32'    , 'Firms not needing a loan (%)'                                                                                 , ['Fin']              ], 
    ['GFDD.AI.33'    , 'Firms whose recent loan application was rejected (%)'                                                         , ['Fin']              ], 
    ['GFDD.AI.34'    , 'Investments financed by banks (%)'                                                                            , ['Fin']              ], 
    ['GFDD.AI.35'    , 'Working capital financed by banks (%)'                                                                        , ['Fin']              ], 
    ['GFDD.AI.36'    , 'Firms identifying access to finance as a major constraint (%)'                                                , ['Fin']              ], 
    ['GFDD.AM.01'    , 'Value traded excluding top 10 traded companies to total value traded (%)'                                     , ['Fin']              ], 
    ['GFDD.AM.02'    , 'Market capitalization excluding top 10 companies to total market capitalization (%)'                          , ['Fin']              ], 
    ['GFDD.AM.03'    , 'Nonfinancial corporate bonds to total bonds and notes outstanding (%)'                                        , ['Fin']              ], 
    ['GFDD.AM.04'    , 'Investments financed by equity or stock sales (%)'                                                            , ['Fin']              ], 
    ['GFDD.DI.01'    , 'Private credit by deposit money banks to GDP (%)'                                                             , ['Fin']              ], 
    ['GFDD.DI.02'    , 'Deposit money banks\'\' assets to GDP (%)'                                                                    , ['Fin']              ], 
    ['GFDD.DI.03'    , 'Nonbank financial institutions’ assets to GDP (%)'                                                            , ['Fin']              ], 
    ['GFDD.DI.04'    , 'Deposit money bank assets to deposit money bank assets and central bank assets (%)'                           , ['Fin']              ], 
    ['GFDD.DI.05'    , 'Liquid liabilities to GDP (%)'                                                                                , ['Fin']              ], 
    ['GFDD.DI.06'    , 'Central bank assets to GDP (%)'                                                                               , ['Fin']              ], 
    ['GFDD.DI.07'    , 'Mutual fund assets to GDP (%)'                                                                                , ['Fin']              ], 
    ['GFDD.DI.08'    , 'Financial system deposits to GDP (%)'                                                                         , ['Fin']              ], 
    ['GFDD.DI.09'    , 'Life insurance premium volume to GDP (%)'                                                                     , ['Fin']              ], 
    ['GFDD.DI.10'    , 'Non-life insurance premium volume to GDP (%)'                                                                 , ['Fin']              ], 
    ['GFDD.DI.11'    , 'Insurance company assets to GDP (%)'                                                                          , ['Fin']              ], 
    ['GFDD.DI.12'    , 'Private credit by deposit money banks and other financial institutions to GDP (%)'                            , ['Fin']              ], 
    ['GFDD.DI.13'    , 'Pension fund assets to GDP (%)'                                                                               , ['Fin']              ], 
    ['GFDD.DI.14'    , 'Domestic credit to private sector (% of GDP)'                                                                 , ['Fin']              ], 
    ['GFDD.DM.01'    , 'Stock market capitalization to GDP (%)'                                                                       , ['Fin']              ], 
    ['GFDD.DM.02'    , 'Stock market total value traded to GDP (%)'                                                                   , ['Fin']              ], 
    ['GFDD.DM.03'    , 'Outstanding domestic private debt securities to GDP (%)'                                                      , ['Fin']              ], 
    ['GFDD.DM.04'    , 'Outstanding domestic public debt securities to GDP (%)'                                                       , ['Fin']              ], 
    ['GFDD.DM.05'    , 'Outstanding international private debt securities to GDP (%)'                                                 , ['Fin']              ], 
    ['GFDD.DM.06'    , 'Outstanding international public debt securities to GDP (%)'                                                  , ['Fin']              ], 
    ['GFDD.DM.07'    , 'International debt issues to GDP (%)'                                                                         , ['Fin']              ], 
    ['GFDD.DM.08'    , 'Gross portfolio equity liabilities to GDP (%)'                                                                , ['Fin']              ], 
    ['GFDD.DM.09'    , 'Gross portfolio equity assets to GDP (%)'                                                                     , ['Fin']              ], 
    ['GFDD.DM.10'    , 'Gross portfolio debt liabilities to GDP (%)'                                                                  , ['Fin']              ], 
    ['GFDD.DM.11'    , 'Gross portfolio debt assets to GDP (%)'                                                                       , null                 ], 
    ['GFDD.DM.12'    , 'Syndicated loan issuance volume to GDP (%)'                                                                   , null                 ], 
    ['GFDD.DM.13'    , 'Corporate bond issuance volume to GDP (%)'                                                                    , null                 ], 
    ['GFDD.DM.14'    , 'Syndicated loan average maturity (years)'                                                                     , null                 ], 
    ['GFDD.DM.15'    , 'Corporate bond average maturity (years)'                                                                      , null                 ], 
    ['GFDD.EI.01'    , 'Bank net interest margin (%)'                                                                                 , ['Fin']              ], 
    ['GFDD.EI.02'    , 'Bank lending-deposit spread'                                                                                  , ['Fin']              ], 
    ['GFDD.EI.03'    , 'Bank noninterest income to total income (%)'                                                                  , ['Fin']              ], 
    ['GFDD.EI.04'    , 'Bank overhead costs to total assets (%)'                                                                      , ['Fin']              ], 
    ['GFDD.EI.05'    , 'Bank return on assets (%, after tax)'                                                                         , ['Fin']              ], 
    ['GFDD.EI.06'    , 'Bank return on equity (%, after tax)'                                                                         , ['Fin']              ], 
    ['GFDD.EI.07'    , 'Bank cost to income ratio (%)'                                                                                , ['Fin']              ], 
    ['GFDD.EI.08'    , 'Credit to government and state-owned enterprises to GDP (%)'                                                  , ['Fin']              ], 
    ['GFDD.EI.09'    , 'Bank return on assets (%, before tax)'                                                                        , ['Fin']              ], 
    ['GFDD.EI.10'    , 'Bank return on equity (%, before tax)'                                                                        , ['Fin']              ], 
    ['GFDD.EM.01'    , 'Stock market turnover ratio (%)'                                                                              , ['Fin']              ], 
    ['GFDD.OE.01'    , 'Consumer price index (2010=100, December)'                                                                    , null                 ], 
    ['GFDD.OE.02'    , 'Consumer price index (2010=100, average)'                                                                     , null                 ], 
    ['GFDD.OI.01'    , 'Bank concentration (%)'                                                                                       , ['Fin']              ], 
    ['GFDD.OI.02'    , 'Bank deposits to GDP (%)'                                                                                     , ['Fin']              ], 
    ['GFDD.OI.03'    , 'H-statistic'                                                                                                  , ['Fin']              ], 
    ['GFDD.OI.04'    , 'Lerner index'                                                                                                 , ['Fin']              ], 
    ['GFDD.OI.05'    , 'Boone indicator'                                                                                              , ['Fin']              ], 
    ['GFDD.OI.06'    , '5-bank asset concentration'                                                                                   , ['Fin']              ], 
    ['GFDD.OI.07'    , 'Liquid liabilities in millions USD (2000 constant)'                                                           , ['Fin']              ], 
    ['GFDD.OI.08'    , 'Loans from nonresident banks (net) to GDP (%)'                                                                , ['Fin']              ], 
    ['GFDD.OI.09'    , 'Loans from nonresident banks (amounts outstanding) to GDP (%)'                                                , ['Fin']              ], 
    ['GFDD.OI.10'    , 'External loans and deposits of reporting banks vis-à-vis the banking sector (% of domestic bank deposits)'    , ['Fin']              ], 
    ['GFDD.OI.11'    , 'External loans and deposits of reporting banks vis-à-vis the nonbanking sectors (% of domestic bank deposits)', ['Fin']              ], 
    ['GFDD.OI.12'    , 'External loans and deposits of reporting banks vis-à-vis all sectors (% of domestic bank deposits)'           , ['Fin']              ], 
    ['GFDD.OI.13'    , 'Remittance inflows to GDP (%)'                                                                                , ['Fin']              ], 
    ['GFDD.OI.14'    , 'Consolidated foreign claims of BIS reporting banks to GDP (%)'                                                , ['Fin']              ], 
    ['GFDD.OI.15'    , 'Foreign banks among total banks (%)'                                                                          , ['Fin']              ], 
    ['GFDD.OI.16'    , 'Foreign bank assets among total bank assets (%)'                                                              , ['Fin']              ], 
    ['GFDD.OI.17'    , 'Global leasing volume to GDP (%)'                                                                             , ['Fin']              ], 
    ['GFDD.OI.18'    , 'Total factoring volume to GDP (%)'                                                                            , ['Fin']              ], 
    ['GFDD.OI.19'    , 'Banking crisis dummy (1=banking crisis, 0=none)'                                                              , ['Fin']              ], 
    ['GFDD.OM.01'    , 'Number of listed companies per 1,000,000 people '                                                             , ['Fin']              ], 
    ['GFDD.OM.02'    , 'Stock market return (%, year-on-year)'                                                                        , ['Fin']              ], 
    ['GFDD.SI.01'    , 'Bank Z-score'                                                                                                 , ['Fin']              ], 
    ['GFDD.SI.02'    , 'Bank non-performing loans to gross loans (%)'                                                                 , ['Fin']              ], 
    ['GFDD.SI.03'    , 'Bank capital to total assets (%)'                                                                             , ['Fin']              ], 
    ['GFDD.SI.04'    , 'Bank credit to bank deposits (%)'                                                                             , ['Fin']              ], 
    ['GFDD.SI.05'    , 'Bank regulatory capital to risk-weighted assets (%) '                                                         , ['Fin']              ], 
    ['GFDD.SI.06'    , 'Liquid assets to deposits and short term funding (%)'                                                         , ['Fin']              ], 
    ['GFDD.SI.07'    , 'Provisions to nonperforming loans (%)'                                                                        , ['Fin']              ], 
    ['GFDD.SM.01'    , 'Stock price volatility'                                                                                       , ['Fin']              ], 
    ['NY.GDP.MKTP.CD', 'GDP (current US$)'                                                                                            , ['Econ']             ], 
    ['NY.GDP.MKTP.KD', 'GDP (constant 2010 US$)'                                                                                      , ['Econ']             ], 
    ['NY.GDP.PCAP.CD', 'GDP per capita (current US$)'                                                                                 , ['Econ']             ], 
    ['NY.GDP.PCAP.KD', 'GDP per capita (constant 2010 US$)'                                                                           , ['Econ']             ], 
    ['NY.GNP.MKTP.CD', 'GNI (current US$)'                                                                                            , ['Econ', 'Debt']     ], 
    ['SP.POP.TOTL'   , 'Population, total'                                                                                            , ['Climate', 'Health']], 
  ], 
}