export const GlobalEconomicMonitor = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['CORENS'       , 'Core CPI,not seas.adj,,,'                                        , null], 
    ['CORESA'       , 'Core CPI,seas.adj,,,'                                            , null], 
    ['CPTOTNSXN'    , 'CPI Price, nominal'                                              , null], 
    ['CPTOTSAXMZGY' , 'CPI Price, % y-o-y, median weighted, seas. adj.'                 , null], 
    ['CPTOTSAXN'    , 'CPI Price, nominal, seas. adj.'                                  , null], 
    ['CPTOTSAXNZGY' , 'CPI Price, % y-o-y, nominal, seas. adj.'                         , null], 
    ['DMGSRMRCHNSCD', 'Imports Merchandise, Customs, current US$, millions'             , null], 
    ['DMGSRMRCHNSKD', 'Imports Merchandise, Customs, constant US$, millions'            , null], 
    ['DMGSRMRCHNSXD', 'Imports Merchandise, Customs, Price, US$'                        , null], 
    ['DMGSRMRCHSACD', 'Imports Merchandise, Customs, current US$, millions, seas. adj.' , null], 
    ['DMGSRMRCHSAKD', 'Imports Merchandise, Customs, constant US$, millions, seas. adj.', null], 
    ['DMGSRMRCHSAXD', 'Imports Merchandise, Customs, Price, US$, seas. adj.'            , null], 
    ['DPANUSLCU'    , 'Official exchange rate, LCU per USD, period average'             , null], 
    ['DPANUSSPB'    , 'Exchange rate, new LCU per USD extended backward, period average', null], 
    ['DPANUSSPF'    , 'Exchange rate, old LCU per USD extended forward, period average' , null], 
    ['DSTKMKTXD'    , 'Stock Markets, US$'                                              , null], 
    ['DSTKMKTXN'    , 'Stock Markets, LCU'                                              , null], 
    ['DXGSRMRCHNSCD', 'Exports Merchandise, Customs, current US$, millions'             , null], 
    ['DXGSRMRCHNSKD', 'Exports Merchandise, Customs, constant US$, millions'            , null], 
    ['DXGSRMRCHNSXD', 'Exports Merchandise, Customs, Price, US$'                        , null], 
    ['DXGSRMRCHSACD', 'Exports Merchandise, Customs, current US$, millions, seas. adj.' , null], 
    ['DXGSRMRCHSAKD', 'Exports Merchandise, Customs, constant US$, millions, seas. adj.', null], 
    ['DXGSRMRCHSAXD', 'Exports Merchandise, Customs, Price, US$, seas. adj.'            , null], 
    ['EMBIG'        , 'J.P. Morgan Emerging Markets Bond Spread (EMBI+),,,,'            , null], 
    ['EMBIGI'       , 'J.P. Morgan Emerging Markets Bond Index(EMBI+),,,,'              , null], 
    ['IMPCOV'       , 'Foreign Reserves, Months Import Cover, Goods'                    , null], 
    ['IPTOTNSKD'    , 'Industrial Production, constant US$'                             , null], 
    ['IPTOTSAKD'    , 'Industrial Production, constant US$, seas. adj.'                 , null], 
    ['NEER'         , 'Nominal Effecive Exchange Rate'                                  , null], 
    ['NYGDPMKTPSACD', 'GDP,current US$,millions,seas. adj.,'                            , null], 
    ['NYGDPMKTPSACN', 'GDP,current LCU,millions,seas. adj.,'                            , null], 
    ['NYGDPMKTPSAKD', 'GDP,constant 2010 US$,millions,seas. adj.,'                      , null], 
    ['NYGDPMKTPSAKN', 'GDP,constant 2010 LCU,millions,seas. adj.,'                      , null], 
    ['REER'         , 'Real Effective Exchange Rate'                                    , null], 
    ['RETSALESSA'   , 'Retail Sales Volume,Index,,,'                                    , null], 
    ['TOT'          , 'Terms of Trade'                                                  , null], 
    ['TOTRESV'      , 'Total Reserves'                                                  , null], 
    ['UNEMPSA_'     , 'Unemployment rate,Percent,,,'                                    , null], 
  ], 
}