export const HealthNutritionAndPopulationStatisticsByWealthQuintile = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['SH.ACS.ALON.Q1.ZS'   , 'Problems in accessing health care (not wanting to go alone) (% of women): Q1 (lowest)'                                 , ['Health']    ], 
    ['SH.ACS.ALON.Q2.ZS'   , 'Problems in accessing health care (not wanting to go alone) (% of women): Q2'                                          , ['Health']    ], 
    ['SH.ACS.ALON.Q3.ZS'   , 'Problems in accessing health care (not wanting to go alone) (% of women): Q3'                                          , ['Health']    ], 
    ['SH.ACS.ALON.Q4.ZS'   , 'Problems in accessing health care (not wanting to go alone) (% of women): Q4'                                          , ['Health']    ], 
    ['SH.ACS.ALON.Q5.ZS'   , 'Problems in accessing health care (not wanting to go alone) (% of women): Q5 (highest)'                                , ['Health']    ], 
    ['SH.ACS.DIST.Q1.ZS'   , 'Problems in accessing health care (distance to health facility) (% of women): Q1 (lowest)'                             , ['Health']    ], 
    ['SH.ACS.DIST.Q2.ZS'   , 'Problems in accessing health care (distance to health facility) (% of women): Q2'                                      , ['Health']    ], 
    ['SH.ACS.DIST.Q3.ZS'   , 'Problems in accessing health care (distance to health facility) (% of women): Q3'                                      , ['Health']    ], 
    ['SH.ACS.DIST.Q4.ZS'   , 'Problems in accessing health care (distance to health facility) (% of women): Q4'                                      , ['Health']    ], 
    ['SH.ACS.DIST.Q5.ZS'   , 'Problems in accessing health care (distance to health facility) (% of women): Q5 (highest)'                            , ['Health']    ], 
    ['SH.ACS.MONY.Q1.ZS'   , 'Problems in accessing health care (getting money for treatment) (% of women): Q1 (lowest)'                             , ['Health']    ], 
    ['SH.ACS.MONY.Q2.ZS'   , 'Problems in accessing health care (getting money for treatment) (% of women): Q2'                                      , ['Health']    ], 
    ['SH.ACS.MONY.Q3.ZS'   , 'Problems in accessing health care (getting money for treatment) (% of women): Q3'                                      , ['Health']    ], 
    ['SH.ACS.MONY.Q4.ZS'   , 'Problems in accessing health care (getting money for treatment) (% of women): Q4'                                      , ['Health']    ], 
    ['SH.ACS.MONY.Q5.ZS'   , 'Problems in accessing health care (getting money for treatment) (% of women): Q5 (highest)'                            , ['Health']    ], 
    ['SH.ACS.NOFP.Q1.ZS'   , 'Problems in accessing health care (concern there may not be a female provider) (% of women): Q1 (lowest)'              , ['Health']    ], 
    ['SH.ACS.NOFP.Q2.ZS'   , 'Problems in accessing health care (concern there may not be a female provider) (% of women): Q2'                       , ['Health']    ], 
    ['SH.ACS.NOFP.Q3.ZS'   , 'Problems in accessing health care (concern there may not be a female provider) (% of women): Q3'                       , ['Health']    ], 
    ['SH.ACS.NOFP.Q4.ZS'   , 'Problems in accessing health care (concern there may not be a female provider) (% of women): Q4'                       , ['Health']    ], 
    ['SH.ACS.NOFP.Q5.ZS'   , 'Problems in accessing health care (concern there may not be a female provider) (% of women): Q5 (highest)'             , ['Health']    ], 
    ['SH.ACS.PERM.Q1.ZS'   , 'Problems in accessing health care (getting permission to go for treatment) (% of women): Q1 (lowest)'                  , ['Health']    ], 
    ['SH.ACS.PERM.Q2.ZS'   , 'Problems in accessing health care (getting permission to go for treatment) (% of women): Q2'                           , ['Health']    ], 
    ['SH.ACS.PERM.Q3.ZS'   , 'Problems in accessing health care (getting permission to go for treatment) (% of women): Q3'                           , ['Health']    ], 
    ['SH.ACS.PERM.Q4.ZS'   , 'Problems in accessing health care (getting permission to go for treatment) (% of women): Q4'                           , ['Health']    ], 
    ['SH.ACS.PERM.Q5.ZS'   , 'Problems in accessing health care (getting permission to go for treatment) (% of women): Q5 (highest)'                 , ['Health']    ], 
    ['SH.ACS.PROB.Q1.ZS'   , 'Problems in accessing health care (any of the specified problems) (% of women): Q1 (lowest)'                           , ['Health']    ], 
    ['SH.ACS.PROB.Q2.ZS'   , 'Problems in accessing health care (any of the specified problems) (% of women): Q2'                                    , ['Health']    ], 
    ['SH.ACS.PROB.Q3.ZS'   , 'Problems in accessing health care (any of the specified problems) (% of women): Q3'                                    , ['Health']    ], 
    ['SH.ACS.PROB.Q4.ZS'   , 'Problems in accessing health care (any of the specified problems) (% of women): Q4'                                    , ['Health']    ], 
    ['SH.ACS.PROB.Q5.ZS'   , 'Problems in accessing health care (any of the specified problems) (% of women): Q5 (highest)'                          , ['Health']    ], 
    ['SH.ACS.TRAN.Q1.ZS'   , 'Problems in accessing health care (having to take transport) (% of women): Q1 (lowest)'                                , ['Health']    ], 
    ['SH.ACS.TRAN.Q2.ZS'   , 'Problems in accessing health care (having to take transport) (% of women): Q2'                                         , ['Health']    ], 
    ['SH.ACS.TRAN.Q3.ZS'   , 'Problems in accessing health care (having to take transport) (% of women): Q3'                                         , ['Health']    ], 
    ['SH.ACS.TRAN.Q4.ZS'   , 'Problems in accessing health care (having to take transport) (% of women): Q4'                                         , ['Health']    ], 
    ['SH.ACS.TRAN.Q5.ZS'   , 'Problems in accessing health care (having to take transport) (% of women): Q5 (highest)'                               , ['Health']    ], 
    ['SH.ACS.WHER.Q1.ZS'   , 'Problems in accessing health care (knowing where to go for treatment) (% of women): Q1 (lowest)'                       , ['Health']    ], 
    ['SH.ACS.WHER.Q2.ZS'   , 'Problems in accessing health care (knowing where to go for treatment) (% of women): Q2'                                , ['Health']    ], 
    ['SH.ACS.WHER.Q3.ZS'   , 'Problems in accessing health care (knowing where to go for treatment) (% of women): Q3'                                , ['Health']    ], 
    ['SH.ACS.WHER.Q4.ZS'   , 'Problems in accessing health care (knowing where to go for treatment) (% of women): Q4'                                , ['Health']    ], 
    ['SH.ACS.WHER.Q5.ZS'   , 'Problems in accessing health care (knowing where to go for treatment) (% of women): Q5 (highest)'                      , ['Health']    ], 
    ['SH.DYN.MORT.Q1'      , 'Under-5 mortality rate (per 1,000 live births): Q1 (lowest)'                                                           , ['Health']    ], 
    ['SH.DYN.MORT.Q2'      , 'Under-5 mortality rate (per 1,000 live births): Q2'                                                                    , ['Health']    ], 
    ['SH.DYN.MORT.Q3'      , 'Under-5 mortality rate (per 1,000 live births): Q3'                                                                    , ['Health']    ], 
    ['SH.DYN.MORT.Q4'      , 'Under-5 mortality rate (per 1,000 live births): Q4'                                                                    , ['Health']    ], 
    ['SH.DYN.MORT.Q5'      , 'Under-5 mortality rate (per 1,000 live births): Q5 (highest)'                                                          , ['Health']    ], 
    ['SH.FPL.ACPT.Q1.ZS'   , 'Acceptability of media messages on family planning (% of women): Q1 (lowest)'                                          , ['Health']    ], 
    ['SH.FPL.ACPT.Q2.ZS'   , 'Acceptability of media messages on family planning (% of women): Q2'                                                   , ['Health']    ], 
    ['SH.FPL.ACPT.Q3.ZS'   , 'Acceptability of media messages on family planning (% of women): Q3'                                                   , ['Health']    ], 
    ['SH.FPL.ACPT.Q4.ZS'   , 'Acceptability of media messages on family planning (% of women): Q4'                                                   , ['Health']    ], 
    ['SH.FPL.ACPT.Q5.ZS'   , 'Acceptability of media messages on family planning (% of women): Q5 (highest)'                                         , ['Health']    ], 
    ['SH.FPL.FBRT.Q1.ZS'   , 'Median age at first birth (women ages 25-49): Q1 (lowest)'                                                             , ['Health']    ], 
    ['SH.FPL.FBRT.Q2.ZS'   , 'Median age at first birth (women ages 25-49): Q2'                                                                      , ['Health']    ], 
    ['SH.FPL.FBRT.Q3.ZS'   , 'Median age at first birth (women ages 25-49): Q3'                                                                      , ['Health']    ], 
    ['SH.FPL.FBRT.Q4.ZS'   , 'Median age at first birth (women ages 25-49): Q4'                                                                      , ['Health']    ], 
    ['SH.FPL.FBRT.Q5.ZS'   , 'Median age at first birth (women ages 25-49): Q5 (highest)'                                                            , ['Health']    ], 
    ['SH.FPL.FMAR.Q1.ZS'   , 'Median age at first marriage (women ages 25-49): Q1 (lowest)'                                                          , ['Health']    ], 
    ['SH.FPL.FMAR.Q2.ZS'   , 'Median age at first marriage (women ages 25-49): Q2'                                                                   , ['Health']    ], 
    ['SH.FPL.FMAR.Q3.ZS'   , 'Median age at first marriage (women ages 25-49): Q3'                                                                   , ['Health']    ], 
    ['SH.FPL.FMAR.Q4.ZS'   , 'Median age at first marriage (women ages 25-49): Q4'                                                                   , ['Health']    ], 
    ['SH.FPL.FMAR.Q5.ZS'   , 'Median age at first marriage (women ages 25-49): Q5 (highest)'                                                         , ['Health']    ], 
    ['SH.FPL.FSEX.Q1.ZS'   , 'Median age at first sexual intercourse (women ages 25-49): Q1 (lowest)'                                                , ['Health']    ], 
    ['SH.FPL.FSEX.Q2.ZS'   , 'Median age at first sexual intercourse (women ages 25-49): Q2'                                                         , ['Health']    ], 
    ['SH.FPL.FSEX.Q3.ZS'   , 'Median age at first sexual intercourse (women ages 25-49): Q3'                                                         , ['Health']    ], 
    ['SH.FPL.FSEX.Q4.ZS'   , 'Median age at first sexual intercourse (women ages 25-49): Q4'                                                         , ['Health']    ], 
    ['SH.FPL.FSEX.Q5.ZS'   , 'Median age at first sexual intercourse (women ages 25-49): Q5 (highest)'                                               , ['Health']    ], 
    ['SH.FPL.HEAR.Q1.ZS'   , 'Heard family planning on radio and television (% of women): Q1 (lowest)'                                               , ['Health']    ], 
    ['SH.FPL.HEAR.Q2.ZS'   , 'Heard family planning on radio and television (% of women): Q2'                                                        , ['Health']    ], 
    ['SH.FPL.HEAR.Q3.ZS'   , 'Heard family planning on radio and television (% of women): Q3'                                                        , ['Health']    ], 
    ['SH.FPL.HEAR.Q4.ZS'   , 'Heard family planning on radio and television (% of women): Q4'                                                        , ['Health']    ], 
    ['SH.FPL.HEAR.Q5.ZS'   , 'Heard family planning on radio and television (% of women): Q5 (highest)'                                              , ['Health']    ], 
    ['SH.FPL.IDLC.Q1'      , 'Mean ideal number of children (per woman): Q1 (lowest)'                                                                , ['Health']    ], 
    ['SH.FPL.IDLC.Q2'      , 'Mean ideal number of children (per woman): Q2'                                                                         , ['Health']    ], 
    ['SH.FPL.IDLC.Q3'      , 'Mean ideal number of children (per woman): Q3'                                                                         , ['Health']    ], 
    ['SH.FPL.IDLC.Q4'      , 'Mean ideal number of children (per woman): Q4'                                                                         , ['Health']    ], 
    ['SH.FPL.IDLC.Q5'      , 'Mean ideal number of children (per woman): Q5 (highest)'                                                               , ['Health']    ], 
    ['SH.FPL.KNOW.Q1.ZS'   , 'Knowledge of contraception (any method) (% of married women): Q1 (lowest)'                                             , ['Health']    ], 
    ['SH.FPL.KNOW.Q2.ZS'   , 'Knowledge of contraception (any method) (% of married women): Q2'                                                      , ['Health']    ], 
    ['SH.FPL.KNOW.Q3.ZS'   , 'Knowledge of contraception (any method) (% of married women): Q3'                                                      , ['Health']    ], 
    ['SH.FPL.KNOW.Q4.ZS'   , 'Knowledge of contraception (any method) (% of married women): Q4'                                                      , ['Health']    ], 
    ['SH.FPL.KNOW.Q5.ZS'   , 'Knowledge of contraception (any method) (% of married women): Q5 (highest)'                                            , ['Health']    ], 
    ['SH.FPL.KWMD.Q1.ZS'   , 'Knowledge of contraception (modern method) (% of married women): Q1 (lowest)'                                          , ['Health']    ], 
    ['SH.FPL.KWMD.Q2.ZS'   , 'Knowledge of contraception (modern method) (% of married women): Q2'                                                   , ['Health']    ], 
    ['SH.FPL.KWMD.Q3.ZS'   , 'Knowledge of contraception (modern method) (% of married women): Q3'                                                   , ['Health']    ], 
    ['SH.FPL.KWMD.Q4.ZS'   , 'Knowledge of contraception (modern method) (% of married women): Q4'                                                   , ['Health']    ], 
    ['SH.FPL.KWMD.Q5.ZS'   , 'Knowledge of contraception (modern method) (% of married women): Q5 (highest)'                                         , ['Health']    ], 
    ['SH.FPL.LIMT.Q1.ZS'   , 'Desire to stop (limit) childbearing (% of married women): Q1 (lowest)'                                                 , ['Health']    ], 
    ['SH.FPL.LIMT.Q2.ZS'   , 'Desire to stop (limit) childbearing (% of married women): Q2'                                                          , ['Health']    ], 
    ['SH.FPL.LIMT.Q3.ZS'   , 'Desire to stop (limit) childbearing (% of married women): Q3'                                                          , ['Health']    ], 
    ['SH.FPL.LIMT.Q4.ZS'   , 'Desire to stop (limit) childbearing (% of married women): Q4'                                                          , ['Health']    ], 
    ['SH.FPL.LIMT.Q5.ZS'   , 'Desire to stop (limit) childbearing (% of married women): Q5 (highest)'                                                , ['Health']    ], 
    ['SH.FPL.MBRI.Q1'      , 'Median birth interval (months): Q1 (lowest)'                                                                           , ['Health']    ], 
    ['SH.FPL.MBRI.Q2'      , 'Median birth interval (months): Q2'                                                                                    , ['Health']    ], 
    ['SH.FPL.MBRI.Q3'      , 'Median birth interval (months): Q3'                                                                                    , ['Health']    ], 
    ['SH.FPL.MBRI.Q4'      , 'Median birth interval (months): Q4'                                                                                    , ['Health']    ], 
    ['SH.FPL.MBRI.Q5'      , 'Median birth interval (months): Q5 (highest)'                                                                          , ['Health']    ], 
    ['SH.FPL.MSTM.Q1.ZS'   , 'Fertility planning status (wanted later) (% of births): Q1 (lowest)'                                                   , ['Health']    ], 
    ['SH.FPL.MSTM.Q2.ZS'   , 'Fertility planning status (wanted later) (% of births): Q2'                                                            , ['Health']    ], 
    ['SH.FPL.MSTM.Q3.ZS'   , 'Fertility planning status (wanted later) (% of births): Q3'                                                            , ['Health']    ], 
    ['SH.FPL.MSTM.Q4.ZS'   , 'Fertility planning status (wanted later) (% of births): Q4'                                                            , ['Health']    ], 
    ['SH.FPL.MSTM.Q5.ZS'   , 'Fertility planning status (wanted later) (% of births): Q5 (highest)'                                                  , ['Health']    ], 
    ['SH.FPL.READ.Q1.ZS'   , 'Family planning messages in print (% of women): Q1 (lowest)'                                                           , ['Health']    ], 
    ['SH.FPL.READ.Q2.ZS'   , 'Family planning messages in print (% of women): Q2'                                                                    , ['Health']    ], 
    ['SH.FPL.READ.Q3.ZS'   , 'Family planning messages in print (% of women): Q3'                                                                    , ['Health']    ], 
    ['SH.FPL.READ.Q4.ZS'   , 'Family planning messages in print (% of women): Q4'                                                                    , ['Health']    ], 
    ['SH.FPL.READ.Q5.ZS'   , 'Family planning messages in print (% of women): Q5 (highest)'                                                          , ['Health']    ], 
    ['SH.FPL.UWTD.Q1.ZS'   , 'Fertility planning status (wanted no more) (% of births): Q1 (lowest)'                                                 , ['Health']    ], 
    ['SH.FPL.UWTD.Q2.ZS'   , 'Fertility planning status (wanted no more) (% of births): Q2'                                                          , ['Health']    ], 
    ['SH.FPL.UWTD.Q3.ZS'   , 'Fertility planning status (wanted no more) (% of births): Q3'                                                          , ['Health']    ], 
    ['SH.FPL.UWTD.Q4.ZS'   , 'Fertility planning status (wanted no more) (% of births): Q4'                                                          , ['Health']    ], 
    ['SH.FPL.UWTD.Q5.ZS'   , 'Fertility planning status (wanted no more) (% of births): Q5 (highest)'                                                , ['Health']    ], 
    ['SH.FPL.WNTD.Q1.ZS'   , 'Fertility planning status (wanted then) (% of births): Q1 (lowest)'                                                    , ['Health']    ], 
    ['SH.FPL.WNTD.Q2.ZS'   , 'Fertility planning status (wanted then) (% of births): Q2'                                                             , ['Health']    ], 
    ['SH.FPL.WNTD.Q3.ZS'   , 'Fertility planning status (wanted then) (% of births): Q3'                                                             , ['Health']    ], 
    ['SH.FPL.WNTD.Q4.ZS'   , 'Fertility planning status (wanted then) (% of births): Q4'                                                             , ['Health']    ], 
    ['SH.FPL.WNTD.Q5.ZS'   , 'Fertility planning status (wanted then) (% of births): Q5 (highest)'                                                   , ['Health']    ], 
    ['SH.H2O.BASW.Q1.ZS'   , 'People using at least basic drinking water services (% of population): Q1 (lowest)'                                    , ['Health']    ], 
    ['SH.H2O.BASW.Q2.ZS'   , 'People using at least basic drinking water services (% of population): Q2'                                             , null          ], 
    ['SH.H2O.BASW.Q3.ZS'   , 'People using at least basic drinking water services (% of population): Q3'                                             , null          ], 
    ['SH.H2O.BASW.Q4.ZS'   , 'People using at least basic drinking water services (% of population): Q4'                                             , null          ], 
    ['SH.H2O.BASW.Q5.ZS'   , 'People using at least basic drinking water services (% of population): Q5 (highest)'                                   , null          ], 
    ['SH.H2O.BASW.RU.Q1.ZS', 'People using at least basic drinking water services, rural (% of rural population): Q1 (lowest)'                       , null          ], 
    ['SH.H2O.BASW.RU.Q2.ZS', 'People using at least basic drinking water services, rural (% of rural population): Q2'                                , ['Health']    ], 
    ['SH.H2O.BASW.RU.Q3.ZS', 'People using at least basic drinking water services, rural (% of rural population): Q3'                                , null          ], 
    ['SH.H2O.BASW.RU.Q4.ZS', 'People using at least basic drinking water services, rural (% of rural population): Q4'                                , null          ], 
    ['SH.H2O.BASW.RU.Q5.ZS', 'People using at least basic drinking water services, rural (% of rural population): Q5 (highest)'                      , null          ], 
    ['SH.H2O.BASW.UR.Q1.ZS', 'People using at least basic drinking water services, urban (% of urban population): Q1 (lowest)'                       , null          ], 
    ['SH.H2O.BASW.UR.Q2.ZS', 'People using at least basic drinking water services, urban (% of urban population): Q2'                                , null          ], 
    ['SH.H2O.BASW.UR.Q3.ZS', 'People using at least basic drinking water services, urban (% of urban population): Q3'                                , null          ], 
    ['SH.H2O.BASW.UR.Q4.ZS', 'People using at least basic drinking water services, urban (% of urban population): Q4'                                , null          ], 
    ['SH.H2O.BASW.UR.Q5.ZS', 'People using at least basic drinking water services, urban (% of urban population): Q5 (highest)'                      , null          ], 
    ['SH.IMM.ALLV.Q1.ZS'   , 'Vaccinations (all vaccinations) (% of children ages 12-23 months): Q1 (lowest)'                                        , ['Health']    ], 
    ['SH.IMM.ALLV.Q2.ZS'   , 'Vaccinations (all vaccinations) (% of children ages 12-23 months): Q2'                                                 , ['Health']    ], 
    ['SH.IMM.ALLV.Q3.ZS'   , 'Vaccinations (all vaccinations) (% of children ages 12-23 months): Q3'                                                 , ['Health']    ], 
    ['SH.IMM.ALLV.Q4.ZS'   , 'Vaccinations (all vaccinations) (% of children ages 12-23 months): Q4'                                                 , ['Health']    ], 
    ['SH.IMM.ALLV.Q5.ZS'   , 'Vaccinations (all vaccinations) (% of children ages 12-23 months): Q5 (highest)'                                       , ['Health']    ], 
    ['SH.IMM.IBCG.Q1.ZS'   , 'Vaccinations (BCG) (% of children ages 12-23 months): Q1 (lowest)'                                                     , ['Health']    ], 
    ['SH.IMM.IBCG.Q2.ZS'   , 'Vaccinations (BCG) (% of children ages 12-23 months): Q2'                                                              , ['Health']    ], 
    ['SH.IMM.IBCG.Q3.ZS'   , 'Vaccinations (BCG) (% of children ages 12-23 months): Q3'                                                              , ['Health']    ], 
    ['SH.IMM.IBCG.Q4.ZS'   , 'Vaccinations (BCG) (% of children ages 12-23 months): Q4'                                                              , ['Health']    ], 
    ['SH.IMM.IBCG.Q5.ZS'   , 'Vaccinations (BCG) (% of children ages 12-23 months): Q5 (highest)'                                                    , ['Health']    ], 
    ['SH.IMM.IDPT.Q1.ZS'   , 'Vaccinations (DPT 3) (% of children ages 12-23 months): Q1 (lowest)'                                                   , ['Health']    ], 
    ['SH.IMM.IDPT.Q2.ZS'   , 'Vaccinations (DPT 3) (% of children ages 12-23 months): Q2'                                                            , ['Health']    ], 
    ['SH.IMM.IDPT.Q3.ZS'   , 'Vaccinations (DPT 3) (% of children ages 12-23 months): Q3'                                                            , ['Health']    ], 
    ['SH.IMM.IDPT.Q4.ZS'   , 'Vaccinations (DPT 3) (% of children ages 12-23 months): Q4'                                                            , ['Health']    ], 
    ['SH.IMM.IDPT.Q5.ZS'   , 'Vaccinations (DPT 3) (% of children ages 12-23 months): Q5 (highest)'                                                  , ['Health']    ], 
    ['SH.IMM.MEAS.Q1.ZS'   , 'Vaccinations (Measles) (% of children ages 12-23 months): Q1 (lowest)'                                                 , ['Health']    ], 
    ['SH.IMM.MEAS.Q2.ZS'   , 'Vaccinations (Measles) (% of children ages 12-23 months): Q2'                                                          , ['Health']    ], 
    ['SH.IMM.MEAS.Q3.ZS'   , 'Vaccinations (Measles) (% of children ages 12-23 months): Q3'                                                          , ['Health']    ], 
    ['SH.IMM.MEAS.Q4.ZS'   , 'Vaccinations (Measles) (% of children ages 12-23 months): Q4'                                                          , ['Health']    ], 
    ['SH.IMM.MEAS.Q5.ZS'   , 'Vaccinations (Measles) (% of children ages 12-23 months): Q5 (highest)'                                                , ['Health']    ], 
    ['SH.IMM.NONE.Q1.ZS'   , 'Vaccinations (no vaccinations) (% of children ages 12-23 months): Q1 (lowest)'                                         , ['Health']    ], 
    ['SH.IMM.NONE.Q2.ZS'   , 'Vaccinations (no vaccinations) (% of children ages 12-23 months): Q2'                                                  , ['Health']    ], 
    ['SH.IMM.NONE.Q3.ZS'   , 'Vaccinations (no vaccinations) (% of children ages 12-23 months): Q3'                                                  , ['Health']    ], 
    ['SH.IMM.NONE.Q4.ZS'   , 'Vaccinations (no vaccinations) (% of children ages 12-23 months): Q4'                                                  , ['Health']    ], 
    ['SH.IMM.NONE.Q5.ZS'   , 'Vaccinations (no vaccinations) (% of children ages 12-23 months): Q5 (highest)'                                        , ['Health']    ], 
    ['SH.MLR.NETA.Q1.ZS'   , 'Mosquito net use by children (any mosquito net) (% of children under 5): Q1 (lowest)'                                  , ['Health']    ], 
    ['SH.MLR.NETA.Q2.ZS'   , 'Mosquito net use by children (any mosquito net) (% of children under 5): Q2'                                           , ['Health']    ], 
    ['SH.MLR.NETA.Q3.ZS'   , 'Mosquito net use by children (any mosquito net) (% of children under 5): Q3'                                           , ['Health']    ], 
    ['SH.MLR.NETA.Q4.ZS'   , 'Mosquito net use by children (any mosquito net) (% of children under 5): Q4'                                           , ['Health']    ], 
    ['SH.MLR.NETA.Q5.ZS'   , 'Mosquito net use by children (any mosquito net) (% of children under 5): Q5 (highest)'                                 , ['Health']    ], 
    ['SH.MLR.NETH.Q1.ZS'   , 'Household posession of mosquito nets (any type of mosquito net) (% of households): Q1 (lowest)'                        , ['Health']    ], 
    ['SH.MLR.NETH.Q2.ZS'   , 'Household posession of mosquito nets (any type of mosquito net) (% of households): Q2'                                 , ['Health']    ], 
    ['SH.MLR.NETH.Q3.ZS'   , 'Household posession of mosquito nets (any type of mosquito net) (% of households): Q3'                                 , ['Health']    ], 
    ['SH.MLR.NETH.Q4.ZS'   , 'Household posession of mosquito nets (any type of mosquito net) (% of households): Q4'                                 , ['Health']    ], 
    ['SH.MLR.NETH.Q5.ZS'   , 'Household posession of mosquito nets (any type of mosquito net) (% of households): Q5 (highest)'                       , ['Health']    ], 
    ['SH.MLR.NETP.Q1.ZS'   , 'Mosquito net use by pregnant women (any mosquito net) (% of pregnant women): Q1 (lowest)'                              , ['Health']    ], 
    ['SH.MLR.NETP.Q2.ZS'   , 'Mosquito net use by pregnant women (any mosquito net) (% of pregnant women): Q2'                                       , ['Health']    ], 
    ['SH.MLR.NETP.Q3.ZS'   , 'Mosquito net use by pregnant women (any mosquito net) (% of pregnant women): Q3'                                       , ['Health']    ], 
    ['SH.MLR.NETP.Q4.ZS'   , 'Mosquito net use by pregnant women (any mosquito net) (% of pregnant women): Q4'                                       , ['Health']    ], 
    ['SH.MLR.NETP.Q5.ZS'   , 'Mosquito net use by pregnant women (any mosquito net) (% of pregnant women): Q5 (highest)'                             , ['Health']    ], 
    ['SH.MLR.NETS.Q1.ZS'   , 'Malaria prevention, use of bed nets (% of under-5 children in the poorest quintile)'                                   , ['2kDevGoals']], 
    ['SH.MLR.NETS.Q2.ZS'   , 'Mosquito net use by children (insecticide-treated net) (% of children under 5): Q2'                                    , ['Health']    ], 
    ['SH.MLR.NETS.Q3.ZS'   , 'Mosquito net use by children (insecticide-treated net) (% of children under 5): Q3'                                    , ['Health']    ], 
    ['SH.MLR.NETS.Q4.ZS'   , 'Mosquito net use by children (insecticide-treated net) (% of children under 5): Q4'                                    , ['Health']    ], 
    ['SH.MLR.NETS.Q5.ZS'   , 'Malaria prevention, use of bed nets (% of under-5 children in the richest quintile)'                                   , ['2kDevGoals']], 
    ['SH.MLR.NTHI.Q1.ZS'   , 'Household posession of mosquito nets (insecticide-treated net) (% of households): Q1 (lowest)'                         , ['Health']    ], 
    ['SH.MLR.NTHI.Q2.ZS'   , 'Household posession of mosquito nets (insecticide-treated net) (% of households): Q2'                                  , ['Health']    ], 
    ['SH.MLR.NTHI.Q3.ZS'   , 'Household posession of mosquito nets (insecticide-treated net) (% of households): Q3'                                  , ['Health']    ], 
    ['SH.MLR.NTHI.Q4.ZS'   , 'Household posession of mosquito nets (insecticide-treated net) (% of households): Q4'                                  , ['Health']    ], 
    ['SH.MLR.NTHI.Q5.ZS'   , 'Household posession of mosquito nets (insecticide-treated net) (% of households): Q5 (highest)'                        , ['Health']    ], 
    ['SH.MLR.NTPI.Q1.ZS'   , 'Mosquito net use by pregnant women (insecticide-treated net) (% of pregnant women): Q1 (lowest)'                       , ['Health']    ], 
    ['SH.MLR.NTPI.Q2.ZS'   , 'Mosquito net use by pregnant women (insecticide-treated net) (% of pregnant women): Q2'                                , ['Health']    ], 
    ['SH.MLR.NTPI.Q3.ZS'   , 'Mosquito net use by pregnant women (insecticide-treated net) (% of pregnant women): Q3'                                , ['Health']    ], 
    ['SH.MLR.NTPI.Q4.ZS'   , 'Mosquito net use by pregnant women (insecticide-treated net) (% of pregnant women): Q4'                                , ['Health']    ], 
    ['SH.MLR.NTPI.Q5.ZS'   , 'Mosquito net use by pregnant women (insecticide-treated net) (% of pregnant women): Q5 (highest)'                      , ['Health']    ], 
    ['SH.MLR.SPFN.Q1.ZS'   , 'Anti-malarial drug use by pregnant women (SP/Fansidar two or more doses) (% of women with a birth): Q1 (lowest)'       , ['Health']    ], 
    ['SH.MLR.SPFN.Q2.ZS'   , 'Anti-malarial drug use by pregnant women (SP/Fansidar two or more doses) (% of women with a birth): Q2'                , ['Health']    ], 
    ['SH.MLR.SPFN.Q3.ZS'   , 'Anti-malarial drug use by pregnant women (SP/Fansidar two or more doses) (% of women with a birth): Q3'                , ['Health']    ], 
    ['SH.MLR.SPFN.Q4.ZS'   , 'Anti-malarial drug use by pregnant women (SP/Fansidar two or more doses) (% of women with a birth): Q4'                , ['Health']    ], 
    ['SH.MLR.SPFN.Q5.ZS'   , 'Anti-malarial drug use by pregnant women (SP/Fansidar two or more doses) (% of women with a birth): Q5 (highest)'      , ['Health']    ], 
    ['SH.MLR.TRET.Q1.ZS'   , 'Treatment of fever (% of children under 5 with fever): Q1 (lowest)'                                                    , ['Health']    ], 
    ['SH.MLR.TRET.Q2.ZS'   , 'Treatment of fever (% of children under 5 with fever): Q2'                                                             , ['Health']    ], 
    ['SH.MLR.TRET.Q3.ZS'   , 'Treatment of fever (% of children under 5 with fever): Q3'                                                             , ['Health']    ], 
    ['SH.MLR.TRET.Q4.ZS'   , 'Treatment of fever (% of children under 5 with fever): Q4'                                                             , ['Health']    ], 
    ['SH.MLR.TRET.Q5.ZS'   , 'Treatment of fever (% of children under 5 with fever): Q5 (highest)'                                                   , ['Health']    ], 
    ['SH.PRV.SMOK.FE.Q1.ZS', 'Smoking (% of women): Q1 (lowest)'                                                                                     , ['Health']    ], 
    ['SH.PRV.SMOK.FE.Q2.ZS', 'Smoking (% of women): Q2'                                                                                              , ['Health']    ], 
    ['SH.PRV.SMOK.FE.Q3.ZS', 'Smoking (% of women): Q3'                                                                                              , ['Health']    ], 
    ['SH.PRV.SMOK.FE.Q4.ZS', 'Smoking (% of women): Q4'                                                                                              , ['Health']    ], 
    ['SH.PRV.SMOK.FE.Q5.ZS', 'Smoking (% of women): Q5 (highest)'                                                                                    , ['Health']    ], 
    ['SH.STA.ANCP.Q1.ZS'   , 'Components of antenatal care (received iron tablets or syrup) (% of women with a birth): Q1 (lowest)'                  , ['Health']    ], 
    ['SH.STA.ANCP.Q2.ZS'   , 'Components of antenatal care (received iron tablets or syrup) (% of women with a birth): Q2'                           , ['Health']    ], 
    ['SH.STA.ANCP.Q3.ZS'   , 'Components of antenatal care (received iron tablets or syrup) (% of women with a birth): Q3'                           , ['Health']    ], 
    ['SH.STA.ANCP.Q4.ZS'   , 'Components of antenatal care (received iron tablets or syrup) (% of women with a birth): Q4'                           , ['Health']    ], 
    ['SH.STA.ANCP.Q5.ZS'   , 'Components of antenatal care (received iron tablets or syrup) (% of women with a birth): Q5 (highest)'                 , ['Health']    ], 
    ['SH.STA.ANVC.Q1.ZS'   , 'Antenatal care (any skilled personnel) (% of women with a birth): Q1 (lowest)'                                         , ['Health']    ], 
    ['SH.STA.ANVC.Q2.ZS'   , 'Antenatal care (any skilled personnel) (% of women with a birth): Q2'                                                  , ['Health']    ], 
    ['SH.STA.ANVC.Q3.ZS'   , 'Antenatal care (any skilled personnel) (% of women with a birth): Q3'                                                  , ['Health']    ], 
    ['SH.STA.ANVC.Q4.ZS'   , 'Antenatal care (any skilled personnel) (% of women with a birth): Q4'                                                  , ['Health']    ], 
    ['SH.STA.ANVC.Q5.ZS'   , 'Antenatal care (any skilled personnel) (% of women with a birth): Q5 (highest)'                                        , ['Health']    ], 
    ['SH.STA.ANVP.Q1.ZS'   , 'Antenatal care (doctor) (% of women with a birth): Q1 (lowest)'                                                        , ['Health']    ], 
    ['SH.STA.ANVP.Q2.ZS'   , 'Antenatal care (doctor) (% of women with a birth): Q2'                                                                 , ['Health']    ], 
    ['SH.STA.ANVP.Q3.ZS'   , 'Antenatal care (doctor) (% of women with a birth): Q3'                                                                 , ['Health']    ], 
    ['SH.STA.ANVP.Q4.ZS'   , 'Antenatal care (doctor) (% of women with a birth): Q4'                                                                 , ['Health']    ], 
    ['SH.STA.ANVP.Q5.ZS'   , 'Antenatal care (doctor) (% of women with a birth): Q5 (highest)'                                                       , ['Health']    ], 
    ['SH.STA.ARIC.Q1.ZS'   , 'Treatment of acute respiratory infection (ARI) (% of children under 5 taken to a health provider): Q1 (lowest)'        , ['Health']    ], 
    ['SH.STA.ARIC.Q2.ZS'   , 'Treatment of acute respiratory infection (ARI) (% of children under 5 taken to a health provider): Q2'                 , ['Health']    ], 
    ['SH.STA.ARIC.Q3.ZS'   , 'Treatment of acute respiratory infection (ARI) (% of children under 5 taken to a health provider): Q3'                 , ['Health']    ], 
    ['SH.STA.ARIC.Q4.ZS'   , 'Treatment of acute respiratory infection (ARI) (% of children under 5 taken to a health provider): Q4'                 , ['Health']    ], 
    ['SH.STA.ARIC.Q5.ZS'   , 'Treatment of acute respiratory infection (ARI) (% of children under 5 taken to a health provider): Q5 (highest)'       , ['Health']    ], 
    ['SH.STA.ARIF.Q1.ZS'   , 'Prevalence of acute respiratory infection (ARI) (% of children under 5): Q1 (lowest)'                                  , ['Health']    ], 
    ['SH.STA.ARIF.Q2.ZS'   , 'Prevalence of acute respiratory infection (ARI) (% of children under 5): Q2'                                           , ['Health']    ], 
    ['SH.STA.ARIF.Q3.ZS'   , 'Prevalence of acute respiratory infection (ARI) (% of children under 5): Q3'                                           , ['Health']    ], 
    ['SH.STA.ARIF.Q4.ZS'   , 'Prevalence of acute respiratory infection (ARI) (% of children under 5): Q4'                                           , ['Health']    ], 
    ['SH.STA.ARIF.Q5.ZS'   , 'Prevalence of acute respiratory infection (ARI) (% of children under 5): Q5 (highest)'                                 , ['Health']    ], 
    ['SH.STA.BASS.Q1.ZS'   , 'People using at least basic sanitation services (% of population): Q1 (lowest)'                                        , null          ], 
    ['SH.STA.BASS.Q2.ZS'   , 'People using at least basic sanitation services (% of population): Q2'                                                 , null          ], 
    ['SH.STA.BASS.Q3.ZS'   , 'People using at least basic sanitation services (% of population): Q3'                                                 , null          ], 
    ['SH.STA.BASS.Q4.ZS'   , 'People using at least basic sanitation services (% of population): Q4'                                                 , null          ], 
    ['SH.STA.BASS.Q5.ZS'   , 'People using at least basic sanitation services (% of population): Q5 (highest)'                                       , null          ], 
    ['SH.STA.BASS.RU.Q1.ZS', 'People using at least basic sanitation services, rural (% of rural population): Q1 (lowest)'                           , null          ], 
    ['SH.STA.BASS.RU.Q2.ZS', 'People using at least basic sanitation services, rural (% of rural population): Q2'                                    , null          ], 
    ['SH.STA.BASS.RU.Q3.ZS', 'People using at least basic sanitation services, rural (% of rural population): Q3'                                    , null          ], 
    ['SH.STA.BASS.RU.Q4.ZS', 'People using at least basic sanitation services, rural (% of rural population): Q4'                                    , null          ], 
    ['SH.STA.BASS.RU.Q5.ZS', 'People using at least basic sanitation services, rural (% of rural population): Q5 (highest)'                          , null          ], 
    ['SH.STA.BASS.UR.Q1.ZS', 'People using at least basic sanitation services, urban  (% of urban population): Q1 (lowest)'                          , null          ], 
    ['SH.STA.BASS.UR.Q2.ZS', 'People using at least basic sanitation services, urban  (% of urban population): Q2'                                   , null          ], 
    ['SH.STA.BASS.UR.Q3.ZS', 'People using at least basic sanitation services, urban  (% of urban population): Q3'                                   , null          ], 
    ['SH.STA.BASS.UR.Q4.ZS', 'People using at least basic sanitation services, urban  (% of urban population): Q4'                                   , null          ], 
    ['SH.STA.BASS.UR.Q5.ZS', 'People using at least basic sanitation services, urban  (% of urban population): Q5 (highest)'                         , null          ], 
    ['SH.STA.BFED.Q1.ZS'   , 'Breastfeeding (% of children under 6 months): Q1 (lowest)'                                                             , ['Health']    ], 
    ['SH.STA.BFED.Q2.ZS'   , 'Breastfeeding (% of children under 6 months): Q2'                                                                      , ['Health']    ], 
    ['SH.STA.BFED.Q3.ZS'   , 'Breastfeeding (% of children under 6 months): Q3'                                                                      , ['Health']    ], 
    ['SH.STA.BFED.Q4.ZS'   , 'Breastfeeding (% of children under 6 months): Q4'                                                                      , ['Health']    ], 
    ['SH.STA.BFED.Q5.ZS'   , 'Breastfeeding (% of children under 6 months): Q5 (highest)'                                                            , ['Health']    ], 
    ['SH.STA.BRTC.Q1.ZS'   , 'Assistance during delivery (any skilled personnel) (% of births): Q1 (lowest)'                                         , ['Health']    ], 
    ['SH.STA.BRTC.Q2.ZS'   , 'Assistance during delivery (any skilled personnel) (% of births): Q2'                                                  , ['Health']    ], 
    ['SH.STA.BRTC.Q3.ZS'   , 'Assistance during delivery (any skilled personnel) (% of births): Q3'                                                  , ['Health']    ], 
    ['SH.STA.BRTC.Q4.ZS'   , 'Assistance during delivery (any skilled personnel) (% of births): Q4'                                                  , ['Health']    ], 
    ['SH.STA.BRTC.Q5.ZS'   , 'Assistance during delivery (any skilled personnel) (% of births): Q5 (highest)'                                        , ['Health']    ], 
    ['SH.STA.BRTF.Q1.ZS'   , 'Place of delivery (births at health facility) (% of births): Q1 (lowest)'                                              , ['Health']    ], 
    ['SH.STA.BRTF.Q2.ZS'   , 'Place of delivery (births at health facility) (% of births): Q2'                                                       , ['Health']    ], 
    ['SH.STA.BRTF.Q3.ZS'   , 'Place of delivery (births at health facility) (% of births): Q3'                                                       , ['Health']    ], 
    ['SH.STA.BRTF.Q4.ZS'   , 'Place of delivery (births at health facility) (% of births): Q4'                                                       , ['Health']    ], 
    ['SH.STA.BRTF.Q5.ZS'   , 'Place of delivery (births at health facility) (% of births): Q5 (highest)'                                             , ['Health']    ], 
    ['SH.STA.BRTP.Q1.ZS'   , 'Assistance during delivery (doctor) (% of births): Q1 (lowest)'                                                        , ['Health']    ], 
    ['SH.STA.BRTP.Q2.ZS'   , 'Assistance during delivery (doctor) (% of births): Q2'                                                                 , ['Health']    ], 
    ['SH.STA.BRTP.Q3.ZS'   , 'Assistance during delivery (doctor) (% of births): Q3'                                                                 , ['Health']    ], 
    ['SH.STA.BRTP.Q4.ZS'   , 'Assistance during delivery (doctor) (% of births): Q4'                                                                 , ['Health']    ], 
    ['SH.STA.BRTP.Q5.ZS'   , 'Assistance during delivery (doctor) (% of births): Q5 (highest)'                                                       , ['Health']    ], 
    ['SH.STA.DIRH.Q1.ZS'   , 'Prevalence of diarrhea (% of children under 5): Q1 (lowest)'                                                           , ['Health']    ], 
    ['SH.STA.DIRH.Q2.ZS'   , 'Prevalence of diarrhea (% of children under 5): Q2'                                                                    , ['Health']    ], 
    ['SH.STA.DIRH.Q3.ZS'   , 'Prevalence of diarrhea (% of children under 5): Q3'                                                                    , ['Health']    ], 
    ['SH.STA.DIRH.Q4.ZS'   , 'Prevalence of diarrhea (% of children under 5): Q4'                                                                    , ['Health']    ], 
    ['SH.STA.DIRH.Q5.ZS'   , 'Prevalence of diarrhea (% of children under 5): Q5 (highest)'                                                          , ['Health']    ], 
    ['SH.STA.FEVR.Q1.ZS'   , 'Prevalence of children with fever (% of children under 5): Q1 (lowest)'                                                , ['Health']    ], 
    ['SH.STA.FEVR.Q2.ZS'   , 'Prevalence of children with fever (% of children under 5): Q2'                                                         , ['Health']    ], 
    ['SH.STA.FEVR.Q3.ZS'   , 'Prevalence of children with fever (% of children under 5): Q3'                                                         , ['Health']    ], 
    ['SH.STA.FEVR.Q4.ZS'   , 'Prevalence of children with fever (% of children under 5): Q4'                                                         , ['Health']    ], 
    ['SH.STA.FEVR.Q5.ZS'   , 'Prevalence of children with fever (% of children under 5): Q5 (highest)'                                               , ['Health']    ], 
    ['SH.STA.HYGN.Q1.ZS'   , 'People with basic handwashing facilities including soap and water (% of population): Q1 (lowest)'                      , null          ], 
    ['SH.STA.HYGN.Q2.ZS'   , 'People with basic handwashing facilities including soap and water (% of population): Q2'                               , null          ], 
    ['SH.STA.HYGN.Q3.ZS'   , 'People with basic handwashing facilities including soap and water (% of population): Q3'                               , null          ], 
    ['SH.STA.HYGN.Q4.ZS'   , 'People with basic handwashing facilities including soap and water (% of population): Q4'                               , null          ], 
    ['SH.STA.HYGN.Q5.ZS'   , 'People with basic handwashing facilities including soap and water (% of population): Q5 (highest)'                     , null          ], 
    ['SH.STA.HYGN.RU.Q1.ZS', 'People with basic handwashing facilities including soap and water, rural (% of rural population): Q1 (lowest)'         , null          ], 
    ['SH.STA.HYGN.RU.Q2.ZS', 'People with basic handwashing facilities including soap and water, rural (% of rural population): Q2'                  , null          ], 
    ['SH.STA.HYGN.RU.Q3.ZS', 'People with basic handwashing facilities including soap and water, rural (% of rural population): Q3'                  , null          ], 
    ['SH.STA.HYGN.RU.Q4.ZS', 'People with basic handwashing facilities including soap and water, rural (% of rural population): Q4'                  , null          ], 
    ['SH.STA.HYGN.RU.Q5.ZS', 'People with basic handwashing facilities including soap and water, rural (% of rural population): Q5 (highest)'        , null          ], 
    ['SH.STA.HYGN.UR.Q1.ZS', 'People with basic handwashing facilities including soap and water, urban (% of urban population): Q1 (lowest)'         , null          ], 
    ['SH.STA.HYGN.UR.Q2.ZS', 'People with basic handwashing facilities including soap and water, urban (% of urban population): Q2'                  , null          ], 
    ['SH.STA.HYGN.UR.Q3.ZS', 'People with basic handwashing facilities including soap and water, urban (% of urban population): Q3'                  , null          ], 
    ['SH.STA.HYGN.UR.Q4.ZS', 'People with basic handwashing facilities including soap and water, urban (% of urban population): Q4'                  , null          ], 
    ['SH.STA.HYGN.UR.Q5.ZS', 'People with basic handwashing facilities including soap and water, urban (% of urban population): Q5 (highest)'        , null          ], 
    ['SH.STA.LBMI.Q1.ZS'   , 'Malnourished women (BMI is less than 18.5) (% of women): Q1 (lowest)'                                                  , ['Health']    ], 
    ['SH.STA.LBMI.Q2.ZS'   , 'Malnourished women (BMI is less than 18.5) (% of women): Q2'                                                           , ['Health']    ], 
    ['SH.STA.LBMI.Q3.ZS'   , 'Malnourished women (BMI is less than 18.5) (% of women): Q3'                                                           , ['Health']    ], 
    ['SH.STA.LBMI.Q4.ZS'   , 'Malnourished women (BMI is less than 18.5) (% of women): Q4'                                                           , ['Health']    ], 
    ['SH.STA.LBMI.Q5.ZS'   , 'Malnourished women (BMI is less than 18.5) (% of women): Q5 (highest)'                                                 , ['Health']    ], 
    ['SH.STA.MALN.Q1.ZS'   , 'Malnourished children (underweight, -2SD) (% of children under 5): Q1 (lowest)'                                        , ['Health']    ], 
    ['SH.STA.MALN.Q2.ZS'   , 'Malnourished children (underweight, -2SD) (% of children under 5): Q2'                                                 , ['Health']    ], 
    ['SH.STA.MALN.Q3.ZS'   , 'Malnourished children (underweight, -2SD) (% of children under 5): Q3'                                                 , ['Health']    ], 
    ['SH.STA.MALN.Q4.ZS'   , 'Malnourished children (underweight, -2SD) (% of children under 5): Q4'                                                 , ['Health']    ], 
    ['SH.STA.MALN.Q5.ZS'   , 'Malnourished children (underweight, -2SD) (% of children under 5): Q5 (highest)'                                       , ['Health']    ], 
    ['SH.STA.MLN3.Q1.ZS'   , 'Malnourished children (underweight, -3SD) (% of children under 5): Q1 (lowest)'                                        , ['Health']    ], 
    ['SH.STA.MLN3.Q2.ZS'   , 'Malnourished children (underweight, -3SD) (% of children under 5): Q2'                                                 , ['Health']    ], 
    ['SH.STA.MLN3.Q3.ZS'   , 'Malnourished children (underweight, -3SD) (% of children under 5): Q3'                                                 , ['Health']    ], 
    ['SH.STA.MLN3.Q4.ZS'   , 'Malnourished children (underweight, -3SD) (% of children under 5): Q4'                                                 , ['Health']    ], 
    ['SH.STA.MLN3.Q5.ZS'   , 'Malnourished children (underweight, -3SD) (% of children under 5): Q5 (highest)'                                       , ['Health']    ], 
    ['SH.STA.ODFC.Q1.ZS'   , 'People practicing open defecation (% of population): Q1 (lowest)'                                                      , null          ], 
    ['SH.STA.ODFC.Q2.ZS'   , 'People practicing open defecation (% of population): Q2'                                                               , null          ], 
    ['SH.STA.ODFC.Q3.ZS'   , 'People practicing open defecation (% of population): Q3'                                                               , null          ], 
    ['SH.STA.ODFC.Q4.ZS'   , 'People practicing open defecation (% of population): Q4'                                                               , null          ], 
    ['SH.STA.ODFC.Q5.ZS'   , 'People practicing open defecation (% of population): Q5 (highest)'                                                     , null          ], 
    ['SH.STA.ODFC.RU.Q1.ZS', 'People practicing open defecation, rural (% of rural population): Q1 (lowest)'                                         , null          ], 
    ['SH.STA.ODFC.RU.Q2.ZS', 'People practicing open defecation, rural (% of rural population): Q2'                                                  , null          ], 
    ['SH.STA.ODFC.RU.Q3.ZS', 'People practicing open defecation, rural (% of rural population): Q3'                                                  , null          ], 
    ['SH.STA.ODFC.RU.Q4.ZS', 'People practicing open defecation, rural (% of rural population): Q4'                                                  , null          ], 
    ['SH.STA.ODFC.RU.Q5.ZS', 'People practicing open defecation, rural (% of rural population): Q5 (highest)'                                        , null          ], 
    ['SH.STA.ODFC.UR.Q1.ZS', 'People practicing open defecation, urban (% of urban population): Q1 (lowest)'                                         , null          ], 
    ['SH.STA.ODFC.UR.Q2.ZS', 'People practicing open defecation, urban (% of urban population): Q2'                                                  , null          ], 
    ['SH.STA.ODFC.UR.Q3.ZS', 'People practicing open defecation, urban (% of urban population): Q3'                                                  , null          ], 
    ['SH.STA.ODFC.UR.Q4.ZS', 'People practicing open defecation, urban (% of urban population): Q4'                                                  , null          ], 
    ['SH.STA.ODFC.UR.Q5.ZS', 'People practicing open defecation, urban (% of urban population): Q5 (highest)'                                        , null          ], 
    ['SH.STA.ORHF.Q1.ZS'   , 'Treatment of diarrhea (ORS, RHS or increased fluids) (% of children under 5): Q1 (lowest)'                             , ['Health']    ], 
    ['SH.STA.ORHF.Q2.ZS'   , 'Treatment of diarrhea (ORS, RHS or increased fluids) (% of children under 5): Q2'                                      , ['Health']    ], 
    ['SH.STA.ORHF.Q3.ZS'   , 'Treatment of diarrhea (ORS, RHS or increased fluids) (% of children under 5): Q3'                                      , ['Health']    ], 
    ['SH.STA.ORHF.Q4.ZS'   , 'Treatment of diarrhea (ORS, RHS or increased fluids) (% of children under 5): Q4'                                      , ['Health']    ], 
    ['SH.STA.ORHF.Q5.ZS'   , 'Treatment of diarrhea (ORS, RHS or increased fluids) (% of children under 5): Q5 (highest)'                            , ['Health']    ], 
    ['SH.STA.ORHK.Q1.ZS'   , 'Knowledge of diarrhea care (% of mothers): Q1 (lowest)'                                                                , ['Health']    ], 
    ['SH.STA.ORHK.Q2.ZS'   , 'Knowledge of diarrhea care (% of mothers): Q2'                                                                         , ['Health']    ], 
    ['SH.STA.ORHK.Q3.ZS'   , 'Knowledge of diarrhea care (% of mothers): Q3'                                                                         , ['Health']    ], 
    ['SH.STA.ORHK.Q4.ZS'   , 'Knowledge of diarrhea care (% of mothers): Q4'                                                                         , ['Health']    ], 
    ['SH.STA.ORHK.Q5.ZS'   , 'Knowledge of diarrhea care (% of mothers): Q5 (highest)'                                                               , ['Health']    ], 
    ['SH.STA.ORHS.Q1ZS'    , 'Treatment of diarrhea (either ORS or RHS) (% of children under 5): Q1 (lowest)'                                        , ['Health']    ], 
    ['SH.STA.ORHS.Q2ZS'    , 'Treatment of diarrhea (either ORS or RHS) (% of children under 5): Q2'                                                 , ['Health']    ], 
    ['SH.STA.ORHS.Q3ZS'    , 'Treatment of diarrhea (either ORS or RHS) (% of children under 5): Q3'                                                 , ['Health']    ], 
    ['SH.STA.ORHS.Q4ZS'    , 'Treatment of diarrhea (either ORS or RHS) (% of children under 5): Q4'                                                 , ['Health']    ], 
    ['SH.STA.ORHS.Q5ZS'    , 'Treatment of diarrhea (either ORS or RHS) (% of children under 5): Q5 (highest)'                                       , ['Health']    ], 
    ['SH.STA.STN3.Q1.ZS'   , 'Malnourished children (stunting, -3SD) (% of children under 5): Q1 (lowest)'                                           , ['Health']    ], 
    ['SH.STA.STN3.Q2.ZS'   , 'Malnourished children (stunting, -3SD) (% of children under 5): Q2'                                                    , ['Health']    ], 
    ['SH.STA.STN3.Q3.ZS'   , 'Malnourished children (stunting, -3SD) (% of children under 5): Q3'                                                    , ['Health']    ], 
    ['SH.STA.STN3.Q4.ZS'   , 'Malnourished children (stunting, -3SD) (% of children under 5): Q4'                                                    , ['Health']    ], 
    ['SH.STA.STN3.Q5.ZS'   , 'Malnourished children (stunting, -3SD) (% of children under 5): Q5 (highest)'                                          , ['Health']    ], 
    ['SH.STA.STNT.Q1.ZS'   , 'Malnourished children (stunting, -2SD) (% of children under 5): Q1 (lowest)'                                           , ['Health']    ], 
    ['SH.STA.STNT.Q2.ZS'   , 'Malnourished children (stunting, -2SD) (% of children under 5): Q2'                                                    , ['Health']    ], 
    ['SH.STA.STNT.Q3.ZS'   , 'Malnourished children (stunting, -2SD) (% of children under 5): Q3'                                                    , ['Health']    ], 
    ['SH.STA.STNT.Q4.ZS'   , 'Malnourished children (stunting, -2SD) (% of children under 5): Q4'                                                    , ['Health']    ], 
    ['SH.STA.STNT.Q5.ZS'   , 'Malnourished children (stunting, -2SD) (% of children under 5): Q5 (highest)'                                          , ['Health']    ], 
    ['SH.STA.WAST.Q1.ZS'   , 'Malnourished children (wasting, -2SD) (% of children under 5): Q1 (lowest)'                                            , ['Health']    ], 
    ['SH.STA.WAST.Q2.ZS'   , 'Malnourished children (wasting, -2SD) (% of children under 5): Q2'                                                     , ['Health']    ], 
    ['SH.STA.WAST.Q3.ZS'   , 'Malnourished children (wasting, -2SD) (% of children under 5): Q3'                                                     , ['Health']    ], 
    ['SH.STA.WAST.Q4.ZS'   , 'Malnourished children (wasting, -2SD) (% of children under 5): Q4'                                                     , ['Health']    ], 
    ['SH.STA.WAST.Q5.ZS'   , 'Malnourished children (wasting, -2SD) (% of children under 5): Q5 (highest)'                                           , ['Health']    ], 
    ['SH.STA.WST3.Q1.ZS'   , 'Malnourished children (wasting, -3SD) (% of children under 5): Q1 (lowest)'                                            , ['Health']    ], 
    ['SH.STA.WST3.Q2.ZS'   , 'Malnourished children (wasting, -3SD) (% of children under 5): Q2'                                                     , ['Health']    ], 
    ['SH.STA.WST3.Q3.ZS'   , 'Malnourished children (wasting, -3SD) (% of children under 5): Q3'                                                     , ['Health']    ], 
    ['SH.STA.WST3.Q4.ZS'   , 'Malnourished children (wasting, -3SD) (% of children under 5): Q4'                                                     , ['Health']    ], 
    ['SH.STA.WST3.Q5.ZS'   , 'Malnourished children (wasting, -3SD) (% of children under 5): Q5 (highest)'                                           , ['Health']    ], 
    ['SH.VAC.TTNS.Q1.ZS'   , 'Tetanus toxoid vaccination (% of live births): Q1 (lowest)'                                                            , ['Health']    ], 
    ['SH.VAC.TTNS.Q2.ZS'   , 'Tetanus toxoid vaccination (% of live births): Q2'                                                                     , ['Health']    ], 
    ['SH.VAC.TTNS.Q3.ZS'   , 'Tetanus toxoid vaccination (% of live births): Q3'                                                                     , ['Health']    ], 
    ['SH.VAC.TTNS.Q4.ZS'   , 'Tetanus toxoid vaccination (% of live births): Q4'                                                                     , ['Health']    ], 
    ['SH.VAC.TTNS.Q5.ZS'   , 'Tetanus toxoid vaccination (% of live births): Q5 (highest)'                                                           , ['Health']    ], 
    ['SN.ITK.VAPP.Q1.ZS'   , 'Vitamin A supplements for postpartum women (% of women with a birth): Q1 (lowest)'                                     , ['Health']    ], 
    ['SN.ITK.VAPP.Q2.ZS'   , 'Vitamin A supplements for postpartum women (% of women with a birth): Q2'                                              , ['Health']    ], 
    ['SN.ITK.VAPP.Q3.ZS'   , 'Vitamin A supplements for postpartum women (% of women with a birth): Q3'                                              , ['Health']    ], 
    ['SN.ITK.VAPP.Q4.ZS'   , 'Vitamin A supplements for postpartum women (% of women with a birth): Q4'                                              , ['Health']    ], 
    ['SN.ITK.VAPP.Q5.ZS'   , 'Vitamin A supplements for postpartum women (% of women with a birth): Q5 (highest)'                                    , ['Health']    ], 
    ['SN.ITK.VITA.Q1.ZS'   , 'Vitamin A supplements for children (% of children ages 6-59 months): Q1 (lowest)'                                      , ['Health']    ], 
    ['SN.ITK.VITA.Q2.ZS'   , 'Vitamin A supplements for children (% of children ages 6-59 months): Q2'                                               , ['Health']    ], 
    ['SN.ITK.VITA.Q3.ZS'   , 'Vitamin A supplements for children (% of children ages 6-59 months): Q3'                                               , ['Health']    ], 
    ['SN.ITK.VITA.Q4.ZS'   , 'Vitamin A supplements for children (% of children ages 6-59 months): Q4'                                               , ['Health']    ], 
    ['SN.ITK.VITA.Q5.ZS'   , 'Vitamin A supplements for children (% of children ages 6-59 months): Q5 (highest)'                                     , ['Health']    ], 
    ['SP.DYN.CEBN.Q1'      , 'Mean number of children ever born to women aged 40-49: Q1 (lowest)'                                                    , ['Health']    ], 
    ['SP.DYN.CEBN.Q2'      , 'Mean number of children ever born to women aged 40-49: Q2'                                                             , ['Health']    ], 
    ['SP.DYN.CEBN.Q3'      , 'Mean number of children ever born to women aged 40-49: Q3'                                                             , ['Health']    ], 
    ['SP.DYN.CEBN.Q4'      , 'Mean number of children ever born to women aged 40-49: Q4'                                                             , ['Health']    ], 
    ['SP.DYN.CEBN.Q5'      , 'Mean number of children ever born to women aged 40-49: Q5 (highest)'                                                   , ['Health']    ], 
    ['SP.DYN.CONM.Q1.ZS'   , 'Current use of contraception (modern method) (% of married women): Q1 (lowest)'                                        , ['Health']    ], 
    ['SP.DYN.CONM.Q2.ZS'   , 'Current use of contraception (modern method) (% of married women): Q2'                                                 , ['Health']    ], 
    ['SP.DYN.CONM.Q3.ZS'   , 'Current use of contraception (modern method) (% of married women): Q3'                                                 , ['Health']    ], 
    ['SP.DYN.CONM.Q4.ZS'   , 'Current use of contraception (modern method) (% of married women): Q4'                                                 , ['Health']    ], 
    ['SP.DYN.CONM.Q5.ZS'   , 'Current use of contraception (modern method) (% of married women): Q5 (highest)'                                       , ['Health']    ], 
    ['SP.DYN.CONU.Q1.ZS'   , 'Current use of contraception (any method) (% of married women): Q1 (lowest)'                                           , ['Health']    ], 
    ['SP.DYN.CONU.Q2.ZS'   , 'Current use of contraception (any method) (% of married women): Q2'                                                    , ['Health']    ], 
    ['SP.DYN.CONU.Q3.ZS'   , 'Current use of contraception (any method) (% of married women): Q3'                                                    , ['Health']    ], 
    ['SP.DYN.CONU.Q4.ZS'   , 'Current use of contraception (any method) (% of married women): Q4'                                                    , ['Health']    ], 
    ['SP.DYN.CONU.Q5.ZS'   , 'Current use of contraception (any method) (% of married women): Q5 (highest)'                                          , ['Health']    ], 
    ['SP.DYN.IMRT.Q1'      , 'Infant mortality rate (per 1,000 live births): Q1 (lowest)'                                                            , ['Health']    ], 
    ['SP.DYN.IMRT.Q2'      , 'Infant mortality rate (per 1,000 live births): Q2'                                                                     , ['Health']    ], 
    ['SP.DYN.IMRT.Q3'      , 'Infant mortality rate (per 1,000 live births): Q3'                                                                     , ['Health']    ], 
    ['SP.DYN.IMRT.Q4'      , 'Infant mortality rate (per 1,000 live births): Q4'                                                                     , ['Health']    ], 
    ['SP.DYN.IMRT.Q5'      , 'Infant mortality rate (per 1,000 live births): Q5 (highest)'                                                           , ['Health']    ], 
    ['SP.DYN.TFRT.Q1'      , ' Total fertility rate (TFR) (births per woman): Q1 (lowest)'                                                           , ['Health']    ], 
    ['SP.DYN.TFRT.Q2'      , ' Total fertility rate (TFR) (births per woman): Q2'                                                                    , ['Health']    ], 
    ['SP.DYN.TFRT.Q3'      , ' Total fertility rate (TFR) (births per woman): Q3'                                                                    , ['Health']    ], 
    ['SP.DYN.TFRT.Q4'      , ' Total fertility rate (TFR) (births per woman): Q4'                                                                    , ['Health']    ], 
    ['SP.DYN.TFRT.Q5'      , ' Total fertility rate (TFR) (births per woman): Q5 (highest)'                                                          , ['Health']    ], 
    ['SP.DYN.WFRT.Q1'      , 'Total wanted fertility rate (births per woman): Q1 (lowest)'                                                           , ['Health']    ], 
    ['SP.DYN.WFRT.Q2'      , 'Total wanted fertility rate (births per woman): Q2'                                                                    , ['Health']    ], 
    ['SP.DYN.WFRT.Q3'      , 'Total wanted fertility rate (births per woman): Q3'                                                                    , ['Health']    ], 
    ['SP.DYN.WFRT.Q4'      , 'Total wanted fertility rate (births per woman): Q4'                                                                    , ['Health']    ], 
    ['SP.DYN.WFRT.Q5'      , 'Total wanted fertility rate (births per woman): Q5 (highest)'                                                          , ['Health']    ], 
    ['SP.MTR.1519.Q1.ZS'   , 'Teenage pregnancy and motherhood (% of women ages 15-19 who have had children or are currently pregnant): Q1 (lowest)' , ['Health']    ], 
    ['SP.MTR.1519.Q2.ZS'   , 'Teenage pregnancy and motherhood (% of women ages 15-19 who have had children or are currently pregnant): Q2'          , ['Health']    ], 
    ['SP.MTR.1519.Q3.ZS'   , 'Teenage pregnancy and motherhood (% of women ages 15-19 who have had children or are currently pregnant): Q3'          , ['Health']    ], 
    ['SP.MTR.1519.Q4.ZS'   , 'Teenage pregnancy and motherhood (% of women ages 15-19 who have had children or are currently pregnant): Q4'          , ['Health']    ], 
    ['SP.MTR.1519.Q5.ZS'   , 'Teenage pregnancy and motherhood (% of women ages 15-19 who have had children or are currently pregnant): Q5 (highest)', ['Health']    ], 
    ['SP.REG.BRTH.Q1.ZS'   , 'Completeness of birth registration (%): Q1 (lowest)'                                                                   , null          ], 
    ['SP.REG.BRTH.Q2.ZS'   , 'Completeness of birth registration (%): Q2'                                                                            , null          ], 
    ['SP.REG.BRTH.Q3.ZS'   , 'Completeness of birth registration (%): Q3'                                                                            , null          ], 
    ['SP.REG.BRTH.Q4.ZS'   , 'Completeness of birth registration (%): Q4'                                                                            , null          ], 
    ['SP.REG.BRTH.Q5.ZS'   , 'Completeness of birth registration (%): Q5 (highest)'                                                                  , null          ], 
    ['SP.UWT.LMTG.Q1.ZS'   , 'Unmet need for family planning (for limiting) (% of married women): Q1 (lowest)'                                       , ['Health']    ], 
    ['SP.UWT.LMTG.Q2.ZS'   , 'Unmet need for family planning (for limiting) (% of married women): Q2'                                                , ['Health']    ], 
    ['SP.UWT.LMTG.Q3.ZS'   , 'Unmet need for family planning (for limiting) (% of married women): Q3'                                                , ['Health']    ], 
    ['SP.UWT.LMTG.Q4.ZS'   , 'Unmet need for family planning (for limiting) (% of married women): Q4'                                                , ['Health']    ], 
    ['SP.UWT.LMTG.Q5.ZS'   , 'Unmet need for family planning (for limiting) (% of married women): Q5 (highest)'                                      , ['Health']    ], 
    ['SP.UWT.SPCG.Q1.ZS'   , 'Unmet need for family planning (for spacing) (% of married women): Q1 (lowest)'                                        , ['Health']    ], 
    ['SP.UWT.SPCG.Q2.ZS'   , 'Unmet need for family planning (for spacing) (% of married women): Q2'                                                 , ['Health']    ], 
    ['SP.UWT.SPCG.Q3.ZS'   , 'Unmet need for family planning (for spacing) (% of married women): Q3'                                                 , ['Health']    ], 
    ['SP.UWT.SPCG.Q4.ZS'   , 'Unmet need for family planning (for spacing) (% of married women): Q4'                                                 , ['Health']    ], 
    ['SP.UWT.SPCG.Q5.ZS'   , 'Unmet need for family planning (for spacing) (% of married women): Q5 (highest)'                                       , ['Health']    ], 
    ['SP.UWT.TFRT.Q1.ZS'   , 'Unmet need for family planning (total) (% of married women): Q1 (lowest)'                                              , ['Health']    ], 
    ['SP.UWT.TFRT.Q2.ZS'   , 'Unmet need for family planning (total) (% of married women): Q2'                                                       , ['Health']    ], 
    ['SP.UWT.TFRT.Q3.ZS'   , 'Unmet need for family planning (total) (% of married women): Q3'                                                       , ['Health']    ], 
    ['SP.UWT.TFRT.Q4.ZS'   , 'Unmet need for family planning (total) (% of married women): Q4'                                                       , ['Health']    ], 
    ['SP.UWT.TFRT.Q5.ZS'   , 'Unmet need for family planning (total) (% of married women): Q5 (highest)'                                             , ['Health']    ], 
  ], 
}