export const HealthNutritionAndPopulationStatistics = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['HD.HCI.OVRL'         , 'Human Capital Index (HCI) (scale 0-1)'                                                                                          , null                                ], 
    ['HD.HCI.OVRL.FE'      , 'Human Capital Index (HCI), Female (scale 0-1)'                                                                                  , null                                ], 
    ['HD.HCI.OVRL.LB'      , 'Human Capital Index (HCI), Lower Bound (scale 0-1)'                                                                             , null                                ], 
    ['HD.HCI.OVRL.LB.FE'   , 'Human Capital Index (HCI), Female, Lower Bound (scale 0-1)'                                                                     , null                                ], 
    ['HD.HCI.OVRL.LB.MA'   , 'Human Capital Index (HCI), Male, Lower Bound (scale 0-1)'                                                                       , null                                ], 
    ['HD.HCI.OVRL.MA'      , 'Human Capital Index (HCI), Male (scale 0-1)'                                                                                    , null                                ], 
    ['HD.HCI.OVRL.UB'      , 'Human Capital Index (HCI), Upper Bound (scale 0-1)'                                                                             , null                                ], 
    ['HD.HCI.OVRL.UB.FE'   , 'Human Capital Index (HCI), Female, Upper Bound (scale 0-1)'                                                                     , null                                ], 
    ['HD.HCI.OVRL.UB.MA'   , 'Human Capital Index (HCI), Male, Upper Bound (scale 0-1)'                                                                       , null                                ], 
    ['NY.GNP.PCAP.CD'      , 'GNI per capita, Atlas method (current US$)'                                                                                     , ['Econ']                            ], 
    ['SE.ADT.1524.LT.FM.ZS', 'Literacy rate, youth (ages 15-24), gender parity index (GPI)'                                                                   , ['Edu', 'Gender', 'Social']         ], 
    ['SE.ADT.1524.LT.MA.ZS', 'Literacy rate, youth male (% of males ages 15-24)'                                                                              , ['Edu', 'Gender']                   ], 
    ['SE.ADT.1524.LT.ZS'   , 'Literacy rate, youth total (% of people ages 15-24)'                                                                            , ['Edu']                             ], 
    ['SE.ADT.LITR.FE.ZS'   , 'Literacy rate, adult female (% of females ages 15 and above)'                                                                   , ['Gender', 'Edu']                   ], 
    ['SE.ADT.LITR.MA.ZS'   , 'Literacy rate, adult male (% of males ages 15 and above)'                                                                       , ['Edu', 'Gender']                   ], 
    ['SE.ADT.LITR.ZS'      , 'Literacy rate, adult total (% of people ages 15 and above)'                                                                     , ['Edu']                             ], 
    ['SE.ENR.ORPH'         , 'Ratio of school attendance of orphans to school attendance of non-orphans ages 10-14'                                           , null                                ], 
    ['SE.PRM.CMPT.FE.ZS'   , 'Primary completion rate, female (% of relevant age group)'                                                                      , ['Edu', 'Gender']                   ], 
    ['SE.PRM.CMPT.MA.ZS'   , 'Primary completion rate, male (% of relevant age group)'                                                                        , ['Edu', 'Gender']                   ], 
    ['SE.PRM.CMPT.ZS'      , 'Primary completion rate, total (% of relevant age group)'                                                                       , ['Aid', 'Climate', 'Edu']           ], 
    ['SE.PRM.ENRR'         , 'School enrollment, primary (% gross)'                                                                                           , ['Edu']                             ], 
    ['SE.PRM.ENRR.FE'      , 'School enrollment, primary, female (% gross)'                                                                                   , ['Edu', 'Gender']                   ], 
    ['SE.PRM.ENRR.MA'      , 'School enrollment, primary, male (% gross)'                                                                                     , ['Edu', 'Gender']                   ], 
    ['SE.PRM.NENR'         , 'School enrollment, primary (% net)'                                                                                             , ['Edu']                             ], 
    ['SE.PRM.NENR.FE'      , 'School enrollment, primary, female (% net)'                                                                                     , ['Edu', 'Gender']                   ], 
    ['SE.PRM.NENR.MA'      , 'School enrollment, primary, male (% net)'                                                                                       , ['Edu', 'Gender']                   ], 
    ['SE.SEC.ENRR'         , 'School enrollment, secondary (% gross)'                                                                                         , ['Edu']                             ], 
    ['SE.SEC.ENRR.FE'      , 'School enrollment, secondary, female (% gross)'                                                                                 , ['Edu', 'Gender']                   ], 
    ['SE.SEC.ENRR.MA'      , 'School enrollment, secondary, male (% gross)'                                                                                   , ['Edu', 'Gender']                   ], 
    ['SE.SEC.NENR'         , 'School enrollment, secondary (% net)'                                                                                           , ['Edu']                             ], 
    ['SE.SEC.NENR.FE'      , 'School enrollment, secondary, female (% net)'                                                                                   , ['Edu', 'Gender']                   ], 
    ['SE.SEC.NENR.MA'      , 'School enrollment, secondary, male (% net)'                                                                                     , ['Edu', 'Gender']                   ], 
    ['SE.TER.ENRR'         , 'School enrollment, tertiary (% gross)'                                                                                          , ['Edu']                             ], 
    ['SE.TER.ENRR.FE'      , 'School enrollment, tertiary, female (% gross)'                                                                                  , ['Edu', 'Gender']                   ], 
    ['SE.XPD.TOTL.GD.ZS'   , 'Government expenditure on education, total (% of GDP)'                                                                          , ['Edu']                             ], 
    ['SH.ALC.PCAP.FE.LI'   , 'Total alcohol consumption per capita, female (liters of pure alcohol, projected estimates, female 15+ years of age)'            , ['Health']                          ], 
    ['SH.ALC.PCAP.LI'      , 'Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)'                           , ['Health']                          ], 
    ['SH.ALC.PCAP.MA.LI'   , 'Total alcohol consumption per capita, male (liters of pure alcohol, projected estimates, male 15+ years of age)'                , ['Health']                          ], 
    ['SH.ANM.ALLW.ZS'      , 'Prevalence of anemia among women of reproductive age (% of women ages 15-49)'                                                   , ['Health']                          ], 
    ['SH.ANM.CHLD.ZS'      , 'Prevalence of anemia among children (% of children under 5)'                                                                    , ['Health']                          ], 
    ['SH.ANM.NPRG.ZS'      , 'Prevalence of anemia among non-pregnant women (% of women ages 15-49)'                                                          , ['Health']                          ], 
    ['SH.CON.1524.FE.ZS'   , 'Condom use, population ages 15-24, female (% of females ages 15-24)'                                                            , ['Health', 'Gender']                ], 
    ['SH.CON.1524.MA.ZS'   , 'Condom use, population ages 15-24, male (% of males ages 15-24)'                                                                , ['Health', 'Gender']                ], 
    ['SH.CON.AIDS.FE.ZS'   , 'Condom use with non regular partner, % adults(15-49), female'                                                                   , null                                ], 
    ['SH.CON.AIDS.MA.ZS'   , 'Condom use with non regular partner, % adults(15-49), male'                                                                     , null                                ], 
    ['SH.DTH.0514'         , 'Number of deaths ages 5-14 years'                                                                                               , ['Health']                          ], 
    ['SH.DTH.COMM.ZS'      , 'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)'                          , ['Health']                          ], 
    ['SH.DTH.IMRT'         , 'Number of infant deaths'                                                                                                        , ['Health']                          ], 
    ['SH.DTH.INJR.ZS'      , 'Cause of death, by injury (% of total)'                                                                                         , ['Health']                          ], 
    ['SH.DTH.MORT'         , 'Number of under-five deaths'                                                                                                    , ['Health']                          ], 
    ['SH.DTH.NCOM.ZS'      , 'Cause of death, by non-communicable diseases (% of total)'                                                                      , ['Health']                          ], 
    ['SH.DTH.NMRT'         , 'Number of neonatal deaths'                                                                                                      , ['Health']                          ], 
    ['SH.DYN.0514'         , 'Probability of dying at age 5-14 years (per 1,000 children age 5)'                                                              , ['Health']                          ], 
    ['SH.DYN.AIDS'         , 'Adults (ages 15+) living with HIV'                                                                                              , null                                ], 
    ['SH.DYN.AIDS.DH'      , 'AIDS estimated deaths (UNAIDS estimates)'                                                                                       , null                                ], 
    ['SH.DYN.AIDS.FE.ZS'   , 'Women\'s share of population ages 15+ living with HIV (%)'                                                                      , ['Health', 'Gender']                ], 
    ['SH.DYN.AIDS.ZS'      , 'Prevalence of HIV, total (% of population ages 15-49)'                                                                          , ['Health', 'Aid']                   ], 
    ['SH.DYN.MORT'         , 'Mortality rate, under-5 (per 1,000 live births)'                                                                                , ['Health', 'Aid', 'Climate']        ], 
    ['SH.DYN.MORT.FE'      , 'Mortality rate, under-5, female (per 1,000 live births)'                                                                        , ['Health']                          ], 
    ['SH.DYN.MORT.MA'      , 'Mortality rate, under-5, male (per 1,000 live births)'                                                                          , ['Health']                          ], 
    ['SH.DYN.NCOM.FE.ZS'   , 'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70, female (%)'                                           , ['Health']                          ], 
    ['SH.DYN.NCOM.MA.ZS'   , 'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70, male (%)'                                             , ['Health']                          ], 
    ['SH.DYN.NCOM.ZS'      , 'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70 (%)'                                                   , ['Health']                          ], 
    ['SH.DYN.NMRT'         , 'Mortality rate, neonatal (per 1,000 live births)'                                                                               , ['Health']                          ], 
    ['SH.FPL.SATI.ZS'      , 'Demand for family planning satisfied by any methods (% of married women with demand for family planning)'                       , ['Gender']                          ], 
    ['SH.FPL.SATM.ZS'      , 'Demand for family planning satisfied by modern methods (% of married women with demand for family planning)'                    , ['Health']                          ], 
    ['SH.H2O.BASW.RU.ZS'   , 'People using at least basic drinking water services, rural (% of rural population)'                                             , ['Health', 'Env']                   ], 
    ['SH.H2O.BASW.UR.ZS'   , 'People using at least basic drinking water services, urban (% of urban population)'                                             , ['Health', 'Env']                   ], 
    ['SH.H2O.BASW.ZS'      , 'People using at least basic drinking water services (% of population)'                                                          , ['Health', 'Env']                   ], 
    ['SH.H2O.SMDW.RU.ZS'   , 'People using safely managed drinking water services, rural (% of rural population)'                                             , ['Health', 'Env']                   ], 
    ['SH.H2O.SMDW.UR.ZS'   , 'People using safely managed drinking water services, urban (% of urban population)'                                             , ['Health', 'Env']                   ], 
    ['SH.H2O.SMDW.ZS'      , 'People using safely managed drinking water services (% of population)'                                                          , ['Health', 'Env']                   ], 
    ['SH.HIV.0014'         , 'Children (0-14) living with HIV'                                                                                                , ['Health']                          ], 
    ['SH.HIV.1524.FE.ZS'   , 'Prevalence of HIV, female (% ages 15-24)'                                                                                       , ['Health', 'Gender', 'Social']      ], 
    ['SH.HIV.1524.KW.FE.ZS', 'Comprehensive correct knowledge of HIV/AIDS, ages 15-24, female (2 prevent ways and reject 3 misconceptions)'                   , null                                ], 
    ['SH.HIV.1524.KW.MA.ZS', 'Comprehensive correct knowledge of HIV/AIDS, ages 15-24, male (2 prevent ways and reject 3 misconceptions)'                     , null                                ], 
    ['SH.HIV.1524.MA.ZS'   , 'Prevalence of HIV, male (% ages 15-24)'                                                                                         , ['Health', 'Gender', 'Social']      ], 
    ['SH.HIV.ARTC.ZS'      , 'Antiretroviral therapy coverage (% of people living with HIV)'                                                                  , ['Health']                          ], 
    ['SH.HIV.INCD'         , 'Adults (ages 15+) newly infected with HIV'                                                                                      , ['Health']                          ], 
    ['SH.HIV.INCD.14'      , 'Children (ages 0-14) newly infected with HIV'                                                                                   , ['Health']                          ], 
    ['SH.HIV.INCD.TL'      , 'Adults (ages 15+) and children (ages 0-14) newly infected with HIV'                                                             , ['Health']                          ], 
    ['SH.HIV.INCD.ZS'      , 'Incidence of HIV (per 1,000 uninfected population ages 15-49)'                                                                  , ['Health']                          ], 
    ['SH.HIV.KNOW.FE.ZS'   , '% of females having comprehensive correct knowledge about HIV (2 prevent ways and reject 3 misconceptions)'                     , null                                ], 
    ['SH.HIV.KNOW.MA.ZS'   , 'Comprehensive correct knowledge of HIV/AIDS, ages 15-49, male (2 prevent ways and reject 3 misconceptions)'                     , null                                ], 
    ['SH.HIV.ORPH'         , 'Children orphaned by HIV/AIDS'                                                                                                  , null                                ], 
    ['SH.HIV.PMTC.ZS'      , 'Antiretroviral therapy coverage for PMTCT (% of pregnant women living with HIV)'                                                , ['Health']                          ], 
    ['SH.HIV.TOTL'         , 'Adults (ages 15+) and children (0-14 years) living with HIV'                                                                    , null                                ], 
    ['SH.IMM.HEPB'         , 'Immunization, HepB3 (% of one-year-old children)'                                                                               , ['Health']                          ], 
    ['SH.IMM.HIB3'         , 'Immunization, Hib3 (% of children ages 12-23 months)'                                                                           , null                                ], 
    ['SH.IMM.IBCG'         , 'Immunization, BCG (% of one-year-old children)'                                                                                 , null                                ], 
    ['SH.IMM.IDPT'         , 'Immunization, DPT (% of children ages 12-23 months)'                                                                            , ['Health']                          ], 
    ['SH.IMM.MEAS'         , 'Immunization, measles (% of children ages 12-23 months)'                                                                        , ['Health']                          ], 
    ['SH.IMM.POL3'         , 'Immunization, Pol3 (% of one-year-old children)'                                                                                , null                                ], 
    ['SH.MED.BEDS.ZS'      , 'Hospital beds (per 1,000 people)'                                                                                               , ['Health']                          ], 
    ['SH.MED.CMHW.P3'      , 'Community health workers (per 1,000 people)'                                                                                    , ['Health', 'Climate']               ], 
    ['SH.MED.NUMW.P3'      , 'Nurses and midwives (per 1,000 people)'                                                                                         , ['Health']                          ], 
    ['SH.MED.PHYS.ZS'      , 'Physicians (per 1,000 people)'                                                                                                  , ['Health']                          ], 
    ['SH.MED.SAOP.P5'      , 'Specialist surgical workforce (per 100,000 population)'                                                                         , ['Health']                          ], 
    ['SH.MLR.INCD.P3'      , 'Incidence of malaria (per 1,000 population at risk)'                                                                            , ['Health']                          ], 
    ['SH.MLR.IPTP.ZS'      , 'Intermittent preventive treatment (IPT) of malaria in pregnancy (% of pregnant women)'                                          , ['Health']                          ], 
    ['SH.MLR.NETS.ZS'      , 'Use of insecticide-treated bed nets (% of under-5 population)'                                                                  , ['Health']                          ], 
    ['SH.MLR.TRET.ZS'      , 'Children with fever receiving antimalarial drugs (% of children under age 5 with fever)'                                        , ['Health']                          ], 
    ['SH.MMR.DTHS'         , 'Number of maternal deaths'                                                                                                      , ['Health']                          ], 
    ['SH.MMR.LEVE'         , 'Length of paid maternity leave (days)'                                                                                          , ['Gender', 'Gender']                ], 
    ['SH.MMR.RISK'         , 'Lifetime risk of maternal death (1 in: rate varies by country)'                                                                 , ['Health', 'Gender']                ], 
    ['SH.MMR.RISK.ZS'      , 'Lifetime risk of maternal death (%)'                                                                                            , ['Health', 'Gender']                ], 
    ['SH.MMR.WAGE.ZS'      , 'Maternity leave benefits (% of wages paid)'                                                                                     , ['Gender']                          ], 
    ['SH.PRG.ANEM'         , 'Prevalence of anemia among pregnant women (%)'                                                                                  , ['Health']                          ], 
    ['SH.PRG.SYPH.ZS'      , 'Prevalence of syphilis (% of women attending antenatal care)'                                                                   , null                                ], 
    ['SH.PRV.SMOK'         , 'Smoking prevalence, total (ages 15+)'                                                                                           , ['Health']                          ], 
    ['SH.PRV.SMOK.FE'      , 'Smoking prevalence, females (% of adults)'                                                                                      , ['Health', 'Gender']                ], 
    ['SH.PRV.SMOK.MA'      , 'Smoking prevalence, males (% of adults)'                                                                                        , ['Health', 'Gender']                ], 
    ['SH.SGR.CRSK.ZS'      , 'Risk of catastrophic expenditure for surgical care (% of people at risk)'                                                       , ['Health']                          ], 
    ['SH.SGR.IRSK.ZS'      , 'Risk of impoverishing expenditure for surgical care (% of people at risk)'                                                      , ['Health']                          ], 
    ['SH.SGR.PROC.P5'      , 'Number of surgical procedures (per 100,000 population)'                                                                         , ['Health']                          ], 
    ['SH.STA.AIRP.FE.P5'   , 'Mortality rate attributed to household and ambient air pollution, age-standardized, female (per 100,000 female population)'     , ['Health']                          ], 
    ['SH.STA.AIRP.MA.P5'   , 'Mortality rate attributed to household and ambient air pollution, age-standardized, male (per 100,000 male population)'         , ['Health']                          ], 
    ['SH.STA.AIRP.P5'      , 'Mortality rate attributed to household and ambient air pollution, age-standardized (per 100,000 population)'                    , ['Health', 'Env']                   ], 
    ['SH.STA.ANV4.ZS'      , 'Pregnant women receiving prenatal care of at least four visits (% of pregnant women)'                                           , null                                ], 
    ['SH.STA.ANVC.ZS'      , 'Pregnant women receiving prenatal care (%)'                                                                                     , ['Health', 'Gender', 'Aid']         ], 
    ['SH.STA.ARIC.ZS'      , 'ARI treatment (% of children under 5 taken to a health provider)'                                                               , ['Health']                          ], 
    ['SH.STA.BASS.RU.ZS'   , 'People using at least basic sanitation services, rural (% of rural population)'                                                 , ['Health', 'Env']                   ], 
    ['SH.STA.BASS.UR.ZS'   , 'People using at least basic sanitation services, urban (% of urban population)'                                                 , ['Health', 'Env']                   ], 
    ['SH.STA.BASS.ZS'      , 'People using at least basic sanitation services (% of population)'                                                              , ['Health', 'Env']                   ], 
    ['SH.STA.BFED.ZS'      , 'Exclusive breastfeeding (% of children under 6 months)'                                                                         , ['Health']                          ], 
    ['SH.STA.BRTC.ZS'      , 'Births attended by skilled health staff (% of total)'                                                                           , ['Health', 'Gender']                ], 
    ['SH.STA.BRTW.ZS'      , 'Low-birthweight babies (% of births)'                                                                                           , ['Health']                          ], 
    ['SH.STA.DIAB.ZS'      , 'Diabetes prevalence (% of population ages 20 to 79)'                                                                            , ['Health']                          ], 
    ['SH.STA.HYGN.RU.ZS'   , 'People with basic handwashing facilities including soap and water, rural (% of rural population)'                               , ['Health', 'Env']                   ], 
    ['SH.STA.HYGN.UR.ZS'   , 'People with basic handwashing facilities including soap and water, urban (% of urban population)'                               , ['Health', 'Env']                   ], 
    ['SH.STA.HYGN.ZS'      , 'People with basic handwashing facilities including soap and water (% of population)'                                            , ['Health', 'Env']                   ], 
    ['SH.STA.IYCF.ZS'      , 'Infant and young child feeding practices, all 3 IYCF (% children ages 6-23 months)'                                             , null                                ], 
    ['SH.STA.MALN.FE.ZS'   , 'Prevalence of underweight, weight for age, female (% of children under 5)'                                                      , ['Health', 'Gender']                ], 
    ['SH.STA.MALN.MA.ZS'   , 'Prevalence of underweight, weight for age, male (% of children under 5)'                                                        , ['Health', 'Gender']                ], 
    ['SH.STA.MALN.ZS'      , 'Prevalence of underweight, weight for age (% of children under 5)'                                                              , ['Health', 'Climate']               ], 
    ['SH.STA.MALR'         , 'Malaria cases reported'                                                                                                         , null                                ], 
    ['SH.STA.MMRT'         , 'Maternal mortality ratio (modeled estimate, per 100,000 live births)'                                                           , ['Health', 'Gender', 'Aid']         ], 
    ['SH.STA.MMRT.NE'      , 'Maternal mortality ratio (national estimate, per 100,000 live births)'                                                          , ['Health', 'Gender']                ], 
    ['SH.STA.ODFC.RU.ZS'   , 'People practicing open defecation, rural (% of rural population)'                                                               , ['Health', 'Env']                   ], 
    ['SH.STA.ODFC.UR.ZS'   , 'People practicing open defecation, urban (% of urban population)'                                                               , ['Health', 'Env']                   ], 
    ['SH.STA.ODFC.ZS'      , 'People practicing open defecation (% of population)'                                                                            , ['Health', 'Env']                   ], 
    ['SH.STA.ORCF.ZS'      , 'Diarrhea treatment (% of children under 5 receiving oral rehydration and continued feeding)'                                    , ['Health']                          ], 
    ['SH.STA.ORTH'         , 'Diarrhea treatment (% of children under 5 who received ORS packet)'                                                             , ['Health']                          ], 
    ['SH.STA.OWAD.FE.ZS'   , 'Prevalence of overweight, female (% of female adults)'                                                                          , null                                ], 
    ['SH.STA.OWAD.MA.ZS'   , 'Prevalence of overweight, male (% of male adults)'                                                                              , null                                ], 
    ['SH.STA.OWAD.ZS'      , 'Prevalence of overweight (% of adults)'                                                                                         , null                                ], 
    ['SH.STA.OWGH.FE.ZS'   , 'Prevalence of overweight, weight for height, female (% of children under 5)'                                                    , ['Health']                          ], 
    ['SH.STA.OWGH.MA.ZS'   , 'Prevalence of overweight, weight for height, male (% of children under 5)'                                                      , ['Health']                          ], 
    ['SH.STA.OWGH.ZS'      , 'Prevalence of overweight, weight for height (% of children under 5)'                                                            , ['Health']                          ], 
    ['SH.STA.PNVC.ZS'      , 'Postnatal care coverage (% mothers)'                                                                                            , null                                ], 
    ['SH.STA.POIS.P5'      , 'Mortality rate attributed to unintentional poisoning (per 100,000 population)'                                                  , ['Health', 'Env']                   ], 
    ['SH.STA.POIS.P5.FE'   , 'Mortality rate attributed to unintentional poisoning, female (per 100,000 female population)'                                   , ['Health', 'Env']                   ], 
    ['SH.STA.POIS.P5.MA'   , 'Mortality rate attributed to unintentional poisoning, male (per 100,000 male population)'                                       , ['Health', 'Env']                   ], 
    ['SH.STA.SMSS.RU.ZS'   , 'People using safely managed sanitation services, rural (% of rural population)'                                                 , ['Health', 'Env']                   ], 
    ['SH.STA.SMSS.UR.ZS'   , 'People using safely managed sanitation services, urban (% of urban population)'                                                 , ['Health', 'Env']                   ], 
    ['SH.STA.SMSS.ZS'      , 'People using safely managed sanitation services (% of population)'                                                              , ['Health', 'Env']                   ], 
    ['SH.STA.STNT.FE.ZS'   , 'Prevalence of stunting, height for age, female (% of children under 5)'                                                         , ['Health']                          ], 
    ['SH.STA.STNT.MA.ZS'   , 'Prevalence of stunting, height for age, male (% of children under 5)'                                                           , ['Health']                          ], 
    ['SH.STA.STNT.ZS'      , 'Prevalence of stunting, height for age (% of children under 5)'                                                                 , ['Health', 'Aid']                   ], 
    ['SH.STA.SUIC.FE.P5'   , 'Suicide mortality rate, female (per 100,000 female population)'                                                                 , ['Health']                          ], 
    ['SH.STA.SUIC.MA.P5'   , 'Suicide mortality rate, male (per 100,000 male population)'                                                                     , ['Health']                          ], 
    ['SH.STA.SUIC.P5'      , 'Suicide mortality rate (per 100,000 population)'                                                                                , ['Health']                          ], 
    ['SH.STA.TRAF.P5'      , 'Mortality caused by road traffic injury (per 100,000 people)'                                                                   , ['Health', 'Urban']                 ], 
    ['SH.STA.WASH.P5'      , 'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene (per 100,000 population)'                      , ['Health', 'Env']                   ], 
    ['SH.STA.WAST.FE.ZS'   , 'Prevalence of wasting, weight for height, female (% of children under 5)'                                                       , ['Health']                          ], 
    ['SH.STA.WAST.MA.ZS'   , 'Prevalence of wasting, weight for height, male (% of children under 5)'                                                         , ['Health']                          ], 
    ['SH.STA.WAST.ZS'      , 'Prevalence of wasting, weight for height (% of children under 5)'                                                               , ['Health']                          ], 
    ['SH.SVR.WAST.FE.ZS'   , 'Prevalence of severe wasting, weight for height, female (% of children under 5)'                                                , ['Health']                          ], 
    ['SH.SVR.WAST.MA.ZS'   , 'Prevalence of severe wasting, weight for height, male (% of children under 5)'                                                  , ['Health']                          ], 
    ['SH.SVR.WAST.ZS'      , 'Prevalence of severe wasting, weight for height (% of children under 5)'                                                        , ['Health']                          ], 
    ['SH.TBS.CURE.ZS'      , 'Tuberculosis treatment success rate (% of new cases)'                                                                           , ['Health']                          ], 
    ['SH.TBS.DTEC.ZS'      , 'Tuberculosis case detection rate (%, all forms)'                                                                                , ['Health']                          ], 
    ['SH.TBS.INCD'         , 'Incidence of tuberculosis (per 100,000 people)'                                                                                 , ['Health', 'Aid']                   ], 
    ['SH.TBS.MORT'         , 'Tuberculosis death rate (per 100,000 people)'                                                                                   , null                                ], 
    ['SH.UHC.NOP1.CG'      , 'Increase in poverty gap at $1.90 ($ 2011 PPP) poverty line due to out-of-pocket health care expenditure (USD)'                  , ['Health']                          ], 
    ['SH.UHC.NOP1.TO'      , 'Number of people pushed below the $1.90 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure'                     , ['Health']                          ], 
    ['SH.UHC.NOP1.ZG'      , 'Increase in poverty gap at $1.90 ($ 2011 PPP) poverty line due to out-of-pocket health care expenditure (% of poverty line)'    , ['Health']                          ], 
    ['SH.UHC.NOP1.ZS'      , 'Proportion of population pushed below the $1.90 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure (%)'         , ['Health']                          ], 
    ['SH.UHC.NOP2.CG'      , 'Increase in poverty gap at $3.20 ($ 2011 PPP) poverty line due to out-of-pocket health care expenditure (USD)'                  , ['Health']                          ], 
    ['SH.UHC.NOP2.TO'      , 'Number of people pushed below the $3.20 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure'                     , ['Health']                          ], 
    ['SH.UHC.NOP2.ZG'      , 'Increase in poverty gap at $3.20 ($ 2011 PPP) poverty line due to out-of-pocket health care expenditure (% of poverty line)'    , ['Health']                          ], 
    ['SH.UHC.NOP2.ZS'      , 'Proportion of population pushed below the $3.20 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure (%)'         , ['Health']                          ], 
    ['SH.UHC.OOPC.10.TO'   , 'Number of people spending more than 10% of household consumption or income on out-of-pocket health care expenditure'            , ['Health']                          ], 
    ['SH.UHC.OOPC.10.ZS'   , 'Proportion of population spending more than 10% of household consumption or income on out-of-pocket health care expenditure (%)', ['Health']                          ], 
    ['SH.UHC.OOPC.25.TO'   , 'Number of people spending more than 25% of household consumption or income on out-of-pocket health care expenditure'            , ['Health']                          ], 
    ['SH.UHC.OOPC.25.ZS'   , 'Proportion of population spending more than 25% of household consumption or income on out-of-pocket health care expenditure (%)', ['Health']                          ], 
    ['SH.UHC.SRVS.CV.XD'   , 'UHC service coverage index'                                                                                                     , ['Health']                          ], 
    ['SH.VAC.TTNS.ZS'      , 'Newborns protected against tetanus (%)'                                                                                         , ['Health']                          ], 
    ['SH.XPD.CHEX.GD.ZS'   , 'Current health expenditure (% of GDP)'                                                                                          , ['Health']                          ], 
    ['SH.XPD.CHEX.PC.CD'   , 'Current health expenditure per capita (current US$)'                                                                            , ['Health']                          ], 
    ['SH.XPD.CHEX.PP.CD'   , 'Current health expenditure per capita, PPP (current international $)'                                                           , ['Health']                          ], 
    ['SH.XPD.EHEX.CH.ZS'   , 'External health expenditure (% of current health expenditure)'                                                                  , ['Health']                          ], 
    ['SH.XPD.EHEX.EH.ZS'   , 'External health expenditure channeled through government (% of external health expenditure)'                                    , null                                ], 
    ['SH.XPD.EHEX.PC.CD'   , 'External health expenditure per capita (current US$)'                                                                           , ['Health']                          ], 
    ['SH.XPD.EHEX.PP.CD'   , 'External health expenditure per capita, PPP (current international $)'                                                          , ['Health']                          ], 
    ['SH.XPD.GHED.CH.ZS'   , 'Domestic general government health expenditure (% of current health expenditure)'                                               , ['Health']                          ], 
    ['SH.XPD.GHED.GD.ZS'   , 'Domestic general government health expenditure (% of GDP)'                                                                      , ['Health']                          ], 
    ['SH.XPD.GHED.GE.ZS'   , 'Domestic general government health expenditure (% of general government expenditure)'                                           , ['Health']                          ], 
    ['SH.XPD.GHED.PC.CD'   , 'Domestic general government health expenditure per capita (current US$)'                                                        , ['Health']                          ], 
    ['SH.XPD.GHED.PP.CD'   , 'Domestic general government health expenditure per capita, PPP (current international $)'                                       , ['Health']                          ], 
    ['SH.XPD.KHEX.GD.ZS'   , 'Capital health expenditure (% of GDP)'                                                                                          , null                                ], 
    ['SH.XPD.OOPC.CH.ZS'   , 'Out-of-pocket expenditure (% of current health expenditure)'                                                                    , ['Health']                          ], 
    ['SH.XPD.OOPC.PC.CD'   , 'Out-of-pocket expenditure per capita (current US$)'                                                                             , ['Health']                          ], 
    ['SH.XPD.OOPC.PP.CD'   , 'Out-of-pocket expenditure per capita, PPP (current international $)'                                                            , ['Health']                          ], 
    ['SH.XPD.PVTD.CH.ZS'   , 'Domestic private health expenditure (% of current health expenditure)'                                                          , ['Health']                          ], 
    ['SH.XPD.PVTD.PC.CD'   , 'Domestic private health expenditure per capita (current US$)'                                                                   , ['Health']                          ], 
    ['SH.XPD.PVTD.PP.CD'   , 'Domestic private health expenditure per capita, PPP (current international $)'                                                  , ['Health']                          ], 
    ['SI.POV.NAHC'         , 'Poverty headcount ratio at national poverty lines (% of population)'                                                            , ['Poverty']                         ], 
    ['SI.POV.RUHC'         , 'Rural poverty headcount ratio at national poverty lines (% of rural population)'                                                , ['AgriRural', 'Poverty']            ], 
    ['SI.POV.URHC'         , 'Urban poverty headcount ratio at national poverty lines (% of urban population)'                                                , ['Poverty', 'Urban']                ], 
    ['SL.EMP.INSV.FE.ZS'   , 'Share of women in wage employment in the nonagricultural sector (% of total nonagricultural employment)'                        , ['Labor', 'Gender', 'Social']       ], 
    ['SL.TLF.TOTL.FE.ZS'   , 'Labor force, female (% of total labor force)'                                                                                   , ['Edu', 'Labor', 'Gender']          ], 
    ['SL.TLF.TOTL.IN'      , 'Labor force, total'                                                                                                             , ['Edu', 'Labor']                    ], 
    ['SL.UEM.TOTL.FE.ZS'   , 'Unemployment, female (% of female labor force) (modeled ILO estimate)'                                                          , ['Edu', 'Labor', 'Gender', 'Social']], 
    ['SL.UEM.TOTL.MA.ZS'   , 'Unemployment, male (% of male labor force) (modeled ILO estimate)'                                                              , ['Edu', 'Labor', 'Gender', 'Social']], 
    ['SL.UEM.TOTL.ZS'      , 'Unemployment, total (% of total labor force) (modeled ILO estimate)'                                                            , ['Edu', 'Labor']                    ], 
    ['SM.POP.NETM'         , 'Net migration'                                                                                                                  , ['Fin', 'Health', 'Aid']            ], 
    ['SN.ITK.DEFC'         , 'Number of people who are undernourished'                                                                                        , null                                ], 
    ['SN.ITK.DEFC.ZS'      , 'Prevalence of undernourishment (% of population)'                                                                               , ['Health']                          ], 
    ['SN.ITK.SALT.ZS'      , 'Consumption of iodized salt (% of households)'                                                                                  , ['Health']                          ], 
    ['SN.ITK.VITA.ZS'      , 'Vitamin A supplementation coverage rate (% of children ages 6-59 months)'                                                       , ['Health']                          ], 
    ['SP.ADO.TFRT'         , 'Adolescent fertility rate (births per 1,000 women ages 15-19)'                                                                  , ['Health', 'Gender', 'Social']      ], 
    ['SP.DYN.AMRT.FE'      , 'Mortality rate, adult, female (per 1,000 female adults)'                                                                        , ['Health', 'Gender']                ], 
    ['SP.DYN.AMRT.MA'      , 'Mortality rate, adult, male (per 1,000 male adults)'                                                                            , ['Health', 'Gender']                ], 
    ['SP.DYN.CBRT.IN'      , 'Birth rate, crude (per 1,000 people)'                                                                                           , ['Health']                          ], 
    ['SP.DYN.CDRT.IN'      , 'Death rate, crude (per 1,000 people)'                                                                                           , ['Health']                          ], 
    ['SP.DYN.CONM.ZS'      , 'Contraceptive prevalence, modern methods (% of women ages 15-49)'                                                               , ['Health']                          ], 
    ['SP.DYN.CONU.ZS'      , 'Contraceptive prevalence, any methods (% of women ages 15-49)'                                                                  , ['Health', 'Gender']                ], 
    ['SP.DYN.IMRT.FE.IN'   , 'Mortality rate, infant, female (per 1,000 live births)'                                                                         , ['Health']                          ], 
    ['SP.DYN.IMRT.IN'      , 'Mortality rate, infant (per 1,000 live births)'                                                                                 , ['Health']                          ], 
    ['SP.DYN.IMRT.MA.IN'   , 'Mortality rate, infant, male (per 1,000 live births)'                                                                           , ['Health']                          ], 
    ['SP.DYN.LE00.FE.IN'   , 'Life expectancy at birth, female (years)'                                                                                       , ['Health', 'Gender', 'Social']      ], 
    ['SP.DYN.LE00.IN'      , 'Life expectancy at birth, total (years)'                                                                                        , ['Health']                          ], 
    ['SP.DYN.LE00.MA.IN'   , 'Life expectancy at birth, male (years)'                                                                                         , ['Health', 'Gender', 'Social']      ], 
    ['SP.DYN.SMAM.FE'      , 'Age at first marriage, female'                                                                                                  , ['Gender']                          ], 
    ['SP.DYN.SMAM.MA'      , 'Age at first marriage, male'                                                                                                    , ['Gender']                          ], 
    ['SP.DYN.TFRT.IN'      , 'Fertility rate, total (births per woman)'                                                                                       , ['Health', 'Gender']                ], 
    ['SP.DYN.TO65.FE.ZS'   , 'Survival to age 65, female (% of cohort)'                                                                                       , ['Health', 'Gender']                ], 
    ['SP.DYN.TO65.MA.ZS'   , 'Survival to age 65, male (% of cohort)'                                                                                         , ['Health', 'Gender']                ], 
    ['SP.DYN.WFRT'         , 'Wanted fertility rate (births per woman)'                                                                                       , ['Health', 'Gender']                ], 
    ['SP.HOU.FEMA.ZS'      , 'Female headed households (% of households with a female head)'                                                                  , ['Health', 'Gender']                ], 
    ['SP.M15.2024.FE.ZS'   , 'Women who were first married by age 15 (% of women ages 20-24)'                                                                 , ['Health', 'Gender']                ], 
    ['SP.M18.2024.FE.ZS'   , 'Women who were first married by age 18 (% of women ages 20-24)'                                                                 , ['Health', 'Gender']                ], 
    ['SP.MTR.1519.ZS'      , 'Teenage mothers (% of women ages 15-19 who have had children or are currently pregnant)'                                        , ['Health', 'Gender']                ], 
    ['SP.POP.0004.FE'      , 'Population ages 00-04, female'                                                                                                  , null                                ], 
    ['SP.POP.0004.FE.5Y'   , 'Population ages 00-04, female (% of female population)'                                                                         , ['Health']                          ], 
    ['SP.POP.0004.MA'      , 'Population ages 00-04, male'                                                                                                    , null                                ], 
    ['SP.POP.0004.MA.5Y'   , 'Population ages 00-04, male (% of male population)'                                                                             , ['Health']                          ], 
    ['SP.POP.0014.FE.IN'   , 'Population ages 0-14, female'                                                                                                   , ['Health']                          ], 
    ['SP.POP.0014.FE.ZS'   , 'Population ages 0-14, female (% of female population)'                                                                          , ['Health']                          ], 
    ['SP.POP.0014.MA.IN'   , 'Population ages 0-14, male'                                                                                                     , ['Health']                          ], 
    ['SP.POP.0014.MA.ZS'   , 'Population ages 0-14, male (% of male population)'                                                                              , ['Health']                          ], 
    ['SP.POP.0014.TO'      , 'Population ages 0-14, total'                                                                                                    , ['Health']                          ], 
    ['SP.POP.0014.TO.ZS'   , 'Population ages 0-14 (% of total population)'                                                                                   , ['Edu', 'Health']                   ], 
    ['SP.POP.0509.FE'      , 'Population ages 05-09, female'                                                                                                  , null                                ], 
    ['SP.POP.0509.FE.5Y'   , 'Population ages 05-09, female (% of female population)'                                                                         , ['Health']                          ], 
    ['SP.POP.0509.MA'      , 'Population ages 05-09, male'                                                                                                    , null                                ], 
    ['SP.POP.0509.MA.5Y'   , 'Population ages 05-09, male (% of male population)'                                                                             , ['Health']                          ], 
    ['SP.POP.1014.FE'      , 'Female population 10-14'                                                                                                        , null                                ], 
    ['SP.POP.1014.FE.5Y'   , 'Population ages 10-14, female (% of female population)'                                                                         , ['Health']                          ], 
    ['SP.POP.1014.MA'      , 'Male population 10-14'                                                                                                          , null                                ], 
    ['SP.POP.1014.MA.5Y'   , 'Population ages 10-14, male (% of male population)'                                                                             , ['Health']                          ], 
    ['SP.POP.1519.FE'      , 'Female population 15-19'                                                                                                        , null                                ], 
    ['SP.POP.1519.FE.5Y'   , 'Population ages 15-19, female (% of female population)'                                                                         , ['Health']                          ], 
    ['SP.POP.1519.MA'      , 'Male population 15-19'                                                                                                          , null                                ], 
    ['SP.POP.1519.MA.5Y'   , 'Population ages 15-19, male (% of male population)'                                                                             , ['Health']                          ], 
    ['SP.POP.1564.FE.IN'   , 'Population ages 15-64, female'                                                                                                  , ['Health']                          ], 
    ['SP.POP.1564.FE.ZS'   , 'Population ages 15-64, female (% of female population)'                                                                         , ['Health']                          ], 
    ['SP.POP.1564.MA.IN'   , 'Population ages 15-64, male'                                                                                                    , ['Health']                          ], 
    ['SP.POP.1564.MA.ZS'   , 'Population ages 15-64, male (% of male population)'                                                                             , ['Health']                          ], 
    ['SP.POP.1564.TO'      , 'Population ages 15-64, total'                                                                                                   , ['Health']                          ], 
    ['SP.POP.1564.TO.ZS'   , 'Population ages 15-64 (% of total population)'                                                                                  , ['Edu', 'Health']                   ], 
    ['SP.POP.2024.FE'      , 'Female population 20-24'                                                                                                        , null                                ], 
    ['SP.POP.2024.FE.5Y'   , 'Population ages 20-24, female (% of female population)'                                                                         , ['Health']                          ], 
    ['SP.POP.2024.MA'      , 'Male population 20-24'                                                                                                          , null                                ], 
    ['SP.POP.2024.MA.5Y'   , 'Population ages 20-24, male (% of male population)'                                                                             , ['Health']                          ], 
    ['SP.POP.2529.FE'      , 'Female population 25-29'                                                                                                        , null                                ], 
    ['SP.POP.2529.FE.5Y'   , 'Population ages 25-29, female (% of female population)'                                                                         , ['Health']                          ], 
    ['SP.POP.2529.MA'      , 'Male population 25-29'                                                                                                          , null                                ], 
    ['SP.POP.2529.MA.5Y'   , 'Population ages 25-29, male (% of male population)'                                                                             , ['Health']                          ], 
    ['SP.POP.3034.FE'      , 'Female population 30-34'                                                                                                        , null                                ], 
    ['SP.POP.3034.FE.5Y'   , 'Population ages 30-34, female (% of female population)'                                                                         , ['Health']                          ], 
    ['SP.POP.3034.MA'      , 'Male population 30-34'                                                                                                          , null                                ], 
    ['SP.POP.3034.MA.5Y'   , 'Population ages 30-34, male (% of male population)'                                                                             , ['Health']                          ], 
    ['SP.POP.3539.FE'      , 'Female population 35-39'                                                                                                        , null                                ], 
    ['SP.POP.3539.FE.5Y'   , 'Population ages 35-39, female (% of female population)'                                                                         , ['Health']                          ], 
    ['SP.POP.3539.MA'      , 'Male population 35-39'                                                                                                          , null                                ], 
    ['SP.POP.3539.MA.5Y'   , 'Population ages 35-39, male (% of male population)'                                                                             , ['Health']                          ], 
    ['SP.POP.4044.FE'      , 'Female population 40-44'                                                                                                        , null                                ], 
    ['SP.POP.4044.FE.5Y'   , 'Population ages 40-44, female (% of female population)'                                                                         , ['Health']                          ], 
    ['SP.POP.4044.MA'      , 'Male population 40-44'                                                                                                          , null                                ], 
    ['SP.POP.4044.MA.5Y'   , 'Population ages 40-44, male (% of male population)'                                                                             , ['Health']                          ], 
    ['SP.POP.4549.FE'      , 'Female population 45-49'                                                                                                        , null                                ], 
    ['SP.POP.4549.FE.5Y'   , 'Population ages 45-49, female (% of female population)'                                                                         , ['Health']                          ], 
    ['SP.POP.4549.MA'      , 'Male population 45-49'                                                                                                          , null                                ], 
    ['SP.POP.4549.MA.5Y'   , 'Population ages 45-49, male (% of male population)'                                                                             , ['Health']                          ], 
    ['SP.POP.5054.FE'      , 'Female population 50-54'                                                                                                        , null                                ], 
    ['SP.POP.5054.FE.5Y'   , 'Population ages 50-54, female (% of female population)'                                                                         , ['Health']                          ], 
    ['SP.POP.5054.MA'      , 'Male population 50-54'                                                                                                          , null                                ], 
    ['SP.POP.5054.MA.5Y'   , 'Population ages 50-54, male (% of male population)'                                                                             , ['Health']                          ], 
    ['SP.POP.5559.FE'      , 'Female population 55-59'                                                                                                        , null                                ], 
    ['SP.POP.5559.FE.5Y'   , 'Population ages 55-59, female (% of female population)'                                                                         , ['Health']                          ], 
    ['SP.POP.5559.MA'      , 'Male population 55-59'                                                                                                          , null                                ], 
    ['SP.POP.5559.MA.5Y'   , 'Population ages 55-59, male (% of male population)'                                                                             , ['Health']                          ], 
    ['SP.POP.6064.FE'      , 'Female population 60-64'                                                                                                        , null                                ], 
    ['SP.POP.6064.FE.5Y'   , 'Population ages 60-64, female (% of female population)'                                                                         , ['Health']                          ], 
    ['SP.POP.6064.MA'      , 'Male population 60-64'                                                                                                          , null                                ], 
    ['SP.POP.6064.MA.5Y'   , 'Population ages 60-64, male (% of male population)'                                                                             , ['Health']                          ], 
    ['SP.POP.6569.FE'      , 'Female population 65-69'                                                                                                        , null                                ], 
    ['SP.POP.6569.FE.5Y'   , 'Population ages 65-69, female (% of female population)'                                                                         , ['Health']                          ], 
    ['SP.POP.6569.MA'      , 'Male population 65-69'                                                                                                          , null                                ], 
    ['SP.POP.6569.MA.5Y'   , 'Population ages 65-69, male (% of male population)'                                                                             , ['Health']                          ], 
    ['SP.POP.65UP.FE.IN'   , 'Population ages 65 and above, female'                                                                                           , ['Health']                          ], 
    ['SP.POP.65UP.FE.ZS'   , 'Population ages 65 and above, female (% of female population)'                                                                  , ['Health']                          ], 
    ['SP.POP.65UP.MA.IN'   , 'Population ages 65 and above, male'                                                                                             , ['Health']                          ], 
    ['SP.POP.65UP.MA.ZS'   , 'Population ages 65 and above, male (% of male population)'                                                                      , ['Health']                          ], 
    ['SP.POP.65UP.TO'      , 'Population ages 65 and above, total'                                                                                            , ['Health']                          ], 
    ['SP.POP.65UP.TO.ZS'   , 'Population ages 65 and above (% of total population)'                                                                           , ['Health']                          ], 
    ['SP.POP.7074.FE'      , 'Female population 70-74 '                                                                                                       , null                                ], 
    ['SP.POP.7074.FE.5Y'   , 'Population ages 70-74, female (% of female population)'                                                                         , ['Health']                          ], 
    ['SP.POP.7074.MA'      , 'Male population 70-74'                                                                                                          , null                                ], 
    ['SP.POP.7074.MA.5Y'   , 'Population ages 70-74, male (% of male population)'                                                                             , ['Health']                          ], 
    ['SP.POP.7579.FE'      , 'Female population 75-79'                                                                                                        , null                                ], 
    ['SP.POP.7579.FE.5Y'   , 'Population ages 75-79, female (% of female population)'                                                                         , ['Health']                          ], 
    ['SP.POP.7579.MA'      , 'Male population 75-79'                                                                                                          , null                                ], 
    ['SP.POP.7579.MA.5Y'   , 'Population ages 75-79, male (% of male population)'                                                                             , ['Health']                          ], 
    ['SP.POP.80UP.FE'      , 'Female population 80+'                                                                                                          , ['Health']                          ], 
    ['SP.POP.80UP.FE.5Y'   , 'Population ages 80 and above, female (% of female population)'                                                                  , ['Health']                          ], 
    ['SP.POP.80UP.MA'      , 'Male population 80+ '                                                                                                           , null                                ], 
    ['SP.POP.80UP.MA.5Y'   , 'Population ages 80 and above, male (% of male population)'                                                                      , ['Health']                          ], 
    ['SP.POP.AG00.FE.IN'   , 'Age population, age 00, female, interpolated'                                                                                   , ['Gender']                          ], 
    ['SP.POP.AG00.MA.IN'   , 'Age population, age 00, male, interpolated'                                                                                     , ['Gender']                          ], 
    ['SP.POP.AG01.FE.IN'   , 'Age population, age 01, female, interpolated'                                                                                   , ['Gender']                          ], 
    ['SP.POP.AG01.MA.IN'   , 'Age population, age 01, male, interpolated'                                                                                     , ['Gender']                          ], 
    ['SP.POP.AG02.FE.IN'   , 'Age population, age 02, female, interpolated'                                                                                   , ['Gender']                          ], 
    ['SP.POP.AG02.MA.IN'   , 'Age population, age 02, male, interpolated'                                                                                     , ['Gender']                          ], 
    ['SP.POP.AG03.FE.IN'   , 'Age population, age 03, female, interpolated'                                                                                   , ['Gender']                          ], 
    ['SP.POP.AG03.MA.IN'   , 'Age population, age 03, male, interpolated'                                                                                     , ['Gender']                          ], 
    ['SP.POP.AG04.FE.IN'   , 'Age population, age 04, female, interpolated'                                                                                   , ['Gender']                          ], 
    ['SP.POP.AG04.MA.IN'   , 'Age population, age 04, male, interpolated'                                                                                     , ['Gender']                          ], 
    ['SP.POP.AG05.FE.IN'   , 'Age population, age 05, female, interpolated'                                                                                   , ['Gender']                          ], 
    ['SP.POP.AG05.MA.IN'   , 'Age population, age 05, male, interpolated'                                                                                     , ['Gender']                          ], 
    ['SP.POP.AG06.FE.IN'   , 'Age population, age 06, female, interpolated'                                                                                   , null                                ], 
    ['SP.POP.AG06.MA.IN'   , 'Age population, age 06, male, interpolated'                                                                                     , null                                ], 
    ['SP.POP.AG07.FE.IN'   , 'Age population, age 07, female, interpolated'                                                                                   , null                                ], 
    ['SP.POP.AG07.MA.IN'   , 'Age population, age 07, male, interpolated'                                                                                     , null                                ], 
    ['SP.POP.AG08.FE.IN'   , 'Age population, age 08, female, interpolated'                                                                                   , null                                ], 
    ['SP.POP.AG08.MA.IN'   , 'Age population, age 08, male, interpolated'                                                                                     , null                                ], 
    ['SP.POP.AG09.FE.IN'   , 'Age population, age 09, female, interpolated'                                                                                   , null                                ], 
    ['SP.POP.AG09.MA.IN'   , 'Age population, age 09, male, interpolated'                                                                                     , null                                ], 
    ['SP.POP.AG10.FE.IN'   , 'Age population, age 10, female, interpolated'                                                                                   , null                                ], 
    ['SP.POP.AG10.MA.IN'   , 'Age population, age 10, male, interpolated'                                                                                     , null                                ], 
    ['SP.POP.AG11.FE.IN'   , 'Age population, age 11, female, interpolated'                                                                                   , null                                ], 
    ['SP.POP.AG11.MA.IN'   , 'Age population, age 11, male, interpolated'                                                                                     , null                                ], 
    ['SP.POP.AG12.FE.IN'   , 'Age population, age 12, female, interpolated'                                                                                   , null                                ], 
    ['SP.POP.AG12.MA.IN'   , 'Age population, age 12, male, interpolated'                                                                                     , null                                ], 
    ['SP.POP.AG13.FE.IN'   , 'Age population, age 13, female, interpolated'                                                                                   , null                                ], 
    ['SP.POP.AG13.MA.IN'   , 'Age population, age 13, male, interpolated'                                                                                     , null                                ], 
    ['SP.POP.AG14.FE.IN'   , 'Age population, age 14, female, interpolated'                                                                                   , null                                ], 
    ['SP.POP.AG14.MA.IN'   , 'Age population, age 14, male, interpolated'                                                                                     , null                                ], 
    ['SP.POP.AG15.FE.IN'   , 'Age population, age 15, female, interpolated'                                                                                   , null                                ], 
    ['SP.POP.AG15.MA.IN'   , 'Age population, age 15, male, interpolated'                                                                                     , null                                ], 
    ['SP.POP.AG16.FE.IN'   , 'Age population, age 16, female, interpolated'                                                                                   , null                                ], 
    ['SP.POP.AG16.MA.IN'   , 'Age population, age 16, male, interpolated'                                                                                     , null                                ], 
    ['SP.POP.AG17.FE.IN'   , 'Age population, age 17, female, interpolated'                                                                                   , null                                ], 
    ['SP.POP.AG17.MA.IN'   , 'Age population, age 17, male, interpolated'                                                                                     , null                                ], 
    ['SP.POP.AG18.FE.IN'   , 'Age population, age 18, female, interpolated'                                                                                   , null                                ], 
    ['SP.POP.AG18.MA.IN'   , 'Age population, age 18, male, interpolated'                                                                                     , null                                ], 
    ['SP.POP.AG19.FE.IN'   , 'Age population, age 19, female, interpolated'                                                                                   , null                                ], 
    ['SP.POP.AG19.MA.IN'   , 'Age population, age 19, male, interpolated'                                                                                     , null                                ], 
    ['SP.POP.AG20.FE.IN'   , 'Age population, age 20, female, interpolated'                                                                                   , null                                ], 
    ['SP.POP.AG20.MA.IN'   , 'Age population, age 20, male, interpolated'                                                                                     , null                                ], 
    ['SP.POP.AG21.FE.IN'   , 'Age population, age 21, female, interpolated'                                                                                   , null                                ], 
    ['SP.POP.AG21.MA.IN'   , 'Age population, age 21, male, interpolated'                                                                                     , null                                ], 
    ['SP.POP.AG22.FE.IN'   , 'Age population, age 22, female, interpolated'                                                                                   , null                                ], 
    ['SP.POP.AG22.MA.IN'   , 'Age population, age 22, male, interpolated'                                                                                     , null                                ], 
    ['SP.POP.AG23.FE.IN'   , 'Age population, age 23, female, interpolated'                                                                                   , null                                ], 
    ['SP.POP.AG23.MA.IN'   , 'Age population, age 23, male, interpolated'                                                                                     , null                                ], 
    ['SP.POP.AG24.FE.IN'   , 'Age population, age 24, female, interpolated'                                                                                   , null                                ], 
    ['SP.POP.AG24.MA.IN'   , 'Age population, age 24, male, interpolated'                                                                                     , null                                ], 
    ['SP.POP.AG25.FE.IN'   , 'Age population, age 25, female, interpolated'                                                                                   , null                                ], 
    ['SP.POP.AG25.MA.IN'   , 'Age population, age 25, male, interpolated'                                                                                     , null                                ], 
    ['SP.POP.BRTH.MF'      , 'Sex ratio at birth (male births per female births)'                                                                             , ['Health']                          ], 
    ['SP.POP.DPND'         , 'Age dependency ratio (% of working-age population)'                                                                             , ['Health']                          ], 
    ['SP.POP.DPND.OL'      , 'Age dependency ratio, old (% of working-age population)'                                                                        , ['Health']                          ], 
    ['SP.POP.DPND.YG'      , 'Age dependency ratio, young (% of working-age population)'                                                                      , ['Health']                          ], 
    ['SP.POP.GROW'         , 'Population growth (annual %)'                                                                                                   , ['Climate', 'Health']               ], 
    ['SP.POP.TOTL'         , 'Population, total'                                                                                                              , ['Climate', 'Health']               ], 
    ['SP.POP.TOTL.FE.IN'   , 'Population, female'                                                                                                             , ['Health']                          ], 
    ['SP.POP.TOTL.FE.ZS'   , 'Population, female (% of total population)'                                                                                     , ['Health']                          ], 
    ['SP.POP.TOTL.MA.IN'   , 'Population, male'                                                                                                               , ['Health']                          ], 
    ['SP.POP.TOTL.MA.ZS'   , 'Population, male (% of total population)'                                                                                       , ['Health']                          ], 
    ['SP.REG.BRTH.FE.ZS'   , 'Completeness of birth registration, female (%)'                                                                                 , ['Health']                          ], 
    ['SP.REG.BRTH.MA.ZS'   , 'Completeness of birth registration, male (%)'                                                                                   , ['Health']                          ], 
    ['SP.REG.BRTH.RU.ZS'   , 'Completeness of birth registration, rural (%)'                                                                                  , ['Health']                          ], 
    ['SP.REG.BRTH.UR.ZS'   , 'Completeness of birth registration, urban (%)'                                                                                  , ['Health']                          ], 
    ['SP.REG.BRTH.ZS'      , 'Completeness of birth registration (%)'                                                                                         , ['Health']                          ], 
    ['SP.REG.DTHS.ZS'      , 'Completeness of death registration with cause-of-death information (%)'                                                         , ['Health']                          ], 
    ['SP.RUR.TOTL'         , 'Rural population'                                                                                                               , ['AgriRural']                       ], 
    ['SP.RUR.TOTL.ZG'      , 'Rural population growth (annual %)'                                                                                             , ['AgriRural']                       ], 
    ['SP.RUR.TOTL.ZS'      , 'Rural population (% of total population)'                                                                                       , ['AgriRural']                       ], 
    ['SP.URB.GROW'         , 'Urban population growth (annual %)'                                                                                             , ['Climate', 'Urban']                ], 
    ['SP.URB.TOTL'         , 'Urban population'                                                                                                               , ['Climate', 'Urban']                ], 
    ['SP.URB.TOTL.IN.ZS'   , 'Urban population (% of total population)'                                                                                       , ['Climate', 'Urban']                ], 
    ['SP.UWT.TFRT'         , 'Unmet need for contraception (% of married women ages 15-49)'                                                                   , ['Health']                          ], 
  ], 
}