export const HumanCapitalIndex = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['HD.HCI.AMRT'      , 'Survival Rate from Age 15-60'                              , null], 
    ['HD.HCI.AMRT.FE'   , 'Survival Rate from Age 15-60, Female'                      , null], 
    ['HD.HCI.AMRT.MA'   , 'Survival Rate from Age 15-60, Male'                        , null], 
    ['HD.HCI.EYRS'      , 'Expected Years of School'                                  , null], 
    ['HD.HCI.EYRS.FE'   , 'Expected Years of School, Female'                          , null], 
    ['HD.HCI.EYRS.MA'   , 'Expected Years of School, Male'                            , null], 
    ['HD.HCI.HLOS'      , 'Harmonized Test Scores'                                    , null], 
    ['HD.HCI.HLOS.FE'   , 'Harmonized Test Scores, Female'                            , null], 
    ['HD.HCI.HLOS.MA'   , 'Harmonized Test Scores, Male'                              , null], 
    ['HD.HCI.LAYS'      , 'Learning-Adjusted Years of School'                         , null], 
    ['HD.HCI.LAYS.FE'   , 'Learning-Adjusted Years of School, Female'                 , null], 
    ['HD.HCI.LAYS.MA'   , 'Learning-Adjusted Years of School, Male'                   , null], 
    ['HD.HCI.MORT'      , 'Probability of Survival to Age 5'                          , null], 
    ['HD.HCI.MORT.FE'   , 'Probability of Survival to Age 5, Female'                  , null], 
    ['HD.HCI.MORT.MA'   , 'Probability of Survival to Age 5, Male'                    , null], 
    ['HD.HCI.OVRL'      , 'Human Capital Index (HCI) (scale 0-1)'                     , null], 
    ['HD.HCI.OVRL.FE'   , 'Human Capital Index (HCI), Female (scale 0-1)'             , null], 
    ['HD.HCI.OVRL.LB'   , 'Human Capital Index (HCI), Lower Bound (scale 0-1)'        , null], 
    ['HD.HCI.OVRL.LB.FE', 'Human Capital Index (HCI), Female, Lower Bound (scale 0-1)', null], 
    ['HD.HCI.OVRL.LB.MA', 'Human Capital Index (HCI), Male, Lower Bound (scale 0-1)'  , null], 
    ['HD.HCI.OVRL.MA'   , 'Human Capital Index (HCI), Male (scale 0-1)'               , null], 
    ['HD.HCI.OVRL.UB'   , 'Human Capital Index (HCI), Upper Bound (scale 0-1)'        , null], 
    ['HD.HCI.OVRL.UB.FE', 'Human Capital Index (HCI), Female, Upper Bound (scale 0-1)', null], 
    ['HD.HCI.OVRL.UB.MA', 'Human Capital Index (HCI), Male, Upper Bound (scale 0-1)'  , null], 
    ['HD.HCI.STNT'      , 'Fraction of Children Under 5 Not Stunted'                  , null], 
    ['HD.HCI.STNT.FE'   , 'Fraction of Children Under 5 Not Stunted, Female'          , null], 
    ['HD.HCI.STNT.MA'   , 'Fraction of Children Under 5 Not Stunted, Male'            , null], 
  ], 
}