export const IdaResultsMeasurementSystem = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['EG.ELC.ACCS.ZS'      , 'Access to electricity (% of population)'                                                     , ['EnergyMining', 'ClimateCh', 'Env']], 
    ['EN.ATM.CO2E.PC'      , 'CO2 emissions (metric tons per capita)'                                                      , ['ClimateCh', 'Env']                ], 
    ['EN.ATM.PM25.MC.ZS'   , 'PM2.5 air pollution, population exposed to levels exceeding WHO guideline value (% of total)', ['UrbanDev', 'Env']                 ], 
    ['ER.FST.DFST.ZG'      , 'Annual deforestation (% of change)'                                                          , null                                ], 
    ['ER.H2O.FWTL.ZS'      , 'Annual freshwater withdrawals, total (% of internal resources)'                              , ['ClimateCh', 'Infras', 'Env']      ], 
    ['IQ.SCI.OVRL'         , 'Statistical Capacity score (Overall average)'                                                , ['Public']                          ], 
    ['LP.LPI.OVRL.XQ'      , 'Logistics performance index: Overall (1=low to 5=high)'                                      , ['Private', 'Trade']                ], 
    ['NY.GDP.PCAP.KD.ZG'   , 'GDP per capita growth (annual %)'                                                            , ['EconGr']                          ], 
    ['SE.SEC.CMPT.LO.FE.ZS', 'Lower secondary completion rate, female (% of relevant age group)'                           , ['Edu']                             ], 
    ['SE.SEC.CMPT.LO.ZS'   , 'Lower secondary completion rate, total (% of relevant age group)'                            , ['Edu']                             ], 
    ['SE.SEC.ENRR.LO'      , 'Gross enrolment ratio, lower secondary, both sexes (%)'                                      , ['Edu']                             ], 
    ['SE.SEC.ENRR.LO.FE'   , 'Gross enrolment ratio, lower secondary, female (%)'                                          , ['Edu']                             ], 
    ['SH.DYN.MORT'         , 'Mortality rate, under-5 (per 1,000 live births)'                                             , ['Health', 'AidEff', 'ClimateCh']   ], 
    ['SH.H2O.BASW.ZS'      , 'People using at least basic drinking water services (% of population)'                       , ['Health', 'Env']                   ], 
    ['SH.HIV.INCD.ZS'      , 'Incidence of HIV (per 1,000 uninfected population ages 15-49)'                               , ['Health']                          ], 
    ['SH.STA.BASS.ZS'      , 'People using at least basic sanitation services (% of population)'                           , ['Health', 'Env']                   ], 
    ['SH.STA.BRTC.ZS'      , 'Births attended by skilled health staff (% of total)'                                        , ['Health', 'Gender']                ], 
    ['SH.STA.MMRT'         , 'Maternal mortality ratio (modeled estimate, per 100,000 live births)'                        , ['Health', 'Gender', 'AidEff']      ], 
    ['SH.STA.STNT.FE.ZS'   , 'Prevalence of stunting, height for age, female (% of children under 5)'                      , ['Health']                          ], 
    ['SH.STA.STNT.ZS'      , 'Prevalence of stunting, height for age (% of children under 5)'                              , ['Health', 'AidEff']                ], 
    ['SL.EMP.1524.SP.FE.ZS', 'Employment to population ratio, ages 15-24, female (%) (modeled ILO estimate)'               , ['SpLabor', 'Gender']               ], 
    ['SL.EMP.1524.SP.MA.ZS', 'Employment to population ratio, ages 15-24, male (%) (modeled ILO estimate)'                 , ['SpLabor', 'Gender']               ], 
    ['SL.EMP.1524.SP.ZS'   , 'Employment to population ratio, ages 15-24, total (%) (modeled ILO estimate)'                , ['SpLabor']                         ], 
    ['SL.GDP.PCAP.EM.KD'   , 'GDP per person employed (constant 2017 PPP $)'                                               , ['SpLabor']                         ], 
    ['SL.TLF.CACT.FM.ZS'   , 'Ratio of female to male labor force participation rate (%) (modeled ILO estimate)'           , ['SpLabor']                         ], 
    ['SM.POP.REFG'         , 'Refugee population by country or territory of asylum'                                        , ['Health', 'SocialDev']             ], 
    ['SP.ADO.TFRT'         , 'Adolescent fertility rate (births per 1,000 women ages 15-19)'                               , ['Health', 'Gender', 'SocialDev']   ], 
    ['SP.DYN.CONM.ZS'      , 'Contraceptive prevalence, modern methods (% of women ages 15-49)'                            , ['Health']                          ], 
    ['VC.IDP.TOCV'         , 'Internally displaced persons, total displaced by conflict and violence (number of people)'   , ['Public']                          ], 
  ], 
}