export const IndonesiaDatabaseForPolicyAndEconomicResearch = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['BPK.AUD.SUBN'             , 'BPK Audit Report on Sub-National Budget'                                                                                   , null                   ], 
    ['DAK.AGR.CR'               , 'Total Specific Allocation Grant for Agriculture (in IDR Billion)'                                                          , null                   ], 
    ['DAK.EDU.CR'               , 'Total Specific Allocation Grant for Education (in IDR Billion)'                                                            , null                   ], 
    ['DAK.ENVR.CR'              , 'Total Specific Allocation Grant for Environment (in IDR Billion)'                                                          , null                   ], 
    ['DAK.FRST.CR'              , 'Total Specific Allocation Grant for Forestry (in IDR Billion)'                                                             , null                   ], 
    ['DAK.FSH.CR'               , 'Total Specific Allocation Grant for Fishery (in IDR Billion)'                                                              , null                   ], 
    ['DAK.GOVT.CR'              , 'Total Specific Allocation Grant for Government Sector (in IDR Billion)'                                                    , null                   ], 
    ['DAK.HE.BSRV.CR'           , 'Total Specific Allocation Grant for Health Sector (Subsect: Basic Services) (in IDR Billion)'                              , null                   ], 
    ['DAK.HE.CR'                , 'Total Specific Allocation Grant for Health (in IDR Billion)'                                                               , null                   ], 
    ['DAK.HE.RSRV.CR'           , 'Total Specific Allocation Grant for Health Sector (Subsect: Recommended Services) (in IDR Billion)'                        , null                   ], 
    ['DAK.INFR.CR'              , 'Total Specific Allocation Grant for Infrastructure (in IDR Billion)'                                                       , null                   ], 
    ['DAK.INFR.H2O.CR'          , 'Total Specific Allocation Grant for Infrastructure Sector (Subsect: Water) (in IDR Billion)'                               , null                   ], 
    ['DAK.INFR.IRIG.CR'         , 'Total Specific Allocation Grant for Infrastructure Sector (Subsect: Irrigation) (in IDR Billion)'                          , null                   ], 
    ['DAK.INFR.ROD.CR'          , 'Total Specific Allocation Grant for Infrastructure Sector (Subsect: Road) (in IDR Billion)'                                , null                   ], 
    ['DAK.POP.CR'               , 'Total Specific Allocation Grant for Demographic (in IDR Billion)'                                                          , null                   ], 
    ['DAK.TRAD.CR'              , 'Total Specific Allocation Grant for Trade (in IDR Billion)'                                                                , null                   ], 
    ['DAK.VILG.CR'              , 'Total Specific Allocation Grant for Village (in IDR Billion)'                                                              , null                   ], 
    ['EC.XPD.CAP.CR'            , 'Capital expenditure (in IDR)'                                                                                              , null                   ], 
    ['EC.XPD.GSR.CR'            , 'Goods and services expenditure (in IDR)'                                                                                   , null                   ], 
    ['EC.XPD.OTHR.CR'           , 'Others expenditure (in IDR)'                                                                                               , null                   ], 
    ['EC.XPD.STAF.CR'           , 'Personnel expenditure (in IDR)'                                                                                            , null                   ], 
    ['EC.XPD.TOTL.CR'           , 'Total Expenditure (in IDR)'                                                                                                , null                   ], 
    ['EP.CPI.1996'              , 'Consumer Price Index in 42 cities base 1996'                                                                               , null                   ], 
    ['EP.CPI.2002'              , 'Consumer Price Index in 45 cities base 2002'                                                                               , null                   ], 
    ['EP.CPI.2007'              , 'Consumer Price Index in 66 cities base 2007'                                                                               , null                   ], 
    ['EP.CPI.2012'              , 'Consumer Price Index in 82 cities base 2012'                                                                               , null                   ], 
    ['FC.XPD.ADMN.CR'           , 'General administration function expenditure (in IDR)'                                                                      , null                   ], 
    ['FC.XPD.AGR.CR'            , 'Agriculture function expenditure (in IDR)'                                                                                 , null                   ], 
    ['FC.XPD.ECON.CR'           , 'Economy function expenditure (in IDR)'                                                                                     , null                   ], 
    ['FC.XPD.EDU.CR'            , 'Education function expenditure (in IDR)'                                                                                   , null                   ], 
    ['FC.XPD.ENVR.CR'           , 'Environment function expenditure (in IDR)'                                                                                 , null                   ], 
    ['FC.XPD.HE.CR'             , 'Health function expenditure (in IDR)'                                                                                      , null                   ], 
    ['FC.XPD.HOUS.CR'           , 'Housing and public facilities function expenditure (in IDR)'                                                               , null                   ], 
    ['FC.XPD.INFR.CR'           , 'Infrastructure function expenditure (in IDR)'                                                                              , null                   ], 
    ['FC.XPD.PROT.CR'           , 'Social protection function expenditure (in IDR)'                                                                           , null                   ], 
    ['FC.XPD.PUBL.CR'           , 'Public, law and order function expenditure (in IDR)'                                                                       , null                   ], 
    ['FC.XPD.RELG.CR'           , 'Religious function expenditure (in IDR)'                                                                                   , null                   ], 
    ['FC.XPD.TOUR.CR'           , 'Tourism and culture function expenditure (in IDR)'                                                                         , null                   ], 
    ['FN.CRED.AGR.TOTL'         , 'Total Credit by Sector: Agriculture (province level, in IDR Million)'                                                      , null                   ], 
    ['FN.CRED.BUS.TOTL'         , 'Total Credit by Sector: Business (province level, in IDR Million)'                                                         , null                   ], 
    ['FN.CRED.CNSP.TOTL'        , 'Total Credit by Utilization: Consumption (province level, in IDR Million)'                                                 , null                   ], 
    ['FN.CRED.CNST.TOTL'        , 'Total Credit by Sector: Construction (province level, in IDR Million)'                                                     , null                   ], 
    ['FN.CRED.INVS.TOTL'        , 'Total credit by Utilization: Investment (province level, in IDR Million)'                                                  , null                   ], 
    ['FN.CRED.MINQ.TOTL'        , 'Total Credit by Sector: Mining and Quarrying (province level, in IDR Million)'                                             , null                   ], 
    ['FN.CRED.MNF.TOTL'         , 'Total Credit by Sector: Manufacture (province level, in IDR Million)'                                                      , null                   ], 
    ['FN.CRED.SRV.OTHR.TOTL'    , 'Total Credit by Sector: Other Services (province level, in IDR Million)'                                                   , null                   ], 
    ['FN.CRED.SRV.SOCL.TOTL'    , 'Total Credit by Sector: Social Services (province level, in IDR Million)'                                                  , null                   ], 
    ['FN.CRED.TRAD.TOTL'        , 'Total Credit by Sector: Trade (province level, in IDR Million)'                                                            , null                   ], 
    ['FN.CRED.TRAN.TOTL'        , 'Total Credit by Sector: Transportation (province level, in IDR Million)'                                                   , null                   ], 
    ['FN.CRED.UTL.TOTL'         , 'Total Credit by Sector: Utilities (province level, in IDR Million)'                                                        , null                   ], 
    ['FN.CRED.WCAP.TOTL'        , 'Total Credit by Utilization: Working Capital (province level, in IDR Million)'                                             , null                   ], 
    ['FN.DPST.TOTL'             , 'Total Deposits (province level, in IDR Million)'                                                                           , null                   ], 
    ['FN.LOAN.CBK.TOTL'         , 'Total Commercial and Rural Banks Loans Rupiah and Foreign Currency (province level, in IDR Million)'                       , null                   ], 
    ['HOU.ELC.ACSN.ZS'          , 'Household Access to Electricity: Total (in % of total household)'                                                          , null                   ], 
    ['HOU.H2O.ACSN.ZS'          , 'Household Access to Safe Water (in % of total household)'                                                                  , null                   ], 
    ['HOU.MLT.MAIN.ZS'          , 'Household Access to Fixed Line Phone Connection (in % of total Household)'                                                 , null                   ], 
    ['HOU.STA.ACSN.ZS'          , 'Household Access to safe Sanitation (in % of total Household)'                                                             , null                   ], 
    ['HOU.XPD.EDU.PC.CR'        , 'Monthly Per Capita Household Education Expenditure (in IDR)'                                                               , null                   ], 
    ['HOU.XPD.HE.PC.CR'         , 'Monthly Per Capita Household Health Expenditure (in IDR)'                                                                  , null                   ], 
    ['HOU.XPD.PC.CR'            , 'Household per capita expenditure (in IDR)'                                                                                 , null                   ], 
    ['HOU.XPD.TOTL.20POOR.CR'   , 'Monthly Per Capita TOTAL Household Expenditure for The Poorest 20 percent (in IDR)'                                        , null                   ], 
    ['IDX.HDI'                  , 'Human Development Index'                                                                                                   , null                   ], 
    ['IDX.HDI.REV'              , 'Human Development Index, revised method'                                                                                   , null                   ], 
    ['LND.TOTL.K2'              , 'Total Area (in Km²)'                                                                                                       , null                   ], 
    ['NA.GDP.ACC.FB.SNA08.CR'   , 'GDP on Accommodation & Food Beverages Activity Sector (in IDR Million), SNA 2008, Current Price'                           , null                   ], 
    ['NA.GDP.ACC.FB.SNA08.KR'   , 'GDP on Accommodation & Food Beverages Activity Sector (in IDR Million), SNA 2008, Constant Price'                          , null                   ], 
    ['NA.GDP.AGR.CR'            , 'GDP on Agriculture Sector (in IDR Million), Current Price'                                                                 , null                   ], 
    ['NA.GDP.AGR.KR'            , 'GDP on Agriculture Sector (in IDR Million), Constant Price'                                                                , null                   ], 
    ['NA.GDP.AGR.SNA08.CR'      , 'GDP on Agriculture, Forestry & Fisheries Sector (in IDR Million), SNA 2008, Current Price'                                 , null                   ], 
    ['NA.GDP.AGR.SNA08.KR'      , 'GDP on Agriculture, Forestry & Fisheries Sector (in IDR Million), SNA 2008, Constant Price'                                , null                   ], 
    ['NA.GDP.BUSS.SNA08.CR'     , 'GDP on Business Services Sector (in IDR Million), SNA 2008, Current Price'                                                 , null                   ], 
    ['NA.GDP.BUSS.SNA08.KR'     , 'GDP on Business Services Sector (in IDR Million), SNA 2008, Constant Price'                                                , null                   ], 
    ['NA.GDP.CNST.CR'           , 'GDP on Construction Sector (in IDR Million), Current Price'                                                                , null                   ], 
    ['NA.GDP.CNST.KR'           , 'GDP on Construction Sector (in IDR Million), Constant Price'                                                               , null                   ], 
    ['NA.GDP.CNST.SNA08.CR'     , 'GDP on Construction Sector (in IDR Million), SNA 2008, Current Price'                                                      , null                   ], 
    ['NA.GDP.CNST.SNA08.KR'     , 'GDP on Construction Sector (in IDR Million), SNA 2008, Constant Price'                                                     , null                   ], 
    ['NA.GDP.EDUS.SNA08.CR'     , 'GDP on Education Services Sector (in IDR Million), SNA 2008, Current Price'                                                , null                   ], 
    ['NA.GDP.EDUS.SNA08.KR'     , 'GDP on Education Services Sector (in IDR Million), SNA 2008, Constant Price'                                               , null                   ], 
    ['NA.GDP.ELEC.GAS.SNA08.CR' , 'GDP on Electricity & Gas Supply Sector (in IDR Million), SNA 2008, Current Price'                                          , null                   ], 
    ['NA.GDP.ELEC.GAS.SNA08.KR' , 'GDP on Electricity & Gas Supply Sector (in IDR Million), SNA 2008, Constant Price'                                         , null                   ], 
    ['NA.GDP.EXC.OG.CR'         , 'Total GDP excluding Oil and Gas (in IDR Million), Current Price'                                                           , null                   ], 
    ['NA.GDP.EXC.OG.KR'         , 'Total GDP excluding Oil and Gas (in IDR Million), Constant Price'                                                          , null                   ], 
    ['NA.GDP.FINS.CR'           , 'GDP on Financial Service Sector (in IDR Million), Current Price'                                                           , null                   ], 
    ['NA.GDP.FINS.KR'           , 'GDP on Financial Service Sector (in IDR Million), Constant Price'                                                          , null                   ], 
    ['NA.GDP.FINS.SNA08.CR'     , 'GDP on Financial & Insurance Activity Sector (in IDR Million), SNA 2008, Current Price'                                    , null                   ], 
    ['NA.GDP.FINS.SNA08.KR'     , 'GDP on Financial & Insurance Activity Sector (in IDR Million), SNA 2008, Constant Price'                                   , null                   ], 
    ['NA.GDP.HLTH.SOCW.SNA08.CR', 'GDP on Human Health & Social Work Activity Sector (in IDR Million), SNA 2008, Current Price'                               , null                   ], 
    ['NA.GDP.HLTH.SOCW.SNA08.KR', 'GDP on Human Health & Social Work Activity Sector (in IDR Million), SNA 2008, Constant Price'                              , null                   ], 
    ['NA.GDP.INC.OG.CR'         , 'Total GDP including Oil and Gas (in IDR Million), Current Price'                                                           , null                   ], 
    ['NA.GDP.INC.OG.KR'         , 'Total GDP including Oil and Gas (in IDR Million), Constant Price'                                                          , null                   ], 
    ['NA.GDP.INC.OG.SNA08.CR'   , 'Total GDP including Oil and Gas (in IDR Million), SNA 2008, Current Price'                                                 , null                   ], 
    ['NA.GDP.INC.OG.SNA08.KR'   , 'Total GDP including Oil and Gas (in IDR Million), SNA 2008, Constant Price'                                                , null                   ], 
    ['NA.GDP.INF.COMM.SNA08.CR' , 'GDP on Information & Communication Sector (in IDR Million), SNA 2008, Current Price'                                       , null                   ], 
    ['NA.GDP.INF.COMM.SNA08.KR' , 'GDP on Information & Communication Sector (in IDR Million), SNA 2008, Constant Price'                                      , null                   ], 
    ['NA.GDP.MINQ.CR'           , 'GDP on Mining and Quarrying Sector (in IDR Million), Current Price'                                                        , null                   ], 
    ['NA.GDP.MINQ.KR'           , 'GDP on Mining and Quarrying Sector (in IDR Million), Constant Price'                                                       , null                   ], 
    ['NA.GDP.MINQ.SNA08.CR'     , 'GDP on Mining & Quarrying Sector (in IDR Million), SNA 2008, Current Price'                                                , null                   ], 
    ['NA.GDP.MINQ.SNA08.KR'     , 'GDP on Mining & Quarrying Sector (in IDR Million), SNA 2008, Constant Price'                                               , null                   ], 
    ['NA.GDP.MNF.CR'            , 'GDP on Manufacturing Sector (in IDR Million), Current Price'                                                               , null                   ], 
    ['NA.GDP.MNF.KR'            , 'GDP on Manufacturing Sector (in IDR Million), Constant Price'                                                              , null                   ], 
    ['NA.GDP.MNF.SNA08.CR'      , 'GDP on Manufacturing Industry Sector (in IDR Million), SNA 2008, Current Price'                                            , null                   ], 
    ['NA.GDP.MNF.SNA08.KR'      , 'GDP on Manufacturing Industry Sector (in IDR Million), SNA 2008, Constant Price'                                           , null                   ], 
    ['NA.GDP.PADM.DEF.SNA08.CR' , 'GDP on Public Administration, Defense & Compulsory Social Security Sector (in IDR Million), SNA 2008, Current Price'       , null                   ], 
    ['NA.GDP.PADM.DEF.SNA08.KR' , 'GDP on Public Administration, Defense & Compulsory Social Security Sector (in IDR Million), SNA 2008, Constant Price'      , null                   ], 
    ['NA.GDP.REST.SNA08.CR'     , 'GDP on Real Estate Sector (in IDR Million), SNA 2008, Current Price'                                                       , null                   ], 
    ['NA.GDP.REST.SNA08.KR'     , 'GDP on Real Estate Sector (in IDR Million), SNA 2008, Constant Price'                                                      , null                   ], 
    ['NA.GDP.SRV.OTHR.CR'       , 'GDP on Other Service Sector (in IDR Million), Current Price'                                                               , null                   ], 
    ['NA.GDP.SRV.OTHR.KR'       , 'GDP on Other Service Sector (in IDR Million), Constant Price'                                                              , null                   ], 
    ['NA.GDP.SRV.OTHR.SNA08.CR' , 'GDP on Other Services Sector (in IDR Million), SNA 2008, Current Price'                                                    , null                   ], 
    ['NA.GDP.SRV.OTHR.SNA08.KR' , 'GDP on Other Services Sector (in IDR Million), SNA 2008, Constant Price'                                                   , null                   ], 
    ['NA.GDP.TRAN.COMM.CR'      , 'GDP on Transportation and Telecommunication Sector (in IDR Million), Current Price'                                        , null                   ], 
    ['NA.GDP.TRAN.COMM.KR'      , 'GDP on Transportation and Telecommunication Sector (in IDR Million), Constant Price'                                       , null                   ], 
    ['NA.GDP.TRAN.STOR.SNA08.CR', 'GDP on Transportation & Storage Sector (in IDR Million), SNA 2008, Current Price'                                          , null                   ], 
    ['NA.GDP.TRAN.STOR.SNA08.KR', 'GDP on Transportation & Storage Sector (in IDR Million), SNA 2008, Constant Price'                                         , null                   ], 
    ['NA.GDP.TRD.HTL.CR'        , 'GDP on Trade, Hotel and Restaurant Sector (in IDR Million), Current Price'                                                 , null                   ], 
    ['NA.GDP.TRD.HTL.KR'        , 'GDP on Trade, Hotel and Restaurant Sector (in IDR Million), Constant Price'                                                , null                   ], 
    ['NA.GDP.TRD.SNA08.CR'      , 'GDP on Wholesales & Retail Trade, Repair of Motor Vehicles & Motorcycles Sector (in IDR Million), SNA 2008, Current Price' , null                   ], 
    ['NA.GDP.TRD.SNA08.KR'      , 'GDP on Wholesales & Retail Trade, Repair of Motor Vehicles & Motorcycles Sector (in IDR Million), SNA 2008, Constant Price', null                   ], 
    ['NA.GDP.UTL.CR'            , 'GDP on Utilities Sector (in IDR Million), Current Price'                                                                   , null                   ], 
    ['NA.GDP.UTL.KR'            , 'GDP on Utilities Sector (in IDR Million), Constant Price'                                                                  , null                   ], 
    ['NA.GDP.WTR.WST.SNA08.CR'  , 'GDP on Water Supply, Sewerage, Waste & Recycling Management Sector (in IDR Million), SNA 2008, Current Price'              , null                   ], 
    ['NA.GDP.WTR.WST.SNA08.KR'  , 'GDP on Water Supply, Sewerage, Waste & Recycling Management Sector (in IDR Million), SNA 2008, Constant Price'             , null                   ], 
    ['NE.GDI.CON.GOVT.CR'       , 'GDP expenditure on general government consumption (in IDR Million)'                                                        , null                   ], 
    ['NE.GDI.CON.GOVT.SNA08.CR' , 'GDP expenditure on general government consumption (in IDR Million), SNA 2008, Current Price'                               , null                   ], 
    ['NE.GDI.CON.NPI.CR'        , 'GDP expenditure on non profit private institution consumption (in IDR Million)'                                            , null                   ], 
    ['NE.GDI.CON.NPI.SNA08.CR'  , 'GDP expenditure on non profit private institution consumption (in IDR Million), SNA 2008, Current Price'                   , null                   ], 
    ['NE.GDI.CON.PRVT.CR'       , 'GDP expenditure on private consumption (in IDR Million)'                                                                   , null                   ], 
    ['NE.GDI.CON.PRVT.SNA08.CR' , 'GDP expenditure on private consumption (in IDR Million), SNA 2008, Current Price'                                          , null                   ], 
    ['NE.GDI.EXPT.CR'           , 'GDP expenditure on exports (in IDR Million)'                                                                               , null                   ], 
    ['NE.GDI.EXPT.SNA08.CR'     , 'GDP expenditure on exports (in IDR Million), SNA 2008, Current Price'                                                      , null                   ], 
    ['NE.GDI.FTOT.CR'           , 'GDP expenditure on gross fixed capital formation (in IDR Million)'                                                         , null                   ], 
    ['NE.GDI.FTOT.SNA08.CR'     , 'GDP expenditure on gross fixed capital formation (in IDR Million), SNA 2008, Current Price'                                , null                   ], 
    ['NE.GDI.IMPT.CR'           , 'GDP expenditure on imports (in IDR Million)'                                                                               , null                   ], 
    ['NE.GDI.IMPT.SNA08.CR'     , 'GDP expenditure on imports (in IDR Million), SNA 2008, Current Price'                                                      , null                   ], 
    ['NE.GDI.INEX.SNA08.CR'     , 'GDP expenditure on inter-region net exports (in IDR Million), SNA 2008, Current Price'                                     , null                   ], 
    ['NE.GDI.STKB.CR'           , 'GDP expenditure on changes in stock (in IDR Million)'                                                                      , null                   ], 
    ['NE.GDI.STKB.SNA08.CR'     , 'GDP expenditure on changes in stock (in IDR Million), SNA 2008, Current Price'                                             , null                   ], 
    ['NE.GDI.TOTL.CR'           , 'Total GDP based on expenditure (in IDR Million)'                                                                           , null                   ], 
    ['NE.GDI.TOTL.SNA08.CR'     , 'Total GDP based on expenditure (in IDR Million), SNA 2008, Current Price'                                                  , null                   ], 
    ['NRRV.SHR.FRST.CR'         , 'Total Natural Resources Revenue Sharing from Forestry (in IDR, realization value)'                                         , null                   ], 
    ['NRRV.SHR.FSH.CR'          , 'Total Natural Resources Revenue Sharing from Fishery (in IDR, realization value)'                                          , null                   ], 
    ['NRRV.SHR.GAS.CR'          , 'Total Natural Resources Revenue Sharing from Gas (in IDR, realization value)'                                              , null                   ], 
    ['NRRV.SHR.GEOT.CR'         , 'Total Natural Resources Revenue Sharing from Geothermal  Energy (in IDR, realization value)'                               , null                   ], 
    ['NRRV.SHR.MIN.CR'          , 'Total Natural Resources Revenue Sharing from Mining (in IDR, realization value)'                                           , null                   ], 
    ['NRRV.SHR.PETR.CR'         , 'Total Natural Resources Revenue Sharing from Oil (in IDR, realization value)'                                              , null                   ], 
    ['PALM.LND.DMG'             , 'Palm Oil Land Area by type of condition: Damaged (in Hectares)'                                                            , null                   ], 
    ['PALM.LND.IMM'             , 'Palm Oil Land Area by type of condition: Immature (in Hectares)'                                                           , null                   ], 
    ['PALM.LND.MTR'             , 'Palm Oil Land Area by type of condition: Mature (in Hectares)'                                                             , null                   ], 
    ['PALM.LND.PRVT'            , 'Palm Oil Land Area by type of ownership: Private (in Hectares)'                                                            , null                   ], 
    ['PALM.LND.SMHD'            , 'Palm Oil Land Area by type of ownership: Smallholder (in Hectares)'                                                        , null                   ], 
    ['PALM.LND.SOE'             , 'Palm Oil Land Area by type of ownership: State Owned Enterprise (in Hectares)'                                             , null                   ], 
    ['PALM.LND.TOTL'            , 'Palm Oil Land Area: Total (in Hectares)'                                                                                   , null                   ], 
    ['PALM.PRD.PRVT'            , 'Palm Production by type of ownership: Private (in Tons)'                                                                   , null                   ], 
    ['PALM.PRD.SMHD'            , 'Palm Production by type of ownership: Smallholder (in Tons)'                                                               , null                   ], 
    ['PALM.PRD.SOE'             , 'Palm Production by type of ownership: State Owned Enterprise (in Tons)'                                                    , null                   ], 
    ['PALM.PRD.TOTL'            , 'Palm Production: Total (in Tons)'                                                                                          , null                   ], 
    ['PALM.YLD.PRVT'            , 'Palm Oil Yield by type of ownership: Private (in Kg/Ha)'                                                                   , null                   ], 
    ['PALM.YLD.SMHD'            , 'Palm Oil Yield by type of ownership: Smallholder (in Kg/Ha)'                                                               , null                   ], 
    ['PALM.YLD.SOE'             , 'Palm Oil Yield by type of ownership: State Owned Enterprise (in Kg/Ha)'                                                    , null                   ], 
    ['RES.DPST.CBK'             , 'Outstanding Deposits of Commercial Banks owned by Regional Government (Province Level, in IDR Million)'                    , null                   ], 
    ['REV.DAK.CR'               , 'Total Special Allocation Grant/DAK (in IDR)'                                                                               , null                   ], 
    ['REV.DAU.CR'               , 'Total General Allocation Grant/DAU (in IDR)'                                                                               , null                   ], 
    ['REV.NRRV.SHR.CR'          , 'Total Natural Resource Revenue Sharing/DBH SDA (in IDR)'                                                                   , null                   ], 
    ['REV.OSRV.CR'              , 'Total Own Source Revenue/PAD (in IDR)'                                                                                     , null                   ], 
    ['REV.OTHR.CR'              , 'Total Other Revenue (in IDR)'                                                                                              , null                   ], 
    ['REV.RV.SHR.CR'            , 'Total Revenue Sharing'                                                                                                     , null                   ], 
    ['REV.TOTL.CR'              , 'Total Revenue (in IDR)'                                                                                                    , null                   ], 
    ['REV.TXRV.SHR.CR'          , 'Total Tax Revenue Sharing/DBH Pajak (in IDR)'                                                                              , null                   ], 
    ['ROD.DIST.ASPH.KM'         , 'Length of District Road: Asphalt (in km) (BPS Data, Province only)'                                                        , null                   ], 
    ['ROD.DIST.BDMG.BM.KM'      , 'Length of District Road: Bad Damage (in km) (Bina Marga Data)'                                                             , null                   ], 
    ['ROD.DIST.BDMG.KM'         , 'Length of District Road: Bad Damage (in km) (BPS Data, Province only)'                                                     , null                   ], 
    ['ROD.DIST.DIRT.KM'         , 'Length of District Road: Dirt (in km) (BPS Data, Province only)'                                                           , null                   ], 
    ['ROD.DIST.FAIR.BM.KM'      , 'Length of District Road: Fair (in km) (Bina Marga Data)'                                                                   , null                   ], 
    ['ROD.DIST.FAIR.KM'         , 'Length of District Road: Fair (in km) (BPS Data, Province only)'                                                           , null                   ], 
    ['ROD.DIST.GOOD.BM.KM'      , 'Length of District Road: Good (in km) (Bina Marga Data)'                                                                   , null                   ], 
    ['ROD.DIST.GOOD.KM'         , 'Length of District Road: Good (in km) (BPS Data, Province only)'                                                           , null                   ], 
    ['ROD.DIST.GRAVL.KM'        , 'Length of District Road: Gravel (in km) (BPS Data, Province only)'                                                         , null                   ], 
    ['ROD.DIST.LDMG.BM.KM'      , 'Length of District Road: Light Damage (in km) (Bina Marga Data)'                                                           , null                   ], 
    ['ROD.DIST.LDMG.KM'         , 'Length of District Road: Light Damage (in km) (BPS Data, Province only)'                                                   , null                   ], 
    ['ROD.DIST.OTHR.KM'         , 'Length of District Road: Other (in km) (BPS Data, Province only)'                                                          , null                   ], 
    ['ROD.NATL.ASPH.KM'         , 'Length of National Road: Asphalt (in km) (BPS Data, Province only)'                                                        , null                   ], 
    ['ROD.NATL.BDMG.KM'         , 'Length of National Road: Bad Damage (in km) (BPS Data, Province only)'                                                     , null                   ], 
    ['ROD.NATL.DIRT.KM'         , 'Length of National Road: Dirt (in km) (BPS Data, Province only)'                                                           , null                   ], 
    ['ROD.NATL.FAIR.KM'         , 'Length of National Road: Fair (in km) (BPS Data, Province only)'                                                           , null                   ], 
    ['ROD.NATL.GOOD.KM'         , 'Length of National Road: Good (in km) (BPS Data, Province only)'                                                           , null                   ], 
    ['ROD.NATL.GRAVL.KM'        , 'Length of National Road: Gravel (in km) (BPS Data, Province only)'                                                         , null                   ], 
    ['ROD.NATL.LDMG.KM'         , 'Length of National Road: Light Damage (in km) (BPS Data, Province only)'                                                   , null                   ], 
    ['ROD.NATL.OTHR.KM'         , 'Length of National Road: Other (in km) (BPS Data, Province only)'                                                          , null                   ], 
    ['ROD.PROV.ASPH.KM'         , 'Length of Province Road: Asphalt (in km) (BPS Data, Province only)'                                                        , null                   ], 
    ['ROD.PROV.BDMG.KM'         , 'Length of Province Road: Bad Damage (in km) (BPS Data, Province only)'                                                     , null                   ], 
    ['ROD.PROV.DIRT.KM'         , 'Length of Province Road: Dirt (in km) (BPS Data, Province only)'                                                           , null                   ], 
    ['ROD.PROV.FAIR.KM'         , 'Length of Province Road: Fair (in km) (BPS Data, Province only)'                                                           , null                   ], 
    ['ROD.PROV.GOOD.KM'         , 'Length of Province Road: Good (in km) (BPS Data, Province only)'                                                           , null                   ], 
    ['ROD.PROV.GRAVL.KM'        , 'Length of Province Road: Gravel (in km) (BPS Data, Province only)'                                                         , null                   ], 
    ['ROD.PROV.LDMG.KM'         , 'Length of Province Road: Light Damage (in km) (BPS Data, Province only)'                                                   , null                   ], 
    ['ROD.PROV.OTHR.KM'         , 'Length of Province Road: Other (in km) (BPS Data, Province only)'                                                          , null                   ], 
    ['ROD.VILG.ASPH.ZS'         , 'Villages with road: Asphalt (in % of total villages)'                                                                      , null                   ], 
    ['ROD.VILG.DIRT.ZS'         , 'Villages with road: Dirt (in % of total villages)'                                                                         , null                   ], 
    ['ROD.VILG.GRAVL.ZS'        , 'Villages with road: Gravel (in % of total villages)'                                                                       , null                   ], 
    ['ROD.VILG.OTHR.ZS'         , 'Villages with road: Other (in % of total villages)'                                                                        , null                   ], 
    ['SE.JRSEC.NENR.ZS'         , 'Net Enrollment Ratio: Junior Secondary (in %)'                                                                             , null                   ], 
    ['SE.LITR.15UP.ZS'          , 'Literacy Rate for Population age 15 and over (in % of total population)'                                                   , null                   ], 
    ['SE.NEXM.SCR.JRSEC'        , 'Average National Exam Score: Junior Secondary Level (out of 100, available only at district level)'                        , null                   ], 
    ['SE.NEXM.SCR.PRM'          , 'Average National Exam Score: Primary Level (out of 100, available only at district level)'                                 , null                   ], 
    ['SE.NEXM.SCR.SRSEC'        , 'Average National Exam Score: Senior Secondary Level (out of 100, available only at district level)'                        , null                   ], 
    ['SE.PRM.NENR.ZS'           , 'Net Enrollment Ratio: Primary (in %)'                                                                                      , null                   ], 
    ['SE.SCHL.JRSEC'            , 'Number of schools at Junior Secondary Level'                                                                               , null                   ], 
    ['SE.SCHL.PRM'              , 'Number of schools at Primary Level'                                                                                        , null                   ], 
    ['SE.SCHL.SRSEC'            , 'Number of schools at Senior Secondary level'                                                                               , null                   ], 
    ['SE.SRSEC.NENR.ZS'         , 'Net Enrollment Ratio: Senior Secondary (in %)'                                                                             , null                   ], 
    ['SE.STUD.JRSEC'            , 'Number of Student: Junior Secondary Level (in number of people, 2009 data only)'                                           , null                   ], 
    ['SE.STUD.PRM'              , 'Number of Student: Primary Level (in number of people, 2009 data only)'                                                    , null                   ], 
    ['SE.STUD.SRSEC'            , 'Number of Student: Senior Secondary Level (in number of people, 2009 data only)'                                           , null                   ], 
    ['SE.TCHR.JRSEC'            , 'Number of Teacher: Junior Secondary Level (in number of people, 2009 data only)'                                           , null                   ], 
    ['SE.TCHR.PRM'              , 'Number of Teacher: Primary Level (in number of people, 2009 data only)'                                                    , null                   ], 
    ['SE.TCHR.SRSEC'            , 'Number of Teacher: Senior Secondary Level (in number of people, 2009 data only)'                                           , null                   ], 
    ['SH.DR.TOTL'               , 'Number of Doctors'                                                                                                         , null                   ], 
    ['SH.HOSP.TOTL'             , 'Number of hospitals'                                                                                                       , null                   ], 
    ['SH.IMM.CHLD.ZS'           , 'Immunization Coverage for Children under 5 years old (in % of children population under 5 years old)'                      , null                   ], 
    ['SH.MED.MWIV.TOTL'         , 'Number of Midwives'                                                                                                        , null                   ], 
    ['SH.MORB.ZS'               , 'Morbidity Rate (in %)'                                                                                                     , null                   ], 
    ['SH.POLINDES.TOTL'         , 'Number of Polindes (Poliklinik Desa/Village Polyclinic)'                                                                   , null                   ], 
    ['SH.PUSKESMAS.TOTL'        , 'Number of Puskesmas and its line services'                                                                                 , null                   ], 
    ['SH.STA.BRTC.ZS'           , 'Births attended by skilled health staff (% of total)'                                                                      , ['Health', 'Gender']   ], 
    ['SI.POV.BPL'               , 'Number of people live below the poverty line (in number of people)'                                                        , null                   ], 
    ['SI.POV.NAPL'              , 'Poverty Line (in IDR)'                                                                                                     , null                   ], 
    ['SI.POV.NAPR.ZS'           , 'Poverty Rate (in % of population)'                                                                                         , null                   ], 
    ['SI.POV.NGAP'              , 'Poverty Gap (index)'                                                                                                       , null                   ], 
    ['SI.POV.NSEV'              , 'Poverty Severity (index)'                                                                                                  , null                   ], 
    ['SL.EMP.AGR.FRST.FSH'      , 'Number of people employed in agriculture, forestry and fishery'                                                            , null                   ], 
    ['SL.EMP.CNST'              , 'Number of people employed in construction sector'                                                                          , null                   ], 
    ['SL.EMP.ELC'               , 'Number of people employed in electricity and utilities sector'                                                             , null                   ], 
    ['SL.EMP.FINS'              , 'Number of people employed in financial services sector'                                                                    , null                   ], 
    ['SL.EMP.IND'               , 'Number of people employed in industrial sector'                                                                            , null                   ], 
    ['SL.EMP.MINQ'              , 'Number of people employed in mining and quarrying sector'                                                                  , null                   ], 
    ['SL.EMP.SOCL'              , 'Number of people employed in social services sector'                                                                       , null                   ], 
    ['SL.EMP.TOTL'              , 'Number of people employed'                                                                                                 , null                   ], 
    ['SL.EMP.TRAD'              , 'Number of people employed in trade, hotel and restaurant sector'                                                           , null                   ], 
    ['SL.EMP.TRAN'              , 'Number of people employed in transportation and telecommunication sector'                                                  , null                   ], 
    ['SL.EMP.UNDR'              , 'Number of people underemployed'                                                                                            , null                   ], 
    ['SL.TLF'                   , 'Number of people in labor force'                                                                                           , null                   ], 
    ['SL.UEM.TOTL'              , 'Number of people unemployed'                                                                                               , null                   ], 
    ['SP.POP.0014.TO'           , 'Population ages 0-14, total'                                                                                               , ['Health']             ], 
    ['SP.POP.1564.TO'           , 'Population ages 15-64, total'                                                                                              , ['Health']             ], 
    ['SP.POP.65UP.TO'           , 'Population ages 65 and above, total'                                                                                       , ['Health']             ], 
    ['SP.POP.TOTL'              , 'Population, total'                                                                                                         , ['ClimateCh', 'Health']], 
    ['SP.RUR.TOTL.ZS'           , 'Rural population (% of total population)'                                                                                  , ['AgriRuralDev']       ], 
    ['SP.URB.TOTL.ZS'           , 'Percentage of Population in Urban Areas (in % of Total Population)'                                                        , null                   ], 
    ['TRAD.EXPT.BVTO'           , 'Export: Beverages and tobacco (province Level, in USD)'                                                                    , null                   ], 
    ['TRAD.EXPT.CHEM'           , 'Export: Chemical and related products, nes (province Level, in USD)'                                                       , null                   ], 
    ['TRAD.EXPT.CRUD'           , 'Export: Crude materials, inedible, except fuels (province Level, in USD)'                                                  , null                   ], 
    ['TRAD.EXPT.FLVSK'          , 'Export: Food and Live Animals (province Level, in USD)'                                                                    , null                   ], 
    ['TRAD.EXPT.FUEL'           , 'Export: Mineral fuels, lubricants and related materials (province Level, in USD)'                                          , null                   ], 
    ['TRAD.EXPT.MANF'           , 'Export: Manufactured goods, classified chiefly by material (province Level, in USD)'                                       , null                   ], 
    ['TRAD.EXPT.MANF.OTHR'      , 'Export: Miscellaneous manufactures articles (province Level, in USD)'                                                      , null                   ], 
    ['TRAD.EXPT.MTRN'           , 'Export: Machinery and transport equipment (province Level, in USD)'                                                        , null                   ], 
    ['TRAD.EXPT.OLFTW'          , 'Export: Animals and vegetable oil, fat and waxes (province Level, in USD)'                                                 , null                   ], 
    ['TRAD.EXPT.OTHR'           , 'Export: Commodities and transaction not elsewhere classified (province Level, in USD)'                                     , null                   ], 
    ['TRAD.IMPT.BVTO'           , 'Import: Beverages and tobacco (province Level, in USD)'                                                                    , null                   ], 
    ['TRAD.IMPT.CHEM'           , 'Import: Chemical and related products, nes (province Level, in USD)'                                                       , null                   ], 
    ['TRAD.IMPT.CRUD'           , 'Import: Crude materials, inedible, except fuels (province Level, in USD)'                                                  , null                   ], 
    ['TRAD.IMPT.FLVSK'          , 'Import: Food and Live Animals (province Level, in USD)'                                                                    , null                   ], 
    ['TRAD.IMPT.FUEL'           , 'Import: Mineral fuels, lubricants and related materials (province Level, in USD)'                                          , null                   ], 
    ['TRAD.IMPT.MANF'           , 'Import: Manufactured goods, classified chiefly by material (province Level, in USD)'                                       , null                   ], 
    ['TRAD.IMPT.MANF.OTHR'      , 'Import: Miscellaneous manufactures articles (province Level, in USD)'                                                      , null                   ], 
    ['TRAD.IMPT.MTRN'           , 'Import: Machinery and transport equipment (province Level, in USD)'                                                        , null                   ], 
    ['TRAD.IMPT.OLFTW'          , 'Import: Animals and vegetable oil, fat and waxes (province Level, in USD)'                                                 , null                   ], 
    ['TRAD.IMPT.OTHR'           , 'Import: Commodities and transaction not elsewhere classified (province Level, in USD)'                                     , null                   ], 
  ], 
}