export const InternationalDebtStatistics = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['BM.GSR.TOTL.CD'     , 'Imports of goods, services and primary income (BoP, current US$)'                                   , ['Econ', 'Debt', 'Trade']], 
    ['BN.CAB.XOKA.CD'     , 'Current account balance (BoP, current US$)'                                                         , ['Econ', 'Debt']         ], 
    ['BX.GRT.EXTA.CD.DT'  , 'Grants, excluding technical cooperation (current US$)'                                              , ['Debt']                 ], 
    ['BX.GRT.TECH.CD.DT'  , 'Technical cooperation grants (current US$)'                                                         , ['Debt']                 ], 
    ['BX.GSR.TOTL.CD'     , 'Exports of goods, services and primary income (BoP, current US$)'                                   , ['Econ', 'Debt', 'Trade']], 
    ['BX.KLT.DINV.CD.DT'  , 'Foreign direct investment, net inflows in reporting economy (DRS, current US$)'                     , ['Debt']                 ], 
    ['BX.KLT.DREM.CD.DT'  , 'Primary income on FDI (current US$)'                                                                , ['Econ', 'Fin', 'Debt']  ], 
    ['BX.PEF.TOTL.CD.DT'  , 'Portfolio investment, equity (DRS, current US$)'                                                    , ['Debt']                 ], 
    ['BX.TRF.PWKR.CD.DT'  , 'Personal remittances, received (current US$)'                                                       , ['Econ', 'Fin', 'Debt']  ], 
    ['DT.AMT.BLAT.CD'     , 'PPG, bilateral (AMT, current US$)'                                                                  , ['Debt']                 ], 
    ['DT.AMT.BLAT.GG.CD'  , 'GG, bilateral (AMT, current US$)'                                                                   , ['Debt']                 ], 
    ['DT.AMT.BLAT.OPS.CD' , 'OPS, bilateral (AMT, current US$)'                                                                  , ['Debt']                 ], 
    ['DT.AMT.BLAT.PRVG.CD', 'PRVG, bilateral (AMT, current US$)'                                                                 , ['Debt']                 ], 
    ['DT.AMT.BLAT.PS.CD'  , 'PS, bilateral (AMT, current US$)'                                                                   , ['Debt']                 ], 
    ['DT.AMT.BLTC.CD'     , 'PPG, bilateral concessional (AMT, current US$)'                                                     , ['Debt']                 ], 
    ['DT.AMT.BLTC.GG.CD'  , 'GG, bilateral concessional (AMT, current US$)'                                                      , ['Debt']                 ], 
    ['DT.AMT.BLTC.OPS.CD' , 'OPS, bilateral concessional (AMT, current US$)'                                                     , ['Debt']                 ], 
    ['DT.AMT.BLTC.PRVG.CD', 'PRVG, bilateral concessional (AMT, current US$)'                                                    , ['Debt']                 ], 
    ['DT.AMT.BLTC.PS.CD'  , 'PS, bilateral concessional (AMT, current US$)'                                                      , ['Debt']                 ], 
    ['DT.AMT.DEGG.CD'     , 'Principal repayments on external debt, general government sector (PPG) (AMT, current US$)'          , ['Debt']                 ], 
    ['DT.AMT.DEPS.CD'     , 'Principal repayments on external debt, public sector (PPG) (AMT, current US$)'                      , ['Debt']                 ], 
    ['DT.AMT.DIMF.CD'     , 'IMF repurchases (AMT, current US$)'                                                                 , ['Debt']                 ], 
    ['DT.AMT.DLTF.CD'     , 'Principal repayments on external debt, long-term + IMF (AMT, current US$)'                          , ['Debt']                 ], 
    ['DT.AMT.DLXF.CD'     , 'Principal repayments on external debt, long-term (AMT, current US$)'                                , ['Debt']                 ], 
    ['DT.AMT.DOPS.CD'     , 'Principal repayments on external debt, other public sector (PPG) (AMT, current US$)'                , ['Debt']                 ], 
    ['DT.AMT.DPNG.CD'     , 'Principal repayments on external debt, private nonguaranteed (PNG) (AMT, current US$)'              , ['Debt']                 ], 
    ['DT.AMT.DPPG.CD'     , 'Principal repayments on external debt, public and publicly guaranteed (PPG) (AMT, current US$)'     , ['Debt']                 ], 
    ['DT.AMT.MIBR.CD'     , 'PPG, IBRD (AMT, current US$)'                                                                       , ['Debt']                 ], 
    ['DT.AMT.MIDA.CD'     , 'PPG, IDA (AMT, current US$)'                                                                        , ['Debt']                 ], 
    ['DT.AMT.MLAT.CD'     , 'PPG, multilateral (AMT, current US$)'                                                               , ['Debt']                 ], 
    ['DT.AMT.MLAT.GG.CD'  , 'GG, multilateral (AMT, current US$)'                                                                , ['Debt']                 ], 
    ['DT.AMT.MLAT.OPS.CD' , 'OPS, multilateral (AMT, current US$)'                                                               , ['Debt']                 ], 
    ['DT.AMT.MLAT.PRVG.CD', 'PRVG, multilateral (AMT, current US$)'                                                              , ['Debt']                 ], 
    ['DT.AMT.MLAT.PS.CD'  , 'PS, multilateral (AMT, current US$)'                                                                , ['Debt']                 ], 
    ['DT.AMT.MLTC.CD'     , 'PPG, multilateral concessional (AMT, current US$)'                                                  , ['Debt']                 ], 
    ['DT.AMT.MLTC.GG.CD'  , 'GG, multilateral concessional (AMT, current US$)'                                                   , ['Debt']                 ], 
    ['DT.AMT.MLTC.OPS.CD' , 'OPS, multilateral concessional (AMT, current US$)'                                                  , ['Debt']                 ], 
    ['DT.AMT.MLTC.PRVG.CD', 'PRVG, multilateral concessional (AMT, current US$)'                                                 , ['Debt']                 ], 
    ['DT.AMT.MLTC.PS.CD'  , 'PS, multilateral concessional (AMT, current US$)'                                                   , ['Debt']                 ], 
    ['DT.AMT.OFFT.CD'     , 'PPG, official creditors (AMT, current US$)'                                                         , ['Debt']                 ], 
    ['DT.AMT.OFFT.GG.CD'  , 'GG, official creditors (AMT, current US$)'                                                          , ['Debt']                 ], 
    ['DT.AMT.OFFT.OPS.CD' , 'OPS, official creditors (AMT, current US$)'                                                         , ['Debt']                 ], 
    ['DT.AMT.OFFT.PRVG.CD', 'PRVG, official creditors (AMT, current US$)'                                                        , ['Debt']                 ], 
    ['DT.AMT.OFFT.PS.CD'  , 'PS, official creditors (AMT, current US$)'                                                          , ['Debt']                 ], 
    ['DT.AMT.PBND.CD'     , 'PPG, bonds (AMT, current US$)'                                                                      , ['Debt']                 ], 
    ['DT.AMT.PBND.GG.CD'  , 'GG, bonds (AMT, current US$)'                                                                       , ['Debt']                 ], 
    ['DT.AMT.PBND.OPS.CD' , 'OPS, bonds (AMT, current US$)'                                                                      , ['Debt']                 ], 
    ['DT.AMT.PBND.PRVG.CD', 'PRVG, bonds (AMT, current US$)'                                                                     , ['Debt']                 ], 
    ['DT.AMT.PBND.PS.CD'  , 'PS, bonds (AMT, current US$)'                                                                       , ['Debt']                 ], 
    ['DT.AMT.PCBK.CD'     , 'PPG, commercial banks (AMT, current US$)'                                                           , ['Debt']                 ], 
    ['DT.AMT.PCBK.GG.CD'  , 'GG, commercial banks (AMT, current US$)'                                                            , ['Debt']                 ], 
    ['DT.AMT.PCBK.OPS.CD' , 'OPS, commercial banks (AMT, current US$)'                                                           , ['Debt']                 ], 
    ['DT.AMT.PCBK.PRVG.CD', 'PRVG, commercial banks (AMT, current US$)'                                                          , ['Debt']                 ], 
    ['DT.AMT.PCBK.PS.CD'  , 'PS, commercial banks (AMT, current US$)'                                                            , ['Debt']                 ], 
    ['DT.AMT.PNGB.CD'     , 'PNG, bonds (AMT, current US$)'                                                                      , ['Debt']                 ], 
    ['DT.AMT.PNGC.CD'     , 'PNG, commercial banks and other creditors (AMT, current US$)'                                       , ['Debt']                 ], 
    ['DT.AMT.PROP.CD'     , 'PPG, other private creditors (AMT, current US$)'                                                    , ['Debt']                 ], 
    ['DT.AMT.PROP.GG.CD'  , 'GG, other private creditors (AMT, current US$)'                                                     , ['Debt']                 ], 
    ['DT.AMT.PROP.OPS.CD' , 'OPS, other private creditors (AMT, current US$)'                                                    , ['Debt']                 ], 
    ['DT.AMT.PROP.PRVG.CD', 'PRVG, other private creditors (AMT, current US$)'                                                   , ['Debt']                 ], 
    ['DT.AMT.PROP.PS.CD'  , 'PS, other private creditors (AMT, current US$)'                                                     , ['Debt']                 ], 
    ['DT.AMT.PRPG.CD'     , 'Principal repayments on external debt, private guaranteed by public sector (PPG) (AMT, current US$)', ['Debt']                 ], 
    ['DT.AMT.PRVT.CD'     , 'PPG, private creditors (AMT, current US$)'                                                          , ['Debt']                 ], 
    ['DT.AMT.PRVT.GG.CD'  , 'GG, private creditors (AMT, current US$)'                                                           , ['Debt']                 ], 
    ['DT.AMT.PRVT.OPS.CD' , 'OPS, private creditors (AMT, current US$)'                                                          , ['Debt']                 ], 
    ['DT.AMT.PRVT.PRVG.CD', 'PRVG, private creditors (AMT, current US$)'                                                         , ['Debt']                 ], 
    ['DT.AMT.PRVT.PS.CD'  , 'PS, private creditors (AMT, current US$)'                                                           , ['Debt']                 ], 
    ['DT.AXA.DPPG.CD'     , 'Principal arrears, long-term DOD (US$)'                                                             , ['Debt']                 ], 
    ['DT.AXA.OFFT.CD'     , 'Principal arrears, official creditors (current US$)'                                                , ['Debt']                 ], 
    ['DT.AXA.PRVT.CD'     , 'Principal arrears, private creditors (current US$)'                                                 , ['Debt']                 ], 
    ['DT.AXF.DPPG.CD'     , 'Principal forgiven (current US$)'                                                                   , ['Debt']                 ], 
    ['DT.AXR.DPPG.CD'     , 'Principal rescheduled (current US$)'                                                                , ['Debt']                 ], 
    ['DT.AXR.OFFT.CD'     , 'Principal rescheduled, official (current US$)'                                                      , ['Debt']                 ], 
    ['DT.AXR.PRVT.CD'     , 'Principal rescheduled, private (current US$)'                                                       , ['Debt']                 ], 
    ['DT.COM.BLAT.CD'     , 'Commitments, bilateral creditors (COM, current US$)'                                                , ['Debt']                 ], 
    ['DT.COM.DPPG.CD'     , 'Commitments, public and publicly guaranteed (COM, current US$)'                                     , ['Debt']                 ], 
    ['DT.COM.MIBR.CD'     , 'Commitments, IBRD (COM, current US$)'                                                               , ['Debt']                 ], 
    ['DT.COM.MIDA.CD'     , 'Commitments, IDA (COM, current US$)'                                                                , ['Debt']                 ], 
    ['DT.COM.MLAT.CD'     , 'Commitments, multilateral creditors (COM, current US$)'                                             , ['Debt']                 ], 
    ['DT.COM.OFFT.CD'     , 'Commitments, official creditors (COM, current US$)'                                                 , ['Debt']                 ], 
    ['DT.COM.PRVT.CD'     , 'Commitments, private creditors (COM, current US$)'                                                  , ['Debt']                 ], 
    ['DT.CUR.DMAK.ZS'     , 'Currency composition of PPG debt, Deutsche mark (%)'                                                , ['Debt']                 ], 
    ['DT.CUR.EURO.ZS'     , 'Currency composition of PPG debt, Euro (%)'                                                         , ['Debt']                 ], 
    ['DT.CUR.FFRC.ZS'     , 'Currency composition of PPG debt, French franc (%)'                                                 , ['Debt']                 ], 
    ['DT.CUR.JYEN.ZS'     , 'Currency composition of PPG debt, Japanese yen (%)'                                                 , ['Debt']                 ], 
    ['DT.CUR.MULC.ZS'     , 'Currency composition of PPG debt, Multiple currencies (%)'                                          , ['Debt']                 ], 
    ['DT.CUR.OTHC.ZS'     , 'Currency composition of PPG debt, all other currencies (%)'                                         , ['Debt']                 ], 
    ['DT.CUR.SDRW.ZS'     , 'Currency composition of PPG debt, SDR (%)'                                                          , ['Debt']                 ], 
    ['DT.CUR.SWFR.ZS'     , 'Currency composition of PPG debt, Swiss franc (%)'                                                  , ['Debt']                 ], 
    ['DT.CUR.UKPS.ZS'     , 'Currency composition of PPG debt, Pound sterling (%)'                                               , ['Debt']                 ], 
    ['DT.CUR.USDL.ZS'     , 'Currency composition of PPG debt, U.S. dollars (%)'                                                 , ['Debt']                 ], 
    ['DT.DFR.DPPG.CD'     , 'Debt forgiveness or reduction (current US$)'                                                        , ['Debt']                 ], 
    ['DT.DIS.BLAT.CD'     , 'PPG, bilateral (DIS, current US$)'                                                                  , ['Debt']                 ], 
    ['DT.DIS.BLAT.GG.CD'  , 'GG, bilateral (DIS, current US$)'                                                                   , ['Debt']                 ], 
    ['DT.DIS.BLAT.OPS.CD' , 'OPS, bilateral (DIS, current US$)'                                                                  , ['Debt']                 ], 
    ['DT.DIS.BLAT.PRVG.CD', 'PRVG, bilateral (DIS, current US$)'                                                                 , ['Debt']                 ], 
    ['DT.DIS.BLAT.PS.CD'  , 'PS, bilateral (DIS, current US$)'                                                                   , ['Debt']                 ], 
    ['DT.DIS.BLTC.CD'     , 'PPG, bilateral concessional (DIS, current US$)'                                                     , ['Debt']                 ], 
    ['DT.DIS.BLTC.GG.CD'  , 'GG, bilateral concessional (DIS, current US$)'                                                      , ['Debt']                 ], 
    ['DT.DIS.BLTC.OPS.CD' , 'OPS, bilateral concessional (DIS, current US$)'                                                     , ['Debt']                 ], 
    ['DT.DIS.BLTC.PRVG.CD', 'PRVG, bilateral concessional (DIS, current US$)'                                                    , ['Debt']                 ], 
    ['DT.DIS.BLTC.PS.CD'  , 'PS, bilateral concessional (DIS, current US$)'                                                      , ['Debt']                 ], 
    ['DT.DIS.DEGG.CD'     , 'Disbursements on external debt, general government sector (PPG) (DIS, current US$)'                 , ['Debt']                 ], 
    ['DT.DIS.DEPS.CD'     , 'Disbursements on external debt, public sector (PPG) (DIS, current US$)'                             , ['Debt']                 ], 
    ['DT.DIS.DIMF.CD'     , 'IMF purchases (DIS, current US$)'                                                                   , ['Debt']                 ], 
    ['DT.DIS.DLTF.CD'     , 'Disbursements on external debt, long-term + IMF (DIS, current US$)'                                 , ['Debt']                 ], 
    ['DT.DIS.DLXF.CD'     , 'Disbursements on external debt, long-term (DIS, current US$)'                                       , ['Debt']                 ], 
    ['DT.DIS.DOPS.CD'     , 'Disbursements on external debt, other public sector (PPG) (DIS, current US$)'                       , ['Debt']                 ], 
    ['DT.DIS.DPNG.CD'     , 'Disbursements on external debt, private nonguaranteed (PNG) (DIS, current US$)'                     , ['Debt']                 ], 
    ['DT.DIS.DPPG.CD'     , 'Disbursements on external debt, public and publicly guaranteed (PPG) (DIS, current US$)'            , ['Debt']                 ], 
    ['DT.DIS.IDAG.CD'     , 'IDA grants (current US$)'                                                                           , ['Aid', 'Debt']          ], 
    ['DT.DIS.MIBR.CD'     , 'PPG, IBRD (DIS, current US$)'                                                                       , ['Debt']                 ], 
    ['DT.DIS.MIDA.CD'     , 'PPG, IDA (DIS, current US$)'                                                                        , ['Debt']                 ], 
    ['DT.DIS.MLAT.CD'     , 'PPG, multilateral (DIS, current US$)'                                                               , ['Debt']                 ], 
    ['DT.DIS.MLAT.GG.CD'  , 'GG, multilateral (DIS, current US$)'                                                                , ['Debt']                 ], 
    ['DT.DIS.MLAT.OPS.CD' , 'OPS, multilateral (DIS, current US$)'                                                               , ['Debt']                 ], 
    ['DT.DIS.MLAT.PRVG.CD', 'PRVG, multilateral (DIS, current US$)'                                                              , ['Debt']                 ], 
    ['DT.DIS.MLAT.PS.CD'  , 'PS, multilateral (DIS, current US$)'                                                                , ['Debt']                 ], 
    ['DT.DIS.MLTC.CD'     , 'PPG, multilateral concessional (DIS, current US$)'                                                  , ['Debt']                 ], 
    ['DT.DIS.MLTC.GG.CD'  , 'GG, multilateral concessional (DIS, current US$)'                                                   , ['Debt']                 ], 
    ['DT.DIS.MLTC.OPS.CD' , 'OPS, multilateral concessional (DIS, current US$)'                                                  , ['Debt']                 ], 
    ['DT.DIS.MLTC.PRVG.CD', 'PRVG, multilateral concessional (DIS, current US$)'                                                 , ['Debt']                 ], 
    ['DT.DIS.MLTC.PS.CD'  , 'PS, multilateral concessional (DIS, current US$)'                                                   , ['Debt']                 ], 
    ['DT.DIS.OFFT.CD'     , 'PPG, official creditors (DIS, current US$)'                                                         , ['Debt']                 ], 
    ['DT.DIS.OFFT.GG.CD'  , 'GG, official creditors (DIS, current US$)'                                                          , ['Debt']                 ], 
    ['DT.DIS.OFFT.OPS.CD' , 'OPS, official creditors (DIS, current US$)'                                                         , ['Debt']                 ], 
    ['DT.DIS.OFFT.PRVG.CD', 'PRVG, official creditors (DIS, current US$)'                                                        , ['Debt']                 ], 
    ['DT.DIS.OFFT.PS.CD'  , 'PS, official creditors (DIS, current US$)'                                                          , ['Debt']                 ], 
    ['DT.DIS.PBND.CD'     , 'PPG, bonds (DIS, current US$)'                                                                      , ['Debt']                 ], 
    ['DT.DIS.PBND.GG.CD'  , 'GG, bonds (DIS, current US$)'                                                                       , ['Debt']                 ], 
    ['DT.DIS.PBND.OPS.CD' , 'OPS, bonds (DIS, current US$)'                                                                      , ['Debt']                 ], 
    ['DT.DIS.PBND.PRVG.CD', 'PRVG, bonds (DIS, current US$)'                                                                     , ['Debt']                 ], 
    ['DT.DIS.PBND.PS.CD'  , 'PS, bonds (DIS, current US$)'                                                                       , ['Debt']                 ], 
    ['DT.DIS.PCBK.CD'     , 'PPG, commercial banks (DIS, current US$)'                                                           , ['Debt']                 ], 
    ['DT.DIS.PCBK.GG.CD'  , 'GG, commercial banks (DIS, current US$)'                                                            , ['Debt']                 ], 
    ['DT.DIS.PCBK.OPS.CD' , 'OPS, commercial banks (DIS, current US$)'                                                           , ['Debt']                 ], 
    ['DT.DIS.PCBK.PRVG.CD', 'PRVG, commercial banks (DIS, current US$)'                                                          , ['Debt']                 ], 
    ['DT.DIS.PCBK.PS.CD'  , 'PS, commercial banks (DIS, current US$)'                                                            , ['Debt']                 ], 
    ['DT.DIS.PNGB.CD'     , 'PNG, bonds (DIS, current US$)'                                                                      , ['Debt']                 ], 
    ['DT.DIS.PNGC.CD'     , 'PNG, commercial banks and other creditors (DIS, current US$)'                                       , ['Debt']                 ], 
    ['DT.DIS.PROP.CD'     , 'PPG, other private creditors (DIS, current US$)'                                                    , ['Debt']                 ], 
    ['DT.DIS.PROP.GG.CD'  , 'GG, other private creditors (DIS, current US$)'                                                     , ['Debt']                 ], 
    ['DT.DIS.PROP.OPS.CD' , 'OPS, other private creditors (DIS, current US$)'                                                    , ['Debt']                 ], 
    ['DT.DIS.PROP.PRVG.CD', 'PRVG, other private creditors (DIS, current US$)'                                                   , ['Debt']                 ], 
    ['DT.DIS.PROP.PS.CD'  , 'PS, other private creditors (DIS, current US$)'                                                     , ['Debt']                 ], 
    ['DT.DIS.PRPG.CD'     , 'Disbursements on external debt, private guaranteed by public sector (PPG) (DIS, current US$)'       , ['Debt']                 ], 
    ['DT.DIS.PRVT.CD'     , 'PPG, private creditors (DIS, current US$)'                                                          , ['Debt']                 ], 
    ['DT.DIS.PRVT.GG.CD'  , 'GG, private creditors (DIS, current US$)'                                                           , ['Debt']                 ], 
    ['DT.DIS.PRVT.OPS.CD' , 'OPS, private creditors (DIS, current US$)'                                                          , ['Debt']                 ], 
    ['DT.DIS.PRVT.PRVG.CD', 'PRVG, private creditors (DIS, current US$)'                                                         , ['Debt']                 ], 
    ['DT.DIS.PRVT.PS.CD'  , 'PS, private creditors (DIS, current US$)'                                                           , ['Debt']                 ], 
    ['DT.DOD.ALLC.CD'     , 'External debt stocks, concessional (DOD, current US$)'                                              , ['Debt']                 ], 
    ['DT.DOD.ALLC.ZS'     , 'Concessional debt (% of total external debt)'                                                       , ['Debt']                 ], 
    ['DT.DOD.BLAT.CD'     , 'PPG, bilateral (DOD, current US$)'                                                                  , ['Debt']                 ], 
    ['DT.DOD.BLAT.GG.CD'  , 'GG, bilateral (DOD, current US$)'                                                                   , ['Debt']                 ], 
    ['DT.DOD.BLAT.OPS.CD' , 'OPS, bilateral (DOD, current US$)'                                                                  , ['Debt']                 ], 
    ['DT.DOD.BLAT.PRVG.CD', 'PRVG, bilateral (DOD, current US$)'                                                                 , ['Debt']                 ], 
    ['DT.DOD.BLAT.PS.CD'  , 'PS, bilateral (DOD, current US$)'                                                                   , ['Debt']                 ], 
    ['DT.DOD.BLTC.CD'     , 'PPG, bilateral concessional (DOD, current US$)'                                                     , ['Debt']                 ], 
    ['DT.DOD.BLTC.GG.CD'  , 'GG, bilateral concessional (DOD, current US$)'                                                      , ['Debt']                 ], 
    ['DT.DOD.BLTC.OPS.CD' , 'OPS, bilateral concessional (DOD, current US$)'                                                     , ['Debt']                 ], 
    ['DT.DOD.BLTC.PRVG.CD', 'PRVG, bilateral concessional (DOD, current US$)'                                                    , ['Debt']                 ], 
    ['DT.DOD.BLTC.PS.CD'  , 'PS, bilateral concessional (DOD, current US$)'                                                      , ['Debt']                 ], 
    ['DT.DOD.DECT.CD'     , 'External debt stocks, total (DOD, current US$)'                                                     , ['Econ', 'Debt']         ], 
    ['DT.DOD.DECT.CD.CG'  , 'Total change in external debt stocks (current US$)'                                                 , ['Debt']                 ], 
    ['DT.DOD.DECT.EX.ZS'  , 'External debt stocks (% of exports of goods, services and primary income)'                          , ['Econ', 'Debt']         ], 
    ['DT.DOD.DECT.GN.ZS'  , 'External debt stocks (% of GNI)'                                                                    , ['Econ', 'Debt']         ], 
    ['DT.DOD.DEGG.CD'     , 'External debt stocks, general government sector (PPG) (DOD, current US$)'                           , ['Debt']                 ], 
    ['DT.DOD.DEPS.CD'     , 'External debt stocks, public sector (PPG) (DOD, current US$)'                                       , ['Debt']                 ], 
    ['DT.DOD.DIMF.CD'     , 'Use of IMF credit (DOD, current US$)'                                                               , ['Debt']                 ], 
    ['DT.DOD.DLXF.CD'     , 'External debt stocks, long-term (DOD, current US$)'                                                 , ['Debt']                 ], 
    ['DT.DOD.DOPS.CD'     , 'External debt stocks, other public sector (PPG) (DOD, current US$)'                                 , ['Debt']                 ], 
    ['DT.DOD.DPNG.CD'     , 'External debt stocks, private nonguaranteed (PNG) (DOD, current US$)'                               , ['Debt']                 ], 
    ['DT.DOD.DPPG.CD'     , 'External debt stocks, public and publicly guaranteed (PPG) (DOD, current US$)'                      , ['Debt']                 ], 
    ['DT.DOD.DSDR.CD'     , 'Use of IMF credit, SDR allocations (DOD, current US$)'                                              , ['Debt']                 ], 
    ['DT.DOD.DSTC.CD'     , 'External debt stocks, short-term (DOD, current US$)'                                                , ['Debt']                 ], 
    ['DT.DOD.DSTC.ZS'     , 'Short-term debt (% of total external debt)'                                                         , ['Debt']                 ], 
    ['DT.DOD.MDRI.CD'     , 'Debt forgiveness grants (current US$)'                                                              , ['Aid', 'Debt']          ], 
    ['DT.DOD.MIBR.CD'     , 'PPG, IBRD (DOD, current US$)'                                                                       , ['Debt']                 ], 
    ['DT.DOD.MIDA.CD'     , 'PPG, IDA (DOD, current US$)'                                                                        , ['Debt']                 ], 
    ['DT.DOD.MLAT.CD'     , 'PPG, multilateral (DOD, current US$)'                                                               , ['Debt']                 ], 
    ['DT.DOD.MLAT.GG.CD'  , 'GG, multilateral (DOD, current US$)'                                                                , ['Debt']                 ], 
    ['DT.DOD.MLAT.OPS.CD' , 'OPS, multilateral (DOD, current US$)'                                                               , ['Debt']                 ], 
    ['DT.DOD.MLAT.PRVG.CD', 'PRVG, multilateral (DOD, current US$)'                                                              , ['Debt']                 ], 
    ['DT.DOD.MLAT.PS.CD'  , 'PS, multilateral (DOD, current US$)'                                                                , ['Debt']                 ], 
    ['DT.DOD.MLAT.ZS'     , 'Multilateral debt (% of total external debt)'                                                       , ['Debt']                 ], 
    ['DT.DOD.MLTC.CD'     , 'PPG, multilateral concessional (DOD, current US$)'                                                  , ['Debt']                 ], 
    ['DT.DOD.MLTC.GG.CD'  , 'GG, multilateral concessional (DOD, current US$)'                                                   , ['Debt']                 ], 
    ['DT.DOD.MLTC.OPS.CD' , 'OPS, multilateral concessional (DOD, current US$)'                                                  , ['Debt']                 ], 
    ['DT.DOD.MLTC.PRVG.CD', 'PRVG, multilateral concessional (DOD, current US$)'                                                 , ['Debt']                 ], 
    ['DT.DOD.MLTC.PS.CD'  , 'PS, multilateral concessional (DOD, current US$)'                                                   , ['Debt']                 ], 
    ['DT.DOD.OFFT.CD'     , 'PPG, official creditors (DOD, current US$)'                                                         , ['Debt']                 ], 
    ['DT.DOD.OFFT.GG.CD'  , 'GG, official creditors (DOD, current US$)'                                                          , ['Debt']                 ], 
    ['DT.DOD.OFFT.OPS.CD' , 'OPS, official creditors (DOD, current US$)'                                                         , ['Debt']                 ], 
    ['DT.DOD.OFFT.PRVG.CD', 'PRVG, official creditors (DOD, current US$)'                                                        , ['Debt']                 ], 
    ['DT.DOD.OFFT.PS.CD'  , 'PS, official creditors (DOD, current US$)'                                                          , ['Debt']                 ], 
    ['DT.DOD.PBND.CD'     , 'PPG, bonds (DOD, current US$)'                                                                      , ['Debt']                 ], 
    ['DT.DOD.PBND.GG.CD'  , 'GG, bonds (DOD, current US$)'                                                                       , ['Debt']                 ], 
    ['DT.DOD.PBND.OPS.CD' , 'OPS, bonds (DOD, current US$)'                                                                      , ['Debt']                 ], 
    ['DT.DOD.PBND.PRVG.CD', 'PRVG, bonds (DOD, current US$)'                                                                     , ['Debt']                 ], 
    ['DT.DOD.PBND.PS.CD'  , 'PS, bonds (DOD, current US$)'                                                                       , ['Debt']                 ], 
    ['DT.DOD.PCBK.CD'     , 'PPG, commercial banks (DOD, current US$)'                                                           , ['Debt']                 ], 
    ['DT.DOD.PCBK.GG.CD'  , 'GG, commercial banks (DOD, current US$)'                                                            , ['Debt']                 ], 
    ['DT.DOD.PCBK.OPS.CD' , 'OPS, commercial banks (DOD, current US$)'                                                           , ['Debt']                 ], 
    ['DT.DOD.PCBK.PRVG.CD', 'PRVG, commercial banks (DOD, current US$)'                                                          , ['Debt']                 ], 
    ['DT.DOD.PCBK.PS.CD'  , 'PS, commercial banks (DOD, current US$)'                                                            , ['Debt']                 ], 
    ['DT.DOD.PNGB.CD'     , 'PNG, bonds (DOD, current US$)'                                                                      , ['Debt']                 ], 
    ['DT.DOD.PNGC.CD'     , 'PNG, commercial banks and other creditors (DOD, current US$)'                                       , ['Debt']                 ], 
    ['DT.DOD.PROP.CD'     , 'PPG, other private creditors (DOD, current US$)'                                                    , ['Debt']                 ], 
    ['DT.DOD.PROP.GG.CD'  , 'GG, other private creditors (DOD, current US$)'                                                     , ['Debt']                 ], 
    ['DT.DOD.PROP.OPS.CD' , 'OPS, other private creditors (DOD, current US$)'                                                    , ['Debt']                 ], 
    ['DT.DOD.PROP.PRVG.CD', 'PRVG, other private creditors (DOD, current US$)'                                                   , ['Debt']                 ], 
    ['DT.DOD.PROP.PS.CD'  , 'PS, other private creditors (DOD, current US$)'                                                     , ['Debt']                 ], 
    ['DT.DOD.PRPG.CD'     , 'External debt stocks, private guaranteed by public sector (PPG) (DOD, current US$)'                 , ['Debt']                 ], 
    ['DT.DOD.PRVS.CD'     , 'External debt stocks, long-term private sector (DOD, current US$)'                                  , ['Debt']                 ], 
    ['DT.DOD.PRVT.CD'     , 'PPG, private creditors (DOD, current US$)'                                                          , ['Debt']                 ], 
    ['DT.DOD.PRVT.GG.CD'  , 'GG, private creditors (DOD, current US$)'                                                           , ['Debt']                 ], 
    ['DT.DOD.PRVT.OPS.CD' , 'OPS, private creditors (DOD, current US$)'                                                          , ['Debt']                 ], 
    ['DT.DOD.PRVT.PRVG.CD', 'PRVG, private creditors (DOD, current US$)'                                                         , ['Debt']                 ], 
    ['DT.DOD.PRVT.PS.CD'  , 'PS, private creditors (DOD, current US$)'                                                           , ['Debt']                 ], 
    ['DT.DOD.PUBS.CD'     , 'External debt stocks, long-term public sector (DOD, current US$)'                                   , ['Debt']                 ], 
    ['DT.DOD.PVLX.CD'     , 'Present value of external debt (current US$)'                                                       , ['Econ', 'Debt']         ], 
    ['DT.DOD.RSDL.CD'     , 'Residual, debt stock-flow reconciliation (current US$)'                                             , ['Debt']                 ], 
    ['DT.DOD.VTOT.CD'     , 'External debt stocks, variable rate (DOD, current US$)'                                             , ['Debt']                 ], 
    ['DT.DSB.DPPG.CD'     , 'Debt buyback (current US$)'                                                                         , ['Debt']                 ], 
    ['DT.DSF.DPPG.CD'     , 'Debt stock reduction (current US$)'                                                                 , ['Debt']                 ], 
    ['DT.DXR.DPPG.CD'     , 'Debt stock rescheduled (current US$)'                                                               , ['Debt']                 ], 
    ['DT.GPA.DPPG'        , 'Average grace period on new external debt commitments (years)'                                      , ['Debt']                 ], 
    ['DT.GPA.OFFT'        , 'Average grace period on new external debt commitments, official (years)'                            , ['Debt']                 ], 
    ['DT.GPA.PRVT'        , 'Average grace period on new external debt commitments, private (years)'                             , ['Debt']                 ], 
    ['DT.GRE.DPPG'        , 'Average grant element on new external debt commitments (%)'                                         , ['Debt']                 ], 
    ['DT.GRE.OFFT'        , 'Average grant element on new external debt commitments, official (%)'                               , ['Debt']                 ], 
    ['DT.GRE.PRVT'        , 'Average grant element on new external debt commitments, private (%)'                                , ['Debt']                 ], 
    ['DT.INR.DPPG'        , 'Average interest on new external debt commitments (%)'                                              , ['Debt']                 ], 
    ['DT.INR.OFFT'        , 'Average interest on new external debt commitments, official (%)'                                    , ['Debt']                 ], 
    ['DT.INR.PRVT'        , 'Average interest on new external debt commitments, private (%)'                                     , ['Debt']                 ], 
    ['DT.INT.BLAT.CD'     , 'PPG, bilateral (INT, current US$)'                                                                  , ['Debt']                 ], 
    ['DT.INT.BLAT.GG.CD'  , 'GG, bilateral (INT, current US$)'                                                                   , ['Debt']                 ], 
    ['DT.INT.BLAT.OPS.CD' , 'OPS, bilateral (INT, current US$)'                                                                  , ['Debt']                 ], 
    ['DT.INT.BLAT.PRVG.CD', 'PRVG, bilateral (INT, current US$)'                                                                 , ['Debt']                 ], 
    ['DT.INT.BLAT.PS.CD'  , 'PS, bilateral (INT, current US$)'                                                                   , ['Debt']                 ], 
    ['DT.INT.BLTC.CD'     , 'PPG, bilateral concessional (INT, current US$)'                                                     , ['Debt']                 ], 
    ['DT.INT.BLTC.GG.CD'  , 'GG, bilateral concessional (INT, current US$)'                                                      , ['Debt']                 ], 
    ['DT.INT.BLTC.OPS.CD' , 'OPS, bilateral concessional (INT, current US$)'                                                     , ['Debt']                 ], 
    ['DT.INT.BLTC.PRVG.CD', 'PRVG, bilateral concessional (INT, current US$)'                                                    , ['Debt']                 ], 
    ['DT.INT.BLTC.PS.CD'  , 'PS, bilateral concessional (INT, current US$)'                                                      , ['Debt']                 ], 
    ['DT.INT.DECT.CD'     , 'Interest payments on external debt, total (INT, current US$)'                                       , ['Debt']                 ], 
    ['DT.INT.DECT.EX.ZS'  , 'Interest payments on external debt (% of exports of goods, services and primary income)'            , ['Econ', 'Debt']         ], 
    ['DT.INT.DECT.GN.ZS'  , 'Interest payments on external debt (% of GNI)'                                                      , ['Econ', 'Debt']         ], 
    ['DT.INT.DEGG.CD'     , 'Interest payments on external debt, general government sector (PPG) (INT, current US$)'             , ['Debt']                 ], 
    ['DT.INT.DEPS.CD'     , 'Interest payments on external debt, public sector (PPG) (INT, current US$)'                         , ['Debt']                 ], 
    ['DT.INT.DIMF.CD'     , 'IMF charges (INT, current US$)'                                                                     , ['Debt']                 ], 
    ['DT.INT.DLXF.CD'     , 'Interest payments on external debt, long-term (INT, current US$)'                                   , ['Debt']                 ], 
    ['DT.INT.DOPS.CD'     , 'Interest payments on external debt, other public sector (PPG) (INT, current US$)'                   , ['Debt']                 ], 
    ['DT.INT.DPNG.CD'     , 'Interest payments on external debt, private nonguaranteed (PNG) (INT, current US$)'                 , ['Debt']                 ], 
    ['DT.INT.DPPG.CD'     , 'Interest payments on external debt, public and publicly guaranteed (PPG) (INT, current US$)'        , ['Debt']                 ], 
    ['DT.INT.DSTC.CD'     , 'Interest payments on external debt, short-term (INT, current US$)'                                  , ['Debt']                 ], 
    ['DT.INT.MIBR.CD'     , 'PPG, IBRD (INT, current US$)'                                                                       , ['Debt']                 ], 
    ['DT.INT.MIDA.CD'     , 'PPG, IDA (INT, current US$)'                                                                        , ['Debt']                 ], 
    ['DT.INT.MLAT.CD'     , 'PPG, multilateral (INT, current US$)'                                                               , ['Debt']                 ], 
    ['DT.INT.MLAT.GG.CD'  , 'GG, multilateral (INT, current US$)'                                                                , ['Debt']                 ], 
    ['DT.INT.MLAT.OPS.CD' , 'OPS, multilateral (INT, current US$)'                                                               , ['Debt']                 ], 
    ['DT.INT.MLAT.PRVG.CD', 'PRVG, multilateral (INT, current US$)'                                                              , ['Debt']                 ], 
    ['DT.INT.MLAT.PS.CD'  , 'PS, multilateral (INT, current US$)'                                                                , ['Debt']                 ], 
    ['DT.INT.MLTC.CD'     , 'PPG, multilateral concessional (INT, current US$)'                                                  , ['Debt']                 ], 
    ['DT.INT.MLTC.GG.CD'  , 'GG, multilateral concessional (INT, current US$)'                                                   , ['Debt']                 ], 
    ['DT.INT.MLTC.OPS.CD' , 'OPS, multilateral concessional (INT, current US$)'                                                  , ['Debt']                 ], 
    ['DT.INT.MLTC.PRVG.CD', 'PRVG, multilateral concessional (INT, current US$)'                                                 , ['Debt']                 ], 
    ['DT.INT.MLTC.PS.CD'  , 'PS, multilateral concessional (INT, current US$)'                                                   , ['Debt']                 ], 
    ['DT.INT.OFFT.CD'     , 'PPG, official creditors (INT, current US$)'                                                         , ['Debt']                 ], 
    ['DT.INT.OFFT.GG.CD'  , 'GG, official creditors (INT, current US$)'                                                          , ['Debt']                 ], 
    ['DT.INT.OFFT.OPS.CD' , 'OPS, official creditors (INT, current US$)'                                                         , ['Debt']                 ], 
    ['DT.INT.OFFT.PRVG.CD', 'PRVG, official creditors (INT, current US$)'                                                        , ['Debt']                 ], 
    ['DT.INT.OFFT.PS.CD'  , 'PS, official creditors (INT, current US$)'                                                          , ['Debt']                 ], 
    ['DT.INT.PBND.CD'     , 'PPG, bonds (INT, current US$)'                                                                      , ['Debt']                 ], 
    ['DT.INT.PBND.GG.CD'  , 'GG, bonds (INT, current US$)'                                                                       , ['Debt']                 ], 
    ['DT.INT.PBND.OPS.CD' , 'OPS, bonds (INT, current US$)'                                                                      , ['Debt']                 ], 
    ['DT.INT.PBND.PRVG.CD', 'PRVG, bonds (INT, current US$)'                                                                     , ['Debt']                 ], 
    ['DT.INT.PBND.PS.CD'  , 'PS, bonds (INT, current US$)'                                                                       , ['Debt']                 ], 
    ['DT.INT.PCBK.CD'     , 'PPG, commercial banks (INT, current US$)'                                                           , ['Debt']                 ], 
    ['DT.INT.PCBK.GG.CD'  , 'GG, commercial banks (INT, current US$)'                                                            , ['Debt']                 ], 
    ['DT.INT.PCBK.OPS.CD' , 'OPS, commercial banks (INT, current US$)'                                                           , ['Debt']                 ], 
    ['DT.INT.PCBK.PRVG.CD', 'PRVG, commercial banks (INT, current US$)'                                                          , ['Debt']                 ], 
    ['DT.INT.PCBK.PS.CD'  , 'PS, commercial banks (INT, current US$)'                                                            , ['Debt']                 ], 
    ['DT.INT.PNGB.CD'     , 'PNG, bonds (INT, current US$)'                                                                      , ['Debt']                 ], 
    ['DT.INT.PNGC.CD'     , 'PNG, commercial banks and other creditors (INT, current US$)'                                       , ['Debt']                 ], 
    ['DT.INT.PROP.CD'     , 'PPG, other private creditors (INT, current US$)'                                                    , ['Debt']                 ], 
    ['DT.INT.PROP.GG.CD'  , 'GG, other private creditors (INT, current US$)'                                                     , ['Debt']                 ], 
    ['DT.INT.PROP.OPS.CD' , 'OPS, other private creditors (INT, current US$)'                                                    , ['Debt']                 ], 
    ['DT.INT.PROP.PRVG.CD', 'PRVG, other private creditors (INT, current US$)'                                                   , ['Debt']                 ], 
    ['DT.INT.PROP.PS.CD'  , 'PS, other private creditors (INT, current US$)'                                                     , ['Debt']                 ], 
    ['DT.INT.PRPG.CD'     , 'Interest payments on external debt, private guaranteed by public sector (PPG) (INT, current US$)'   , ['Debt']                 ], 
    ['DT.INT.PRVT.CD'     , 'PPG, private creditors (INT, current US$)'                                                          , ['Debt']                 ], 
    ['DT.INT.PRVT.GG.CD'  , 'GG, private creditors (INT, current US$)'                                                           , ['Debt']                 ], 
    ['DT.INT.PRVT.OPS.CD' , 'OPS, private creditors (INT, current US$)'                                                          , ['Debt']                 ], 
    ['DT.INT.PRVT.PRVG.CD', 'PRVG, private creditors (INT, current US$)'                                                         , ['Debt']                 ], 
    ['DT.INT.PRVT.PS.CD'  , 'PS, private creditors (INT, current US$)'                                                           , ['Debt']                 ], 
    ['DT.IXA.DPPG.CD'     , 'Interest arrears, long-term DOD (US$)'                                                              , ['Debt']                 ], 
    ['DT.IXA.DPPG.CD.CG'  , 'Net change in interest arrears (current US$)'                                                       , ['Debt']                 ], 
    ['DT.IXA.OFFT.CD'     , 'Interest arrears, official creditors (current US$)'                                                 , ['Debt']                 ], 
    ['DT.IXA.PRVT.CD'     , 'Interest arrears, private creditors (current US$)'                                                  , ['Debt']                 ], 
    ['DT.IXF.DPPG.CD'     , 'Interest forgiven (current US$)'                                                                    , ['Debt']                 ], 
    ['DT.IXR.DPPG.CD'     , 'Interest rescheduled (capitalized) (current US$)'                                                   , ['Debt']                 ], 
    ['DT.IXR.OFFT.CD'     , 'Interest rescheduled, official (current US$)'                                                       , ['Debt']                 ], 
    ['DT.IXR.PRVT.CD'     , 'Interest rescheduled, private (current US$)'                                                        , ['Debt']                 ], 
    ['DT.MAT.DPPG'        , 'Average maturity on new external debt commitments (years)'                                          , ['Debt']                 ], 
    ['DT.MAT.OFFT'        , 'Average maturity on new external debt commitments, official (years)'                                , ['Debt']                 ], 
    ['DT.MAT.PRVT'        , 'Average maturity on new external debt commitments, private (years)'                                 , ['Debt']                 ], 
    ['DT.NFL.BLAT.CD'     , 'Net financial flows, bilateral (NFL, current US$)'                                                  , ['Debt']                 ], 
    ['DT.NFL.BLAT.GG.CD'  , 'GG, bilateral (NFL, current US$)'                                                                   , ['Debt']                 ], 
    ['DT.NFL.BLAT.OPS.CD' , 'OPS, bilateral (NFL, current US$)'                                                                  , ['Debt']                 ], 
    ['DT.NFL.BLAT.PRVG.CD', 'PRVG, bilateral (NFL, current US$)'                                                                 , ['Debt']                 ], 
    ['DT.NFL.BLAT.PS.CD'  , 'PS, bilateral (NFL, current US$)'                                                                   , ['Debt']                 ], 
    ['DT.NFL.BLTC.CD'     , 'PPG, bilateral concessional (NFL, current US$)'                                                     , ['Debt']                 ], 
    ['DT.NFL.BLTC.GG.CD'  , 'GG, bilateral concessional (NFL, current US$)'                                                      , ['Debt']                 ], 
    ['DT.NFL.BLTC.OPS.CD' , 'OPS, bilateral concessional (NFL, current US$)'                                                     , ['Debt']                 ], 
    ['DT.NFL.BLTC.PRVG.CD', 'PRVG, bilateral concessional (NFL, current US$)'                                                    , ['Debt']                 ], 
    ['DT.NFL.BLTC.PS.CD'  , 'PS, bilateral concessional (NFL, current US$)'                                                      , ['Debt']                 ], 
    ['DT.NFL.DECT.CD'     , 'Net flows on external debt, total (NFL, current US$)'                                               , ['Debt']                 ], 
    ['DT.NFL.DEGG.CD'     , 'Net flows on external debt, general government sector (PPG) (NFL, current US$)'                     , ['Debt']                 ], 
    ['DT.NFL.DEPS.CD'     , 'Net flows on external debt, public sector (PPG) (NFL, current US$)'                                 , ['Debt']                 ], 
    ['DT.NFL.DLXF.CD'     , 'Net flows on external debt, long-term (NFL, current US$)'                                           , ['Debt']                 ], 
    ['DT.NFL.DOPS.CD'     , 'Net flows on external debt, other public sector (PPG) (NFL, current US$)'                           , ['Debt']                 ], 
    ['DT.NFL.DPNG.CD'     , 'Net flows on external debt, private nonguaranteed (PNG) (NFL, current US$)'                         , ['Debt']                 ], 
    ['DT.NFL.DPPG.CD'     , 'Net flows on external debt, public and publicly guaranteed (PPG) (NFL, current US$)'                , ['Debt']                 ], 
    ['DT.NFL.DSTC.CD'     , 'Net flows on external debt, short-term (NFL, current US$)'                                          , ['Debt']                 ], 
    ['DT.NFL.IMFC.CD'     , 'Net financial flows, IMF concessional (NFL, current US$)'                                           , ['Debt']                 ], 
    ['DT.NFL.IMFN.CD'     , 'Net financial flows, IMF nonconcessional (NFL, current US$)'                                        , ['Debt']                 ], 
    ['DT.NFL.MIBR.CD'     , 'Net financial flows, IBRD (NFL, current US$)'                                                       , ['Debt']                 ], 
    ['DT.NFL.MIDA.CD'     , 'Net financial flows, IDA (NFL, current US$)'                                                        , ['Debt']                 ], 
    ['DT.NFL.MLAT.CD'     , 'Net financial flows, multilateral (NFL, current US$)'                                               , ['Debt']                 ], 
    ['DT.NFL.MLAT.GG.CD'  , 'GG, multilateral (NFL, current US$)'                                                                , ['Debt']                 ], 
    ['DT.NFL.MLAT.OPS.CD' , 'OPS, multilateral (NFL, current US$)'                                                               , ['Debt']                 ], 
    ['DT.NFL.MLAT.PRVG.CD', 'PRVG, multilateral (NFL, current US$)'                                                              , ['Debt']                 ], 
    ['DT.NFL.MLAT.PS.CD'  , 'PS, multilateral (NFL, current US$)'                                                                , ['Debt']                 ], 
    ['DT.NFL.MLTC.CD'     , 'PPG, multilateral concessional (NFL, current US$)'                                                  , ['Debt']                 ], 
    ['DT.NFL.MLTC.GG.CD'  , 'GG, multilateral concessional (NFL, current US$)'                                                   , ['Debt']                 ], 
    ['DT.NFL.MLTC.OPS.CD' , 'OPS, multilateral concessional (NFL, current US$)'                                                  , ['Debt']                 ], 
    ['DT.NFL.MLTC.PRVG.CD', 'PRVG, multilateral concessional (NFL, current US$)'                                                 , ['Debt']                 ], 
    ['DT.NFL.MLTC.PS.CD'  , 'PS, multilateral concessional (NFL, current US$)'                                                   , ['Debt']                 ], 
    ['DT.NFL.MOTH.CD'     , 'Net financial flows, others (NFL, current US$)'                                                     , ['Debt']                 ], 
    ['DT.NFL.NEBR.CD'     , 'EBRD, private nonguaranteed (NFL, current US$)'                                                     , ['Debt']                 ], 
    ['DT.NFL.NIFC.CD'     , 'IFC, private nonguaranteed (NFL, current US$)'                                                      , ['Debt']                 ], 
    ['DT.NFL.OFFT.CD'     , 'PPG, official creditors (NFL, current US$)'                                                         , ['Debt']                 ], 
    ['DT.NFL.OFFT.GG.CD'  , 'GG, official creditors (NFL, current US$)'                                                          , ['Debt']                 ], 
    ['DT.NFL.OFFT.OPS.CD' , 'OPS, official creditors (NFL, current US$)'                                                         , ['Debt']                 ], 
    ['DT.NFL.OFFT.PRVG.CD', 'PRVG, official creditors (NFL, current US$)'                                                        , ['Debt']                 ], 
    ['DT.NFL.OFFT.PS.CD'  , 'PS, official creditors (NFL, current US$)'                                                          , ['Debt']                 ], 
    ['DT.NFL.PBND.CD'     , 'PPG, bonds (NFL, current US$)'                                                                      , ['Debt']                 ], 
    ['DT.NFL.PBND.GG.CD'  , 'GG, bonds (NFL, current US$)'                                                                       , ['Debt']                 ], 
    ['DT.NFL.PBND.OPS.CD' , 'OPS, bonds (NFL, current US$)'                                                                      , ['Debt']                 ], 
    ['DT.NFL.PBND.PRVG.CD', 'PRVG, bonds (NFL, current US$)'                                                                     , ['Debt']                 ], 
    ['DT.NFL.PBND.PS.CD'  , 'PS, bonds (NFL, current US$)'                                                                       , ['Debt']                 ], 
    ['DT.NFL.PCBK.CD'     , 'PPG, commercial banks (NFL, current US$)'                                                           , ['Debt']                 ], 
    ['DT.NFL.PCBK.GG.CD'  , 'GG, commercial banks (NFL, current US$)'                                                            , ['Debt']                 ], 
    ['DT.NFL.PCBK.OPS.CD' , 'OPS, commercial banks (NFL, current US$)'                                                           , ['Debt']                 ], 
    ['DT.NFL.PCBK.PRVG.CD', 'PRVG, commercial banks (NFL, current US$)'                                                          , ['Debt']                 ], 
    ['DT.NFL.PCBK.PS.CD'  , 'PS, commercial banks (NFL, current US$)'                                                            , ['Debt']                 ], 
    ['DT.NFL.PNGB.CD'     , 'PNG, bonds (NFL, current US$)'                                                                      , ['Debt']                 ], 
    ['DT.NFL.PNGC.CD'     , 'PNG, commercial banks and other creditors (NFL, current US$)'                                       , ['Debt']                 ], 
    ['DT.NFL.PROP.CD'     , 'PPG, other private creditors (NFL, current US$)'                                                    , ['Debt']                 ], 
    ['DT.NFL.PROP.GG.CD'  , 'GG, other private creditors (NFL, current US$)'                                                     , ['Debt']                 ], 
    ['DT.NFL.PROP.OPS.CD' , 'OPS, other private creditors (NFL, current US$)'                                                    , ['Debt']                 ], 
    ['DT.NFL.PROP.PRVG.CD', 'PRVG, other private creditors (NFL, current US$)'                                                   , ['Debt']                 ], 
    ['DT.NFL.PROP.PS.CD'  , 'PS, other private creditors (NFL, current US$)'                                                     , ['Debt']                 ], 
    ['DT.NFL.PRPG.CD'     , 'Net flows on external debt, private guaranteed by public sector (PPG) (NFL, current US$)'           , ['Debt']                 ], 
    ['DT.NFL.PRVT.CD'     , 'PPG, private creditors (NFL, current US$)'                                                          , ['Debt']                 ], 
    ['DT.NFL.PRVT.GG.CD'  , 'GG, private creditors (NFL, current US$)'                                                           , ['Debt']                 ], 
    ['DT.NFL.PRVT.OPS.CD' , 'OPS, private creditors (NFL, current US$)'                                                          , ['Debt']                 ], 
    ['DT.NFL.PRVT.PRVG.CD', 'PRVG, private creditors (NFL, current US$)'                                                         , ['Debt']                 ], 
    ['DT.NFL.PRVT.PS.CD'  , 'PS, private creditors (NFL, current US$)'                                                           , ['Debt']                 ], 
    ['DT.NFL.RDBC.CD'     , 'Net financial flows, RDB concessional (NFL, current US$)'                                           , ['Debt']                 ], 
    ['DT.NFL.RDBN.CD'     , 'Net financial flows, RDB nonconcessional (NFL, current US$)'                                        , ['Debt']                 ], 
    ['DT.NTR.BLAT.CD'     , 'PPG, bilateral (NTR, current US$)'                                                                  , ['Debt']                 ], 
    ['DT.NTR.BLAT.GG.CD'  , 'GG, bilateral (NTR, current US$)'                                                                   , ['Debt']                 ], 
    ['DT.NTR.BLAT.OPS.CD' , 'OPS, bilateral (NTR, current US$)'                                                                  , ['Debt']                 ], 
    ['DT.NTR.BLAT.PRVG.CD', 'PRVG, bilateral (NTR, current US$)'                                                                 , ['Debt']                 ], 
    ['DT.NTR.BLAT.PS.CD'  , 'PS, bilateral (NTR, current US$)'                                                                   , ['Debt']                 ], 
    ['DT.NTR.BLTC.CD'     , 'PPG, bilateral concessional (NTR, current US$)'                                                     , ['Debt']                 ], 
    ['DT.NTR.BLTC.GG.CD'  , 'GG, bilateral concessional (NTR, current US$)'                                                      , ['Debt']                 ], 
    ['DT.NTR.BLTC.OPS.CD' , 'OPS, bilateral concessional (NTR, current US$)'                                                     , ['Debt']                 ], 
    ['DT.NTR.BLTC.PRVG.CD', 'PRVG, bilateral concessional (NTR, current US$)'                                                    , ['Debt']                 ], 
    ['DT.NTR.BLTC.PS.CD'  , 'PS, bilateral concessional (NTR, current US$)'                                                      , ['Debt']                 ], 
    ['DT.NTR.DECT.CD'     , 'Net transfers on external debt, total (NTR, current US$)'                                           , ['Debt']                 ], 
    ['DT.NTR.DEGG.CD'     , 'Net transfers on external debt, general government sector (PPG) (NTR, current US$)'                 , ['Debt']                 ], 
    ['DT.NTR.DEPS.CD'     , 'Net transfers on external debt, public sector (PPG) (NTR, current US$)'                             , ['Debt']                 ], 
    ['DT.NTR.DLXF.CD'     , 'Net transfers on external debt, long-term (NTR, current US$)'                                       , ['Debt']                 ], 
    ['DT.NTR.DOPS.CD'     , 'Net transfers on external debt, other public sector (PPG) (NTR, current US$)'                       , ['Debt']                 ], 
    ['DT.NTR.DPNG.CD'     , 'Net transfers on external debt, private nonguaranteed (PNG) (NTR, current US$)'                     , ['Debt']                 ], 
    ['DT.NTR.DPPG.CD'     , 'Net transfers on external debt, public and publicly guaranteed (PPG) (NTR, current US$)'            , ['Debt']                 ], 
    ['DT.NTR.MIBR.CD'     , 'PPG, IBRD (NTR, current US$)'                                                                       , ['Debt']                 ], 
    ['DT.NTR.MIDA.CD'     , 'PPG, IDA (NTR, current US$)'                                                                        , ['Debt']                 ], 
    ['DT.NTR.MLAT.CD'     , 'PPG, multilateral (NTR, current US$)'                                                               , ['Debt']                 ], 
    ['DT.NTR.MLAT.GG.CD'  , 'GG, multilateral (NTR, current US$)'                                                                , ['Debt']                 ], 
    ['DT.NTR.MLAT.OPS.CD' , 'OPS, multilateral (NTR, current US$)'                                                               , ['Debt']                 ], 
    ['DT.NTR.MLAT.PRVG.CD', 'PRVG, multilateral (NTR, current US$)'                                                              , ['Debt']                 ], 
    ['DT.NTR.MLAT.PS.CD'  , 'PS, multilateral (NTR, current US$)'                                                                , ['Debt']                 ], 
    ['DT.NTR.MLTC.CD'     , 'PPG, multilateral concessional (NTR, current US$)'                                                  , ['Debt']                 ], 
    ['DT.NTR.MLTC.GG.CD'  , 'GG, multilateral concessional (NTR, current US$)'                                                   , ['Debt']                 ], 
    ['DT.NTR.MLTC.OPS.CD' , 'OPS, multilateral concessional (NTR, current US$)'                                                  , ['Debt']                 ], 
    ['DT.NTR.MLTC.PRVG.CD', 'PRVG, multilateral concessional (NTR, current US$)'                                                 , ['Debt']                 ], 
    ['DT.NTR.MLTC.PS.CD'  , 'PS, multilateral concessional (NTR, current US$)'                                                   , ['Debt']                 ], 
    ['DT.NTR.OFFT.CD'     , 'PPG, official creditors (NTR, current US$)'                                                         , ['Debt']                 ], 
    ['DT.NTR.OFFT.GG.CD'  , 'GG, official creditors (NTR, current US$)'                                                          , ['Debt']                 ], 
    ['DT.NTR.OFFT.OPS.CD' , 'OPS, official creditors (NTR, current US$)'                                                         , ['Debt']                 ], 
    ['DT.NTR.OFFT.PRVG.CD', 'PRVG, official creditors (NTR, current US$)'                                                        , ['Debt']                 ], 
    ['DT.NTR.OFFT.PS.CD'  , 'PS, official creditors (NTR, current US$)'                                                          , ['Debt']                 ], 
    ['DT.NTR.PBND.CD'     , 'PPG, bonds (NTR, current US$)'                                                                      , ['Debt']                 ], 
    ['DT.NTR.PBND.GG.CD'  , 'GG, bonds (NTR, current US$)'                                                                       , ['Debt']                 ], 
    ['DT.NTR.PBND.OPS.CD' , 'OPS, bonds (NTR, current US$)'                                                                      , ['Debt']                 ], 
    ['DT.NTR.PBND.PRVG.CD', 'PRVG, bonds (NTR, current US$)'                                                                     , ['Debt']                 ], 
    ['DT.NTR.PBND.PS.CD'  , 'PS, bonds (NTR, current US$)'                                                                       , ['Debt']                 ], 
    ['DT.NTR.PCBK.CD'     , 'PPG, commercial banks (NTR, current US$)'                                                           , ['Debt']                 ], 
    ['DT.NTR.PCBK.GG.CD'  , 'GG, commercial banks (NTR, current US$)'                                                            , ['Debt']                 ], 
    ['DT.NTR.PCBK.OPS.CD' , 'OPS, commercial banks (NTR, current US$)'                                                           , ['Debt']                 ], 
    ['DT.NTR.PCBK.PRVG.CD', 'PRVG, commercial banks (NTR, current US$)'                                                          , ['Debt']                 ], 
    ['DT.NTR.PCBK.PS.CD'  , 'PS, commercial banks (NTR, current US$)'                                                            , ['Debt']                 ], 
    ['DT.NTR.PNGB.CD'     , 'PNG, bonds (NTR, current US$)'                                                                      , ['Debt']                 ], 
    ['DT.NTR.PNGC.CD'     , 'PNG, commercial banks and other creditors (NTR, current US$)'                                       , ['Debt']                 ], 
    ['DT.NTR.PROP.CD'     , 'PPG, other private creditors (NTR, current US$)'                                                    , ['Debt']                 ], 
    ['DT.NTR.PROP.GG.CD'  , 'GG, other private creditors (NTR, current US$)'                                                     , ['Debt']                 ], 
    ['DT.NTR.PROP.OPS.CD' , 'OPS, other private creditors (NTR, current US$)'                                                    , ['Debt']                 ], 
    ['DT.NTR.PROP.PRVG.CD', 'PRVG, other private creditors (NTR, current US$)'                                                   , ['Debt']                 ], 
    ['DT.NTR.PROP.PS.CD'  , 'PS, other private creditors (NTR, current US$)'                                                     , ['Debt']                 ], 
    ['DT.NTR.PRPG.CD'     , 'Net transfers on external debt, private guaranteed by public sector (PPG) (NTR, current US$)'       , ['Debt']                 ], 
    ['DT.NTR.PRVT.CD'     , 'PPG, private creditors (NTR, current US$)'                                                          , ['Debt']                 ], 
    ['DT.NTR.PRVT.GG.CD'  , 'GG, private creditors (NTR, current US$)'                                                           , ['Debt']                 ], 
    ['DT.NTR.PRVT.OPS.CD' , 'OPS, private creditors (NTR, current US$)'                                                          , ['Debt']                 ], 
    ['DT.NTR.PRVT.PRVG.CD', 'PRVG, private creditors (NTR, current US$)'                                                         , ['Debt']                 ], 
    ['DT.NTR.PRVT.PS.CD'  , 'PS, private creditors (NTR, current US$)'                                                           , ['Debt']                 ], 
    ['DT.TDS.BLAT.CD'     , 'PPG, bilateral (TDS, current US$)'                                                                  , ['Debt']                 ], 
    ['DT.TDS.BLAT.GG.CD'  , 'GG, bilateral (TDS, current US$)'                                                                   , ['Debt']                 ], 
    ['DT.TDS.BLAT.OPS.CD' , 'OPS, bilateral (TDS, current US$)'                                                                  , ['Debt']                 ], 
    ['DT.TDS.BLAT.PRVG.CD', 'PRVG, bilateral (TDS, current US$)'                                                                 , ['Debt']                 ], 
    ['DT.TDS.BLAT.PS.CD'  , 'PS, bilateral (TDS, current US$)'                                                                   , ['Debt']                 ], 
    ['DT.TDS.BLTC.CD'     , 'PPG, bilateral concessional (TDS, current US$)'                                                     , ['Debt']                 ], 
    ['DT.TDS.BLTC.GG.CD'  , 'GG, bilateral concessional (TDS, current US$)'                                                      , ['Debt']                 ], 
    ['DT.TDS.BLTC.OPS.CD' , 'OPS, bilateral concessional (TDS, current US$)'                                                     , ['Debt']                 ], 
    ['DT.TDS.BLTC.PRVG.CD', 'PRVG, bilateral concessional (TDS, current US$)'                                                    , ['Debt']                 ], 
    ['DT.TDS.BLTC.PS.CD'  , 'PS, bilateral concessional (TDS, current US$)'                                                      , ['Debt']                 ], 
    ['DT.TDS.DECT.CD'     , 'Debt service on external debt, total (TDS, current US$)'                                            , ['Debt']                 ], 
    ['DT.TDS.DECT.EX.ZS'  , 'Total debt service (% of exports of goods, services and primary income)'                            , ['Econ', 'Debt']         ], 
    ['DT.TDS.DEGG.CD'     , 'Debt service on external debt, general government sector (PPG) (TDS, current US$)'                  , ['Debt']                 ], 
    ['DT.TDS.DEPS.CD'     , 'Debt service on external debt, public sector (PPG) (TDS, current US$)'                              , ['Debt']                 ], 
    ['DT.TDS.DIMF.CD'     , 'IMF repurchases and charges (TDS, current US$)'                                                     , ['Debt']                 ], 
    ['DT.TDS.DLXF.CD'     , 'Debt service on external debt, long-term (TDS, current US$)'                                        , ['Debt']                 ], 
    ['DT.TDS.DOPS.CD'     , 'Debt service on external debt, other public sector (PPG) (TDS, current US$)'                        , ['Debt']                 ], 
    ['DT.TDS.DPNG.CD'     , 'Debt service on external debt, private nonguaranteed (PNG) (TDS, current US$)'                      , ['Debt']                 ], 
    ['DT.TDS.DPPG.CD'     , 'Debt service on external debt, public and publicly guaranteed (PPG) (TDS, current US$)'             , ['Debt']                 ], 
    ['DT.TDS.MIBR.CD'     , 'PPG, IBRD (TDS, current US$)'                                                                       , ['Debt']                 ], 
    ['DT.TDS.MIDA.CD'     , 'PPG, IDA (TDS, current US$)'                                                                        , ['Debt']                 ], 
    ['DT.TDS.MLAT.CD'     , 'Multilateral debt service (TDS, current US$)'                                                       , ['Debt']                 ], 
    ['DT.TDS.MLAT.GG.CD'  , 'GG, multilateral (TDS, current US$)'                                                                , ['Debt']                 ], 
    ['DT.TDS.MLAT.OPS.CD' , 'OPS, multilateral (TDS, current US$)'                                                               , ['Debt']                 ], 
    ['DT.TDS.MLAT.PRVG.CD', 'PRVG, multilateral (TDS, current US$)'                                                              , ['Debt']                 ], 
    ['DT.TDS.MLAT.PS.CD'  , 'PS, multilateral (TDS, current US$)'                                                                , ['Debt']                 ], 
    ['DT.TDS.MLTC.CD'     , 'PPG, multilateral concessional (TDS, current US$)'                                                  , ['Debt']                 ], 
    ['DT.TDS.MLTC.GG.CD'  , 'GG, multilateral concessional (TDS, current US$)'                                                   , ['Debt']                 ], 
    ['DT.TDS.MLTC.OPS.CD' , 'OPS, multilateral concessional (TDS, current US$)'                                                  , ['Debt']                 ], 
    ['DT.TDS.MLTC.PRVG.CD', 'PRVG, multilateral concessional (TDS, current US$)'                                                 , ['Debt']                 ], 
    ['DT.TDS.MLTC.PS.CD'  , 'PS, multilateral concessional (TDS, current US$)'                                                   , ['Debt']                 ], 
    ['DT.TDS.OFFT.CD'     , 'PPG, official creditors (TDS, current US$)'                                                         , ['Debt']                 ], 
    ['DT.TDS.OFFT.GG.CD'  , 'GG, official creditors (TDS, current US$)'                                                          , ['Debt']                 ], 
    ['DT.TDS.OFFT.OPS.CD' , 'OPS, official creditors (TDS, current US$)'                                                         , ['Debt']                 ], 
    ['DT.TDS.OFFT.PRVG.CD', 'PRVG, official creditors (TDS, current US$)'                                                        , ['Debt']                 ], 
    ['DT.TDS.OFFT.PS.CD'  , 'PS, official creditors (TDS, current US$)'                                                          , ['Debt']                 ], 
    ['DT.TDS.PBND.CD'     , 'PPG, bonds (TDS, current US$)'                                                                      , ['Debt']                 ], 
    ['DT.TDS.PBND.GG.CD'  , 'GG, bonds (TDS, current US$)'                                                                       , ['Debt']                 ], 
    ['DT.TDS.PBND.OPS.CD' , 'OPS, bonds (TDS, current US$)'                                                                      , ['Debt']                 ], 
    ['DT.TDS.PBND.PRVG.CD', 'PRVG, bonds (TDS, current US$)'                                                                     , ['Debt']                 ], 
    ['DT.TDS.PBND.PS.CD'  , 'PS, bonds (TDS, current US$)'                                                                       , ['Debt']                 ], 
    ['DT.TDS.PCBK.CD'     , 'PPG, commercial banks (TDS, current US$)'                                                           , ['Debt']                 ], 
    ['DT.TDS.PCBK.GG.CD'  , 'GG, commercial banks (TDS, current US$)'                                                            , ['Debt']                 ], 
    ['DT.TDS.PCBK.OPS.CD' , 'OPS, commercial banks (TDS, current US$)'                                                           , ['Debt']                 ], 
    ['DT.TDS.PCBK.PRVG.CD', 'PRVG, commercial banks (TDS, current US$)'                                                          , ['Debt']                 ], 
    ['DT.TDS.PCBK.PS.CD'  , 'PS, commercial banks (TDS, current US$)'                                                            , ['Debt']                 ], 
    ['DT.TDS.PNGB.CD'     , 'PNG, bonds (TDS, current US$)'                                                                      , ['Debt']                 ], 
    ['DT.TDS.PNGC.CD'     , 'PNG, commercial banks and other creditors (TDS, current US$)'                                       , ['Debt']                 ], 
    ['DT.TDS.PROP.CD'     , 'PPG, other private creditors (TDS, current US$)'                                                    , ['Debt']                 ], 
    ['DT.TDS.PROP.GG.CD'  , 'GG, other private creditors (TDS, current US$)'                                                     , ['Debt']                 ], 
    ['DT.TDS.PROP.OPS.CD' , 'OPS, other private creditors (TDS, current US$)'                                                    , ['Debt']                 ], 
    ['DT.TDS.PROP.PRVG.CD', 'PRVG, other private creditors (TDS, current US$)'                                                   , ['Debt']                 ], 
    ['DT.TDS.PROP.PS.CD'  , 'PS, other private creditors (TDS, current US$)'                                                     , ['Debt']                 ], 
    ['DT.TDS.PRPG.CD'     , 'Debt service on external debt, private guaranteed by public sector (PPG) (TDS, current US$)'        , ['Debt']                 ], 
    ['DT.TDS.PRVT.CD'     , 'PPG, private creditors (TDS, current US$)'                                                          , ['Debt']                 ], 
    ['DT.TDS.PRVT.GG.CD'  , 'GG, private creditors (TDS, current US$)'                                                           , ['Debt']                 ], 
    ['DT.TDS.PRVT.OPS.CD' , 'OPS, private creditors (TDS, current US$)'                                                          , ['Debt']                 ], 
    ['DT.TDS.PRVT.PRVG.CD', 'PRVG, private creditors (TDS, current US$)'                                                         , ['Debt']                 ], 
    ['DT.TDS.PRVT.PS.CD'  , 'PS, private creditors (TDS, current US$)'                                                           , ['Debt']                 ], 
    ['DT.TXR.DPPG.CD'     , 'Total amount of debt rescheduled (current US$)'                                                     , ['Debt']                 ], 
    ['DT.UND.DPPG.CD'     , 'Undisbursed external debt, total (UND, current US$)'                                                , ['Debt']                 ], 
    ['DT.UND.OFFT.CD'     , 'Undisbursed external debt, official creditors (UND, current US$)'                                   , ['Debt']                 ], 
    ['DT.UND.PRVT.CD'     , 'Undisbursed external debt, private creditors (UND, current US$)'                                    , ['Debt']                 ], 
    ['FI.RES.TOTL.CD'     , 'Total reserves (includes gold, current US$)'                                                        , ['Econ', 'Fin', 'Debt']  ], 
    ['FI.RES.TOTL.DT.ZS'  , 'Total reserves (% of total external debt)'                                                          , ['Fin', 'Debt']          ], 
    ['FI.RES.TOTL.MO'     , 'Total reserves in months of imports'                                                                , ['Fin', 'Debt']          ], 
    ['NY.GNP.MKTP.CD'     , 'GNI (current US$)'                                                                                  , ['Econ', 'Debt']         ], 
  ], 
}