export const Jobs = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['BM.KLT.DINV.WD.GD.ZS', 'Foreign direct investment, net outflows (% of GDP)'                                                              , ['Econ', 'Fin']                     ], 
    ['BM.TRF.PWKR.CD.DT'   , 'Personal remittances, paid (current US$)'                                                                        , ['Econ', 'Fin']                     ], 
    ['BX.KLT.DINV.WD.GD.ZS', 'Foreign direct investment, net inflows (% of GDP)'                                                               , ['Econ', 'Fin', 'Climate']          ], 
    ['BX.TRF.PWKR.CD'      , 'Personal transfers, receipts (BoP, current US$)'                                                                 , ['Econ', 'Fin']                     ], 
    ['CM.MKT.LCAP.GD.ZS'   , 'Market capitalization of listed domestic companies (% of GDP)'                                                   , ['Fin']                             ], 
    ['EG.ELC.ACCS.ZS'      , 'Access to electricity (% of population)'                                                                         , ['Energy', 'Climate', 'Env']        ], 
    ['EG.USE.ELEC.KH.PC'   , 'Electric power consumption (kWh per capita)'                                                                     , ['Energy', 'Climate', 'Infras']     ], 
    ['EN.POP.DNST'         , 'Population density (people per sq. km of land area)'                                                             , ['Urban']                           ], 
    ['FB.ATM.TOTL.P5'      , 'Automated teller machines (ATMs) (per 100,000 adults)'                                                           , ['Fin']                             ], 
    ['FB.CBK.BRWR.P3'      , 'Borrowers from commercial banks (per 1,000 adults)'                                                              , ['Fin']                             ], 
    ['FP.CPI.TOTL'         , 'Consumer price index (2010 = 100)'                                                                               , ['Fin']                             ], 
    ['FP.CPI.TOTL.ZG'      , 'Inflation, consumer prices (annual %)'                                                                           , ['Econ', 'Fin']                     ], 
    ['FS.AST.DOMS.GD.ZS'   , 'Domestic credit provided by financial sector (% of GDP)'                                                         , ['Fin']                             ], 
    ['FS.AST.PRVT.GD.ZS'   , 'Domestic credit to private sector (% of GDP)'                                                                    , ['Fin', 'Private']                  ], 
    ['GB.XPD.RSDV.GD.ZS'   , 'Research and development expenditure (% of GDP)'                                                                 , ['Stem']                            ], 
    ['GC.TAX.TOTL.GD.ZS'   , 'Tax revenue (% of GDP)'                                                                                          , ['Public']                          ], 
    ['GC.TAX.YPKG.ZS'      , 'Taxes on income, profits and capital gains (% of total taxes)'                                                   , ['Public']                          ], 
    ['IC.BUS.EASE.XQ'      , 'Ease of doing business index (1=most business-friendly regulations)'                                             , ['Climate', 'Private']              ], 
    ['IC.BUS.NDNS.ZS'      , 'New business density (new registrations per 1,000 people ages 15-64)'                                            , ['Private']                         ], 
    ['IC.BUS.NREG'         , 'New businesses registered (number)'                                                                              , ['Private']                         ], 
    ['IC.CRD.INFO.XQ'      , 'Depth of credit information index (0=low to 8=high)'                                                             , ['Fin', 'Private']                  ], 
    ['IC.CRD.PRVT.ZS'      , 'Private credit bureau coverage (% of adults)'                                                                    , ['Fin', 'Private']                  ], 
    ['IC.CRD.PUBL.ZS'      , 'Public credit registry coverage (% of adults)'                                                                   , ['Fin', 'Private', 'Public']        ], 
    ['IC.FRM.CORR.ZS'      , 'Informal payments to public officials (% of firms)'                                                              , ['Private']                         ], 
    ['IC.FRM.DURS'         , 'Time required to obtain an operating license (days)'                                                             , ['Private']                         ], 
    ['IC.ISV.DURS'         , 'Time to resolve insolvency (years)'                                                                              , ['Private']                         ], 
    ['IC.LGL.DURS'         , 'Time required to enforce a contract (days)'                                                                      , ['Private']                         ], 
    ['IC.PRP.DURS'         , 'Time required to register property (days)'                                                                       , ['Private']                         ], 
    ['IC.REG.DURS'         , 'Time required to start a business (days)'                                                                        , ['Private']                         ], 
    ['IC.TAX.DURS'         , 'Time to prepare and pay taxes (hours)'                                                                           , ['Private', 'Public']               ], 
    ['IC.TAX.METG'         , 'Average number of visits or required meetings with tax officials (for affected firms)'                           , ['Private']                         ], 
    ['IC.TAX.PAYM'         , 'Tax payments (number)'                                                                                           , ['Private', 'Public']               ], 
    ['IQ.CPA.ECON.XQ'      , 'CPIA economic management cluster average (1=low to 6=high)'                                                      , ['Public']                          ], 
    ['IQ.CPA.FINS.XQ'      , 'CPIA financial sector rating (1=low to 6=high)'                                                                  , ['Public']                          ], 
    ['IQ.CPA.GNDR.XQ'      , 'CPIA gender equality rating (1=low to 6=high)'                                                                   , ['Public']                          ], 
    ['IQ.CPA.MACR.XQ'      , 'CPIA macroeconomic management rating (1=low to 6=high)'                                                          , ['Public']                          ], 
    ['IQ.CPA.PROP.XQ'      , 'CPIA property rights and rule-based governance rating (1=low to 6=high)'                                         , ['Public']                          ], 
    ['IQ.CPA.PROT.XQ'      , 'CPIA social protection rating (1=low to 6=high)'                                                                 , ['Public']                          ], 
    ['IQ.CPA.SOCI.XQ'      , 'CPIA policies for social inclusion/equity cluster average (1=low to 6=high)'                                     , ['Public']                          ], 
    ['IS.AIR.DPRT'         , 'Air transport, registered carrier departures worldwide'                                                          , ['Infras']                          ], 
    ['IT.CEL.SETS.P2'      , 'Mobile cellular subscriptions (per 100 people)'                                                                  , ['Infras']                          ], 
    ['IT.MLT.MAIN.P2'      , 'Fixed telephone subscriptions (per 100 people)'                                                                  , ['Infras']                          ], 
    ['IT.NET.BBND.P2'      , 'Fixed broadband subscriptions (per 100 people)'                                                                  , ['Infras']                          ], 
    ['IT.NET.USER.ZS'      , 'Individuals using the Internet (% of population)'                                                                , ['Infras']                          ], 
    ['NE.EXP.GNFS.KD.ZG'   , 'Exports of goods and services (annual % growth)'                                                                 , ['Econ', 'Trade']                   ], 
    ['NE.EXP.GNFS.ZS'      , 'Exports of goods and services (% of GDP)'                                                                        , ['Econ', 'Trade']                   ], 
    ['NE.GDI.FPRV.ZS'      , 'Gross fixed capital formation, private sector (% of GDP)'                                                        , ['Econ']                            ], 
    ['NE.GDI.TOTL.KD.ZG'   , 'Gross capital formation (annual % growth)'                                                                       , ['Econ']                            ], 
    ['NE.GDI.TOTL.ZS'      , 'Gross capital formation (% of GDP)'                                                                              , ['Econ']                            ], 
    ['NE.IMP.GNFS.ZS'      , 'Imports of goods and services (% of GDP)'                                                                        , ['Econ', 'Trade']                   ], 
    ['NV.AGR.TOTL.KD'      , 'Agriculture, forestry, and fishing, value added (constant 2010 US$)'                                             , ['Econ']                            ], 
    ['NV.AGR.TOTL.KD.ZG'   , 'Agriculture, forestry, and fishing, value added (annual % growth)'                                               , ['Econ']                            ], 
    ['NV.AGR.TOTL.ZS'      , 'Agriculture, forestry, and fishing, value added (% of GDP)'                                                      , ['AgriRural', 'Econ', 'Climate']    ], 
    ['NV.IND.MANF.KD'      , 'Manufacturing, value added (constant 2010 US$)'                                                                  , ['Econ']                            ], 
    ['NV.IND.MANF.KD.ZG'   , 'Manufacturing, value added (annual % growth)'                                                                    , ['Econ']                            ], 
    ['NV.IND.MANF.ZS'      , 'Manufacturing, value added (% of GDP)'                                                                           , ['Econ']                            ], 
    ['NV.IND.TOTL.KD'      , 'Industry (including construction), value added (constant 2010 US$)'                                              , ['Econ']                            ], 
    ['NV.IND.TOTL.KD.ZG'   , 'Industry (including construction), value added (annual % growth)'                                                , ['Econ']                            ], 
    ['NV.IND.TOTL.ZS'      , 'Industry (including construction), value added (% of GDP)'                                                       , ['Econ']                            ], 
    ['NY.GDP.MKTP.KD.ZG'   , 'GDP growth (annual %)'                                                                                           , ['Econ']                            ], 
    ['NY.GDP.PCAP.KD'      , 'GDP per capita (constant 2010 US$)'                                                                              , ['Econ']                            ], 
    ['NY.GDP.PCAP.PP.KD'   , 'GDP per capita, PPP (constant 2017 international $)'                                                             , ['Econ']                            ], 
    ['SE.ADT.1524.LT.FE.ZS', 'Literacy rate, youth female (% of females ages 15-24)'                                                           , ['Edu', 'Gender']                   ], 
    ['SE.ADT.1524.LT.MA.ZS', 'Literacy rate, youth male (% of males ages 15-24)'                                                               , ['Edu', 'Gender']                   ], 
    ['SE.ADT.1524.LT.ZS'   , 'Literacy rate, youth total (% of people ages 15-24)'                                                             , ['Edu']                             ], 
    ['SE.ADT.LITR.FE.ZS'   , 'Literacy rate, adult female (% of females ages 15 and above)'                                                    , ['Gender', 'Edu']                   ], 
    ['SE.ADT.LITR.MA.ZS'   , 'Literacy rate, adult male (% of males ages 15 and above)'                                                        , ['Edu', 'Gender']                   ], 
    ['SE.ADT.LITR.ZS'      , 'Literacy rate, adult total (% of people ages 15 and above)'                                                      , ['Edu']                             ], 
    ['SE.ENR.SECO.FM.ZS'   , 'School enrollment, secondary (gross), gender parity index (GPI)'                                                 , ['Edu', 'Gender', 'Social']         ], 
    ['SE.ENR.TERT.FM.ZS'   , 'School enrollment, tertiary (gross), gender parity index (GPI)'                                                  , ['Edu', 'Gender', 'Social']         ], 
    ['SE.PRM.CMPT.FE.ZS'   , 'Primary completion rate, female (% of relevant age group)'                                                       , ['Edu', 'Gender']                   ], 
    ['SE.PRM.CMPT.MA.ZS'   , 'Primary completion rate, male (% of relevant age group)'                                                         , ['Edu', 'Gender']                   ], 
    ['SE.PRM.CMPT.ZS'      , 'Primary completion rate, total (% of relevant age group)'                                                        , ['Aid', 'Climate', 'Edu']           ], 
    ['SE.PRM.ENRR'         , 'School enrollment, primary (% gross)'                                                                            , ['Edu']                             ], 
    ['SE.PRM.ENRR.FE'      , 'School enrollment, primary, female (% gross)'                                                                    , ['Edu', 'Gender']                   ], 
    ['SE.PRM.ENRR.MA'      , 'School enrollment, primary, male (% gross)'                                                                      , ['Edu', 'Gender']                   ], 
    ['SE.SEC.ENRR'         , 'School enrollment, secondary (% gross)'                                                                          , ['Edu']                             ], 
    ['SE.SEC.ENRR.FE'      , 'School enrollment, secondary, female (% gross)'                                                                  , ['Edu', 'Gender']                   ], 
    ['SE.SEC.ENRR.MA'      , 'School enrollment, secondary, male (% gross)'                                                                    , ['Edu', 'Gender']                   ], 
    ['SE.TER.ENRR'         , 'School enrollment, tertiary (% gross)'                                                                           , ['Edu']                             ], 
    ['SE.TER.ENRR.FE'      , 'School enrollment, tertiary, female (% gross)'                                                                   , ['Edu', 'Gender']                   ], 
    ['SE.TER.ENRR.MA'      , 'School enrollment, tertiary, male (% gross)'                                                                     , ['Edu', 'Gender']                   ], 
    ['SE.XPD.TOTL.GD.ZS'   , 'Government expenditure on education, total (% of GDP)'                                                           , ['Edu']                             ], 
    ['SH.DYN.AIDS.ZS'      , 'Prevalence of HIV, total (% of population ages 15-49)'                                                           , ['Health', 'Aid']                   ], 
    ['SH.MMR.RISK.ZS'      , 'Lifetime risk of maternal death (%)'                                                                             , ['Health', 'Gender']                ], 
    ['SI.POV.DDAY'         , 'Poverty headcount ratio at $1.90 a day (2011 PPP) (% of population)'                                             , ['Poverty', 'Aid', 'Climate']       ], 
    ['SI.POV.GINI'         , 'Gini index (World Bank estimate)'                                                                                , ['Poverty']                         ], 
    ['SL.AGR.EMPL.FE.ZS'   , 'Employment in agriculture, female (% of female employment) (modeled ILO estimate)'                               , ['AgriRural', 'Labor', 'Gender']    ], 
    ['SL.AGR.EMPL.MA.ZS'   , 'Employment in agriculture, male (% of male employment) (modeled ILO estimate)'                                   , ['AgriRural', 'Labor', 'Gender']    ], 
    ['SL.AGR.EMPL.ZS'      , 'Employment in agriculture (% of total employment) (modeled ILO estimate)'                                        , ['AgriRural', 'Labor']              ], 
    ['SL.EMP.MPYR.FE.ZS'   , 'Employers, female (% of female employment) (modeled ILO estimate)'                                               , ['Labor', 'Gender']                 ], 
    ['SL.EMP.MPYR.MA.ZS'   , 'Employers, male (% of male employment) (modeled ILO estimate)'                                                   , ['Labor', 'Gender']                 ], 
    ['SL.EMP.MPYR.ZS'      , 'Employers, total (% of total employment) (modeled ILO estimate)'                                                 , ['Labor']                           ], 
    ['SL.EMP.OWAC.FE.ZS'   , 'Own-account workers, female (% of female employment) (modeled ILO estimate)'                                     , ['Gender']                          ], 
    ['SL.EMP.OWAC.MA.ZS'   , 'Own-account workers, male (% of male employment) (modeled ILO estimate)'                                         , ['Gender']                          ], 
    ['SL.EMP.OWAC.ZS'      , 'Own-account workers, total (% of total employment)'                                                              , null                                ], 
    ['SL.EMP.SELF.FE.ZS'   , 'Self-employed, female (% of female employment) (modeled ILO estimate)'                                           , ['Labor', 'Gender']                 ], 
    ['SL.EMP.SELF.MA.ZS'   , 'Self-employed, male (% of male employment) (modeled ILO estimate)'                                               , ['Labor', 'Gender']                 ], 
    ['SL.EMP.SELF.ZS'      , 'Self-employed, total (% of total employment) (modeled ILO estimate)'                                             , ['Labor']                           ], 
    ['SL.EMP.TOTL'         , 'Number of people employed'                                                                                       , null                                ], 
    ['SL.EMP.VULN.FE.ZS'   , 'Vulnerable employment, female (% of female employment) (modeled ILO estimate)'                                   , ['Labor', 'Gender', 'Social']       ], 
    ['SL.EMP.VULN.MA.ZS'   , 'Vulnerable employment, male (% of male employment) (modeled ILO estimate)'                                       , ['Labor', 'Gender', 'Social']       ], 
    ['SL.EMP.VULN.ZS'      , 'Vulnerable employment, total (% of total employment) (modeled ILO estimate)'                                     , ['Labor', 'Aid']                    ], 
    ['SL.EMP.WORK.FE.ZS'   , 'Wage and salaried workers, female (% of female employment) (modeled ILO estimate)'                               , ['Labor', 'Gender']                 ], 
    ['SL.EMP.WORK.MA.ZS'   , 'Wage and salaried workers, male (% of male employment) (modeled ILO estimate)'                                   , ['Labor', 'Gender']                 ], 
    ['SL.EMP.WORK.ZS'      , 'Wage and salaried workers, total (% of total employment) (modeled ILO estimate)'                                 , ['Labor']                           ], 
    ['SL.FAM.WORK.FE.ZS'   , 'Contributing family workers, female (% of female employment) (modeled ILO estimate)'                             , ['Labor', 'Gender']                 ], 
    ['SL.FAM.WORK.MA.ZS'   , 'Contributing family workers, male (% of male employment) (modeled ILO estimate)'                                 , ['Labor', 'Gender']                 ], 
    ['SL.FAM.WORK.ZS'      , 'Contributing family workers, total (% of total employment) (modeled ILO estimate)'                               , ['Labor']                           ], 
    ['SL.GDP.PCAP.EM.KD'   , 'GDP per person employed (constant 2017 PPP $)'                                                                   , ['Labor']                           ], 
    ['SL.IND.EMPL.FE.ZS'   , 'Employment in industry, female (% of female employment) (modeled ILO estimate)'                                  , ['Labor', 'Gender']                 ], 
    ['SL.IND.EMPL.MA.ZS'   , 'Employment in industry, male (% of male employment) (modeled ILO estimate)'                                      , ['Labor', 'Gender']                 ], 
    ['SL.IND.EMPL.ZS'      , 'Employment in industry (% of total employment) (modeled ILO estimate)'                                           , ['Labor']                           ], 
    ['SL.SRV.EMPL.FE.ZS'   , 'Employment in services, female (% of female employment) (modeled ILO estimate)'                                  , ['Labor', 'Gender']                 ], 
    ['SL.SRV.EMPL.MA.ZS'   , 'Employment in services, male (% of male employment) (modeled ILO estimate)'                                      , ['Labor', 'Gender']                 ], 
    ['SL.SRV.EMPL.ZS'      , 'Employment in services (% of total employment) (modeled ILO estimate)'                                           , ['Labor']                           ], 
    ['SL.TLF.ADVN.FE.ZS'   , 'Labor force with advanced education, female (% of female working-age population with advanced education)'        , ['Labor']                           ], 
    ['SL.TLF.ADVN.MA.ZS'   , 'Labor force with advanced education, male (% of male working-age population with advanced education)'            , ['Labor']                           ], 
    ['SL.TLF.ADVN.ZS'      , 'Labor force with advanced education (% of total working-age population with advanced education)'                 , ['Labor']                           ], 
    ['SL.TLF.BASC.FE.ZS'   , 'Labor force with basic education, female (% of female working-age population with basic education)'              , ['Labor']                           ], 
    ['SL.TLF.BASC.MA.ZS'   , 'Labor force with basic education, male (% of male working-age population with basic education)'                  , ['Labor']                           ], 
    ['SL.TLF.BASC.ZS'      , 'Labor force with basic education (% of total working-age population with basic education)'                       , ['Labor']                           ], 
    ['SL.TLF.CACT.FE.ZS'   , 'Labor force participation rate, female (% of female population ages 15+) (modeled ILO estimate)'                 , ['Labor', 'Gender', 'Social']       ], 
    ['SL.TLF.CACT.MA.ZS'   , 'Labor force participation rate, male (% of male population ages 15+) (modeled ILO estimate)'                     , ['Labor', 'Gender', 'Social']       ], 
    ['SL.TLF.CACT.ZS'      , 'Labor force participation rate, total (% of total population ages 15+) (modeled ILO estimate)'                   , ['Labor']                           ], 
    ['SL.TLF.INTM.FE.ZS'   , 'Labor force with intermediate education, female (% of female working-age population with intermediate education)', ['Labor']                           ], 
    ['SL.TLF.INTM.MA.ZS'   , 'Labor force with intermediate education, male (% of male working-age population with intermediate education)'    , ['Labor']                           ], 
    ['SL.TLF.INTM.ZS'      , 'Labor force with intermediate education (% of total working-age population with intermediate education)'         , ['Labor']                           ], 
    ['SL.TLF.TOTL.IN'      , 'Labor force, total'                                                                                              , ['Edu', 'Labor']                    ], 
    ['SL.UEM.1524.FE.ZS'   , 'Unemployment, youth female (% of female labor force ages 15-24) (modeled ILO estimate)'                          , ['Labor', 'Gender']                 ], 
    ['SL.UEM.1524.MA.ZS'   , 'Unemployment, youth male (% of male labor force ages 15-24) (modeled ILO estimate)'                              , ['Labor', 'Gender']                 ], 
    ['SL.UEM.1524.ZS'      , 'Unemployment, youth total (% of total labor force ages 15-24) (modeled ILO estimate)'                            , ['Labor']                           ], 
    ['SL.UEM.ADVN.FE.ZS'   , 'Unemployment with advanced education, female (% of female labor force with advanced education)'                  , ['Labor']                           ], 
    ['SL.UEM.ADVN.MA.ZS'   , 'Unemployment with advanced education, male (% of male labor force with advanced education)'                      , ['Labor']                           ], 
    ['SL.UEM.ADVN.ZS'      , 'Unemployment with advanced education (% of total labor force with advanced education)'                           , ['Labor']                           ], 
    ['SL.UEM.INTM.FE.ZS'   , 'Unemployment with intermediate education, female (% of female labor force with intermediate education)'          , ['Labor']                           ], 
    ['SL.UEM.INTM.MA.ZS'   , 'Unemployment with intermediate education, male (% of male labor force with intermediate education)'              , ['Labor']                           ], 
    ['SL.UEM.INTM.ZS'      , 'Unemployment with intermediate education (% of total labor force with intermediate education)'                   , ['Labor']                           ], 
    ['SL.UEM.TOTL.FE.ZS'   , 'Unemployment, female (% of female labor force) (modeled ILO estimate)'                                           , ['Edu', 'Labor', 'Gender', 'Social']], 
    ['SL.UEM.TOTL.MA.ZS'   , 'Unemployment, male (% of male labor force) (modeled ILO estimate)'                                               , ['Edu', 'Labor', 'Gender', 'Social']], 
    ['SL.UEM.TOTL.ZS'      , 'Unemployment, total (% of total labor force) (modeled ILO estimate)'                                             , ['Edu', 'Labor']                    ], 
    ['SM.POP.TOTL.ZS'      , 'International migrant stock (% of population)'                                                                   , ['Fin', 'Health']                   ], 
    ['SP.ADO.TFRT'         , 'Adolescent fertility rate (births per 1,000 women ages 15-19)'                                                   , ['Health', 'Gender', 'Social']      ], 
    ['SP.DYN.LE00.FE.IN'   , 'Life expectancy at birth, female (years)'                                                                        , ['Health', 'Gender', 'Social']      ], 
    ['SP.DYN.LE00.MA.IN'   , 'Life expectancy at birth, male (years)'                                                                          , ['Health', 'Gender', 'Social']      ], 
    ['SP.DYN.TFRT.IN'      , 'Fertility rate, total (births per woman)'                                                                        , ['Health', 'Gender']                ], 
    ['SP.POP.0014.TO'      , 'Population ages 0-14, total'                                                                                     , ['Health']                          ], 
    ['SP.POP.0014.TO.ZS'   , 'Population ages 0-14 (% of total population)'                                                                    , ['Edu', 'Health']                   ], 
    ['SP.POP.1564.TO'      , 'Population ages 15-64, total'                                                                                    , ['Health']                          ], 
    ['SP.POP.1564.TO.ZS'   , 'Population ages 15-64 (% of total population)'                                                                   , ['Edu', 'Health']                   ], 
    ['SP.POP.65UP.TO'      , 'Population ages 65 and above, total'                                                                             , ['Health']                          ], 
    ['SP.POP.65UP.TO.ZS'   , 'Population ages 65 and above (% of total population)'                                                            , ['Health']                          ], 
    ['SP.POP.DPND'         , 'Age dependency ratio (% of working-age population)'                                                              , ['Health']                          ], 
    ['SP.POP.GROW'         , 'Population growth (annual %)'                                                                                    , ['Climate', 'Health']               ], 
    ['SP.POP.SCIE.RD.P6'   , 'Researchers in R&D (per million people)'                                                                         , ['Stem']                            ], 
    ['SP.POP.TECH.RD.P6'   , 'Technicians in R&D (per million people)'                                                                         , ['Stem']                            ], 
    ['SP.POP.TOTL'         , 'Population, total'                                                                                               , ['Climate', 'Health']               ], 
    ['SP.RUR.TOTL'         , 'Rural population'                                                                                                , ['AgriRural']                       ], 
    ['SP.RUR.TOTL.ZS'      , 'Rural population (% of total population)'                                                                        , ['AgriRural']                       ], 
    ['SP.URB.TOTL'         , 'Urban population'                                                                                                , ['Climate', 'Urban']                ], 
    ['SP.URB.TOTL.IN.ZS'   , 'Urban population (% of total population)'                                                                        , ['Climate', 'Urban']                ], 
    ['TM.VAL.ICTG.ZS.UN'   , 'ICT goods imports (% total goods imports)'                                                                       , ['Infras', 'Private', 'Trade']      ], 
    ['TX.QTY.MRCH.XD.WD'   , 'Export volume index (2000 = 100)'                                                                                , ['Private', 'Trade']                ], 
    ['TX.VAL.FUEL.ZS.UN'   , 'Fuel exports (% of merchandise exports)'                                                                         , ['Energy', 'Private', 'Trade']      ], 
    ['TX.VAL.MRCH.XD.WD'   , 'Export value index (2000 = 100)'                                                                                 , ['Private', 'Trade']                ], 
    ['TX.VAL.TECH.MF.ZS'   , 'High-technology exports (% of manufactured exports)'                                                             , ['Private', 'Stem', 'Trade']        ], 
  ], 
}