export const JointExternalDebtHub = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['Q.1C0.1C0.C.9A.ALL.PITT.1.ALL.MV.TO1.ALL', '26_Portfolio investment assets'                            , null], 
    ['Q.1C0.1C0.C.9A.MOA.RXGT.1.ALL.MV.TO1.ALL', '24_International reserves (excluding gold)'                , null], 
    ['Q.1C0.1C0.C.9B.IFI.LMIM.1.ALL.NV.SDR.MOA', '07_Multilateral loans, IMF'                                , null], 
    ['Q.1C0.1C0.C.9B.IFI.LMIM.1.STR.NV.SDR.MOA', '13_Multilateral loans, IMF, short term'                    , null], 
    ['Q.1C0.1C0.C.9B.IFI.SDAL.1.ALL.MV.SDR.MOA', '11_SDR allocation'                                         , null], 
    ['Q.1C0.1C0.C.9E.ALL.DSTT.1.ALL.MV.TO1.ALL', '14_Debt securities held by nonresidents'                   , null], 
    ['Q.1C0.1C0.C.9E.ALL.DSTT.1.STO.MV.TO1.ALL', '15_Debt securities held by nonresidents, total, short term', null], 
    ['Q.1C0.1C0.D.9B.MOA.SDHO.1.ALL.MV.SDR.IFI', '25_SDR holdings'                                           , null], 
    ['Q.1E0.1E0.C.9B.IFI.LMOI.1.ALL.NV.TO1.ALL', '08_Multilateral loans, other institutions'                 , null], 
    ['Q.1E0.1E0.C.9B.IFI.LMTT.1.ALL.NV.TO1.ALL', '06_Multilateral loans, total'                              , null], 
    ['Q.5A0.5A0.C.9C.GGO.LOBA.1.ALL.NV.TO1.ALL', '04_Official bilateral loans, aid loans'                    , null], 
    ['Q.5A0.5A0.C.9C.GGO.LOBN.1.ALL.NV.TO1.ALL', '05_Official bilateral loans, other'                        , null], 
    ['Q.5A0.5A0.C.9C.GGO.LOBT.1.ALL.NV.TO1.ALL', '03_Official bilateral loans, total'                        , null], 
    ['Q.5B0.5B0.C.5A.BKC.ASTT.1.ALL.MX.TO1.ALL', '23_Liabilities to BIS banks, consolidated, total'          , null], 
    ['Q.5B0.5B0.C.5A.BKC.ASTT.1.STR.MX.TO1.ALL', '12_Liabilities to BIS banks (cons.), short term'           , null], 
    ['Q.5B0.5B0.C.5A.BKL.ASTT.1.ALL.MX.TO1.ALL', '22_Liabilities to BIS banks, locational, total'            , null], 
    ['Q.5B0.5B0.C.5A.BKL.LDPT.1.ALL.NV.TO1.ALL', '01_Cross-border loans from BIS reporting banks'            , null], 
    ['Q.5B0.5B0.C.5A.BKL.LDPT.1.ALL.NV.TO1.NBK', '02_Cross-border loans from BIS banks to nonbanks'          , null], 
    ['Q.5B0.5B0.D.5A.ALL.DFXB.1.ALL.NV.TO1.BMA', '27_Cross-border deposits with BIS rep. banks'              , null], 
    ['Q.5B0.5B0.D.5A.NBK.DFXB.1.ALL.NV.TO1.BMA', '28_Cross-border dep. with BIS banks,  nonbanks'            , null], 
    ['Q.5B0.5B0.M.3P.ALL.DSIT.1.ALL.NV.TO1.ALL', '16_International debt securities, all maturities'          , null], 
    ['Q.5B0.5B0.M.3P.ALL.DSIT.1.ALL.NV.TO1.NBK', '17_International debt securities, nonbanks'                , null], 
    ['Q.5B0.5B0.M.3P.ALL.DSIT.1.STR.NV.TO1.ALL', '18_International debt securities, short term'              , null], 
    ['Q.5B0.5B0.M.3P.ALL.DSIT.1.STR.NV.TO1.NBK', '19_Intnl debt securities, nonbanks, short term'            , null], 
    ['Q.6T0.5B0.C.3P.GGO.PCNO.1.ALL.NV.TO1.GGO', '21_Paris Club claims (non ODA)'                            , null], 
    ['Q.6T0.5B0.C.3P.GGO.PCOD.1.ALL.NV.TO1.GGO', '20_Paris Club claims (ODA)'                                , null], 
    ['Q.8A0.5B0.C.5A.ALL.IECE.1.ALL.MX.TO1.ALL', '09_Insured export credit exposures, Berne Union'           , null], 
    ['Q.8A0.5B0.C.5A.ALL.IECE.1.STR.MX.TO1.ALL', '10_Insured export credit exposures, short term (BU)'       , null], 
  ], 
}