export const LacEquityLab = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['1.0.HCount.1.90usd'   , 'Poverty Headcount ($1.90 a day)'                             , ['Poverty']], 
    ['1.0.HCount.2.5usd'    , 'Poverty Headcount ($2.50 a day)'                             , ['Poverty']], 
    ['1.0.HCount.Mid10to50' , 'Middle Class ($10-50 a day) Headcount'                       , ['Poverty']], 
    ['1.0.HCount.Ofcl'      , 'Official Moderate Poverty Rate-National'                     , ['Poverty']], 
    ['1.0.HCount.Poor4uds'  , 'Poverty Headcount ($4 a day)'                                , ['Poverty']], 
    ['1.0.HCount.Vul4to10'  , 'Vulnerable ($4-10 a day) Headcount'                          , ['Poverty']], 
    ['1.0.PGap.1.90usd'     , 'Poverty Gap ($1.90 a day)'                                   , ['Poverty']], 
    ['1.0.PGap.2.5usd'      , 'Poverty Gap ($2.50 a day)'                                   , ['Poverty']], 
    ['1.0.PGap.Poor4uds'    , 'Poverty Gap ($4 a day)'                                      , ['Poverty']], 
    ['1.0.PSev.1.90usd'     , 'Poverty Severity ($1.90 a day)'                              , ['Poverty']], 
    ['1.0.PSev.2.5usd'      , 'Poverty Severity ($2.50 a day)'                              , ['Poverty']], 
    ['1.0.PSev.Poor4uds'    , 'Poverty Severity ($4 a day)'                                 , ['Poverty']], 
    ['1.1.HCount.1.90usd'   , 'Poverty Headcount ($1.90 a day)-Rural'                       , ['Poverty']], 
    ['1.1.HCount.2.5usd'    , 'Poverty Headcount ($2.50 a day)-Rural'                       , ['Poverty']], 
    ['1.1.HCount.Mid10to50' , 'Middle Class ($10-50 a day) Headcount-Rural'                 , ['Poverty']], 
    ['1.1.HCount.Ofcl'      , 'Official Moderate Poverty Rate- Rural'                       , ['Poverty']], 
    ['1.1.HCount.Poor4uds'  , 'Poverty Headcount ($4 a day)-Rural'                          , ['Poverty']], 
    ['1.1.HCount.Vul4to10'  , 'Vulnerable ($4-10 a day) Headcount-Rural'                    , ['Poverty']], 
    ['1.1.PGap.1.90usd'     , 'Poverty Gap ($1.90 a day)-Rural'                             , ['Poverty']], 
    ['1.1.PGap.2.5usd'      , 'Poverty Gap ($2.50 a day)-Rural'                             , ['Poverty']], 
    ['1.1.PGap.Poor4uds'    , 'Poverty Gap ($4 a day)-Rural'                                , ['Poverty']], 
    ['1.1.PSev.1.90usd'     , 'Poverty Severity ($1.90 a day)-Rural'                        , ['Poverty']], 
    ['1.1.PSev.2.5usd'      , 'Poverty Severity ($2.50 a day)-Rural'                        , ['Poverty']], 
    ['1.1.PSev.Poor4uds'    , 'Poverty Severity ($4 a day)-Rural'                           , ['Poverty']], 
    ['1.2.HCount.1.90usd'   , 'Poverty Headcount ($1.90 a day)-Urban'                       , ['Poverty']], 
    ['1.2.HCount.2.5usd'    , 'Poverty Headcount ($2.50 a day)-Urban'                       , ['Poverty']], 
    ['1.2.HCount.Mid10to50' , 'Middle Class ($10-50 a day) Headcount-Urban'                 , ['Poverty']], 
    ['1.2.HCount.Ofcl'      , 'Official Moderate Poverty Rate-Urban'                        , ['Poverty']], 
    ['1.2.HCount.Poor4uds'  , 'Poverty Headcount ($4 a day)-Urban'                          , ['Poverty']], 
    ['1.2.HCount.Vul4to10'  , 'Vulnerable ($4-10 a day) Headcount-Urban'                    , ['Poverty']], 
    ['1.2.PGap.1.90usd'     , 'Poverty Gap ($1.90 a day)-Urban'                             , ['Poverty']], 
    ['1.2.PGap.2.5usd'      , 'Poverty Gap ($2.50 a day)-Urban'                             , ['Poverty']], 
    ['1.2.PGap.Poor4uds'    , 'Poverty Gap ($4 a day)-Urban'                                , ['Poverty']], 
    ['1.2.PSev.1.90usd'     , 'Poverty Severity ($1.90 a day)-Urban'                        , ['Poverty']], 
    ['1.2.PSev.2.5usd'      , 'Poverty Severity ($2.50 a day)-Urban'                        , ['Poverty']], 
    ['1.2.PSev.Poor4uds'    , 'Poverty Severity ($4 a day)-Urban'                           , ['Poverty']], 
    ['2.0.cov.Cel'          , 'Coverage: Mobile Phone'                                      , ['Poverty']], 
    ['2.0.cov.Ele'          , 'Coverage: Electricity'                                       , ['Poverty']], 
    ['2.0.cov.FPS'          , 'Coverage: Finished Primary School'                           , ['Edu']    ], 
    ['2.0.cov.Int'          , 'Coverage: Internet '                                         , ['Poverty']], 
    ['2.0.cov.Math.pl_2.all', 'Coverage: Mathematics Proficiency Level 2'                   , ['Poverty']], 
    ['2.0.cov.Math.pl_2.prv', 'Coverage: Mathematics Proficiency Level 2, Private schools'  , ['Poverty']], 
    ['2.0.cov.Math.pl_2.pub', 'Coverage: Mathematics Proficiency Level 2, Public schools'   , ['Poverty']], 
    ['2.0.cov.Math.pl_3.all', 'Coverage: Mathematics Proficiency Level 3'                   , ['Poverty']], 
    ['2.0.cov.Math.pl_3.prv', 'Coverage: Mathematics Proficiency Level 3, Private schools'  , ['Poverty']], 
    ['2.0.cov.Math.pl_3.pub', 'Coverage: Mathematics Proficiency Level 3, Public schools'   , ['Poverty']], 
    ['2.0.cov.Read.pl_2.all', 'Coverage: Reading Proficiency Level 2'                       , ['Poverty']], 
    ['2.0.cov.Read.pl_2.prv', 'Coverage: Reading Proficiency Level 2, Private schools'      , ['Poverty']], 
    ['2.0.cov.Read.pl_2.pub', 'Coverage: Reading Proficiency Level 2, Public schools'       , ['Poverty']], 
    ['2.0.cov.Read.pl_3.all', 'Coverage: Reading Proficiency Level 3'                       , ['Poverty']], 
    ['2.0.cov.Read.pl_3.prv', 'Coverage: Reading Proficiency Level 3, Private schools'      , ['Poverty']], 
    ['2.0.cov.Read.pl_3.pub', 'Coverage: Reading Proficiency Level 3, Public schools'       , ['Poverty']], 
    ['2.0.cov.San'          , 'Coverage: Sanitation'                                        , ['Poverty']], 
    ['2.0.cov.Sch'          , 'Coverage: School Enrollment'                                 , ['Poverty']], 
    ['2.0.cov.Scie.pl_2.all', 'Coverage: Science Proficiency Level 2'                       , ['Poverty']], 
    ['2.0.cov.Scie.pl_2.prv', 'Coverage: Science Proficiency Level 2, Private schools'      , ['Poverty']], 
    ['2.0.cov.Scie.pl_2.pub', 'Coverage: Science Proficiency Level 2, Public schools'       , ['Poverty']], 
    ['2.0.cov.Scie.pl_3.all', 'Coverage: Science Proficiency Level 3'                       , ['Poverty']], 
    ['2.0.cov.Scie.pl_3.prv', 'Coverage: Science Proficiency Level 3, Private schools'      , ['Poverty']], 
    ['2.0.cov.Scie.pl_3.pub', 'Coverage: Science Proficiency Level 3, Public schools'       , ['Poverty']], 
    ['2.0.cov.Wat'          , 'Coverage: Water'                                             , ['Poverty']], 
    ['2.0.hoi.Cel'          , 'HOI: Mobile Phone'                                           , ['Poverty']], 
    ['2.0.hoi.Ele'          , 'HOI: Electricity'                                            , ['Poverty']], 
    ['2.0.hoi.FPS'          , 'HOI: Finished Primary School'                                , ['Edu']    ], 
    ['2.0.hoi.Int'          , 'HOI: Internet '                                              , ['Poverty']], 
    ['2.0.hoi.Math.pl_2.all', 'HOI: Mathematics Proficiency Level 2'                        , ['Poverty']], 
    ['2.0.hoi.Math.pl_2.prv', 'HOI: Mathematics Proficiency Level 2, Private schools'       , ['Poverty']], 
    ['2.0.hoi.Math.pl_2.pub', 'HOI: Mathematics Proficiency Level 2, Public schools'        , ['Poverty']], 
    ['2.0.hoi.Math.pl_3.all', 'HOI: Mathematics Proficiency Level 3'                        , ['Poverty']], 
    ['2.0.hoi.Math.pl_3.prv', 'HOI: Mathematics Proficiency Level 3, Private schools'       , ['Poverty']], 
    ['2.0.hoi.Math.pl_3.pub', 'HOI: Mathematics Proficiency Level 3, Public schools'        , ['Poverty']], 
    ['2.0.hoi.Read.pl_2.all', 'HOI: Reading Proficiency Level 2'                            , ['Poverty']], 
    ['2.0.hoi.Read.pl_2.prv', 'HOI: Reading Proficiency Level 2, Private schools'           , ['Poverty']], 
    ['2.0.hoi.Read.pl_2.pub', 'HOI: Reading Proficiency Level 2, Public schools'            , ['Poverty']], 
    ['2.0.hoi.Read.pl_3.all', 'HOI: Reading Proficiency Level 3'                            , ['Poverty']], 
    ['2.0.hoi.Read.pl_3.prv', 'HOI: Reading Proficiency Level 3, Private schools'           , ['Poverty']], 
    ['2.0.hoi.Read.pl_3.pub', 'HOI: Reading Proficiency Level 3, Public schools'            , ['Poverty']], 
    ['2.0.hoi.San'          , 'HOI: Sanitation'                                             , ['Poverty']], 
    ['2.0.hoi.Sch'          , 'HOI: School Enrollment'                                      , ['Poverty']], 
    ['2.0.hoi.Scie.pl_2.all', 'HOI: Science Proficiency Level 2'                            , ['Poverty']], 
    ['2.0.hoi.Scie.pl_2.prv', 'HOI: Science Proficiency Level 2, Private schools'           , ['Poverty']], 
    ['2.0.hoi.Scie.pl_2.pub', 'HOI: Science Proficiency Level 2, Public schools'            , ['Poverty']], 
    ['2.0.hoi.Scie.pl_3.all', 'HOI: Science Proficiency Level 3'                            , ['Poverty']], 
    ['2.0.hoi.Scie.pl_3.prv', 'HOI: Science Proficiency Level 3, Private schools'           , ['Poverty']], 
    ['2.0.hoi.Scie.pl_3.pub', 'HOI: Science Proficiency Level 3, Public schools'            , ['Poverty']], 
    ['2.0.hoi.Wat'          , 'HOI: Water'                                                  , ['Poverty']], 
    ['3.0.Atkin.0.5'        , 'Atkinson, A(.5)'                                             , ['Poverty']], 
    ['3.0.Atkin.1'          , 'Atkinson, A(1)'                                              , ['Poverty']], 
    ['3.0.Atkin.2'          , 'Atkinson, A(2)'                                              , ['Poverty']], 
    ['3.0.GenEnt-1'         , 'Generalized Entrophy, GE(-1)'                                , ['Poverty']], 
    ['3.0.GenEnt2'          , 'Generalized Entrophy, GE(2)'                                 , ['Poverty']], 
    ['3.0.Gini'             , 'Gini Coefficient'                                            , ['Poverty']], 
    ['3.0.Gini_nozero'      , 'Gini Coefficient (No Zero Income)'                           , ['Poverty']], 
    ['3.0.IncShr.q1'        , 'Income Share of First Quintile'                              , ['Poverty']], 
    ['3.0.IncShr.q2'        , 'Income Share of Second Quintile'                             , ['Poverty']], 
    ['3.0.IncShr.q3'        , 'Income Share of Third Quintile'                              , ['Poverty']], 
    ['3.0.IncShr.q4'        , 'Income Share of Fourth Quintile'                             , ['Poverty']], 
    ['3.0.IncShr.q5'        , 'Income Share of Fifth Quintile'                              , ['Poverty']], 
    ['3.0.MLongDev0'        , 'Mean Log Deviation, GE(0)'                                   , ['Poverty']], 
    ['3.0.Rate75-25'        , 'Rate 75/25'                                                  , ['Poverty']], 
    ['3.0.Rate90-10'        , 'Rate 90/10'                                                  , ['Poverty']], 
    ['3.0.TheilInd1'        , 'Theil Index, GE(1)'                                          , ['Poverty']], 
    ['3.1.Gini'             , 'Gini, Rural'                                                 , ['Poverty']], 
    ['3.1.MLongDev0'        , 'Mean Log Deviation, GE(0), Rural'                            , ['Poverty']], 
    ['3.1.TheilInd1'        , 'Theil Index, GE(1), Rural'                                   , ['Poverty']], 
    ['3.2.Gini'             , 'Gini, Urban'                                                 , ['Poverty']], 
    ['3.2.MLongDev0'        , 'Mean Log Deviation, GE(0),Urban'                             , ['Poverty']], 
    ['3.2.TheilInd1'        , 'Theil Index, GE(1),Urban'                                    , ['Poverty']], 
    ['4.0.nini.15a18'       , 'Youth: Neither in School Nor Working  (15-18)'               , ['Labor']  ], 
    ['4.0.nini.15a24'       , 'Youth: Neither in School Nor Working  (15-24)'               , ['Labor']  ], 
    ['4.0.nini.19a24'       , 'Youth: Neither in School Nor Working  (19-24)'               , ['Labor']  ], 
    ['4.0.stud.15a18'       , 'Youth: In School (15-18)'                                    , ['Labor']  ], 
    ['4.0.stud.15a24'       , 'Youth: In School (15-24)'                                    , ['Labor']  ], 
    ['4.0.stud.19a24'       , 'Youth: In School (19-24)'                                    , ['Labor']  ], 
    ['4.0.studwork.15a18'   , 'Youth: In School and Employed (15-18)'                       , ['Labor']  ], 
    ['4.0.studwork.15a24'   , 'Youth: In School and Employed (15-24)'                       , ['Labor']  ], 
    ['4.0.studwork.19a24'   , 'Youth: In School and Employed (19-24)'                       , ['Labor']  ], 
    ['4.0.work.15a18'       , 'Youth: Employed (15-18)'                                     , ['Labor']  ], 
    ['4.0.work.15a24'       , 'Youth: Employed (15-24)'                                     , ['Labor']  ], 
    ['4.0.work.19a24'       , 'Youth: Employed (19-24)'                                     , ['Labor']  ], 
    ['4.1.nini.15a18'       , 'Youth: Neither in School Nor Working  (15-18), Male'         , ['Labor']  ], 
    ['4.1.nini.15a24'       , 'Youth: Neither in School Nor Working  (15-24), Male'         , ['Labor']  ], 
    ['4.1.nini.19a24'       , 'Youth: Neither in School Nor Working  (19-24), Male'         , ['Labor']  ], 
    ['4.1.stud.15a18'       , 'Youth: In School (15-18), Male'                              , ['Labor']  ], 
    ['4.1.stud.15a24'       , 'Youth: In School (15-24), Male'                              , ['Labor']  ], 
    ['4.1.stud.19a24'       , 'Youth: In School (19-24), Male'                              , ['Labor']  ], 
    ['4.1.studwork.15a18'   , 'Youth: In School and Employed (15-18), Male'                 , ['Labor']  ], 
    ['4.1.studwork.15a24'   , 'Youth: In School and Employed (15-24), Male'                 , ['Labor']  ], 
    ['4.1.studwork.19a24'   , 'Youth: In School and Employed (19-24), Male'                 , ['Labor']  ], 
    ['4.1.work.15a18'       , 'Youth: Employed (15-18), Male'                               , ['Labor']  ], 
    ['4.1.work.15a24'       , 'Youth: Employed (15-24), Male'                               , ['Labor']  ], 
    ['4.1.work.19a24'       , 'Youth: Employed (19-24), Male'                               , ['Labor']  ], 
    ['4.2.nini.15a18'       , 'Youth: Neither in School Nor Working  (15-18), Female'       , ['Labor']  ], 
    ['4.2.nini.15a24'       , 'Youth: Neither in School Nor Working  (15-24), Female'       , ['Labor']  ], 
    ['4.2.nini.19a24'       , 'Youth: Neither in School Nor Working  (19-24), Female'       , ['Labor']  ], 
    ['4.2.stud.15a18'       , 'Youth: In School (15-18), Female'                            , ['Labor']  ], 
    ['4.2.stud.15a24'       , 'Youth: In School (15-24), Female'                            , ['Labor']  ], 
    ['4.2.stud.19a24'       , 'Youth: In School (19-24), Female'                            , ['Labor']  ], 
    ['4.2.studwork.15a18'   , 'Youth: In School and Employed (15-18), Female'               , ['Labor']  ], 
    ['4.2.studwork.15a24'   , 'Youth: In School and Employed (15-24), Female'               , ['Labor']  ], 
    ['4.2.studwork.19a24'   , 'Youth: In School and Employed (19-24), Female'               , ['Labor']  ], 
    ['4.2.work.15a18'       , 'Youth: Employed (15-18), Female'                             , ['Labor']  ], 
    ['4.2.work.15a24'       , 'Youth: Employed (15-24), Female'                             , ['Labor']  ], 
    ['4.2.work.19a24'       , 'Youth: Employed (19-24), Female'                             , ['Labor']  ], 
    ['5.0.AMeanIncGr.All'   , 'Annualized Mean Income Growth (2004-2014)'                   , ['Econ']   ], 
    ['5.0.AMeanIncGr.B40'   , 'Annualized Mean Income Growth Bottom 40 Percent (2004-2014)' , ['Econ']   ], 
    ['5.1.AMeanIncGr.All'   , 'Annualized Mean Income Growth (2004-2009)'                   , ['Econ']   ], 
    ['5.1.AMeanIncGr.B40'   , 'Annualized Mean Income Growth Bottom 40 Percent (2004-2009)' , ['Econ']   ], 
    ['5.2.AMeanIncGr.All'   , 'Annualized Mean Income Growth (2009-2014)'                   , ['Econ']   ], 
    ['5.2.AMeanIncGr.B40'   , 'Annualized Mean Income Growth Bottom 40 Percent (2009-2014)' , ['Econ']   ], 
    ['6.0.Conspc'           , 'Consumption per capita (2011 $)'                             , ['Econ']   ], 
    ['6.0.GDP_current'      , 'GDP (current $)'                                             , ['Econ']   ], 
    ['6.0.GDP_growth'       , 'GDP growth (annual %)'                                       , ['Econ']   ], 
    ['6.0.GDP_usd'          , 'GDP (constant 2005 $)'                                       , ['Econ']   ], 
    ['6.0.GDPpc_constant'   , 'GDP per capita, PPP (constant 2011 international $) '        , ['Econ']   ], 
    ['6.0.GNIpc'            , 'GNI per capita (2011 $)'                                     , ['Econ']   ], 
    ['8.0.LIPI'             , 'Labor Income Poverty Index'                                  , ['Poverty']], 
    ['9.0.Employee.All'     , 'Employees (%)'                                               , ['Labor']  ], 
    ['9.0.Employee.B40'     , 'Employees-Bottom 40 Percent (%)'                             , ['Labor']  ], 
    ['9.0.Employee.T60'     , 'Employees-Top 60 Percent (%)'                                , ['Labor']  ], 
    ['9.0.Employer.All'     , 'Employers (%)'                                               , ['Labor']  ], 
    ['9.0.Employer.B40'     , 'Employers-Bottom 40 Percent (%)'                             , ['Labor']  ], 
    ['9.0.Employer.T60'     , 'Employers-Top 60 Percent (%)'                                , ['Labor']  ], 
    ['9.0.Labor.All'        , 'Labor Force Participation Rate (%)'                          , ['Labor']  ], 
    ['9.0.Labor.B40'        , 'Labor Force Participation Rate (%)-Bottom 40 Percent'        , ['Econ']   ], 
    ['9.0.Labor.T60'        , 'Labor Force Participation Rate (%)-Top 60 Percent'           , ['Econ']   ], 
    ['9.0.SelfEmp.All'      , 'Self-Employed (%)'                                           , ['Labor']  ], 
    ['9.0.SelfEmp.B40'      , 'Self-Employed-Bottom 40 Percent (%)'                         , ['Labor']  ], 
    ['9.0.SelfEmp.T60'      , 'Self-Employed-Top 60 Percent (%)'                            , ['Labor']  ], 
    ['9.0.Unemp.All'        , 'Unemployed (%)'                                              , ['Labor']  ], 
    ['9.0.Unemp.B40'        , 'Unemployed-Bottom 40 Percent (%)'                            , ['Labor']  ], 
    ['9.0.Unemp.T60'        , 'Unemployed-Top 60 Percent (%)'                               , ['Labor']  ], 
    ['9.0.Unpaid.All'       , 'Unpaid Workers (%)'                                          , ['Labor']  ], 
    ['9.0.Unpaid.B40'       , 'Unpaid Workers-Bottom 40 Percent (%)'                        , ['Labor']  ], 
    ['9.0.Unpaid.T60'       , 'Unpaid Workers-Top 60 Percent (%)'                           , ['Labor']  ], 
    ['9.1.Employee.All'     , 'Employees (%), Male'                                         , ['Labor']  ], 
    ['9.1.Employee.B40'     , 'Employees-Bottom 40 Percent (%), Male'                       , ['Labor']  ], 
    ['9.1.Employee.T60'     , 'Employees-Top 60 Percent (%), Male'                          , ['Labor']  ], 
    ['9.1.Employer.All'     , 'Employers (%), Male'                                         , ['Labor']  ], 
    ['9.1.Employer.B40'     , 'Employers-Bottom 40 Percent (%), Male'                       , ['Labor']  ], 
    ['9.1.Employer.T60'     , 'Employers-Top 60 Percent (%), Male'                          , ['Labor']  ], 
    ['9.1.Labor.All'        , 'Labor Force Participation Rate (%), Male'                    , ['Labor']  ], 
    ['9.1.Labor.B40'        , 'Labor Force Participation Rate (%)-Bottom 40 Percent, Male'  , ['Econ']   ], 
    ['9.1.Labor.T60'        , 'Labor Force Participation Rate (%)-Top 60 Percent, Male'     , ['Econ']   ], 
    ['9.1.SelfEmp.All'      , 'Self-Employed (%), Male'                                     , ['Labor']  ], 
    ['9.1.SelfEmp.B40'      , 'Self-Employed-Bottom 40 Percent (%), Male'                   , ['Labor']  ], 
    ['9.1.SelfEmp.T60'      , 'Self-Employed-Top 60 Percent (%), Male'                      , ['Labor']  ], 
    ['9.1.Unemp.All'        , 'Unemployed (%), Male'                                        , ['Labor']  ], 
    ['9.1.Unemp.B40'        , 'Unemployed-Bottom 40 Percent (%), Male'                      , ['Labor']  ], 
    ['9.1.Unemp.T60'        , 'Unemployed-Top 60 Percent (%), Male'                         , ['Labor']  ], 
    ['9.1.Unpaid.All'       , 'Unpaid Workers (%), Male'                                    , ['Labor']  ], 
    ['9.1.Unpaid.B40'       , 'Unpaid Workers-Bottom 40 Percent (%), Male'                  , ['Labor']  ], 
    ['9.1.Unpaid.T60'       , 'Unpaid Workers-Top 60 Percent (%), Male'                     , ['Labor']  ], 
    ['9.2.Employee.All'     , 'Employees (%), Female'                                       , ['Labor']  ], 
    ['9.2.Employee.B40'     , 'Employees-Bottom 40 Percent (%), Female'                     , ['Labor']  ], 
    ['9.2.Employee.T60'     , 'Employees-Top 60 Percent (%), Female'                        , ['Labor']  ], 
    ['9.2.Employer.All'     , 'Employers (%), Female'                                       , ['Labor']  ], 
    ['9.2.Employer.B40'     , 'Employers-Bottom 40 Percent (%), Female'                     , ['Labor']  ], 
    ['9.2.Employer.T60'     , 'Employers-Top 60 Percent (%), Female'                        , ['Labor']  ], 
    ['9.2.Labor.All'        , 'Labor Force Participation Rate (%), Female'                  , ['Labor']  ], 
    ['9.2.Labor.B40'        , 'Labor Force Participation Rate (%)-Bottom 40 Percent, Female', ['Econ']   ], 
    ['9.2.Labor.T60'        , 'Labor Force Participation Rate (%)-Top 60 Percent, Female'   , ['Econ']   ], 
    ['9.2.SelfEmp.All'      , 'Self-Employed (%), Female'                                   , ['Labor']  ], 
    ['9.2.SelfEmp.B40'      , 'Self-Employed-Bottom 40 Percent (%), Female'                 , ['Labor']  ], 
    ['9.2.SelfEmp.T60'      , 'Self-Employed-Top 60 Percent (%), Female'                    , ['Labor']  ], 
    ['9.2.Unemp.All'        , 'Unemployed (%), Female'                                      , ['Labor']  ], 
    ['9.2.Unemp.B40'        , 'Unemployed-Bottom 40 Percent (%), Female'                    , ['Labor']  ], 
    ['9.2.Unemp.T60'        , 'Unemployed-Top 60 Percent (%), Female'                       , ['Labor']  ], 
    ['9.2.Unpaid.All'       , 'Unpaid Workers (%), Female'                                  , ['Labor']  ], 
    ['9.2.Unpaid.B40'       , 'Unpaid Workers-Bottom 40 Percent (%), Female'                , ['Labor']  ], 
    ['9.2.Unpaid.T60'       , 'Unpaid Workers-Top 60 Percent (%), Female'                   , ['Labor']  ], 
  ], 
}