export const LogisticsPerformanceIndex = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['LP.LPI.CUST.RK'   , 'Efficiency of the clearance process, rank (1=highest performer)'                                                                , null                ], 
    ['LP.LPI.CUST.XQ'   , 'Logistics performance index: Efficiency of customs clearance process (1=low to 5=high)'                                         , ['Private', 'Trade']], 
    ['LP.LPI.INFR.RK'   , 'Quality- of trade and transport-related infrastructure, rank (1=highest performer)'                                             , null                ], 
    ['LP.LPI.INFR.XQ'   , 'Logistics performance index: Quality of trade and transport-related infrastructure (1=low to 5=high)'                           , ['Private', 'Trade']], 
    ['LP.LPI.ITRN.RK'   , 'Ease of arranging competitively priced international shipments, rank (1=highest performer)'                                     , null                ], 
    ['LP.LPI.ITRN.XQ'   , 'Logistics performance index: Ease of arranging competitively priced shipments (1=low to 5=high)'                                , ['Private', 'Trade']], 
    ['LP.LPI.LOGS.RK'   , 'Competence and quality of logistics services, rank (1=highest performer)'                                                       , null                ], 
    ['LP.LPI.LOGS.XQ'   , 'Logistics performance index: Competence and quality of logistics services (1=low to 5=high)'                                    , ['Private', 'Trade']], 
    ['LP.LPI.OVRL.RK'   , 'Logistics performance index: Overall rank (1=highest performance)'                                                              , null                ], 
    ['LP.LPI.OVRL.RK.LB', 'Logistics performance index: Overall rank (1=highest performance), lower bound'                                                 , null                ], 
    ['LP.LPI.OVRL.RK.UB', 'Logistics performance index: Overall rank (1=highest performance), upper bound'                                                 , null                ], 
    ['LP.LPI.OVRL.RK.ZS', 'Logistics performance index: Percent of highest performer)'                                                                     , null                ], 
    ['LP.LPI.OVRL.XQ'   , 'Logistics performance index: Overall (1=low to 5=high)'                                                                         , ['Private', 'Trade']], 
    ['LP.LPI.OVRL.XQ.LB', 'Logistics performance index: Overall score (1=low to 5=high), lower bound'                                                      , null                ], 
    ['LP.LPI.OVRL.XQ.UB', 'Logistics performance index: Overall score (1=low to 5=high), upper bound'                                                      , null                ], 
    ['LP.LPI.TIME.RK'   , 'Frequency with which shipments reach consignee within scheduled or expected time, rank (1=highest performer)'                   , null                ], 
    ['LP.LPI.TIME.XQ'   , 'Logistics performance index: Frequency with which shipments reach consignee within scheduled or expected time (1=low to 5=high)', ['Private', 'Trade']], 
    ['LP.LPI.TRAC.RK'   , 'Ability to track and trace consignments, rank (1=highest performer)'                                                            , null                ], 
    ['LP.LPI.TRAC.XQ'   , 'Logistics performance index: Ability to track and trace consignments (1=low to 5=high)'                                         , ['Private', 'Trade']], 
  ], 
}