export const MillenniumDevelopmentGoals = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['AG.LND.FRST.K2'      , 'Forest area (sq. km)'                                                                                                       , ['AgriRural', 'Climate', 'Env']              ], 
    ['AG.LND.FRST.ZS'      , 'Forest area (% of land area)'                                                                                               , ['AgriRural', 'Climate', 'Env']              ], 
    ['DC.ODA.COMM.CD'      , 'Total bilateral ODA commitments (current US$)'                                                                              , ['2kGoals']                                  ], 
    ['DC.ODA.COMM.SA.CD'   , 'Total bilateral sector allocable ODA commitments (current US$)'                                                             , ['2kGoals']                                  ], 
    ['DC.ODA.SOCL.CD'      , 'Bilateral, sector-allocable ODA to basic social services (current US$)'                                                     , ['2kGoals']                                  ], 
    ['DC.ODA.SOCL.ZS'      , 'Bilateral, sector-allocable ODA to basic social services (% of bilateral ODA commitments)'                                  , ['2kGoals']                                  ], 
    ['DC.ODA.TLDC.CD'      , 'Net ODA provided, to the least developed countries (current US$)'                                                           , ['2kGoals']                                  ], 
    ['DC.ODA.TLDC.GN.ZS'   , 'Net ODA provided to the least developed countries (% of GNI)'                                                               , ['2kGoals']                                  ], 
    ['DC.ODA.TOTL.CD'      , 'Net ODA provided, total (current US$)'                                                                                      , ['2kGoals']                                  ], 
    ['DC.ODA.TOTL.GN.ZS'   , 'Net ODA provided, total (% of GNI)'                                                                                         , ['2kGoals']                                  ], 
    ['DC.ODA.TOTL.KD'      , 'Net ODA provided, total (constant 2015 US$)'                                                                                , ['2kGoals']                                  ], 
    ['DC.ODA.UNTD.CD'      , 'Bilateral ODA commitments that is untied (current US$)'                                                                     , ['2kGoals']                                  ], 
    ['DC.ODA.UNTD.ZS'      , 'Bilateral ODA commitments that is untied (% of bilateral ODA commitments)'                                                  , ['2kGoals']                                  ], 
    ['DT.HPC.COMR.PV'      , 'Debt relief committed under HIPC initiative, cumulative US$ in end-2012 NPV terms'                                          , ['2kGoals']                                  ], 
    ['DT.HPC.MDRI.PV'      , 'Debt relief delivered in full under MDRI initiative, cumulative US$ in end-2012 NPV terms'                                  , ['2kGoals']                                  ], 
    ['DT.HPC.STTS'         , 'Status under enhanced HIPC initiative'                                                                                      , ['2kGoals']                                  ], 
    ['DT.HPC.TOTL.PV'      , 'Debt relief committed under HIPC and MDRI initiatives, cumulative US$ in end-2012 NPV terms'                                , ['2kGoals']                                  ], 
    ['DT.ODA.ALLD.CD'      , 'Net official development assistance and official aid received (current US$)'                                                , ['Aid']                                      ], 
    ['DT.ODA.ODAT.CD'      , 'Net official development assistance received (current US$)'                                                                 , ['Aid', 'Econ', 'Debt']                      ], 
    ['DT.ODA.ODAT.GN.ZS'   , 'Net ODA received (% of GNI)'                                                                                                , ['Aid', 'Econ', 'Debt']                      ], 
    ['DT.ODA.ODAT.PC.ZS'   , 'Net ODA received per capita (current US$)'                                                                                  , ['Aid', 'Econ', 'Debt']                      ], 
    ['DT.TDS.DECT.EX.ZS'   , 'Total debt service (% of exports of goods, services and primary income)'                                                    , ['Econ', 'Debt']                             ], 
    ['DT.TDS.DPPF.XP.ZS'   , 'Debt service (PPG and IMF only, % of exports of goods, services and primary income)'                                        , ['Debt']                                     ], 
    ['EG.GDP.PUSE.KO.PP.KD', 'GDP per unit of energy use (constant 2017 PPP $ per kg of oil equivalent)'                                                  , ['Energy']                                   ], 
    ['EG.USE.COMM.GD.PP.KD', 'Energy use (kg of oil equivalent) per $1,000 GDP (constant 2017 PPP)'                                                       , ['Energy', 'Climate']                        ], 
    ['EN.ATM.CO2E.KT'      , 'CO2 emissions (kt)'                                                                                                         , ['Climate', 'Env']                           ], 
    ['EN.ATM.CO2E.PC'      , 'CO2 emissions (metric tons per capita)'                                                                                     , ['Climate', 'Env']                           ], 
    ['EN.ATM.CO2E.PP.GD'   , 'CO2 emissions (kg per PPP $ of GDP)'                                                                                        , ['Climate', 'Env']                           ], 
    ['EN.POP.SLUM.UR.ZS'   , 'Population living in slums (% of urban population)'                                                                         , ['Poverty', 'Urban', 'Env']                  ], 
    ['ER.H2O.FWTL.ZS'      , 'Annual freshwater withdrawals, total (% of internal resources)'                                                             , ['Climate', 'Infras', 'Env']                 ], 
    ['ER.H2O.INTR.PC'      , 'Renewable internal freshwater resources per capita (cubic meters)'                                                          , ['Infras', 'Env']                            ], 
    ['ER.LND.PTLD.ZS'      , 'Terrestrial protected areas (% of total land area)'                                                                         , ['Climate', 'Env']                           ], 
    ['ER.MRN.PTMR.ZS'      , 'Marine protected areas (% of territorial waters)'                                                                           , ['Climate', 'Env']                           ], 
    ['IT.CEL.SETS.P2'      , 'Mobile cellular subscriptions (per 100 people)'                                                                             , ['Infras']                                   ], 
    ['IT.MLT.MAIN.P2'      , 'Fixed telephone subscriptions (per 100 people)'                                                                             , ['Infras']                                   ], 
    ['IT.NET.USER.P2'      , 'Internet users (per 100 people)'                                                                                            , ['Infras']                                   ], 
    ['NE.GDI.TOTL.ZS'      , 'Gross capital formation (% of GDP)'                                                                                         , ['Econ']                                     ], 
    ['NE.TRD.GNFS.ZS'      , 'Trade (% of GDP)'                                                                                                           , ['Econ', 'Trade']                            ], 
    ['NY.AGR.SUBS.GD.ZS'   , 'Agricultural support estimate (% of GDP)'                                                                                   , ['2kGoals']                                  ], 
    ['NY.GNP.ATLS.CD'      , 'GNI, Atlas method (current US$)'                                                                                            , ['Econ']                                     ], 
    ['NY.GNP.PCAP.CD'      , 'GNI per capita, Atlas method (current US$)'                                                                                 , ['Econ']                                     ], 
    ['PA.NUS.PPP'          , 'PPP conversion factor, GDP (LCU per international $)'                                                                       , ['Econ']                                     ], 
    ['PA.NUS.PRVT.PP'      , 'PPP conversion factor, private consumption (LCU per international $)'                                                       , ['Econ']                                     ], 
    ['SE.ADT.1524.LT.FE.ZS', 'Literacy rate, youth female (% of females ages 15-24)'                                                                      , ['Edu', 'Gender']                            ], 
    ['SE.ADT.1524.LT.MA.ZS', 'Literacy rate, youth male (% of males ages 15-24)'                                                                          , ['Edu', 'Gender']                            ], 
    ['SE.ADT.1524.LT.ZS'   , 'Literacy rate, youth total (% of people ages 15-24)'                                                                        , ['Edu']                                      ], 
    ['SE.ADT.LITR.ZS'      , 'Literacy rate, adult total (% of people ages 15 and above)'                                                                 , ['Edu']                                      ], 
    ['SE.ENR.ORPH'         , 'Ratio of school attendance of orphans to school attendance of non-orphans ages 10-14'                                       , null                                         ], 
    ['SE.ENR.PRIM.FM.ZS'   , 'School enrollment, primary (gross), gender parity index (GPI)'                                                              , ['Edu', 'Gender', 'Social']                  ], 
    ['SE.ENR.PRSC.FM.ZS'   , 'School enrollment, primary and secondary (gross), gender parity index (GPI)'                                                , ['Aid', 'Climate', 'Edu', 'Gender', 'Social']], 
    ['SE.ENR.SECO.FM.ZS'   , 'School enrollment, secondary (gross), gender parity index (GPI)'                                                            , ['Edu', 'Gender', 'Social']                  ], 
    ['SE.ENR.TERT.FM.ZS'   , 'School enrollment, tertiary (gross), gender parity index (GPI)'                                                             , ['Edu', 'Gender', 'Social']                  ], 
    ['SE.PRM.CMPT.ZS'      , 'Primary completion rate, total (% of relevant age group)'                                                                   , ['Aid', 'Climate', 'Edu']                    ], 
    ['SE.PRM.NENR'         , 'School enrollment, primary (% net)'                                                                                         , ['Edu']                                      ], 
    ['SE.PRM.PRSL.FE.ZS'   , 'Persistence to last grade of primary, female (% of cohort)'                                                                 , ['Edu', 'Gender']                            ], 
    ['SE.PRM.PRSL.MA.ZS'   , 'Persistence to last grade of primary, male (% of cohort)'                                                                   , ['Edu', 'Gender']                            ], 
    ['SE.PRM.PRSL.ZS'      , 'Persistence to last grade of primary, total (% of cohort)'                                                                  , ['Edu']                                      ], 
    ['SE.PRM.TENR'         , 'Adjusted net enrollment rate, primary (% of primary school age children)'                                                   , ['Edu']                                      ], 
    ['SG.GEN.PARL.ZS'      , 'Proportion of seats held by women in national parliaments (%)'                                                              , ['Public', 'Gender', 'Social']               ], 
    ['SH.CON.1524.FE.ZS'   , 'Condom use, population ages 15-24, female (% of females ages 15-24)'                                                        , ['Health', 'Gender']                         ], 
    ['SH.CON.1524.MA.ZS'   , 'Condom use, population ages 15-24, male (% of males ages 15-24)'                                                            , ['Health', 'Gender']                         ], 
    ['SH.CON.AIDS.FE.ZS'   , 'Condom use at last high-risk sex, adult female (% ages 15-49)'                                                              , null                                         ], 
    ['SH.CON.AIDS.MA.ZS'   , 'Condom use at last high-risk sex, adult male (% ages 15-49)'                                                                , null                                         ], 
    ['SH.DYN.AIDS.DH'      , 'AIDS estimated deaths (UNAIDS estimates)'                                                                                   , null                                         ], 
    ['SH.DYN.AIDS.ZS'      , 'Prevalence of HIV, total (% of population ages 15-49)'                                                                      , ['Health', 'Aid']                            ], 
    ['SH.DYN.MORT'         , 'Mortality rate, under-5 (per 1,000 live births)'                                                                            , ['Health', 'Aid', 'Climate']                 ], 
    ['SH.H2O.SAFE.ZS'      , 'Improved water source (% of population with access)'                                                                        , ['Climate', 'Infras', 'Health']              ], 
    ['SH.HIV.1524.FE.ZS'   , 'Prevalence of HIV, female (% ages 15-24)'                                                                                   , ['Health', 'Gender', 'Social']               ], 
    ['SH.HIV.1524.KW.FE.ZS', 'Comprehensive correct knowledge of HIV/AIDS, ages 15-24, female (2 prevent ways and reject 3 misconceptions)'               , null                                         ], 
    ['SH.HIV.1524.KW.MA.ZS', 'Comprehensive correct knowledge of HIV/AIDS, ages 15-24, male (2 prevent ways and reject 3 misconceptions)'                 , null                                         ], 
    ['SH.HIV.1524.MA.ZS'   , 'Prevalence of HIV, male (% ages 15-24)'                                                                                     , ['Health', 'Gender', 'Social']               ], 
    ['SH.HIV.ARTC.ZS'      , 'Antiretroviral therapy coverage (% of people living with HIV)'                                                              , ['Health']                                   ], 
    ['SH.HIV.KNOW.FE.ZS'   , '% of females having comprehensive correct knowledge about HIV (2 prevent ways and reject 3 misconceptions)'                 , null                                         ], 
    ['SH.HIV.KNOW.MA.ZS'   , 'Comprehensive correct knowledge of HIV/AIDS, ages 15-49, male (2 prevent ways and reject 3 misconceptions)'                 , null                                         ], 
    ['SH.HIV.ORPH'         , 'Children orphaned by HIV/AIDS'                                                                                              , null                                         ], 
    ['SH.IMM.MEAS'         , 'Immunization, measles (% of children ages 12-23 months)'                                                                    , ['Health']                                   ], 
    ['SH.MLR.NETS.ZS'      , 'Use of insecticide-treated bed nets (% of under-5 population)'                                                              , ['Health']                                   ], 
    ['SH.MLR.TRET.ZS'      , 'Children with fever receiving antimalarial drugs (% of children under age 5 with fever)'                                    , ['Health']                                   ], 
    ['SH.STA.ACSN'         , 'Improved sanitation facilities (% of population with access)'                                                               , ['Health', 'Aid', 'Climate']                 ], 
    ['SH.STA.ANV4.ZS'      , 'Pregnant women receiving prenatal care of at least four visits (% of pregnant women)'                                       , null                                         ], 
    ['SH.STA.ANVC.ZS'      , 'Pregnant women receiving prenatal care (%)'                                                                                 , ['Health', 'Gender', 'Aid']                  ], 
    ['SH.STA.ARIC.ZS'      , 'ARI treatment (% of children under 5 taken to a health provider)'                                                           , ['Health']                                   ], 
    ['SH.STA.BRTC.ZS'      , 'Births attended by skilled health staff (% of total)'                                                                       , ['Health', 'Gender']                         ], 
    ['SH.STA.MALN.ZS'      , 'Prevalence of underweight, weight for age (% of children under 5)'                                                          , ['Health', 'Climate']                        ], 
    ['SH.STA.MALR'         , 'Malaria cases reported'                                                                                                     , null                                         ], 
    ['SH.STA.MMRT'         , 'Maternal mortality ratio (modeled estimate, per 100,000 live births)'                                                       , ['Health', 'Gender', 'Aid']                  ], 
    ['SH.TBS.CURE.ZS'      , 'Tuberculosis treatment success rate (% of new cases)'                                                                       , ['Health']                                   ], 
    ['SH.TBS.DTEC.ZS'      , 'Tuberculosis case detection rate (%, all forms)'                                                                            , ['Health']                                   ], 
    ['SH.TBS.INCD'         , 'Incidence of tuberculosis (per 100,000 people)'                                                                             , ['Health', 'Aid']                            ], 
    ['SH.TBS.MORT'         , 'Tuberculosis death rate (per 100,000 people)'                                                                               , null                                         ], 
    ['SI.DST.FRST.20'      , 'Income share held by lowest 20%'                                                                                            , ['Poverty', 'Aid']                           ], 
    ['SI.POV.DDAY'         , 'Poverty headcount ratio at $1.90 a day (2011 PPP) (% of population)'                                                        , ['Poverty', 'Aid', 'Climate']                ], 
    ['SI.POV.GAPS'         , 'Poverty gap at $1.90 a day (2011 PPP) (%)'                                                                                  , ['Poverty']                                  ], 
    ['SI.POV.NAGP'         , 'Poverty gap at national poverty lines (%)'                                                                                  , ['Poverty']                                  ], 
    ['SI.POV.NAHC'         , 'Poverty headcount ratio at national poverty lines (% of population)'                                                        , ['Poverty']                                  ], 
    ['SI.POV.RUGP'         , 'Rural poverty gap at national poverty lines (%)'                                                                            , ['AgriRural', 'Poverty']                     ], 
    ['SI.POV.RUHC'         , 'Rural poverty headcount ratio at national poverty lines (% of rural population)'                                            , ['AgriRural', 'Poverty']                     ], 
    ['SI.POV.URGP'         , 'Urban poverty gap at national poverty lines (%)'                                                                            , ['Poverty', 'Urban']                         ], 
    ['SI.POV.URHC'         , 'Urban poverty headcount ratio at national poverty lines (% of urban population)'                                            , ['Poverty', 'Urban']                         ], 
    ['SL.EMP.1524.SP.FE.ZS', 'Employment to population ratio, ages 15-24, female (%) (modeled ILO estimate)'                                              , ['Labor', 'Gender']                          ], 
    ['SL.EMP.1524.SP.MA.ZS', 'Employment to population ratio, ages 15-24, male (%) (modeled ILO estimate)'                                                , ['Labor', 'Gender']                          ], 
    ['SL.EMP.1524.SP.ZS'   , 'Employment to population ratio, ages 15-24, total (%) (modeled ILO estimate)'                                               , ['Labor']                                    ], 
    ['SL.EMP.INSV.FE.ZS'   , 'Share of women in wage employment in the nonagricultural sector (% of total nonagricultural employment)'                    , ['Labor', 'Gender', 'Social']                ], 
    ['SL.EMP.SELF.FE.ZS'   , 'Self-employed, female (% of female employment) (modeled ILO estimate)'                                                      , ['Labor', 'Gender']                          ], 
    ['SL.EMP.SELF.MA.ZS'   , 'Self-employed, male (% of male employment) (modeled ILO estimate)'                                                          , ['Labor', 'Gender']                          ], 
    ['SL.EMP.SELF.ZS'      , 'Self-employed, total (% of total employment) (modeled ILO estimate)'                                                        , ['Labor']                                    ], 
    ['SL.EMP.TOTL.SP.FE.ZS', 'Employment to population ratio, 15+, female (%) (modeled ILO estimate)'                                                     , ['Labor', 'Gender']                          ], 
    ['SL.EMP.TOTL.SP.MA.ZS', 'Employment to population ratio, 15+, male (%) (modeled ILO estimate)'                                                       , ['Labor', 'Gender']                          ], 
    ['SL.EMP.TOTL.SP.ZS'   , 'Employment to population ratio, 15+, total (%) (modeled ILO estimate)'                                                      , ['Labor']                                    ], 
    ['SL.EMP.VULN.FE.ZS'   , 'Vulnerable employment, female (% of female employment) (modeled ILO estimate)'                                              , ['Labor', 'Gender', 'Social']                ], 
    ['SL.EMP.VULN.MA.ZS'   , 'Vulnerable employment, male (% of male employment) (modeled ILO estimate)'                                                  , ['Labor', 'Gender', 'Social']                ], 
    ['SL.EMP.VULN.ZS'      , 'Vulnerable employment, total (% of total employment) (modeled ILO estimate)'                                                , ['Labor', 'Aid']                             ], 
    ['SL.FAM.WORK.FE.ZS'   , 'Contributing family workers, female (% of female employment) (modeled ILO estimate)'                                        , ['Labor', 'Gender']                          ], 
    ['SL.FAM.WORK.MA.ZS'   , 'Contributing family workers, male (% of male employment) (modeled ILO estimate)'                                            , ['Labor', 'Gender']                          ], 
    ['SL.FAM.WORK.ZS'      , 'Contributing family workers, total (% of total employment) (modeled ILO estimate)'                                          , ['Labor']                                    ], 
    ['SL.GDP.PCAP.EM.KD'   , 'GDP per person employed (constant 2017 PPP $)'                                                                              , ['Labor']                                    ], 
    ['SN.ITK.DEFC.ZS'      , 'Prevalence of undernourishment (% of population)'                                                                           , ['Health']                                   ], 
    ['SP.ADO.TFRT'         , 'Adolescent fertility rate (births per 1,000 women ages 15-19)'                                                              , ['Health', 'Gender', 'Social']               ], 
    ['SP.DYN.CONU.ZS'      , 'Contraceptive prevalence, any methods (% of women ages 15-49)'                                                              , ['Health', 'Gender']                         ], 
    ['SP.DYN.IMRT.IN'      , 'Mortality rate, infant (per 1,000 live births)'                                                                             , ['Health']                                   ], 
    ['SP.DYN.LE00.IN'      , 'Life expectancy at birth, total (years)'                                                                                    , ['Health']                                   ], 
    ['SP.DYN.TFRT.IN'      , 'Fertility rate, total (births per woman)'                                                                                   , ['Health', 'Gender']                         ], 
    ['SP.POP.TOTL'         , 'Population, total'                                                                                                          , ['Climate', 'Health']                        ], 
    ['SP.UWT.TFRT'         , 'Unmet need for contraception (% of married women ages 15-49)'                                                               , ['Health']                                   ], 
    ['TM.MRC.NOTX.DV.ZS'   , 'Goods (excluding arms) admitted free of tariffs from developing countries (% total merchandise imports excluding arms)'     , ['2kGoals']                                  ], 
    ['TM.MRC.NOTX.LD.ZS'   , 'Goods (excluding arms) admitted free of tariffs from least developed countries (% total merchandise imports excluding arms)', ['2kGoals']                                  ], 
    ['TM.TAX.AGRI.CD.DV'   , 'Average tariffs imposed by developed countries on agricultural products from developing countries (%)'                      , ['2kGoals']                                  ], 
    ['TM.TAX.AGRI.CD.LD'   , 'Average tariffs imposed by developed countries on agricultural products from least developed countries (%)'                 , ['2kGoals']                                  ], 
    ['TM.TAX.CLTH.CD.DV'   , 'Average tariffs imposed by developed countries on clothing products from developing countries (%)'                          , ['2kGoals']                                  ], 
    ['TM.TAX.CLTH.CD.LD'   , 'Average tariffs imposed by developed countries on clothing products from least developed countries (%)'                     , ['2kGoals']                                  ], 
    ['TM.TAX.TXTL.CD.DV'   , 'Average tariffs imposed by developed countries on textile products from developing countries (%)'                           , ['2kGoals']                                  ], 
    ['TM.TAX.TXTL.CD.LD'   , 'Average tariffs imposed by developed countries on textile products from least developed countries (%)'                      , ['2kGoals']                                  ], 
  ], 
}