export const PopulationEstimatesAndProjections = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['SH.DTH.0509'      , 'Number of deaths ages 5-9 years'                                    , ['Edu']                       ], 
    ['SH.DTH.1014'      , 'Number of deaths ages 10-14 years'                                  , ['Edu']                       ], 
    ['SH.DTH.1519'      , 'Number of deaths ages 15-19 years'                                  , ['Edu']                       ], 
    ['SH.DTH.2024'      , 'Number of deaths ages 20-24 years'                                  , ['Edu']                       ], 
    ['SH.DTH.IMRT'      , 'Number of infant deaths'                                            , ['Health']                    ], 
    ['SH.DTH.IMRT.FE'   , 'Number of infant deaths, female'                                    , ['Edu', 'Health']             ], 
    ['SH.DTH.IMRT.MA'   , 'Number of infant deaths, male'                                      , ['Edu', 'Health', 'Health']   ], 
    ['SH.DTH.MORT'      , 'Number of under-five deaths'                                        , ['Health']                    ], 
    ['SH.DTH.MORT.FE'   , 'Number of under-five deaths, female'                                , ['Edu', 'Health', 'Health']   ], 
    ['SH.DTH.MORT.MA'   , 'Number of under-five deaths, male'                                  , ['Edu', 'Health', 'Health']   ], 
    ['SH.DTH.NMRT'      , 'Number of neonatal deaths'                                          , ['Health']                    ], 
    ['SH.DYN.0509'      , 'Probability of dying among children ages 5-9 years (per 1,000)'     , ['Edu']                       ], 
    ['SH.DYN.1014'      , 'Probability of dying among adolescents ages 10-14 years (per 1,000)', ['Edu']                       ], 
    ['SH.DYN.1519'      , 'Probability of dying among adolescents ages 15-19 years (per 1,000)', ['Edu']                       ], 
    ['SH.DYN.2024'      , 'Probability of dying among youth ages 20-24 years (per 1,000)'      , ['Edu']                       ], 
    ['SH.DYN.MORT'      , 'Mortality rate, under-5 (per 1,000 live births)'                    , ['Health', 'Aid', 'Climate']  ], 
    ['SH.DYN.MORT.FE'   , 'Mortality rate, under-5, female (per 1,000 live births)'            , ['Health']                    ], 
    ['SH.DYN.MORT.MA'   , 'Mortality rate, under-5, male (per 1,000 live births)'              , ['Health']                    ], 
    ['SH.DYN.NMRT'      , 'Mortality rate, neonatal (per 1,000 live births)'                   , ['Health']                    ], 
    ['SM.POP.NETM'      , 'Net migration'                                                      , ['Fin', 'Health', 'Aid']      ], 
    ['SP.DYN.AMRT.FE'   , 'Mortality rate, adult, female (per 1,000 female adults)'            , ['Health', 'Gender']          ], 
    ['SP.DYN.AMRT.MA'   , 'Mortality rate, adult, male (per 1,000 male adults)'                , ['Health', 'Gender']          ], 
    ['SP.DYN.CBRT.IN'   , 'Birth rate, crude (per 1,000 people)'                               , ['Health']                    ], 
    ['SP.DYN.CDRT.IN'   , 'Death rate, crude (per 1,000 people)'                               , ['Health']                    ], 
    ['SP.DYN.IMRT.FE.IN', 'Mortality rate, infant, female (per 1,000 live births)'             , ['Health']                    ], 
    ['SP.DYN.IMRT.IN'   , 'Mortality rate, infant (per 1,000 live births)'                     , ['Health']                    ], 
    ['SP.DYN.IMRT.MA.IN', 'Mortality rate, infant, male (per 1,000 live births)'               , ['Health']                    ], 
    ['SP.DYN.LE00.FE.IN', 'Life expectancy at birth, female (years)'                           , ['Health', 'Gender', 'Social']], 
    ['SP.DYN.LE00.IN'   , 'Life expectancy at birth, total (years)'                            , ['Health']                    ], 
    ['SP.DYN.LE00.MA.IN', 'Life expectancy at birth, male (years)'                             , ['Health', 'Gender', 'Social']], 
    ['SP.DYN.TFRT.IN'   , 'Fertility rate, total (births per woman)'                           , ['Health', 'Gender']          ], 
    ['SP.POP.0004.FE'   , 'Population ages 00-04, female'                                      , null                          ], 
    ['SP.POP.0004.FE.5Y', 'Population ages 00-04, female (% of female population)'             , ['Health']                    ], 
    ['SP.POP.0004.MA'   , 'Population ages 00-04, male'                                        , null                          ], 
    ['SP.POP.0004.MA.5Y', 'Population ages 00-04, male (% of male population)'                 , ['Health']                    ], 
    ['SP.POP.0014.FE.IN', 'Population ages 0-14, female'                                       , ['Health']                    ], 
    ['SP.POP.0014.FE.ZS', 'Population ages 0-14, female (% of female population)'              , ['Health']                    ], 
    ['SP.POP.0014.MA.IN', 'Population ages 0-14, male'                                         , ['Health']                    ], 
    ['SP.POP.0014.MA.ZS', 'Population ages 0-14, male (% of male population)'                  , ['Health']                    ], 
    ['SP.POP.0014.TO'   , 'Population ages 0-14, total'                                        , ['Health']                    ], 
    ['SP.POP.0014.TO.ZS', 'Population ages 0-14 (% of total population)'                       , ['Edu', 'Health']             ], 
    ['SP.POP.0509.FE'   , 'Population ages 05-09, female'                                      , null                          ], 
    ['SP.POP.0509.FE.5Y', 'Population ages 05-09, female (% of female population)'             , ['Health']                    ], 
    ['SP.POP.0509.MA'   , 'Population ages 05-09, male'                                        , null                          ], 
    ['SP.POP.0509.MA.5Y', 'Population ages 05-09, male (% of male population)'                 , ['Health']                    ], 
    ['SP.POP.1014.FE'   , 'Population ages 10-14, female'                                      , null                          ], 
    ['SP.POP.1014.FE.5Y', 'Population ages 10-14, female (% of female population)'             , ['Health']                    ], 
    ['SP.POP.1014.MA'   , 'Population ages 10-14, male'                                        , null                          ], 
    ['SP.POP.1014.MA.5Y', 'Population ages 10-14, male (% of male population)'                 , ['Health']                    ], 
    ['SP.POP.1519.FE'   , 'Population ages 15-19, female'                                      , null                          ], 
    ['SP.POP.1519.FE.5Y', 'Population ages 15-19, female (% of female population)'             , ['Health']                    ], 
    ['SP.POP.1519.MA'   , 'Population ages 15-19, male'                                        , null                          ], 
    ['SP.POP.1519.MA.5Y', 'Population ages 15-19, male (% of male population)'                 , ['Health']                    ], 
    ['SP.POP.1564.FE.IN', 'Population ages 15-64, female'                                      , ['Health']                    ], 
    ['SP.POP.1564.FE.ZS', 'Population ages 15-64, female (% of female population)'             , ['Health']                    ], 
    ['SP.POP.1564.MA.IN', 'Population ages 15-64, male'                                        , ['Health']                    ], 
    ['SP.POP.1564.MA.ZS', 'Population ages 15-64, male (% of male population)'                 , ['Health']                    ], 
    ['SP.POP.1564.TO'   , 'Population ages 15-64, total'                                       , ['Health']                    ], 
    ['SP.POP.1564.TO.ZS', 'Population ages 15-64 (% of total population)'                      , ['Edu', 'Health']             ], 
    ['SP.POP.2024.FE'   , 'Population ages 20-24, female'                                      , null                          ], 
    ['SP.POP.2024.FE.5Y', 'Population ages 20-24, female (% of female population)'             , ['Health']                    ], 
    ['SP.POP.2024.MA'   , 'Population ages 20-24, male'                                        , null                          ], 
    ['SP.POP.2024.MA.5Y', 'Population ages 20-24, male (% of male population)'                 , ['Health']                    ], 
    ['SP.POP.2529.FE'   , 'Population ages 25-29, female'                                      , null                          ], 
    ['SP.POP.2529.FE.5Y', 'Population ages 25-29, female (% of female population)'             , ['Health']                    ], 
    ['SP.POP.2529.MA'   , 'Population ages 25-29, male'                                        , null                          ], 
    ['SP.POP.2529.MA.5Y', 'Population ages 25-29, male (% of male population)'                 , ['Health']                    ], 
    ['SP.POP.3034.FE'   , 'Population ages 30-34, female'                                      , null                          ], 
    ['SP.POP.3034.FE.5Y', 'Population ages 30-34, female (% of female population)'             , ['Health']                    ], 
    ['SP.POP.3034.MA'   , 'Population ages 30-34, male'                                        , null                          ], 
    ['SP.POP.3034.MA.5Y', 'Population ages 30-34, male (% of male population)'                 , ['Health']                    ], 
    ['SP.POP.3539.FE'   , 'Population ages 35-39, female'                                      , null                          ], 
    ['SP.POP.3539.FE.5Y', 'Population ages 35-39, female (% of female population)'             , ['Health']                    ], 
    ['SP.POP.3539.MA'   , 'Population ages 35-39, male'                                        , null                          ], 
    ['SP.POP.3539.MA.5Y', 'Population ages 35-39, male (% of male population)'                 , ['Health']                    ], 
    ['SP.POP.4044.FE'   , 'Population ages 40-44, female'                                      , null                          ], 
    ['SP.POP.4044.FE.5Y', 'Population ages 40-44, female (% of female population)'             , ['Health']                    ], 
    ['SP.POP.4044.MA'   , 'Population ages 40-44, male'                                        , null                          ], 
    ['SP.POP.4044.MA.5Y', 'Population ages 40-44, male (% of male population)'                 , ['Health']                    ], 
    ['SP.POP.4549.FE'   , 'Population ages 45-49, female'                                      , null                          ], 
    ['SP.POP.4549.FE.5Y', 'Population ages 45-49, female (% of female population)'             , ['Health']                    ], 
    ['SP.POP.4549.MA'   , 'Population ages 45-49, male'                                        , null                          ], 
    ['SP.POP.4549.MA.5Y', 'Population ages 45-49, male (% of male population)'                 , ['Health']                    ], 
    ['SP.POP.5054.FE'   , 'Population ages 50-54, female'                                      , null                          ], 
    ['SP.POP.5054.FE.5Y', 'Population ages 50-54, female (% of female population)'             , ['Health']                    ], 
    ['SP.POP.5054.MA'   , 'Population ages 50-54, male'                                        , null                          ], 
    ['SP.POP.5054.MA.5Y', 'Population ages 50-54, male (% of male population)'                 , ['Health']                    ], 
    ['SP.POP.5559.FE'   , 'Population ages 55-59, female'                                      , null                          ], 
    ['SP.POP.5559.FE.5Y', 'Population ages 55-59, female (% of female population)'             , ['Health']                    ], 
    ['SP.POP.5559.MA'   , 'Population ages 55-59, male'                                        , null                          ], 
    ['SP.POP.5559.MA.5Y', 'Population ages 55-59, male (% of male population)'                 , ['Health']                    ], 
    ['SP.POP.6064.FE'   , 'Population ages 60-64, female'                                      , null                          ], 
    ['SP.POP.6064.FE.5Y', 'Population ages 60-64, female (% of female population)'             , ['Health']                    ], 
    ['SP.POP.6064.MA'   , 'Population ages 60-64, male'                                        , null                          ], 
    ['SP.POP.6064.MA.5Y', 'Population ages 60-64, male (% of male population)'                 , ['Health']                    ], 
    ['SP.POP.6569.FE'   , 'Population ages 65-69, female'                                      , null                          ], 
    ['SP.POP.6569.FE.5Y', 'Population ages 65-69, female (% of female population)'             , ['Health']                    ], 
    ['SP.POP.6569.MA'   , 'Population ages 65-69, male'                                        , null                          ], 
    ['SP.POP.6569.MA.5Y', 'Population ages 65-69, male (% of male population)'                 , ['Health']                    ], 
    ['SP.POP.65UP.FE.IN', 'Population ages 65 and above, female'                               , ['Health']                    ], 
    ['SP.POP.65UP.FE.ZS', 'Population ages 65 and above, female (% of female population)'      , ['Health']                    ], 
    ['SP.POP.65UP.MA.IN', 'Population ages 65 and above, male'                                 , ['Health']                    ], 
    ['SP.POP.65UP.MA.ZS', 'Population ages 65 and above, male (% of male population)'          , ['Health']                    ], 
    ['SP.POP.65UP.TO'   , 'Population ages 65 and above, total'                                , ['Health']                    ], 
    ['SP.POP.65UP.TO.ZS', 'Population ages 65 and above (% of total population)'               , ['Health']                    ], 
    ['SP.POP.7074.FE'   , 'Population ages 70-74, female'                                      , null                          ], 
    ['SP.POP.7074.FE.5Y', 'Population ages 70-74, female (% of female population)'             , ['Health']                    ], 
    ['SP.POP.7074.MA'   , 'Population ages 70-74, male'                                        , null                          ], 
    ['SP.POP.7074.MA.5Y', 'Population ages 70-74, male (% of male population)'                 , ['Health']                    ], 
    ['SP.POP.7579.FE'   , 'Population ages 75-79, female'                                      , null                          ], 
    ['SP.POP.7579.FE.5Y', 'Population ages 75-79, female (% of female population)'             , ['Health']                    ], 
    ['SP.POP.7579.MA'   , 'Population ages 75-79, male'                                        , null                          ], 
    ['SP.POP.7579.MA.5Y', 'Population ages 75-79, male (% of male population)'                 , ['Health']                    ], 
    ['SP.POP.80UP.FE'   , 'Population ages 80 and above, female'                               , ['Health']                    ], 
    ['SP.POP.80UP.FE.5Y', 'Population ages 80 and above, female (% of female population)'      , ['Health']                    ], 
    ['SP.POP.80UP.MA'   , 'Population ages 80 and above, male'                                 , null                          ], 
    ['SP.POP.80UP.MA.5Y', 'Population ages 80 and above, male (% of male population)'          , ['Health']                    ], 
    ['SP.POP.AG00.FE.IN', 'Age population, age 00, female, interpolated'                       , ['Gender']                    ], 
    ['SP.POP.AG00.MA.IN', 'Age population, age 00, male, interpolated'                         , ['Gender']                    ], 
    ['SP.POP.AG01.FE.IN', 'Age population, age 01, female, interpolated'                       , ['Gender']                    ], 
    ['SP.POP.AG01.MA.IN', 'Age population, age 01, male, interpolated'                         , ['Gender']                    ], 
    ['SP.POP.AG02.FE.IN', 'Age population, age 02, female, interpolated'                       , ['Gender']                    ], 
    ['SP.POP.AG02.MA.IN', 'Age population, age 02, male, interpolated'                         , ['Gender']                    ], 
    ['SP.POP.AG03.FE.IN', 'Age population, age 03, female, interpolated'                       , ['Gender']                    ], 
    ['SP.POP.AG03.MA.IN', 'Age population, age 03, male, interpolated'                         , ['Gender']                    ], 
    ['SP.POP.AG04.FE.IN', 'Age population, age 04, female, interpolated'                       , ['Gender']                    ], 
    ['SP.POP.AG04.MA.IN', 'Age population, age 04, male, interpolated'                         , ['Gender']                    ], 
    ['SP.POP.AG05.FE.IN', 'Age population, age 05, female, interpolated'                       , ['Gender']                    ], 
    ['SP.POP.AG05.MA.IN', 'Age population, age 05, male, interpolated'                         , ['Gender']                    ], 
    ['SP.POP.AG06.FE.IN', 'Age population, age 06, female, interpolated'                       , null                          ], 
    ['SP.POP.AG06.MA.IN', 'Age population, age 06, male, interpolated'                         , null                          ], 
    ['SP.POP.AG07.FE.IN', 'Age population, age 07, female, interpolated'                       , null                          ], 
    ['SP.POP.AG07.MA.IN', 'Age population, age 07, male, interpolated'                         , null                          ], 
    ['SP.POP.AG08.FE.IN', 'Age population, age 08, female, interpolated'                       , null                          ], 
    ['SP.POP.AG08.MA.IN', 'Age population, age 08, male, interpolated'                         , null                          ], 
    ['SP.POP.AG09.FE.IN', 'Age population, age 09, female, interpolated'                       , null                          ], 
    ['SP.POP.AG09.MA.IN', 'Age population, age 09, male, interpolated'                         , null                          ], 
    ['SP.POP.AG10.FE.IN', 'Age population, age 10, female, interpolated'                       , null                          ], 
    ['SP.POP.AG10.MA.IN', 'Age population, age 10, male, interpolated'                         , null                          ], 
    ['SP.POP.AG11.FE.IN', 'Age population, age 11, female, interpolated'                       , null                          ], 
    ['SP.POP.AG11.MA.IN', 'Age population, age 11, male, interpolated'                         , null                          ], 
    ['SP.POP.AG12.FE.IN', 'Age population, age 12, female, interpolated'                       , null                          ], 
    ['SP.POP.AG12.MA.IN', 'Age population, age 12, male, interpolated'                         , null                          ], 
    ['SP.POP.AG13.FE.IN', 'Age population, age 13, female, interpolated'                       , null                          ], 
    ['SP.POP.AG13.MA.IN', 'Age population, age 13, male, interpolated'                         , null                          ], 
    ['SP.POP.AG14.FE.IN', 'Age population, age 14, female, interpolated'                       , null                          ], 
    ['SP.POP.AG14.MA.IN', 'Age population, age 14, male, interpolated'                         , null                          ], 
    ['SP.POP.AG15.FE.IN', 'Age population, age 15, female, interpolated'                       , null                          ], 
    ['SP.POP.AG15.MA.IN', 'Age population, age 15, male, interpolated'                         , null                          ], 
    ['SP.POP.AG16.FE.IN', 'Age population, age 16, female, interpolated'                       , null                          ], 
    ['SP.POP.AG16.MA.IN', 'Age population, age 16, male, interpolated'                         , null                          ], 
    ['SP.POP.AG17.FE.IN', 'Age population, age 17, female, interpolated'                       , null                          ], 
    ['SP.POP.AG17.MA.IN', 'Age population, age 17, male, interpolated'                         , null                          ], 
    ['SP.POP.AG18.FE.IN', 'Age population, age 18, female, interpolated'                       , null                          ], 
    ['SP.POP.AG18.MA.IN', 'Age population, age 18, male, interpolated'                         , null                          ], 
    ['SP.POP.AG19.FE.IN', 'Age population, age 19, female, interpolated'                       , null                          ], 
    ['SP.POP.AG19.MA.IN', 'Age population, age 19, male, interpolated'                         , null                          ], 
    ['SP.POP.AG20.FE.IN', 'Age population, age 20, female, interpolated'                       , null                          ], 
    ['SP.POP.AG20.MA.IN', 'Age population, age 20, male, interpolated'                         , null                          ], 
    ['SP.POP.AG21.FE.IN', 'Age population, age 21, female, interpolated'                       , null                          ], 
    ['SP.POP.AG21.MA.IN', 'Age population, age 21, male, interpolated'                         , null                          ], 
    ['SP.POP.AG22.FE.IN', 'Age population, age 22, female, interpolated'                       , null                          ], 
    ['SP.POP.AG22.MA.IN', 'Age population, age 22, male, interpolated'                         , null                          ], 
    ['SP.POP.AG23.FE.IN', 'Age population, age 23, female, interpolated'                       , null                          ], 
    ['SP.POP.AG23.MA.IN', 'Age population, age 23, male, interpolated'                         , null                          ], 
    ['SP.POP.AG24.FE.IN', 'Age population, age 24, female, interpolated'                       , null                          ], 
    ['SP.POP.AG24.MA.IN', 'Age population, age 24, male, interpolated'                         , null                          ], 
    ['SP.POP.AG25.FE.IN', 'Age population, age 25, female, interpolated'                       , null                          ], 
    ['SP.POP.AG25.MA.IN', 'Age population, age 25, male, interpolated'                         , null                          ], 
    ['SP.POP.BRTH.MF'   , 'Sex ratio at birth (male births per female births)'                 , ['Health']                    ], 
    ['SP.POP.DPND'      , 'Age dependency ratio (% of working-age population)'                 , ['Health']                    ], 
    ['SP.POP.DPND.OL'   , 'Age dependency ratio, old (% of working-age population)'            , ['Health']                    ], 
    ['SP.POP.DPND.YG'   , 'Age dependency ratio, young (% of working-age population)'          , ['Health']                    ], 
    ['SP.POP.GROW'      , 'Population growth (annual %)'                                       , ['Climate', 'Health']         ], 
    ['SP.POP.TOTL'      , 'Population, total'                                                  , ['Climate', 'Health']         ], 
    ['SP.POP.TOTL.FE.IN', 'Population, female'                                                 , ['Health']                    ], 
    ['SP.POP.TOTL.FE.ZS', 'Population, female (% of total population)'                         , ['Health']                    ], 
    ['SP.POP.TOTL.MA.IN', 'Population, male'                                                   , ['Health']                    ], 
    ['SP.POP.TOTL.MA.ZS', 'Population, male (% of total population)'                           , ['Health']                    ], 
    ['SP.RUR.TOTL'      , 'Rural population'                                                   , ['AgriRural']                 ], 
    ['SP.RUR.TOTL.ZG'   , 'Rural population growth (annual %)'                                 , ['AgriRural']                 ], 
    ['SP.RUR.TOTL.ZS'   , 'Rural population (% of total population)'                           , ['AgriRural']                 ], 
    ['SP.URB.GROW'      , 'Urban population growth (annual %)'                                 , ['Climate', 'Urban']          ], 
    ['SP.URB.TOTL'      , 'Urban population'                                                   , ['Climate', 'Urban']          ], 
    ['SP.URB.TOTL.IN.ZS', 'Urban population (% of total population)'                           , ['Climate', 'Urban']          ], 
  ], 
}