export const QuarterlyExternalDebtStatisticsGdds = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['DT.AMT.DECT.CD.00.03.MO.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 0 to 3 mo., All instruments, Principal, USD'         , null], 
    ['DT.AMT.DECT.CD.03.YR.US'   , 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 3yrs, All instruments, Principal, USD'               , null], 
    ['DT.AMT.DECT.CD.04.06.MO.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 3 to 6 mo., All instruments, Principal, USD'         , null], 
    ['DT.AMT.DECT.CD.04.YR.US'   , 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 4yrs, All instruments, Principal, USD'               , null], 
    ['DT.AMT.DECT.CD.05.10.YR.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 5 to 10 yrs, All instruments, Principal, USD'        , null], 
    ['DT.AMT.DECT.CD.05.YR.US'   , 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 5yrs, All instruments, Principal, USD'               , null], 
    ['DT.AMT.DECT.CD.07.09.MO.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 6 to 9 mo., All instruments, Principal, USD'         , null], 
    ['DT.AMT.DECT.CD.10.12.MO.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 9 to 12 mo., All instruments, Principal, USD'        , null], 
    ['DT.AMT.DECT.CD.10.15.YR.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 10 to 15 yrs, All instruments, Principal, USD'       , null], 
    ['DT.AMT.DECT.CD.13.18.MO.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 12 to 18 mo., All instruments, Principal, USD'       , null], 
    ['DT.AMT.DECT.CD.15.UP.YR.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, More than15yrs, All instruments, Principal, USD'     , null], 
    ['DT.AMT.DECT.CD.19.24.MO.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 18 to 24 mo., All instruments, Principal, USD'       , null], 
    ['DT.AMT.DECT.CD.IQ.00.US'   , 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, Immediately, All instruments, Principal, USD'        , null], 
    ['DT.AMT.PRVS.CD.00.03.MO.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 0 to 3 mo., All instruments, Principal, USD'                    , null], 
    ['DT.AMT.PRVS.CD.03.YR.US'   , 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 3yrs, All instruments, Principal, USD'                          , null], 
    ['DT.AMT.PRVS.CD.04.06.MO.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 3 to 6 mo., All instruments, Principal, USD'                    , null], 
    ['DT.AMT.PRVS.CD.04.YR.US'   , 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 4yrs, All instruments, Principal, USD'                          , null], 
    ['DT.AMT.PRVS.CD.05.10.YR.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 5 to 10 yrs, All instruments, Principal, USD'                   , null], 
    ['DT.AMT.PRVS.CD.05.YR.US'   , 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 5yrs, All instruments, Principal, USD'                          , null], 
    ['DT.AMT.PRVS.CD.07.09.MO.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 6 to 9 mo., All instruments, Principal, USD'                    , null], 
    ['DT.AMT.PRVS.CD.10.12.MO.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 9 to 12 mo., All instruments, Principal, USD'                   , null], 
    ['DT.AMT.PRVS.CD.10.15.YR.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 10 to 15 yrs, All instruments, Principal, USD'                  , null], 
    ['DT.AMT.PRVS.CD.13.18.MO.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 12 to 18 mo., All instruments, Principal, USD'                  , null], 
    ['DT.AMT.PRVS.CD.15.UP.YR.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, More than15yrs, All instruments, Principal, USD'                , null], 
    ['DT.AMT.PRVS.CD.19.24.MO.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 18 to 24 mo., All instruments, Principal, USD'                  , null], 
    ['DT.AMT.PRVS.CD.IQ.00.US'   , 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, Immediately, All instruments, Principal, USD'                   , null], 
    ['DT.AMT.PUBS.CD.00.03.MO.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 0 to 3 mo., All instruments, Principal, USD'                                    , null], 
    ['DT.AMT.PUBS.CD.03.YR.US'   , 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 3yrs, All instruments, Principal, USD'                                          , null], 
    ['DT.AMT.PUBS.CD.04.06.MO.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 3 to 6 mo., All instruments, Principal, USD'                                    , null], 
    ['DT.AMT.PUBS.CD.04.YR.US'   , 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 4yrs, All instruments, Principal, USD'                                          , null], 
    ['DT.AMT.PUBS.CD.05.10.YR.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 5 to 10 yrs, All instruments, Principal, USD'                                   , null], 
    ['DT.AMT.PUBS.CD.05.YR.US'   , 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 5yrs, All instruments, Principal, USD'                                          , null], 
    ['DT.AMT.PUBS.CD.07.09.MO.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 6 to 9 mo., All instruments, Principal, USD'                                    , null], 
    ['DT.AMT.PUBS.CD.10.12.MO.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 9 to 12 mo., All instruments, Principal, USD'                                   , null], 
    ['DT.AMT.PUBS.CD.10.15.YR.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 10 to 15 yrs, All instruments, Principal, USD'                                  , null], 
    ['DT.AMT.PUBS.CD.13.18.MO.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 12 to 18 mo., All instruments, Principal, USD'                                  , null], 
    ['DT.AMT.PUBS.CD.15.UP.YR.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, More than15yrs, All instruments, Principal, USD'                                , null], 
    ['DT.AMT.PUBS.CD.19.24.MO.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 18 to 24 mo., All instruments, Principal, USD'                                  , null], 
    ['DT.AMT.PUBS.CD.IQ.00.US'   , 'Ext. Debt Service Pmt, Public Sector Ext. Debt, Immediately, All instruments, Principal, USD'                                   , null], 
    ['DT.DOD.DECT.AR.T4.US'      , 'Public and Publicly Guar. Private Sector Ext. Debt Pos., All maturities, All instruments, Prin. and Int., USD'                  , null], 
    ['DT.DOD.DECT.CD.AR.TL.US'   , 'Gross Ext. Debt Pos., All Sectors, All maturities, Arrears, USD'                                                                , null], 
    ['DT.DOD.DECT.CD.DC.T5.US'   , 'Public and Publicly Guar. Private Sector Ext. Debt Pos., All Sectors, All maturities, All instruments, Domestic currency, USD'  , null], 
    ['DT.DOD.DECT.CD.FC.T5.US'   , 'Public and Publicly Guar. Private Sector Ext. Debt Pos., All Sectors, All maturities, All instruments, Foreign currency, USD'   , null], 
    ['DT.DOD.DECT.CD.LT.US'      , 'Gross Ext. Debt Pos., All Sectors, Long-term, All instruments, USD'                                                             , null], 
    ['DT.DOD.DECT.CD.ST.US'      , 'Gross Ext. Debt Pos., All Sectors, Short-term, All instruments, USD'                                                            , null], 
    ['DT.DOD.DECT.CD.TL.US'      , 'Gross Ext. Debt Pos., All Sectors, All maturities, All instruments, USD'                                                        , null], 
    ['DT.DOD.DECT.CD.UC.T5.US'   , 'Public and Publicly Guar. Private Sector Ext. Debt Pos., All Sectors, All maturities, All instruments, Unallocated, USD'        , null], 
    ['DT.DOD.DECT.DS.T4.US'      , 'Public and Publicly Guar. Private Sector Ext. Debt Pos., All maturities, Debt securities, Memo item, USD'                       , null], 
    ['DT.DOD.DECT.T4.AR.US'      , 'Public and Publicly Guar. Private Sector Ext. Debt Pos., All maturities, All instruments, USD'                                  , null], 
    ['DT.DOD.DLXF.CD.DC.T5.US'   , 'Public and Publicly Guar. Private Sector Ext. Debt Pos., All Sectors, Long-term, All instruments, Domestic currency, USD'       , null], 
    ['DT.DOD.DLXF.CD.FC.T5.US'   , 'Public and Publicly Guar. Private Sector Ext. Debt Pos., All Sectors, Long-term, All instruments, Foreign currency, USD'        , null], 
    ['DT.DOD.DPNG.CD.AR.US'      , 'Gross Ext. Debt Pos., Private Sector Ext. Debt Not Publicly Guar., All maturities, Arrears, USD'                                , null], 
    ['DT.DOD.DPNG.CD.LT.US'      , 'Gross Ext. Debt Pos., Private Sector Ext. Debt Not Publicly Guar., Long-term, All instruments, USD'                             , null], 
    ['DT.DOD.DPNG.CD.ST.US'      , 'Gross Ext. Debt Pos., Private Sector Ext. Debt Not Publicly Guar., Short-term, All instruments, USD'                            , null], 
    ['DT.DOD.DPNG.CD.US'         , 'Gross Ext. Debt Pos., Private Sector Ext. Debt Not Publicly Guar., All maturities, All instruments, USD'                        , null], 
    ['DT.DOD.DPPC.CD.DT.T5.US'   , 'Public and Publicly Guar. Private Sector Ext. Debt Pos., All Sectors, All maturities, All instruments, All currencies, USD'     , null], 
    ['DT.DOD.DPPC.CD.TO.US'      , 'Public and Publicly Guar. Private Sector Ext. Debt Pos., All Creditors, All maturities, All instruments, USD'                   , null], 
    ['DT.DOD.DSTC.CD.DC.T5.US'   , 'Public and Publicly Guar. Private Sector Ext. Debt Pos., All Sectors, Short-term, All instruments, Domestic currency, USD'      , null], 
    ['DT.DOD.DSTC.CD.FC.T5.US'   , 'Public and Publicly Guar. Private Sector Ext. Debt Pos., All Sectors, Short-term, All instruments, Foreign currency, USD'       , null], 
    ['DT.DOD.PCCR.US'            , 'Public and Publicly Guar. Private Sector Ext. Debt Pos., Paris Club member creditors, All maturities, All instruments, USD'     , null], 
    ['DT.DOD.PCPR.LT.US'         , 'Publicly Guar. Private Sector Ext. Debt Pos., Paris Club member creditors, Long-term, All instruments, USD'                     , null], 
    ['DT.DOD.PCPR.ST.US'         , 'Publicly Guar. Private Sector Ext. Debt Pos., Paris Club member creditors, Short-term, All instruments, USD'                    , null], 
    ['DT.DOD.PCPR.US'            , 'Publicly Guar. Private Sector Ext. Debt Pos., Paris Club member creditors, All maturities, All instruments, USD'                , null], 
    ['DT.DOD.PCPU.LT.US'         , 'Public Sector Ext. Debt Pos., Paris Club member creditors, Long-term, All instruments, USD'                                     , null], 
    ['DT.DOD.PCPU.ST.US'         , 'Public Sector Ext. Debt Pos., Paris Club member creditors, Short-term, All instruments, USD'                                    , null], 
    ['DT.DOD.PCPU.US'            , 'Public Sector Ext. Debt Pos., Paris Club member creditors, All maturities, All instruments, USD'                                , null], 
    ['DT.DOD.PRAE.IL.US'         , 'Publicly Guar. Private Sector Ext. Debt Pos., All maturities, Debt liab. of dir. investors to DI ent., USD'                     , null], 
    ['DT.DOD.PRBA.CD.LT.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., Deposit-Taking Corp., exc. CB, creditors, Long-term, All instruments, USD'        , null], 
    ['DT.DOD.PRBA.CD.ST.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., Deposit-Taking Corp., exc. CB, creditors, Short-term, All instruments, USD'       , null], 
    ['DT.DOD.PRBA.CD.US'         , 'Publicly Guar. Private Sector Ext. Debt Pos., Deposit-Taking Corp., exc. CB, creditors, All maturities, All instruments, USD'   , null], 
    ['DT.DOD.PRBL.CD.LT.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., Official bilateral creditors, Long-term, All instruments, USD'                    , null], 
    ['DT.DOD.PRBL.CD.ST.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., Official bilateral creditors, Short-term, All instruments, USD'                   , null], 
    ['DT.DOD.PRBL.CD.US'         , 'Publicly Guar. Private Sector Ext. Debt Pos., Official bilateral creditors, All maturities, All instruments, USD'               , null], 
    ['DT.DOD.PRBN.LT.AR.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., Long-term, Debt securities, USD'                                                  , null], 
    ['DT.DOD.PRCD.LT.AR.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., Long-term, Currency and deposits , USD'                                           , null], 
    ['DT.DOD.PRCD.ST.AR.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., Short-term, Currency and deposits , USD'                                          , null], 
    ['DT.DOD.PRDI.IL.US'         , 'Publicly Guar. Private Sector Ext. Debt Pos., All maturities, Debt liab. of DI ent. to dir. investors, USD'                     , null], 
    ['DT.DOD.PRFE.IL.US'         , 'Publicly Guar. Private Sector Ext. Debt Pos., All maturities, Debt liab. to fellow ent., USD'                                   , null], 
    ['DT.DOD.PRLO.LT.AR.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., Long-term, Loans, USD'                                                            , null], 
    ['DT.DOD.PRLO.ST.AR.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., Short-term, Loans, USD'                                                           , null], 
    ['DT.DOD.PRMM.ST.AR.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., Short-term, Debt securities, USD'                                                 , null], 
    ['DT.DOD.PRMU.CD.LT.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., Multilateral creditors, Long-term, All instruments, USD'                          , null], 
    ['DT.DOD.PRMU.CD.ST.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., Multilateral creditors, Short-term, All instruments, USD'                         , null], 
    ['DT.DOD.PRMU.CD.US'         , 'Publicly Guar. Private Sector Ext. Debt Pos., Multilateral creditors, All maturities, All instruments, USD'                     , null], 
    ['DT.DOD.PROD.LT.AR.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., Long-term, Other debt liabilities, USD'                                           , null], 
    ['DT.DOD.PROD.ST.AR.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., Short-term, Other debt liabilities, USD'                                          , null], 
    ['DT.DOD.PROT.CD.LT.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., Other creditors, Long-term, All instruments, USD'                                 , null], 
    ['DT.DOD.PROT.CD.ST.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., Other creditors, Short-term, All instruments, USD'                                , null], 
    ['DT.DOD.PROT.CD.US'         , 'Publicly Guar. Private Sector Ext. Debt Pos., Other creditors, All maturities, All instruments, USD'                            , null], 
    ['DT.DOD.PRTC.LT.AR.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., Long-term, Trade credit and advances, USD'                                        , null], 
    ['DT.DOD.PRTC.ST.AR.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., Short-term, Trade credit and advances, USD'                                       , null], 
    ['DT.DOD.PRTD.CD.LT.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., Debt securities\' holders, Long-term, All instruments, USD'                       , null], 
    ['DT.DOD.PRTD.CD.ST.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., Debt securities\' holders, Short-term, All instruments, USD'                      , null], 
    ['DT.DOD.PRTD.CD.US'         , 'Publicly Guar. Private Sector Ext. Debt Pos., Debt securities\' holders, All maturities, All instruments, USD'                  , null], 
    ['DT.DOD.PRVS.AR.T4.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., All maturities, Arrears, Prin. and Int., USD'                                     , null], 
    ['DT.DOD.PRVS.CD.AR.US'      , 'Gross Ext. Debt Pos., Publicly Guar. Private Sector Ext. Debt, All maturities, Arrears, USD'                                    , null], 
    ['DT.DOD.PRVS.CD.LT.US'      , 'Gross Ext. Debt Pos., Publicly Guar. Private Sector Ext. Debt, Long-term, All instruments, USD'                                 , null], 
    ['DT.DOD.PRVS.CD.ST.US'      , 'Gross Ext. Debt Pos., Publicly Guar. Private Sector Ext. Debt, Short-term, All instruments, USD'                                , null], 
    ['DT.DOD.PRVS.CD.T3.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., All Creditors, All maturities, All instruments, USD'                              , null], 
    ['DT.DOD.PRVS.CD.US'         , 'Gross Ext. Debt Pos., Publicly Guar. Private Sector Ext. Debt, All maturities, All instruments, USD'                            , null], 
    ['DT.DOD.PRVS.DI.US'         , 'Publicly Guar. Private Sector Ext. Debt Pos., Long-term, DI: Intercom. Lending, USD'                                            , null], 
    ['DT.DOD.PRVS.DS.LT.T4.US'   , 'Publicly Guar. Private Sector Ext. Debt Pos., Long-term, Debt securities, Memo item, USD'                                       , null], 
    ['DT.DOD.PRVS.DS.ST.T4.US'   , 'Publicly Guar. Private Sector Ext. Debt Pos., Short-term, Debt securities, Memo item, USD'                                      , null], 
    ['DT.DOD.PRVS.DS.T4.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., All maturities, Debt securities, Memo item, USD'                                  , null], 
    ['DT.DOD.PRVS.IR.T4.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., All maturities, Arrears, Interest, USD'                                           , null], 
    ['DT.DOD.PRVS.LT.TO.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., Long-term, All instruments, USD'                                                  , null], 
    ['DT.DOD.PRVS.PR.T4.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., All maturities, Arrears, Principal, USD'                                          , null], 
    ['DT.DOD.PRVS.ST.AR.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., Short-term, All instruments, USD'                                                 , null], 
    ['DT.DOD.PRVS.TO.T4.US'      , 'Publicly Guar. Private Sector Ext. Debt Pos., All maturities, All instruments, USD'                                             , null], 
    ['DT.DOD.PSDR.LT.AR.US'      , 'Public Sector Ext. Debt Pos., Long-term, Special drawing rights (allocations), USD'                                             , null], 
    ['DT.DOD.PUAE.IL.US'         , 'Public Sector Ext. Debt Pos., All maturities, Debt liab. of dir. investors to DI ent., USD'                                     , null], 
    ['DT.DOD.PUBA.CD.LT.US'      , 'Public Sector Ext. Debt Pos., Deposit-Taking Corp., exc. CB, creditors, Long-term, All instruments, USD'                        , null], 
    ['DT.DOD.PUBA.CD.ST.US'      , 'Public Sector Ext. Debt Pos., Deposit-Taking Corp., exc. CB, creditors, Short-term, All instruments, USD'                       , null], 
    ['DT.DOD.PUBA.CD.US'         , 'Public Sector Ext. Debt Pos., Deposit-Taking Corp., exc. CB, creditors, All maturities, All instruments, USD'                   , null], 
    ['DT.DOD.PUBL.CD.LT.US'      , 'Public Sector Ext. Debt Pos., Official bilateral creditors, Long-term, All instruments, USD'                                    , null], 
    ['DT.DOD.PUBL.CD.ST.US'      , 'Public Sector Ext. Debt Pos., Official bilateral creditors, Short-term, All instruments, USD'                                   , null], 
    ['DT.DOD.PUBL.CD.US'         , 'Public Sector Ext. Debt Pos., Official bilateral creditors, All maturities, All instruments, USD'                               , null], 
    ['DT.DOD.PUBN.LT.AR.US'      , 'Public Sector Ext. Debt Pos., Long-term, Debt securities, USD'                                                                  , null], 
    ['DT.DOD.PUBS.AR.T4.US'      , 'Public Sector Ext. Debt Pos., All maturities, Arrears, Prin. and Int., USD'                                                     , null], 
    ['DT.DOD.PUBS.CD.AR.US'      , 'Gross Ext. Debt Pos., Public Sector Ext. Debt, All maturities, Arrears, USD'                                                    , null], 
    ['DT.DOD.PUBS.CD.LT.US'      , 'Gross Ext. Debt Pos., Public Sector Ext. Debt, Long-term, All instruments, USD'                                                 , null], 
    ['DT.DOD.PUBS.CD.ST.US'      , 'Gross Ext. Debt Pos., Public Sector Ext. Debt, Short-term, All instruments, USD'                                                , null], 
    ['DT.DOD.PUBS.CD.T3.US'      , 'Public Sector Ext. Debt Pos., All Creditors, All maturities, All instruments, USD'                                              , null], 
    ['DT.DOD.PUBS.CD.US'         , 'Gross Ext. Debt Pos., Public Sector Ext. Debt, All maturities, All instruments, USD'                                            , null], 
    ['DT.DOD.PUBS.DI.US'         , 'Public Sector Ext. Debt Pos., All maturities, DI: Intercom. Lending, USD'                                                       , null], 
    ['DT.DOD.PUBS.DS.LT.T4.US'   , 'Public Sector Ext. Debt Pos., Long-term, Debt securities, Memo item, USD'                                                       , null], 
    ['DT.DOD.PUBS.DS.ST.T4.US'   , 'Public Sector Ext. Debt Pos., Short-term, Debt securities, Memo item, USD'                                                      , null], 
    ['DT.DOD.PUBS.DS.T4.US'      , 'Public Sector Ext. Debt Pos., All maturities, Debt securities, Memo item, USD'                                                  , null], 
    ['DT.DOD.PUBS.IR.T4.US'      , 'Public Sector Ext. Debt Pos., All maturities, Arrears, Interest, USD'                                                           , null], 
    ['DT.DOD.PUBS.LT.TO.US'      , 'Public Sector Ext. Debt Pos., Long-term, All instruments, USD'                                                                  , null], 
    ['DT.DOD.PUBS.PR.T4.US'      , 'Public Sector Ext. Debt Pos., All maturities, Arrears, Principal, USD'                                                          , null], 
    ['DT.DOD.PUBS.ST.AR.US'      , 'Public Sector Ext. Debt Pos., Short-term, All instruments, USD'                                                                 , null], 
    ['DT.DOD.PUBS.TO.T4.US'      , 'Public Sector Ext. Debt Pos., All maturities, All instruments, USD'                                                             , null], 
    ['DT.DOD.PUCD.LT.AR.US'      , 'Public Sector Ext. Debt Pos., Long-term, Currency and deposits , USD'                                                           , null], 
    ['DT.DOD.PUCD.ST.AR.US'      , 'Public Sector Ext. Debt Pos., Short-term, Currency and deposits , USD'                                                          , null], 
    ['DT.DOD.PUDI.IL.US'         , 'Public Sector Ext. Debt Pos., All maturities, Debt liab. of DI ent. to dir. investors, USD'                                     , null], 
    ['DT.DOD.PUFE.IL.US'         , 'Public Sector Ext. Debt Pos., All maturities, Debt liab. to fellow ent., USD'                                                   , null], 
    ['DT.DOD.PULO.LT.AR.US'      , 'Public Sector Ext. Debt Pos., Long-term, Loans, USD'                                                                            , null], 
    ['DT.DOD.PULO.ST.AR.US'      , 'Public Sector Ext. Debt Pos., Short-term, Loans, USD'                                                                           , null], 
    ['DT.DOD.PUMM.ST.AR.US'      , 'Public Sector Ext. Debt Pos., Short-term, Debt securities, USD'                                                                 , null], 
    ['DT.DOD.PUMU.CD.LT.US'      , 'Public Sector Ext. Debt Pos., Multilateral creditors, Long-term, All instruments, USD'                                          , null], 
    ['DT.DOD.PUMU.CD.ST.US'      , 'Public Sector Ext. Debt Pos., Multilateral creditors, Short-term, All instruments, USD'                                         , null], 
    ['DT.DOD.PUMU.CD.US'         , 'Public Sector Ext. Debt Pos., Multilateral creditors, All maturities, All instruments, USD'                                     , null], 
    ['DT.DOD.PUOD.LT.AR.US'      , 'Public Sector Ext. Debt Pos., Long-term, Other debt liabilities, USD'                                                           , null], 
    ['DT.DOD.PUOO.ST.AR.US'      , 'Public Sector Ext. Debt Pos., Short-term, Other debt liabilities, USD'                                                          , null], 
    ['DT.DOD.PUOT.CD.LT.US'      , 'Public Sector Ext. Debt Pos., Other creditors, Long-term, All instruments, USD'                                                 , null], 
    ['DT.DOD.PUOT.CD.ST.US'      , 'Public Sector Ext. Debt Pos., Other creditors, Short-term, All instruments, USD'                                                , null], 
    ['DT.DOD.PUOT.CD.US'         , 'Public Sector Ext. Debt Pos., Other creditors, All maturities, All instruments, USD'                                            , null], 
    ['DT.DOD.PUTC.LT.AR.US'      , 'Public Sector Ext. Debt Pos., Long-term, Trade credit and advances, USD'                                                        , null], 
    ['DT.DOD.PUTC.ST.AR.US'      , 'Public Sector Ext. Debt Pos., Short-term, Trade credit and advances, USD'                                                       , null], 
    ['DT.DOD.PUTD.CD.LT.US'      , 'Public Sector Ext. Debt Pos., Debt securities\' holders, Long-term, All instruments, USD'                                       , null], 
    ['DT.DOD.PUTD.CD.ST.US'      , 'Public Sector Ext. Debt Pos., Debt securities\' holders, Short-term, All instruments, USD'                                      , null], 
    ['DT.DOD.PUTD.CD.US'         , 'Public Sector Ext. Debt Pos., Debt securities\' holders, All maturities, All instruments, USD'                                  , null], 
    ['DT.INP.DECT.00.03.MO.SA.US', 'Ext. Debt Service Pmt, Interest payments on SDR allocations, 0 to 3 mo., All instruments, USD'                                  , null], 
    ['DT.INP.DECT.03.YR.SA.US'   , 'Ext. Debt Service Pmt, Interest payments on SDR allocations, 3yrs, All instruments, USD'                                        , null], 
    ['DT.INP.DECT.04.06.MO.SA.US', 'Ext. Debt Service Pmt, Interest payments on SDR allocations, 3 to 6 mo., All instruments, USD'                                  , null], 
    ['DT.INP.DECT.04.YR.SA.US'   , 'Ext. Debt Service Pmt, Interest payments on SDR allocations, 4yrs, All instruments, USD'                                        , null], 
    ['DT.INP.DECT.05.10.YR.SA.US', 'Ext. Debt Service Pmt, Interest payments on SDR allocations, 5 to 10 yrs, All instruments, USD'                                 , null], 
    ['DT.INP.DECT.05.YR.SA.US'   , 'Ext. Debt Service Pmt, Interest payments on SDR allocations, 5yrs, All instruments, USD'                                        , null], 
    ['DT.INP.DECT.07.09.MO.SA.US', 'Ext. Debt Service Pmt, Interest payments on SDR allocations, 6 to 9 mo., All instruments, USD'                                  , null], 
    ['DT.INP.DECT.10.12.MO.SA.US', 'Ext. Debt Service Pmt, Interest payments on SDR allocations, 9 to 12 mo., All instruments, USD'                                 , null], 
    ['DT.INP.DECT.10.15.YR.SA.US', 'Ext. Debt Service Pmt, Interest payments on SDR allocations, 10 to 15 yrs, All instruments, USD'                                , null], 
    ['DT.INP.DECT.13.18.MO.SA.US', 'Ext. Debt Service Pmt, Interest payments on SDR allocations, 12 to 18 mo., All instruments, USD'                                , null], 
    ['DT.INP.DECT.19.24.MO.SA.US', 'Ext. Debt Service Pmt, Interest payments on SDR allocations, 18 to 24 mo., All instruments, USD'                                , null], 
    ['DT.INP.DECT.IQ.SA.00.US'   , 'Ext. Debt Service Pmt, Interest payments on SDR allocations, Immediately, All instruments, USD'                                 , null], 
    ['DT.INR.DECT.00.03.MO.SA.US', 'Ext. Debt Service Pmt, Interest receipts on SDR holdings, 0 to 3 mo., All instruments, USD'                                     , null], 
    ['DT.INR.DECT.03.YR.SA.US'   , 'Ext. Debt Service Pmt, Interest receipts on SDR holdings, 3yrs, All instruments, USD'                                           , null], 
    ['DT.INR.DECT.04.06.MO.SA.US', 'Ext. Debt Service Pmt, Interest receipts on SDR holdings, 3 to 6 mo., All instruments, USD'                                     , null], 
    ['DT.INR.DECT.04.YR.SA.US'   , 'Ext. Debt Service Pmt, Interest receipts on SDR holdings, 4yrs, All instruments, USD'                                           , null], 
    ['DT.INR.DECT.05.10.YR.SA.US', 'Ext. Debt Service Pmt, Interest receipts on SDR holdings, 5 to 10 yrs, All instruments, USD'                                    , null], 
    ['DT.INR.DECT.05.YR.SA.US'   , 'Ext. Debt Service Pmt, Interest receipts on SDR holdings, 5yrs, All instruments, USD'                                           , null], 
    ['DT.INR.DECT.07.09.MO.SA.US', 'Ext. Debt Service Pmt, Interest receipts on SDR holdings, 6 to 9 mo., All instruments, USD'                                     , null], 
    ['DT.INR.DECT.10.12.MO.SA.US', 'Ext. Debt Service Pmt, Interest receipts on SDR holdings, 9 to 12 mo., All instruments, USD'                                    , null], 
    ['DT.INR.DECT.10.15.YR.SA.US', 'Ext. Debt Service Pmt, Interest receipts on SDR holdings, 10 to 15 yrs, All instruments, USD'                                   , null], 
    ['DT.INR.DECT.13.18.MO.SA.US', 'Ext. Debt Service Pmt, Interest receipts on SDR holdings, 12 to 18 mo., All instruments, USD'                                   , null], 
    ['DT.INR.DECT.19.24.MO.SA.US', 'Ext. Debt Service Pmt, Interest receipts on SDR holdings, 18 to 24 mo., All instruments, USD'                                   , null], 
    ['DT.INR.DECT.IQ.SA.00.US'   , 'Ext. Debt Service Pmt, Interest receipts on SDR holdings, Immediately, All instruments, USD'                                    , null], 
    ['DT.INT.DECT.CD.00.03.MO.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 0 to 3 mo., All instruments, Interest, USD'          , null], 
    ['DT.INT.DECT.CD.03.YR.US'   , 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 3yrs, All instruments, Interest, USD'                , null], 
    ['DT.INT.DECT.CD.04.06.MO.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 3 to 6 mo., All instruments, Interest, USD'          , null], 
    ['DT.INT.DECT.CD.04.YR.US'   , 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 4yrs, All instruments, Interest, USD'                , null], 
    ['DT.INT.DECT.CD.05.10.YR.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 5 to 10 yrs, All instruments, Interest, USD'         , null], 
    ['DT.INT.DECT.CD.05.YR.US'   , 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 5yrs, All instruments, Interest, USD'                , null], 
    ['DT.INT.DECT.CD.07.09.MO.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 6 to 9 mo., All instruments, Interest, USD'          , null], 
    ['DT.INT.DECT.CD.10.12.MO.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 9 to 12 mo., All instruments, Interest, USD'         , null], 
    ['DT.INT.DECT.CD.10.15.YR.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 10 to 15 yrs, All instruments, Interest, USD'        , null], 
    ['DT.INT.DECT.CD.13.18.MO.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 12 to 18 mo., All instruments, Interest, USD'        , null], 
    ['DT.INT.DECT.CD.15.UP.YR.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, More than15yrs, All instruments, Interest, USD'      , null], 
    ['DT.INT.DECT.CD.19.24.MO.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 18 to 24 mo., All instruments, Interest, USD'        , null], 
    ['DT.INT.DECT.CD.IQ.00.US'   , 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, Immediately, All instruments, Interest, USD'         , null], 
    ['DT.INT.PRVS.CD.00.03.MO.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 0 to 3 mo., All instruments, Interest, USD'                     , null], 
    ['DT.INT.PRVS.CD.03.YR.US'   , 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 3yrs, All instruments, Interest, USD'                           , null], 
    ['DT.INT.PRVS.CD.04.06.MO.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 3 to 6 mo., All instruments, Interest, USD'                     , null], 
    ['DT.INT.PRVS.CD.04.YR.US'   , 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 4yrs, All instruments, Interest, USD'                           , null], 
    ['DT.INT.PRVS.CD.05.10.YR.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 5 to 10 yrs, All instruments, Interest, USD'                    , null], 
    ['DT.INT.PRVS.CD.05.YR.US'   , 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 5yrs, All instruments, Interest, USD'                           , null], 
    ['DT.INT.PRVS.CD.07.09.MO.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 6 to 9 mo., All instruments, Interest, USD'                     , null], 
    ['DT.INT.PRVS.CD.10.12.MO.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 9 to 12 mo., All instruments, Interest, USD'                    , null], 
    ['DT.INT.PRVS.CD.10.15.YR.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 10 to 15 yrs, All instruments, Interest, USD'                   , null], 
    ['DT.INT.PRVS.CD.13.18.MO.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 12 to 18 mo., All instruments, Interest, USD'                   , null], 
    ['DT.INT.PRVS.CD.15.UP.YR.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, More than15yrs, All instruments, Interest, USD'                 , null], 
    ['DT.INT.PRVS.CD.19.24.MO.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 18 to 24 mo., All instruments, Interest, USD'                   , null], 
    ['DT.INT.PRVS.CD.IQ.00.US'   , 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, Immediately, All instruments, Interest, USD'                    , null], 
    ['DT.INT.PUBS.CD.00.03.MO.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 0 to 3 mo., All instruments, Interest, USD'                                     , null], 
    ['DT.INT.PUBS.CD.03.YR.US'   , 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 3yrs, All instruments, Interest, USD'                                           , null], 
    ['DT.INT.PUBS.CD.04.06.MO.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 3 to 6 mo., All instruments, Interest, USD'                                     , null], 
    ['DT.INT.PUBS.CD.04.YR.US'   , 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 4yrs, All instruments, Interest, USD'                                           , null], 
    ['DT.INT.PUBS.CD.05.10.YR.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 5 to 10 yrs, All instruments, Interest, USD'                                    , null], 
    ['DT.INT.PUBS.CD.05.YR.US'   , 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 5yrs, All instruments, Interest, USD'                                           , null], 
    ['DT.INT.PUBS.CD.07.09.MO.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 6 to 9 mo., All instruments, Interest, USD'                                     , null], 
    ['DT.INT.PUBS.CD.10.12.MO.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 9 to 12 mo., All instruments, Interest, USD'                                    , null], 
    ['DT.INT.PUBS.CD.10.15.YR.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 10 to 15 yrs, All instruments, Interest, USD'                                   , null], 
    ['DT.INT.PUBS.CD.13.18.MO.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 12 to 18 mo., All instruments, Interest, USD'                                   , null], 
    ['DT.INT.PUBS.CD.15.UP.YR.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, More than15yrs, All instruments, Interest, USD'                                 , null], 
    ['DT.INT.PUBS.CD.19.24.MO.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 18 to 24 mo., All instruments, Interest, USD'                                   , null], 
    ['DT.INT.PUBS.CD.IQ.00.US'   , 'Ext. Debt Service Pmt, Public Sector Ext. Debt, Immediately, All instruments, Interest, USD'                                    , null], 
    ['DT.TDS.DECT.15.UP.YR.SA.US', 'Ext. Debt Service Pmt, SDR allocations, More than15yrs, All instruments, Principal, USD'                                        , null], 
    ['DT.TDS.DECT.CD.00.03.MO.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 0 to 3 mo., All instruments, Prin. and Int., USD'    , null], 
    ['DT.TDS.DECT.CD.03.YR.US'   , 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 3yrs, All instruments, Prin. and Int., USD'          , null], 
    ['DT.TDS.DECT.CD.04.06.MO.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 3 to 6 mo., All instruments, Prin. and Int., USD'    , null], 
    ['DT.TDS.DECT.CD.04.YR.US'   , 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 4yrs, All instruments, Prin. and Int., USD'          , null], 
    ['DT.TDS.DECT.CD.05.10.YR.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 5 to 10 yrs, All instruments, Prin. and Int., USD'   , null], 
    ['DT.TDS.DECT.CD.05.YR.US'   , 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 5yrs, All instruments, Prin. and Int., USD'          , null], 
    ['DT.TDS.DECT.CD.07.09.MO.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 6 to 9 mo., All instruments, Prin. and Int., USD'    , null], 
    ['DT.TDS.DECT.CD.10.12.MO.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 9 to 12 mo., All instruments, Prin. and Int., USD'   , null], 
    ['DT.TDS.DECT.CD.10.15.YR.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 10 to 15 yrs, All instruments, Prin. and Int., USD'  , null], 
    ['DT.TDS.DECT.CD.13.18.MO.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 12 to 18 mo., All instruments, Prin. and Int., USD'  , null], 
    ['DT.TDS.DECT.CD.15.UP.YR.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, More than15yrs, All instruments, Prin. and Int., USD', null], 
    ['DT.TDS.DECT.CD.19.24.MO.US', 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, 18 to 24 mo., All instruments, Prin. and Int., USD'  , null], 
    ['DT.TDS.DECT.CD.IQ.00.US'   , 'Ext. Debt Service Pmt, Public and Publicly Guar. Private Sector Ext. Debt, Immediately, All instruments, Prin. and Int., USD'   , null], 
    ['DT.TDS.PRVS.CD.00.03.MO.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 0 to 3 mo., All instruments, Prin. and Int., USD'               , null], 
    ['DT.TDS.PRVS.CD.03.YR.US'   , 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 3yrs, All instruments, Prin. and Int., USD'                     , null], 
    ['DT.TDS.PRVS.CD.04.06.MO.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 3 to 6 mo., All instruments, Prin. and Int., USD'               , null], 
    ['DT.TDS.PRVS.CD.04.YR.US'   , 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 4yrs, All instruments, Prin. and Int., USD'                     , null], 
    ['DT.TDS.PRVS.CD.05.10.YR.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 5 to 10 yrs, All instruments, Prin. and Int., USD'              , null], 
    ['DT.TDS.PRVS.CD.05.YR.US'   , 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 5yrs, All instruments, Prin. and Int., USD'                     , null], 
    ['DT.TDS.PRVS.CD.07.09.MO.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 6 to 9 mo., All instruments, Prin. and Int., USD'               , null], 
    ['DT.TDS.PRVS.CD.10.12.MO.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 9 to 12 mo., All instruments, Prin. and Int., USD'              , null], 
    ['DT.TDS.PRVS.CD.10.15.YR.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 10 to 15 yrs, All instruments, Prin. and Int., USD'             , null], 
    ['DT.TDS.PRVS.CD.13.18.MO.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 12 to 18 mo., All instruments, Prin. and Int., USD'             , null], 
    ['DT.TDS.PRVS.CD.15.UP.YR.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, More than15yrs, All instruments, Prin. and Int., USD'           , null], 
    ['DT.TDS.PRVS.CD.19.24.MO.US', 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, 18 to 24 mo., All instruments, Prin. and Int., USD'             , null], 
    ['DT.TDS.PRVS.CD.IQ.00.US'   , 'Ext. Debt Service Pmt, Publicly Guar. Private Sector Ext. Debt, Immediately, All instruments, Prin. and Int., USD'              , null], 
    ['DT.TDS.PUBS.CD.00.03.MO.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 0 to 3 mo., All instruments, Prin. and Int., USD'                               , null], 
    ['DT.TDS.PUBS.CD.03.YR.US'   , 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 3yrs, All instruments, Prin. and Int., USD'                                     , null], 
    ['DT.TDS.PUBS.CD.04.06.MO.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 3 to 6 mo., All instruments, Prin. and Int., USD'                               , null], 
    ['DT.TDS.PUBS.CD.04.YR.US'   , 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 4yrs, All instruments, Prin. and Int., USD'                                     , null], 
    ['DT.TDS.PUBS.CD.05.10.YR.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 5 to 10 yrs, All instruments, Prin. and Int., USD'                              , null], 
    ['DT.TDS.PUBS.CD.05.YR.US'   , 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 5yrs, All instruments, Prin. and Int., USD'                                     , null], 
    ['DT.TDS.PUBS.CD.07.09.MO.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 6 to 9 mo., All instruments, Prin. and Int., USD'                               , null], 
    ['DT.TDS.PUBS.CD.10.12.MO.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 9 to 12 mo., All instruments, Prin. and Int., USD'                              , null], 
    ['DT.TDS.PUBS.CD.10.15.YR.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 10 to 15 yrs, All instruments, Prin. and Int., USD'                             , null], 
    ['DT.TDS.PUBS.CD.13.18.MO.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 12 to 18 mo., All instruments, Prin. and Int., USD'                             , null], 
    ['DT.TDS.PUBS.CD.15.UP.YR.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, More than15yrs, All instruments, Prin. and Int., USD'                           , null], 
    ['DT.TDS.PUBS.CD.19.24.MO.US', 'Ext. Debt Service Pmt, Public Sector Ext. Debt, 18 to 24 mo., All instruments, Prin. and Int., USD'                             , null], 
    ['DT.TDS.PUBS.CD.IQ.00.US'   , 'Ext. Debt Service Pmt, Public Sector Ext. Debt, Immediately, All instruments, Prin. and Int., USD'                              , null], 
  ], 
}