export const StatisticalCapacityIndicators = {
  head: ['id', 'name', 'topics'], 
  rows: [
    ['2.01.01.02.nabase'  , 'National accounts base year'                                                  , null      ], 
    ['2.01.03.01.prcpbase', 'Consumer price index base year'                                               , null      ], 
    ['2.04.01.01.excncpt' , 'Balance of payments manual in use'                                            , null      ], 
    ['3.01.04.01.agcen'   , 'Agricultural census'                                                          , null      ], 
    ['3.02.01.02.fscov'   , 'Government finance accounting'                                                , null      ], 
    ['3.11.01.01.popcen'  , 'Population census'                                                            , null      ], 
    ['3.11.01.03.popreg'  , 'Vital registration system coverage'                                           , null      ], 
    ['5.01.01.01.indust'  , 'Industrial production index'                                                  , null      ], 
    ['5.04.01.01.exdebt'  , 'External debt reporting status'                                               , null      ], 
    ['5.04.01.02.impexp'  , 'Import and export price indexes'                                              , null      ], 
    ['5.12.01.01.unesco'  , 'UNESCO reporting'                                                             , null      ], 
    ['5.13.01.01.hlthsurv', 'Health survey'                                                                , null      ], 
    ['5.13.01.01.who'     , 'National immunization coverage'                                               , null      ], 
    ['5.14.01.01.povsurv' , 'Poverty survey'                                                               , null      ], 
    ['5.21.01.01.sdds'    , 'Special Data Dissemination Standard'                                          , null      ], 
    ['5.51.01.01.poverty' , 'Income poverty'                                                               , null      ], 
    ['5.51.01.02.malnut'  , 'Child malnutrition'                                                           , null      ], 
    ['5.51.01.03.mortal'  , 'Child mortality'                                                              , null      ], 
    ['5.51.01.04.immun'   , 'Immunization'                                                                 , null      ], 
    ['5.51.01.05.hiv'     , 'HIV/AIDS'                                                                     , null      ], 
    ['5.51.01.06.matern'  , 'Maternal health'                                                              , null      ], 
    ['5.51.01.07.gender'  , 'Gender equality'                                                              , null      ], 
    ['5.51.01.08.primcomp', 'Primary completion'                                                           , null      ], 
    ['5.51.01.09.water'   , 'Access to water'                                                              , null      ], 
    ['5.51.01.10.gdp'     , 'Per capita GDP growth'                                                        , null      ], 
    ['IQ.SCI.MTHD'        , 'Methodology assessment of statistical capacity (scale 0 - 100)'               , ['Public']], 
    ['IQ.SCI.OVRL'        , 'Statistical Capacity score (Overall average)'                                 , ['Public']], 
    ['IQ.SCI.PRDC'        , 'Periodicity and timeliness assessment of statistical capacity (scale 0 - 100)', ['Public']], 
    ['IQ.SCI.SRCE'        , 'Source data assessment of statistical capacity (scale 0 - 100)'               , ['Public']], 
  ], 
}