export const AllSources = {
  head: ['id', 'lastupdated', 'name', 'code', 'description', 'url', 'dataavailability', 'metadataavailability', 'concepts'], 
  rows: [
    [ 1, '2019-10-23', 'Doing Business'                                                      , 'DBS', '', '', 'Y', 'Y', 3], 
    [ 6, '2019-12-02', 'International Debt Statistics'                                       , 'IDS', '', '', 'Y', 'Y', 3], 
    [11, '2013-02-22', 'Africa Development Indicators'                                       , 'ADI', '', '', 'Y', 'Y', 3], 
    [12, '2020-04-21', 'Education Statistics'                                                , 'EDS', '', '', 'Y', 'Y', 3], 
    [13, '2017-01-03', 'Enterprise Surveys'                                                  , 'ESY', '', '', 'Y', 'Y', 3], 
    [14, '2020-07-02', 'Gender Statistics'                                                   , 'GDS', '', '', 'Y', 'Y', 3], 
    [15, '2020-07-27', 'Global Economic Monitor'                                             , 'GEM', '', '', 'Y', 'Y', 3], 
    [16, '2020-07-02', 'Health Nutrition and Population Statistics'                          , 'HNP', '', '', 'Y', 'Y', 3], 
    [18, '2020-07-07', 'IDA Results Measurement System'                                      , 'IDA', '', '', 'Y', 'Y', 3], 
    [19, '2018-09-19', 'Millennium Development Goals'                                        , 'MDG', '', '', 'Y', 'Y', 3], 
    [20, '2020-08-06', 'Quarterly Public Sector Debt'                                        , 'PSD', '', '', 'Y', 'Y', 3], 
    [22, '2020-04-30', 'Quarterly External Debt Statistics SDDS'                             , 'QDS', '', '', 'Y', 'Y', 3], 
    [23, '2020-04-30', 'Quarterly External Debt Statistics GDDS'                             , 'QDG', '', '', 'Y', 'Y', 3], 
    [24, '2020-03-18', 'Poverty and Equity'                                                  , 'POV', '', '', 'Y', 'Y', 3], 
    [25, '2020-08-14', 'Jobs'                                                                , 'JOB', '', '', 'Y', 'Y', 3], 
    [27, '2020-06-08', 'Global Economic Prospects'                                           , 'GEP', '', '', 'Y', 'N', 3], 
    [28, '2018-10-15', 'Global Financial Inclusion'                                          , 'FDX', '', '', 'Y', 'Y', 3], 
    [29, '2020-07-24', 'The Atlas of Social Protection: Indicators of Resilience and Equity' , 'GSP', '', '', 'Y', 'Y', 3], 
    [30, '2016-03-31', 'Exporter Dynamics Database – Indicators at Country-Year Level'       , 'ED1', '', '', 'Y', 'N', 3], 
    [31, '2020-07-24', 'Country Policy and Institutional Assessment'                         , 'CPI', '', '', 'Y', 'Y', 3], 
    [32, '2019-10-30', 'Global Financial Development'                                        , 'GFD', '', '', 'Y', 'N', 3], 
    [33, '2019-02-27', 'G20 Financial Inclusion Indicators'                                  , 'G2F', '', '', 'Y', 'Y', 3], 
    [34, '2013-04-12', 'Global Partnership for Education'                                    , 'GPE', '', '', 'Y', 'Y', 3], 
    [36, '2020-08-19', 'Statistical Capacity Indicators'                                     , 'BBS', '', '', 'Y', '' , 3], 
    [37, '2016-04-06', 'LAC Equity Lab'                                                      , 'LEL', '', '', 'Y', 'Y', 3], 
    [39, '2020-05-20', 'Health Nutrition and Population Statistics by Wealth Quintile'       , 'HNQ', '', '', 'Y', 'Y', 3], 
    [40, '2020-07-01', 'Population estimates and projections'                                , 'HPP', '', '', 'Y', 'Y', 3], 
    [41, '2015-05-22', 'Country Partnership Strategy for India (FY2013 - 17)'                , 'CPS', '', '', 'Y', 'N', 3], 
    [44, '2015-06-11', 'Readiness for Investment in Sustainable Energy'                      , 'RIS', '', '', 'Y', '' , 3], 
    [45, '2019-05-07', 'Indonesia Database for Policy and Economic Research'                 , 'IDD', '', '', 'Y', '' , 3], 
    [54, '2020-06-04', 'Joint External Debt Hub'                                             , 'JED', '', '', 'Y', '' , 3], 
    [60, '2018-04-19', 'Economic Fitness'                                                    , 'EFT', '', '', 'Y', 'Y', 3], 
    [61, '2019-04-25', 'PPPs Regulatory Quality'                                             , 'PRQ', '', '', 'Y', 'Y', 3], 
    [63, '2018-10-10', 'Human Capital Index'                                                 , 'HCI', '', '', 'Y', 'Y', 3], 
    [65, '2019-11-06', 'Health Equity and Financial Protection Indicators'                   , 'HPI', '', '', 'Y', 'Y', 3], 
    [66, '2019-10-29', 'Logistics Performance Index'                                         , 'LPI', '', '', 'Y', 'Y', 3], 
    [69, '2019-06-27', 'Global Financial Inclusion and Consumer Protection Survey'           , 'RFA', '', '', 'Y', 'Y', 3], 
    [70, '2019-04-26', 'Economic Fitness 2'                                                  , 'EF2', '', '', 'Y', 'Y', 3], 
    [73, '2019-06-27', 'Global Financial Inclusion and Consumer Protection Survey (Internal)', 'RFI', '', '', 'Y', 'Y', 3], 
    [75, '2020-07-06', 'Environment, Social and Governance (ESG) Data'                       , 'ESG', '', '', 'Y', 'Y', 3], 
    [76, '2018-01-22', 'Remittance Prices Worldwide (Sending Countries)'                     , 'RWS', '', '', 'Y', 'N', 3], 
    [77, '2018-01-22', 'Remittance Prices Worldwide (Receiving Countries)'                   , 'RWR', '', '', 'Y', 'N', 3], 
    [80, '2020-07-25', 'Gender Disaggregated Labor Database (GDLD)'                          , 'GDL', '', '', 'Y', 'N', 4], 
  ], 
}