export const countryList = [
  { name:'Aruba'                        , value:'ABW' }, 
  { name:'Afghanistan'                  , value:'AFG' }, 
  { name:'Angola'                       , value:'AGO' }, 
  { name:'Albania'                      , value:'ALB' }, 
  { name:'Andorra'                      , value:'AND' }, 
  { name:'United Arab Emirates'         , value:'ARE' }, 
  { name:'Argentina'                    , value:'ARG' }, 
  { name:'Armenia'                      , value:'ARM' }, 
  { name:'American Samoa'               , value:'ASM' }, 
  { name:'Antigua and Barbuda'          , value:'ATG' }, 
  { name:'Australia'                    , value:'AUS' }, 
  { name:'Austria'                      , value:'AUT' }, 
  { name:'Azerbaijan'                   , value:'AZE' }, 
  { name:'Burundi'                      , value:'BDI' }, 
  { name:'Belgium'                      , value:'BEL' }, 
  { name:'Benin'                        , value:'BEN' }, 
  { name:'Burkina Faso'                 , value:'BFA' }, 
  { name:'Bangladesh'                   , value:'BGD' }, 
  { name:'Bulgaria'                     , value:'BGR' }, 
  { name:'Bahrain'                      , value:'BHR' }, 
  { name:'Bahamas The'                  , value:'BHS' }, 
  { name:'Bosnia and Herzegovina'       , value:'BIH' }, 
  { name:'Belarus'                      , value:'BLR' }, 
  { name:'Belize'                       , value:'BLZ' }, 
  { name:'Bermuda'                      , value:'BMU' }, 
  { name:'Bolivia'                      , value:'BOL' }, 
  { name:'Brazil'                       , value:'BRA' }, 
  { name:'Barbados'                     , value:'BRB' }, 
  { name:'Brunei Darussalam'            , value:'BRN' }, 
  { name:'Bhutan'                       , value:'BTN' }, 
  { name:'Botswana'                     , value:'BWA' }, 
  { name:'Central African Rep'          , value:'CAF' }, 
  { name:'Canada'                       , value:'CAN' }, 
  { name:'Switzerland'                  , value:'CHE' }, 
  { name:'Channel Islands'              , value:'CHI' }, 
  { name:'Chile'                        , value:'CHL' }, 
  { name:'China'                        , value:'CHN' }, 
  { name:'Cote d Ivoire'                , value:'CIV' }, 
  { name:'Cameroon'                     , value:'CMR' }, 
  { name:'Congo DR'                     , value:'COD' }, 
  { name:'Congo Rep'                    , value:'COG' }, 
  { name:'Colombia'                     , value:'COL' }, 
  { name:'Comoros'                      , value:'COM' }, 
  { name:'Cabo Verde'                   , value:'CPV' }, 
  { name:'Costa Rica'                   , value:'CRI' }, 
  { name:'Cuba'                         , value:'CUB' }, 
  { name:'Curacao'                      , value:'CUW' }, 
  { name:'Cayman Islands'               , value:'CYM' }, 
  { name:'Cyprus'                       , value:'CYP' }, 
  { name:'Czech Rep'                    , value:'CZE' }, 
  { name:'Germany'                      , value:'DEU' }, 
  { name:'Djibouti'                     , value:'DJI' }, 
  { name:'Dominica'                     , value:'DMA' }, 
  { name:'Denmark'                      , value:'DNK' }, 
  { name:'Dominican Rep'                , value:'DOM' }, 
  { name:'Algeria'                      , value:'DZA' }, 
  { name:'Ecuador'                      , value:'ECU' }, 
  { name:'Egypt Arab Rep'               , value:'EGY' }, 
  { name:'Eritrea'                      , value:'ERI' }, 
  { name:'Spain'                        , value:'ESP' }, 
  { name:'Estonia'                      , value:'EST' }, 
  { name:'Ethiopia'                     , value:'ETH' }, 
  { name:'Finland'                      , value:'FIN' }, 
  { name:'Fiji'                         , value:'FJI' }, 
  { name:'France'                       , value:'FRA' }, 
  { name:'Faroe Islands'                , value:'FRO' }, 
  { name:'Micronesia Fed Sts'           , value:'FSM' }, 
  { name:'Gabon'                        , value:'GAB' }, 
  { name:'United Kingdom'               , value:'GBR' }, 
  { name:'Georgia'                      , value:'GEO' }, 
  { name:'Ghana'                        , value:'GHA' }, 
  { name:'Gibraltar'                    , value:'GIB' }, 
  { name:'Guinea'                       , value:'GIN' }, 
  { name:'Gambia The'                   , value:'GMB' }, 
  { name:'Guinea Bissau'                , value:'GNB' }, 
  { name:'Equatorial Guinea'            , value:'GNQ' }, 
  { name:'Greece'                       , value:'GRC' }, 
  { name:'Grenada'                      , value:'GRD' }, 
  { name:'Greenland'                    , value:'GRL' }, 
  { name:'Guatemala'                    , value:'GTM' }, 
  { name:'Guam'                         , value:'GUM' }, 
  { name:'Guyana'                       , value:'GUY' }, 
  { name:'Hong Kong SAR China'          , value:'HKG' }, 
  { name:'Honduras'                     , value:'HND' }, 
  { name:'Croatia'                      , value:'HRV' }, 
  { name:'Haiti'                        , value:'HTI' }, 
  { name:'Hungary'                      , value:'HUN' }, 
  { name:'Indonesia'                    , value:'IDN' }, 
  { name:'Isle of Man'                  , value:'IMN' }, 
  { name:'India'                        , value:'IND' }, 
  { name:'Ireland'                      , value:'IRL' }, 
  { name:'Iran'                         , value:'IRN' }, 
  { name:'Iraq'                         , value:'IRQ' }, 
  { name:'Iceland'                      , value:'ISL' }, 
  { name:'Israel'                       , value:'ISR' }, 
  { name:'Italy'                        , value:'ITA' }, 
  { name:'Jamaica'                      , value:'JAM' }, 
  { name:'Jordan'                       , value:'JOR' }, 
  { name:'Japan'                        , value:'JPN' }, 
  { name:'Kazakhstan'                   , value:'KAZ' }, 
  { name:'Kenya'                        , value:'KEN' }, 
  { name:'Kyrgyz Rep'                   , value:'KGZ' }, 
  { name:'Cambodia'                     , value:'KHM' }, 
  { name:'Kiribati'                     , value:'KIR' }, 
  { name:'St Kitts and Nevis'           , value:'KNA' }, 
  { name:'Korea Rep'                    , value:'KOR' }, 
  { name:'Kuwait'                       , value:'KWT' }, 
  { name:'Lao PDR'                      , value:'LAO' }, 
  { name:'Lebanon'                      , value:'LBN' }, 
  { name:'Liberia'                      , value:'LBR' }, 
  { name:'Libya'                        , value:'LBY' }, 
  { name:'St Lucia'                     , value:'LCA' }, 
  { name:'Liechtenstein'                , value:'LIE' }, 
  { name:'Sri Lanka'                    , value:'LKA' }, 
  { name:'Lesotho'                      , value:'LSO' }, 
  { name:'Lithuania'                    , value:'LTU' }, 
  { name:'Luxembourg'                   , value:'LUX' }, 
  { name:'Latvia'                       , value:'LVA' }, 
  { name:'Macao SAR China'              , value:'MAC' }, 
  { name:'St Martin French part'        , value:'MAF' }, 
  { name:'Morocco'                      , value:'MAR' }, 
  { name:'Monaco'                       , value:'MCO' }, 
  { name:'Moldova'                      , value:'MDA' }, 
  { name:'Madagascar'                   , value:'MDG' }, 
  { name:'Maldives'                     , value:'MDV' }, 
  { name:'Mexico'                       , value:'MEX' }, 
  { name:'Marshall Islands'             , value:'MHL' }, 
  { name:'North Macedonia'              , value:'MKD' }, 
  { name:'Mali'                         , value:'MLI' }, 
  { name:'Malta'                        , value:'MLT' }, 
  { name:'Myanmar'                      , value:'MMR' }, 
  { name:'Montenegro'                   , value:'MNE' }, 
  { name:'Mongolia'                     , value:'MNG' }, 
  { name:'Northern Mariana Islands'     , value:'MNP' }, 
  { name:'Mozambique'                   , value:'MOZ' }, 
  { name:'Mauritania'                   , value:'MRT' }, 
  { name:'Mauritius'                    , value:'MUS' }, 
  { name:'Malawi'                       , value:'MWI' }, 
  { name:'Malaysia'                     , value:'MYS' }, 
  { name:'Namibia'                      , value:'NAM' }, 
  { name:'New Caledonia'                , value:'NCL' }, 
  { name:'Niger'                        , value:'NER' }, 
  { name:'Nigeria'                      , value:'NGA' }, 
  { name:'Nicaragua'                    , value:'NIC' }, 
  { name:'Netherlands'                  , value:'NLD' }, 
  { name:'Norway'                       , value:'NOR' }, 
  { name:'Nepal'                        , value:'NPL' }, 
  { name:'Nauru'                        , value:'NRU' }, 
  { name:'New Zealand'                  , value:'NZL' }, 
  { name:'Oman'                         , value:'OMN' }, 
  { name:'Pakistan'                     , value:'PAK' }, 
  { name:'Panama'                       , value:'PAN' }, 
  { name:'Peru'                         , value:'PER' }, 
  { name:'Philippines'                  , value:'PHL' }, 
  { name:'Palau'                        , value:'PLW' }, 
  { name:'Papua New Guinea'             , value:'PNG' }, 
  { name:'Poland'                       , value:'POL' }, 
  { name:'Puerto Rico'                  , value:'PRI' }, 
  { name:'Korea DPR'                    , value:'PRK' }, 
  { name:'Portugal'                     , value:'PRT' }, 
  { name:'Paraguay'                     , value:'PRY' }, 
  { name:'West Bank and Gaza'           , value:'PSE' }, 
  { name:'French Polynesia'             , value:'PYF' }, 
  { name:'Qatar'                        , value:'QAT' }, 
  { name:'Romania'                      , value:'ROU' }, 
  { name:'Russian Federation'           , value:'RUS' }, 
  { name:'Rwanda'                       , value:'RWA' }, 
  { name:'Saudi Arabia'                 , value:'SAU' }, 
  { name:'Sudan'                        , value:'SDN' }, 
  { name:'Senegal'                      , value:'SEN' }, 
  { name:'Singapore'                    , value:'SGP' }, 
  { name:'Solomon Islands'              , value:'SLB' }, 
  { name:'Sierra Leone'                 , value:'SLE' }, 
  { name:'El Salvador'                  , value:'SLV' }, 
  { name:'San Marino'                   , value:'SMR' }, 
  { name:'Somalia'                      , value:'SOM' }, 
  { name:'Serbia'                       , value:'SRB' }, 
  { name:'South Sudan'                  , value:'SSD' }, 
  { name:'Sao Tome and Principe'        , value:'STP' }, 
  { name:'Suriname'                     , value:'SUR' }, 
  { name:'Slovak Rep'                   , value:'SVK' }, 
  { name:'Slovenia'                     , value:'SVN' }, 
  { name:'Sweden'                       , value:'SWE' }, 
  { name:'Eswatini'                     , value:'SWZ' }, 
  { name:'Sint Maarten Dutch part'      , value:'SXM' }, 
  { name:'Seychelles'                   , value:'SYC' }, 
  { name:'Syrian Arab Rep'              , value:'SYR' }, 
  { name:'Turks and Caicos Islands'     , value:'TCA' }, 
  { name:'Chad'                         , value:'TCD' }, 
  { name:'Togo'                         , value:'TGO' }, 
  { name:'Thailand'                     , value:'THA' }, 
  { name:'Tajikistan'                   , value:'TJK' }, 
  { name:'Turkmenistan'                 , value:'TKM' }, 
  { name:'Timor Leste'                  , value:'TLS' }, 
  { name:'Tonga'                        , value:'TON' }, 
  { name:'Trinidad and Tobago'          , value:'TTO' }, 
  { name:'Tunisia'                      , value:'TUN' }, 
  { name:'Turkey'                       , value:'TUR' }, 
  { name:'Tuvalu'                       , value:'TUV' }, 
  { name:'Taiwan China'                 , value:'TWN' }, 
  { name:'Tanzania'                     , value:'TZA' }, 
  { name:'Uganda'                       , value:'UGA' }, 
  { name:'Ukraine'                      , value:'UKR' }, 
  { name:'Uruguay'                      , value:'URY' }, 
  { name:'United States'                , value:'USA' }, 
  { name:'Uzbekistan'                   , value:'UZB' }, 
  { name:'St Vincent and the Grenadines', value:'VCT' }, 
  { name:'Venezuela RB'                 , value:'VEN' }, 
  { name:'British Virgin Islands'       , value:'VGB' }, 
  { name:'Virgin Islands U S'           , value:'VIR' }, 
  { name:'Vietnam'                      , value:'VNM' }, 
  { name:'Vanuatu'                      , value:'VUT' }, 
  { name:'Samoa'                        , value:'WSM' }, 
  { name:'Kosovo'                       , value:'XKX' }, 
  { name:'Yemen Rep'                    , value:'YEM' }, 
  { name:'South Africa'                 , value:'ZAF' }, 
  { name:'Zambia'                       , value:'ZMB' }, 
  { name:'Zimbabwe'                     , value:'ZWE' }, 
]