export const countryList = [
  { name:'Afghanistan | AFG'                                         , value:'AFG' }, 
  { name:'Åland Islands | ALA'                                       , value:'ALA' }, 
  { name:'Albania | ALB'                                             , value:'ALB' }, 
  { name:'Algeria | DZA'                                             , value:'DZA' }, 
  { name:'American Samoa | ASM'                                      , value:'ASM' }, 
  { name:'Andorra | AND'                                             , value:'AND' }, 
  { name:'Angola | AGO'                                              , value:'AGO' }, 
  { name:'Anguilla | AIA'                                            , value:'AIA' }, 
  { name:'Antarctica | ATA'                                          , value:'ATA' }, 
  { name:'Antigua and Barbuda | ATG'                                 , value:'ATG' }, 
  { name:'Argentina | ARG'                                           , value:'ARG' }, 
  { name:'Armenia | ARM'                                             , value:'ARM' }, 
  { name:'Aruba | ABW'                                               , value:'ABW' }, 
  { name:'Australia | AUS'                                           , value:'AUS' }, 
  { name:'Austria | AUT'                                             , value:'AUT' }, 
  { name:'Azerbaijan | AZE'                                          , value:'AZE' }, 
  { name:'Bahamas | BHS'                                             , value:'BHS' }, 
  { name:'Bahrain | BHR'                                             , value:'BHR' }, 
  { name:'Bangladesh | BGD'                                          , value:'BGD' }, 
  { name:'Barbados | BRB'                                            , value:'BRB' }, 
  { name:'Belarus | BLR'                                             , value:'BLR' }, 
  { name:'Belgium | BEL'                                             , value:'BEL' }, 
  { name:'Belize | BLZ'                                              , value:'BLZ' }, 
  { name:'Benin | BEN'                                               , value:'BEN' }, 
  { name:'Bermuda | BMU'                                             , value:'BMU' }, 
  { name:'Bhutan | BTN'                                              , value:'BTN' }, 
  { name:'Bolivia Plurinational State of | BOL'                      , value:'BOL' }, 
  { name:'Bonaire Sint Eustatius and Saba | BES'                     , value:'BES' }, 
  { name:'Bosnia and Herzegovina | BIH'                              , value:'BIH' }, 
  { name:'Botswana | BWA'                                            , value:'BWA' }, 
  { name:'Bouvet Island | BVT'                                       , value:'BVT' }, 
  { name:'Brazil | BRA'                                              , value:'BRA' }, 
  { name:'British Indian Ocean Territory | IOT'                      , value:'IOT' }, 
  { name:'Brunei Darussalam | BRN'                                   , value:'BRN' }, 
  { name:'Bulgaria | BGR'                                            , value:'BGR' }, 
  { name:'Burkina Faso | BFA'                                        , value:'BFA' }, 
  { name:'Burundi | BDI'                                             , value:'BDI' }, 
  { name:'Cabo Verde | CPV'                                          , value:'CPV' }, 
  { name:'Cambodia | KHM'                                            , value:'KHM' }, 
  { name:'Cameroon | CMR'                                            , value:'CMR' }, 
  { name:'Canada | CAN'                                              , value:'CAN' }, 
  { name:'Cayman Islands | CYM'                                      , value:'CYM' }, 
  { name:'Central African Republic | CAF'                            , value:'CAF' }, 
  { name:'Chad | TCD'                                                , value:'TCD' }, 
  { name:'Chile | CHL'                                               , value:'CHL' }, 
  { name:'China | CHN'                                               , value:'CHN' }, 
  { name:'Christmas Island | CXR'                                    , value:'CXR' }, 
  { name:'Cocos Keeling Islands | CCK'                               , value:'CCK' }, 
  { name:'Colombia | COL'                                            , value:'COL' }, 
  { name:'Comoros | COM'                                             , value:'COM' }, 
  { name:'Congo | COG'                                               , value:'COG' }, 
  { name:'Congo Democratic Republic of the | COD'                    , value:'COD' }, 
  { name:'Cook Islands | COK'                                        , value:'COK' }, 
  { name:'Costa Rica | CRI'                                          , value:'CRI' }, 
  { name:'Côte dIvoire | CIV'                                        , value:'CIV' }, 
  { name:'Croatia | HRV'                                             , value:'HRV' }, 
  { name:'Cuba | CUB'                                                , value:'CUB' }, 
  { name:'Curaçao | CUW'                                             , value:'CUW' }, 
  { name:'Cyprus | CYP'                                              , value:'CYP' }, 
  { name:'Czechia | CZE'                                             , value:'CZE' }, 
  { name:'Denmark | DNK'                                             , value:'DNK' }, 
  { name:'Djibouti | DJI'                                            , value:'DJI' }, 
  { name:'Dominica | DMA'                                            , value:'DMA' }, 
  { name:'Dominican Republic | DOM'                                  , value:'DOM' }, 
  { name:'Ecuador | ECU'                                             , value:'ECU' }, 
  { name:'Egypt | EGY'                                               , value:'EGY' }, 
  { name:'El Salvador | SLV'                                         , value:'SLV' }, 
  { name:'Equatorial Guinea | GNQ'                                   , value:'GNQ' }, 
  { name:'Eritrea | ERI'                                             , value:'ERI' }, 
  { name:'Estonia | EST'                                             , value:'EST' }, 
  { name:'Eswatini | SWZ'                                            , value:'SWZ' }, 
  { name:'Ethiopia | ETH'                                            , value:'ETH' }, 
  { name:'Falkland Islands Malvinas | FLK'                           , value:'FLK' }, 
  { name:'Faroe Islands | FRO'                                       , value:'FRO' }, 
  { name:'Fiji | FJI'                                                , value:'FJI' }, 
  { name:'Finland | FIN'                                             , value:'FIN' }, 
  { name:'France | FRA'                                              , value:'FRA' }, 
  { name:'French Guiana | GUF'                                       , value:'GUF' }, 
  { name:'French Polynesia | PYF'                                    , value:'PYF' }, 
  { name:'French Southern Territories | ATF'                         , value:'ATF' }, 
  { name:'Gabon | GAB'                                               , value:'GAB' }, 
  { name:'Gambia | GMB'                                              , value:'GMB' }, 
  { name:'Georgia | GEO'                                             , value:'GEO' }, 
  { name:'Germany | DEU'                                             , value:'DEU' }, 
  { name:'Ghana | GHA'                                               , value:'GHA' }, 
  { name:'Gibraltar | GIB'                                           , value:'GIB' }, 
  { name:'Greece | GRC'                                              , value:'GRC' }, 
  { name:'Greenland | GRL'                                           , value:'GRL' }, 
  { name:'Grenada | GRD'                                             , value:'GRD' }, 
  { name:'Guadeloupe | GLP'                                          , value:'GLP' }, 
  { name:'Guam | GUM'                                                , value:'GUM' }, 
  { name:'Guatemala | GTM'                                           , value:'GTM' }, 
  { name:'Guernsey | GGY'                                            , value:'GGY' }, 
  { name:'Guinea | GIN'                                              , value:'GIN' }, 
  { name:'Guinea Bissau | GNB'                                       , value:'GNB' }, 
  { name:'Guyana | GUY'                                              , value:'GUY' }, 
  { name:'Haiti | HTI'                                               , value:'HTI' }, 
  { name:'Heard Island and McDonald Islands | HMD'                   , value:'HMD' }, 
  { name:'Holy See | VAT'                                            , value:'VAT' }, 
  { name:'Honduras | HND'                                            , value:'HND' }, 
  { name:'Hong Kong | HKG'                                           , value:'HKG' }, 
  { name:'Hungary | HUN'                                             , value:'HUN' }, 
  { name:'Iceland | ISL'                                             , value:'ISL' }, 
  { name:'India | IND'                                               , value:'IND' }, 
  { name:'Indonesia | IDN'                                           , value:'IDN' }, 
  { name:'Iran Islamic Republic of | IRN'                            , value:'IRN' }, 
  { name:'Iraq | IRQ'                                                , value:'IRQ' }, 
  { name:'Ireland | IRL'                                             , value:'IRL' }, 
  { name:'Isle of Man | IMN'                                         , value:'IMN' }, 
  { name:'Israel | ISR'                                              , value:'ISR' }, 
  { name:'Italy | ITA'                                               , value:'ITA' }, 
  { name:'Jamaica | JAM'                                             , value:'JAM' }, 
  { name:'Japan | JPN'                                               , value:'JPN' }, 
  { name:'Jersey | JEY'                                              , value:'JEY' }, 
  { name:'Jordan | JOR'                                              , value:'JOR' }, 
  { name:'Kazakhstan | KAZ'                                          , value:'KAZ' }, 
  { name:'Kenya | KEN'                                               , value:'KEN' }, 
  { name:'Kiribati | KIR'                                            , value:'KIR' }, 
  { name:'Korea Democratic Peoples Republic of | PRK'                , value:'PRK' }, 
  { name:'Korea Republic of | KOR'                                   , value:'KOR' }, 
  { name:'Kuwait | KWT'                                              , value:'KWT' }, 
  { name:'Kyrgyzstan | KGZ'                                          , value:'KGZ' }, 
  { name:'Lao Peoples Democratic Republic | LAO'                     , value:'LAO' }, 
  { name:'Latvia | LVA'                                              , value:'LVA' }, 
  { name:'Lebanon | LBN'                                             , value:'LBN' }, 
  { name:'Lesotho | LSO'                                             , value:'LSO' }, 
  { name:'Liberia | LBR'                                             , value:'LBR' }, 
  { name:'Libya | LBY'                                               , value:'LBY' }, 
  { name:'Liechtenstein | LIE'                                       , value:'LIE' }, 
  { name:'Lithuania | LTU'                                           , value:'LTU' }, 
  { name:'Luxembourg | LUX'                                          , value:'LUX' }, 
  { name:'Macao | MAC'                                               , value:'MAC' }, 
  { name:'Madagascar | MDG'                                          , value:'MDG' }, 
  { name:'Malawi | MWI'                                              , value:'MWI' }, 
  { name:'Malaysia | MYS'                                            , value:'MYS' }, 
  { name:'Maldives | MDV'                                            , value:'MDV' }, 
  { name:'Mali | MLI'                                                , value:'MLI' }, 
  { name:'Malta | MLT'                                               , value:'MLT' }, 
  { name:'Marshall Islands | MHL'                                    , value:'MHL' }, 
  { name:'Martinique | MTQ'                                          , value:'MTQ' }, 
  { name:'Mauritania | MRT'                                          , value:'MRT' }, 
  { name:'Mauritius | MUS'                                           , value:'MUS' }, 
  { name:'Mayotte | MYT'                                             , value:'MYT' }, 
  { name:'Mexico | MEX'                                              , value:'MEX' }, 
  { name:'Micronesia Federated States of | FSM'                      , value:'FSM' }, 
  { name:'Moldova Republic of | MDA'                                 , value:'MDA' }, 
  { name:'Monaco | MCO'                                              , value:'MCO' }, 
  { name:'Mongolia | MNG'                                            , value:'MNG' }, 
  { name:'Montenegro | MNE'                                          , value:'MNE' }, 
  { name:'Montserrat | MSR'                                          , value:'MSR' }, 
  { name:'Morocco | MAR'                                             , value:'MAR' }, 
  { name:'Mozambique | MOZ'                                          , value:'MOZ' }, 
  { name:'Myanmar | MMR'                                             , value:'MMR' }, 
  { name:'Namibia | NAM'                                             , value:'NAM' }, 
  { name:'Nauru | NRU'                                               , value:'NRU' }, 
  { name:'Nepal | NPL'                                               , value:'NPL' }, 
  { name:'Netherlands | NLD'                                         , value:'NLD' }, 
  { name:'New Caledonia | NCL'                                       , value:'NCL' }, 
  { name:'New Zealand | NZL'                                         , value:'NZL' }, 
  { name:'Nicaragua | NIC'                                           , value:'NIC' }, 
  { name:'Niger | NER'                                               , value:'NER' }, 
  { name:'Nigeria | NGA'                                             , value:'NGA' }, 
  { name:'Niue | NIU'                                                , value:'NIU' }, 
  { name:'Norfolk Island | NFK'                                      , value:'NFK' }, 
  { name:'North Macedonia | MKD'                                     , value:'MKD' }, 
  { name:'Northern Mariana Islands | MNP'                            , value:'MNP' }, 
  { name:'Norway | NOR'                                              , value:'NOR' }, 
  { name:'Oman | OMN'                                                , value:'OMN' }, 
  { name:'Pakistan | PAK'                                            , value:'PAK' }, 
  { name:'Palau | PLW'                                               , value:'PLW' }, 
  { name:'Palestine State of | PSE'                                  , value:'PSE' }, 
  { name:'Panama | PAN'                                              , value:'PAN' }, 
  { name:'Papua New Guinea | PNG'                                    , value:'PNG' }, 
  { name:'Paraguay | PRY'                                            , value:'PRY' }, 
  { name:'Peru | PER'                                                , value:'PER' }, 
  { name:'Philippines | PHL'                                         , value:'PHL' }, 
  { name:'Pitcairn | PCN'                                            , value:'PCN' }, 
  { name:'Poland | POL'                                              , value:'POL' }, 
  { name:'Portugal | PRT'                                            , value:'PRT' }, 
  { name:'Puerto Rico | PRI'                                         , value:'PRI' }, 
  { name:'Qatar | QAT'                                               , value:'QAT' }, 
  { name:'Réunion | REU'                                             , value:'REU' }, 
  { name:'Romania | ROU'                                             , value:'ROU' }, 
  { name:'Russian Federation | RUS'                                  , value:'RUS' }, 
  { name:'Rwanda | RWA'                                              , value:'RWA' }, 
  { name:'Saint Barthélemy | BLM'                                    , value:'BLM' }, 
  { name:'Saint Helena Ascension and Tristan da Cunha | SHN'         , value:'SHN' }, 
  { name:'Saint Kitts and Nevis | KNA'                               , value:'KNA' }, 
  { name:'Saint Lucia | LCA'                                         , value:'LCA' }, 
  { name:'Saint Martin French part | MAF'                            , value:'MAF' }, 
  { name:'Saint Pierre and Miquelon | SPM'                           , value:'SPM' }, 
  { name:'Saint Vincent and the Grenadines | VCT'                    , value:'VCT' }, 
  { name:'Samoa | WSM'                                               , value:'WSM' }, 
  { name:'San Marino | SMR'                                          , value:'SMR' }, 
  { name:'Sao Tome and Principe | STP'                               , value:'STP' }, 
  { name:'Saudi Arabia | SAU'                                        , value:'SAU' }, 
  { name:'Senegal | SEN'                                             , value:'SEN' }, 
  { name:'Serbia | SRB'                                              , value:'SRB' }, 
  { name:'Seychelles | SYC'                                          , value:'SYC' }, 
  { name:'Sierra Leone | SLE'                                        , value:'SLE' }, 
  { name:'Singapore | SGP'                                           , value:'SGP' }, 
  { name:'Sint Maarten Dutch part | SXM'                             , value:'SXM' }, 
  { name:'Slovakia | SVK'                                            , value:'SVK' }, 
  { name:'Slovenia | SVN'                                            , value:'SVN' }, 
  { name:'Solomon Islands | SLB'                                     , value:'SLB' }, 
  { name:'Somalia | SOM'                                             , value:'SOM' }, 
  { name:'South Africa | ZAF'                                        , value:'ZAF' }, 
  { name:'South Georgia and the South Sandwich Islands | SGS'        , value:'SGS' }, 
  { name:'South Sudan | SSD'                                         , value:'SSD' }, 
  { name:'Spain | ESP'                                               , value:'ESP' }, 
  { name:'Sri Lanka | LKA'                                           , value:'LKA' }, 
  { name:'Sudan | SDN'                                               , value:'SDN' }, 
  { name:'Suriname | SUR'                                            , value:'SUR' }, 
  { name:'Svalbard and Jan Mayen | SJM'                              , value:'SJM' }, 
  { name:'Sweden | SWE'                                              , value:'SWE' }, 
  { name:'Switzerland | CHE'                                         , value:'CHE' }, 
  { name:'Syrian Arab Republic | SYR'                                , value:'SYR' }, 
  { name:'Taiwan Province of China | TWN'                            , value:'TWN' }, 
  { name:'Tajikistan | TJK'                                          , value:'TJK' }, 
  { name:'Tanzania United Republic of | TZA'                         , value:'TZA' }, 
  { name:'Thailand | THA'                                            , value:'THA' }, 
  { name:'Timor Leste | TLS'                                         , value:'TLS' }, 
  { name:'Togo | TGO'                                                , value:'TGO' }, 
  { name:'Tokelau | TKL'                                             , value:'TKL' }, 
  { name:'Tonga | TON'                                               , value:'TON' }, 
  { name:'Trinidad and Tobago | TTO'                                 , value:'TTO' }, 
  { name:'Tunisia | TUN'                                             , value:'TUN' }, 
  { name:'Turkey | TUR'                                              , value:'TUR' }, 
  { name:'Turkmenistan | TKM'                                        , value:'TKM' }, 
  { name:'Turks and Caicos Islands | TCA'                            , value:'TCA' }, 
  { name:'Tuvalu | TUV'                                              , value:'TUV' }, 
  { name:'Uganda | UGA'                                              , value:'UGA' }, 
  { name:'Ukraine | UKR'                                             , value:'UKR' }, 
  { name:'United Arab Emirates | ARE'                                , value:'ARE' }, 
  { name:'United Kingdom of Great Britain and Northern Ireland | GBR', value:'GBR' }, 
  { name:'United States of America | USA'                            , value:'USA' }, 
  { name:'United States Minor Outlying Islands | UMI'                , value:'UMI' }, 
  { name:'Uruguay | URY'                                             , value:'URY' }, 
  { name:'Uzbekistan | UZB'                                          , value:'UZB' }, 
  { name:'Vanuatu | VUT'                                             , value:'VUT' }, 
  { name:'Venezuela Bolivarian Republic of | VEN'                    , value:'VEN' }, 
  { name:'Viet Nam | VNM'                                            , value:'VNM' }, 
  { name:'Virgin Islands British | VGB'                              , value:'VGB' }, 
  { name:'Virgin Islands US | VIR'                                   , value:'VIR' }, 
  { name:'Wallis and Futuna | WLF'                                   , value:'WLF' }, 
  { name:'Western Sahara | ESH'                                      , value:'ESH' }, 
  { name:'Yemen | YEM'                                               , value:'YEM' }, 
  { name:'Zambia | ZMB'                                              , value:'ZMB' }, 
  { name:'Zimbabwe | ZWE'                                            , value:'ZWE' }, 
]