export const countryList = [
  { name:'Aruba | ABW'                        , value:'ABW' }, 
  { name:'Afghanistan | AFG'                  , value:'AFG' }, 
  { name:'Angola | AGO'                       , value:'AGO' }, 
  { name:'Albania | ALB'                      , value:'ALB' }, 
  { name:'Andorra | AND'                      , value:'AND' }, 
  { name:'United Arab Emirates | ARE'         , value:'ARE' }, 
  { name:'Argentina | ARG'                    , value:'ARG' }, 
  { name:'Armenia | ARM'                      , value:'ARM' }, 
  { name:'American Samoa | ASM'               , value:'ASM' }, 
  { name:'Antigua and Barbuda | ATG'          , value:'ATG' }, 
  { name:'Australia | AUS'                    , value:'AUS' }, 
  { name:'Austria | AUT'                      , value:'AUT' }, 
  { name:'Azerbaijan | AZE'                   , value:'AZE' }, 
  { name:'Burundi | BDI'                      , value:'BDI' }, 
  { name:'Belgium | BEL'                      , value:'BEL' }, 
  { name:'Benin | BEN'                        , value:'BEN' }, 
  { name:'Burkina Faso | BFA'                 , value:'BFA' }, 
  { name:'Bangladesh | BGD'                   , value:'BGD' }, 
  { name:'Bulgaria | BGR'                     , value:'BGR' }, 
  { name:'Bahrain | BHR'                      , value:'BHR' }, 
  { name:'Bahamas The | BHS'                  , value:'BHS' }, 
  { name:'Bosnia and Herzegovina | BIH'       , value:'BIH' }, 
  { name:'Belarus | BLR'                      , value:'BLR' }, 
  { name:'Belize | BLZ'                       , value:'BLZ' }, 
  { name:'Bermuda | BMU'                      , value:'BMU' }, 
  { name:'Bolivia | BOL'                      , value:'BOL' }, 
  { name:'Brazil | BRA'                       , value:'BRA' }, 
  { name:'Barbados | BRB'                     , value:'BRB' }, 
  { name:'Brunei Darussalam | BRN'            , value:'BRN' }, 
  { name:'Bhutan | BTN'                       , value:'BTN' }, 
  { name:'Botswana | BWA'                     , value:'BWA' }, 
  { name:'Central African Rep | CAF'          , value:'CAF' }, 
  { name:'Canada | CAN'                       , value:'CAN' }, 
  { name:'Switzerland | CHE'                  , value:'CHE' }, 
  { name:'Channel Islands | CHI'              , value:'CHI' }, 
  { name:'Chile | CHL'                        , value:'CHL' }, 
  { name:'China | CHN'                        , value:'CHN' }, 
  { name:'Cote d Ivoire | CIV'                , value:'CIV' }, 
  { name:'Cameroon | CMR'                     , value:'CMR' }, 
  { name:'Congo DR | COD'                     , value:'COD' }, 
  { name:'Congo Rep | COG'                    , value:'COG' }, 
  { name:'Colombia | COL'                     , value:'COL' }, 
  { name:'Comoros | COM'                      , value:'COM' }, 
  { name:'Cabo Verde | CPV'                   , value:'CPV' }, 
  { name:'Costa Rica | CRI'                   , value:'CRI' }, 
  { name:'Cuba | CUB'                         , value:'CUB' }, 
  { name:'Curacao | CUW'                      , value:'CUW' }, 
  { name:'Cayman Islands | CYM'               , value:'CYM' }, 
  { name:'Cyprus | CYP'                       , value:'CYP' }, 
  { name:'Czech Rep | CZE'                    , value:'CZE' }, 
  { name:'Germany | DEU'                      , value:'DEU' }, 
  { name:'Djibouti | DJI'                     , value:'DJI' }, 
  { name:'Dominica | DMA'                     , value:'DMA' }, 
  { name:'Denmark | DNK'                      , value:'DNK' }, 
  { name:'Dominican Rep | DOM'                , value:'DOM' }, 
  { name:'Algeria | DZA'                      , value:'DZA' }, 
  { name:'Ecuador | ECU'                      , value:'ECU' }, 
  { name:'Egypt Arab Rep | EGY'               , value:'EGY' }, 
  { name:'Eritrea | ERI'                      , value:'ERI' }, 
  { name:'Spain | ESP'                        , value:'ESP' }, 
  { name:'Estonia | EST'                      , value:'EST' }, 
  { name:'Ethiopia | ETH'                     , value:'ETH' }, 
  { name:'Finland | FIN'                      , value:'FIN' }, 
  { name:'Fiji | FJI'                         , value:'FJI' }, 
  { name:'France | FRA'                       , value:'FRA' }, 
  { name:'Faroe Islands | FRO'                , value:'FRO' }, 
  { name:'Micronesia Fed Sts | FSM'           , value:'FSM' }, 
  { name:'Gabon | GAB'                        , value:'GAB' }, 
  { name:'United Kingdom | GBR'               , value:'GBR' }, 
  { name:'Georgia | GEO'                      , value:'GEO' }, 
  { name:'Ghana | GHA'                        , value:'GHA' }, 
  { name:'Gibraltar | GIB'                    , value:'GIB' }, 
  { name:'Guinea | GIN'                       , value:'GIN' }, 
  { name:'Gambia The | GMB'                   , value:'GMB' }, 
  { name:'Guinea Bissau | GNB'                , value:'GNB' }, 
  { name:'Equatorial Guinea | GNQ'            , value:'GNQ' }, 
  { name:'Greece | GRC'                       , value:'GRC' }, 
  { name:'Grenada | GRD'                      , value:'GRD' }, 
  { name:'Greenland | GRL'                    , value:'GRL' }, 
  { name:'Guatemala | GTM'                    , value:'GTM' }, 
  { name:'Guam | GUM'                         , value:'GUM' }, 
  { name:'Guyana | GUY'                       , value:'GUY' }, 
  { name:'Hong Kong SAR China | HKG'          , value:'HKG' }, 
  { name:'Honduras | HND'                     , value:'HND' }, 
  { name:'Croatia | HRV'                      , value:'HRV' }, 
  { name:'Haiti | HTI'                        , value:'HTI' }, 
  { name:'Hungary | HUN'                      , value:'HUN' }, 
  { name:'Indonesia | IDN'                    , value:'IDN' }, 
  { name:'Isle of Man | IMN'                  , value:'IMN' }, 
  { name:'India | IND'                        , value:'IND' }, 
  { name:'Ireland | IRL'                      , value:'IRL' }, 
  { name:'Iran | IRN'                         , value:'IRN' }, 
  { name:'Iraq | IRQ'                         , value:'IRQ' }, 
  { name:'Iceland | ISL'                      , value:'ISL' }, 
  { name:'Israel | ISR'                       , value:'ISR' }, 
  { name:'Italy | ITA'                        , value:'ITA' }, 
  { name:'Jamaica | JAM'                      , value:'JAM' }, 
  { name:'Jordan | JOR'                       , value:'JOR' }, 
  { name:'Japan | JPN'                        , value:'JPN' }, 
  { name:'Kazakhstan | KAZ'                   , value:'KAZ' }, 
  { name:'Kenya | KEN'                        , value:'KEN' }, 
  { name:'Kyrgyz Rep | KGZ'                   , value:'KGZ' }, 
  { name:'Cambodia | KHM'                     , value:'KHM' }, 
  { name:'Kiribati | KIR'                     , value:'KIR' }, 
  { name:'St Kitts and Nevis | KNA'           , value:'KNA' }, 
  { name:'Korea Rep | KOR'                    , value:'KOR' }, 
  { name:'Kuwait | KWT'                       , value:'KWT' }, 
  { name:'Lao PDR | LAO'                      , value:'LAO' }, 
  { name:'Lebanon | LBN'                      , value:'LBN' }, 
  { name:'Liberia | LBR'                      , value:'LBR' }, 
  { name:'Libya | LBY'                        , value:'LBY' }, 
  { name:'St Lucia | LCA'                     , value:'LCA' }, 
  { name:'Liechtenstein | LIE'                , value:'LIE' }, 
  { name:'Sri Lanka | LKA'                    , value:'LKA' }, 
  { name:'Lesotho | LSO'                      , value:'LSO' }, 
  { name:'Lithuania | LTU'                    , value:'LTU' }, 
  { name:'Luxembourg | LUX'                   , value:'LUX' }, 
  { name:'Latvia | LVA'                       , value:'LVA' }, 
  { name:'Macao SAR China | MAC'              , value:'MAC' }, 
  { name:'St Martin French part | MAF'        , value:'MAF' }, 
  { name:'Morocco | MAR'                      , value:'MAR' }, 
  { name:'Monaco | MCO'                       , value:'MCO' }, 
  { name:'Moldova | MDA'                      , value:'MDA' }, 
  { name:'Madagascar | MDG'                   , value:'MDG' }, 
  { name:'Maldives | MDV'                     , value:'MDV' }, 
  { name:'Mexico | MEX'                       , value:'MEX' }, 
  { name:'Marshall Islands | MHL'             , value:'MHL' }, 
  { name:'North Macedonia | MKD'              , value:'MKD' }, 
  { name:'Mali | MLI'                         , value:'MLI' }, 
  { name:'Malta | MLT'                        , value:'MLT' }, 
  { name:'Myanmar | MMR'                      , value:'MMR' }, 
  { name:'Montenegro | MNE'                   , value:'MNE' }, 
  { name:'Mongolia | MNG'                     , value:'MNG' }, 
  { name:'Northern Mariana Islands | MNP'     , value:'MNP' }, 
  { name:'Mozambique | MOZ'                   , value:'MOZ' }, 
  { name:'Mauritania | MRT'                   , value:'MRT' }, 
  { name:'Mauritius | MUS'                    , value:'MUS' }, 
  { name:'Malawi | MWI'                       , value:'MWI' }, 
  { name:'Malaysia | MYS'                     , value:'MYS' }, 
  { name:'Namibia | NAM'                      , value:'NAM' }, 
  { name:'New Caledonia | NCL'                , value:'NCL' }, 
  { name:'Niger | NER'                        , value:'NER' }, 
  { name:'Nigeria | NGA'                      , value:'NGA' }, 
  { name:'Nicaragua | NIC'                    , value:'NIC' }, 
  { name:'Netherlands | NLD'                  , value:'NLD' }, 
  { name:'Norway | NOR'                       , value:'NOR' }, 
  { name:'Nepal | NPL'                        , value:'NPL' }, 
  { name:'Nauru | NRU'                        , value:'NRU' }, 
  { name:'New Zealand | NZL'                  , value:'NZL' }, 
  { name:'Oman | OMN'                         , value:'OMN' }, 
  { name:'Pakistan | PAK'                     , value:'PAK' }, 
  { name:'Panama | PAN'                       , value:'PAN' }, 
  { name:'Peru | PER'                         , value:'PER' }, 
  { name:'Philippines | PHL'                  , value:'PHL' }, 
  { name:'Palau | PLW'                        , value:'PLW' }, 
  { name:'Papua New Guinea | PNG'             , value:'PNG' }, 
  { name:'Poland | POL'                       , value:'POL' }, 
  { name:'Puerto Rico | PRI'                  , value:'PRI' }, 
  { name:'Korea DPR | PRK'                    , value:'PRK' }, 
  { name:'Portugal | PRT'                     , value:'PRT' }, 
  { name:'Paraguay | PRY'                     , value:'PRY' }, 
  { name:'West Bank and Gaza | PSE'           , value:'PSE' }, 
  { name:'French Polynesia | PYF'             , value:'PYF' }, 
  { name:'Qatar | QAT'                        , value:'QAT' }, 
  { name:'Romania | ROU'                      , value:'ROU' }, 
  { name:'Russian Federation | RUS'           , value:'RUS' }, 
  { name:'Rwanda | RWA'                       , value:'RWA' }, 
  { name:'Saudi Arabia | SAU'                 , value:'SAU' }, 
  { name:'Sudan | SDN'                        , value:'SDN' }, 
  { name:'Senegal | SEN'                      , value:'SEN' }, 
  { name:'Singapore | SGP'                    , value:'SGP' }, 
  { name:'Solomon Islands | SLB'              , value:'SLB' }, 
  { name:'Sierra Leone | SLE'                 , value:'SLE' }, 
  { name:'El Salvador | SLV'                  , value:'SLV' }, 
  { name:'San Marino | SMR'                   , value:'SMR' }, 
  { name:'Somalia | SOM'                      , value:'SOM' }, 
  { name:'Serbia | SRB'                       , value:'SRB' }, 
  { name:'South Sudan | SSD'                  , value:'SSD' }, 
  { name:'Sao Tome and Principe | STP'        , value:'STP' }, 
  { name:'Suriname | SUR'                     , value:'SUR' }, 
  { name:'Slovak Rep | SVK'                   , value:'SVK' }, 
  { name:'Slovenia | SVN'                     , value:'SVN' }, 
  { name:'Sweden | SWE'                       , value:'SWE' }, 
  { name:'Eswatini | SWZ'                     , value:'SWZ' }, 
  { name:'Sint Maarten Dutch part | SXM'      , value:'SXM' }, 
  { name:'Seychelles | SYC'                   , value:'SYC' }, 
  { name:'Syrian Arab Rep | SYR'              , value:'SYR' }, 
  { name:'Turks and Caicos Islands | TCA'     , value:'TCA' }, 
  { name:'Chad | TCD'                         , value:'TCD' }, 
  { name:'Togo | TGO'                         , value:'TGO' }, 
  { name:'Thailand | THA'                     , value:'THA' }, 
  { name:'Tajikistan | TJK'                   , value:'TJK' }, 
  { name:'Turkmenistan | TKM'                 , value:'TKM' }, 
  { name:'Timor Leste | TLS'                  , value:'TLS' }, 
  { name:'Tonga | TON'                        , value:'TON' }, 
  { name:'Trinidad and Tobago | TTO'          , value:'TTO' }, 
  { name:'Tunisia | TUN'                      , value:'TUN' }, 
  { name:'Turkey | TUR'                       , value:'TUR' }, 
  { name:'Tuvalu | TUV'                       , value:'TUV' }, 
  { name:'Taiwan China | TWN'                 , value:'TWN' }, 
  { name:'Tanzania | TZA'                     , value:'TZA' }, 
  { name:'Uganda | UGA'                       , value:'UGA' }, 
  { name:'Ukraine | UKR'                      , value:'UKR' }, 
  { name:'Uruguay | URY'                      , value:'URY' }, 
  { name:'United States | USA'                , value:'USA' }, 
  { name:'Uzbekistan | UZB'                   , value:'UZB' }, 
  { name:'St Vincent and the Grenadines | VCT', value:'VCT' }, 
  { name:'Venezuela RB | VEN'                 , value:'VEN' }, 
  { name:'British Virgin Islands | VGB'       , value:'VGB' }, 
  { name:'Virgin Islands U S | VIR'           , value:'VIR' }, 
  { name:'Vietnam | VNM'                      , value:'VNM' }, 
  { name:'Vanuatu | VUT'                      , value:'VUT' }, 
  { name:'Samoa | WSM'                        , value:'WSM' }, 
  { name:'Kosovo | XKX'                       , value:'XKX' }, 
  { name:'Yemen Rep | YEM'                    , value:'YEM' }, 
  { name:'South Africa | ZAF'                 , value:'ZAF' }, 
  { name:'Zambia | ZMB'                       , value:'ZMB' }, 
  { name:'Zimbabwe | ZWE'                     , value:'ZWE' }, 
]